### ISSUE TITLE
Add normal map to interior

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1009]
Add normal map to the interior of the aircraft, e.g. add texture to the panel material, leather seats, walls, etc.

**Comment by onox** [comment]
@gilbertohasnofb @wlbragg Is this something that can be done easily? (just some baking in Blender)

**Comment by gilbertohasnofb** [comment]
@onox nope, I would need to create it manually and it would be a lot of work. This is one of those issues I wouldn't like to rush.

**Comment by legoboyvdlp** [comment]
Actually, it should be possible to bake the normal map in blender using a sculpture tool? 

At least as a starting point...

The way you do it, if I remember correctly, you sculpt the detailed mesh with all the rivets or whatever, then, selecting the uvmapped original mesh you bake the normal, like a lightmap.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp In the exterior we use normal map for those tiny details that we did not 3D model. In the case of the panel, everything is highly modelled and thus there is no need to use the same technique for it. My idea of using normal map (and let me be clear this might not work out) would be to bring out some of the minor details of the _textures_  in the panel, e.g. the small imperfections of the plastic material that make out the main panel. But I did have a bunch of bad experiences trying to use normal maps for shallow details in the exterior so I am really not sure I will be able to pull this out. Anyway, this has to be done manually.

**Comment by legoboyvdlp** [comment]
You could probably model the imperfections and bake the normal but if it is easier to manually do it that's fine ;)

**Comment by gilbertohasnofb** [comment]
I am talking about minuscule ultra detailed imperfections, modelling doesn't work here at all.

**Comment by gilbertohasnofb** [comment]
@wlbragg could you give me a hand with this one? I am attempting to create some normal maps to the interior but I don't know how to implement the effect itself. I don't want to push my normal texture to the opened PR since I don't know if the effect will look good or not, so perhaps a new branch for this would be best. How much trouble would it be for you to help me with the effect files in a new branch? Is that a lot of work?

Here is the first test of the normal for panel_parts:

![image](https://user-images.githubusercontent.com/5700795/42663321-f4ba0860-862c-11e8-8b8d-801307b11ba6.png)

Only the circuit breakers, mixture lever and panel leather have normal maps applied to them. But I am really not sure the effect will be good in the interior and if it doesn't look that good we just close this issue and leave things as they are, since the interior is looking already pretty good.

**Comment by wlbragg** [comment]
@gilbertohasnofb sure, Let me set it up using this map and I'll push a new branch and we can see how effective (or not) it is!

**Comment by gilbertohasnofb** [comment]
@wlbragg if you set up the branch do let me know so I can experiment with the textures, ok?

**Comment by wlbragg** [comment]
@gilbertohasnofb as far as I can tell we don't have the ability to do normal maps in the interior effects framework. It used model-combined-differed. We use model-interior. So unless someone can shed some light on this, it's beyond my capabilities.

**Comment by gilbertohasnofb** [comment]
Well let's close this issue then, this was a super long shot anyway as I don't think these maps would look very good. Our interior is very detailed and I am quite satisfied with it.
