### ISSUE TITLE
Improve 3D model and texture of all levers

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1023]
Improve 3D model and texture of all levers (including throttle, mixture, primer and carb heat):

![aad](https://user-images.githubusercontent.com/5700795/37676517-05ba8ff2-2c70-11e8-8243-0320a506e516.jpg)

![aaf](https://user-images.githubusercontent.com/5700795/37676518-05e4c1fa-2c70-11e8-9b65-f646c65e2e60.jpg)

![aag](https://user-images.githubusercontent.com/5700795/37676519-05ff85a8-2c70-11e8-80f3-59c6aae49668.jpg)

![abh](https://user-images.githubusercontent.com/5700795/37676520-062db824-2c70-11e8-8341-f4a5ebff19ce.jpg)

![_full](https://user-images.githubusercontent.com/5700795/37676521-064e29e2-2c70-11e8-98ab-f7a7de066abe.jpg)

![aaj](https://user-images.githubusercontent.com/5700795/37676587-3ac6ca30-2c70-11e8-9ca3-ebf5681f1f32.jpg)

![](https://user-images.githubusercontent.com/423703/37675452-3db04c04-2cb0-11e8-8836-b2ee6e94988f.png)

* throttle and mixture need a better 3D model, the handle needs a bit more detail and be a bit longer perhaps. Their bases (where the lever 'enters' the cockpit) need some rework.
* primer needs a better 3D model (handle is too shallow and not looking very good) + also a better texture
* carb heat needs a little bit more thickness, the handle is too big and the length when extended is way too short. The base needs to be resized as well, it's too big. Also the handle does not seem fixed which is why the 'square' handle does not necessarily point at 0 degrees nor 45 degrees with the horizon. Ours is ar 45 degrees, perhaps we could twist it a bit more?  
* consider improving the illuminations knobs as well

Related to: https://github.com/c172p-team/c172p-detailed/issues/802

**Comment by gilbertohasnofb** [comment]
@wlbragg just notice two more things: our carb heat lever looks too short and the bit where you hold looks too large. See this excellent video at around 6:00 (this is a valuable source for a lot of things concerning the interior)

https://www.youtube.com/watch?v=sLFX33Ogmus

**Comment by gilbertohasnofb** [comment]
I've updated list of things to do in the issue description

**Comment by gilbertohasnofb** [comment]
Also, this issue is related to https://github.com/c172p-team/c172p-detailed/issues/802

**Comment by gilbertohasnofb** [comment]
A couple more issues about the carb heater:

* it should be smaller
* it's corners should be rounder (see the photos of OH-CTL in the main post above)
* it should have its sides UV-mapped as well (marked in green below)

![image](https://user-images.githubusercontent.com/5700795/40260245-7f4604be-5af1-11e8-85ec-eafe2dcc8831.png)

**Comment by wlbragg** [comment]
@gilbertohasnofb Couple things,

The chrome circle needs to be a tiny bit smaller.

![knob](https://user-images.githubusercontent.com/11069680/40264686-87c9dcd4-5aef-11e8-8a60-3c4661cb7911.jpg)

The base I think doesn't look anything like in the video. In the video it's just a small ring similar to the throttle base. Also it is mapped wrong,iIt really needs its own base texture.

![knob1](https://user-images.githubusercontent.com/11069680/40264687-87e1883e-5aef-11e8-9ed2-47d976037b33.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg i will work on those

**Comment by gilbertohasnofb** [comment]
@wlbragg new textures are pushed.

> The base I think doesn't look anything like in the video. In the video it's just a small ring similar to the throttle base. Should I change it? Also it is mapped wrong, it really needs its own base texture.
I already rounded the corners and textured the edges.

Yes please, do improve that model if you can. And map it to this:
![image](https://user-images.githubusercontent.com/5700795/40269793-c25f208a-5b7a-11e8-8d8c-37791b8b0674.png)

**Comment by gilbertohasnofb** [comment]
Also, note that the carb heat needs a new UV-map as enlarging the texture had side effects on its inner walls:

![image](https://user-images.githubusercontent.com/5700795/40269881-eabe65b2-5b7b-11e8-84b3-9a9ecba14e9a.png)

**Comment by wlbragg** [comment]
>Also, note that the carb heat needs a new UV-map as enlarging the texture had side effects

@gilbertohasnofb yep, already one step ahead here. I needed it slightly reduced to get a better visual when resizing and rounding the corners. It actually was doing the opposite in that case, I couldn't reduce the chrome area as the back-plate was picking up the chrome texture so I was reducing the size of the knob but not the chrome circle.

I hesitated to mention it as I knew things like this require the full run across liveries. I am afraid there still might be one or two more minor issues slimier to this when I get there. We have already cleaned the vast majority of these issues up, ones that really affected the AO, but I kind of remember in the back of my head a few minor thing that weren't going to affect the AO maps enough to bother with that would potentially affect the light maps. So sorry we didn't address everything all at once. This particular issue though I have to admit, escaped my notice completely until now.

**Comment by gilbertohasnofb** [comment]
Great!

> I hesitated to mention it as I knew things like this require the full run across liveries. I am afraid there still might be one or two more minor issues slimier to this when I get there. We have already cleaned the vast majority of these issues up, ones that really affected the AO, but I kind of remember in the back of my head a few minor thing that weren't going to affect the AO maps enough to bother with that would potentially affect the light maps. So sorry we didn't address everything all at once. 

No worries about that, it's really not that much work. But do always mention things that you spot and I am happy to improve them in all liveries. It's of course easier to fix many things at once since these texture files can bog the size of the git repository but this is not the end of the planet either and for me fixes come first to anything else :smile:

**Comment by onox** [comment]
> We should consider removing all the blends from the main repository

I'm afraid that isn't going to help much. The checkout of the `dev/` is only 60 MiB. The Git history is still over 1 GiB.

What we could do though, is use BFG to delete the .blend blobs.

**Comment by gilbertohasnofb** [comment]
@onox the history of the textures is potentially quite large as well, I believe.

**Comment by wlbragg** [comment]
@onox 
>What we could do though, is use BFG to delete the .blend blobs. I've done this for the p51d repository to delete its giant 

So is this something we would do periodically?

**Comment by wlbragg** [comment]
@gilbertohasnofb I remapped the carb heat base as discussed. I was looking over your notes in this issue and went ahead and retopologized the primer base. To really get the effect we want I think it needs a new "chrome" texture as in the picture. The current dark texture won't allow us to see any of the 3D relief work.

**Comment by gilbertohasnofb** [comment]
@wlbragg I am back from my trip, sorry for the silence during this last week :smile: 

This is looking really great, these last commits are excellent. I will add a chrome texture for the primer base. I think the handle of the primer could also do with some small tweaks on its 3D model, see:

![](https://user-images.githubusercontent.com/423703/37675452-3db04c04-2cb0-11e8-8836-b2ee6e94988f.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg Done, I am pushing it. There is a texture to be applied radially on the base of primer (the strip) and there is another one which is to be applied where the base meets the lever. If this doesn't make sense give me a shout:

![image](https://user-images.githubusercontent.com/5700795/41163713-5791a8b0-6b31-11e8-99b2-15327f934dc0.png)

**Comment by gilbertohasnofb** [comment]
Also, I only pushed it to the 4X-CHV livery as we might need to do a lot of work on the `panel_part` texture. Once we are done with everything I will sync all textures of all liveries.

**Comment by onox** [comment]
> So is this something we would do periodically?

No, the blobs are just deleted once. After that you have to make sure to not check in any new .blend files.

**Comment by legoboyvdlp** [comment]
Image of the throttle lever:
![image](https://user-images.githubusercontent.com/10434911/41193225-36355de4-6c01-11e8-8c89-e4e23808e600.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg this could be our next project together with https://github.com/c172p-team/c172p/issues/802 and from there we finish with all other alterations necessary to finish the interior improvements.

My advice is for us to now select photos of each of the levers that we will use as reference. Our primer and carb heat are looking good now and I really like the throttle and mixture posted by lego above, they are pretty common on Model P's as far as I can tell.

**Comment by wlbragg** [comment]
@gilbertohasnofb , yes, where do we start?  Do we have anything specific yet?

**Comment by gilbertohasnofb** [comment]
@wlbragg Let's start with remodelling and improving textures of the throttle and mixture levers. The models of these levers vary _a lot_ even within the model P range. This is a photo from the OH-CTL:

![image](https://user-images.githubusercontent.com/5700795/42422229-093ff232-82da-11e8-82a9-0068a7beeb80.png)

Using the OH-CTL photo as reference for our redesign, here is how I suggest our models would look like in a 2.5D view (please forgive the roughness of the design):

![image](https://user-images.githubusercontent.com/5700795/42422280-ea8bbf64-82da-11e8-8632-f3364cfe0317.png)

![image](https://user-images.githubusercontent.com/5700795/42422316-9996b874-82db-11e8-81dd-dcd4d651f9d5.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg what do you think about the modifications I suggested above?

**Comment by wlbragg** [comment]
@gilbertohasnofb  looks good. I have a bit of a time conflict currently. Hopefully I can get on some of this during the next week or so.

**Comment by gilbertohasnofb** [comment]
@wlbragg no worries, we pick the work up when you have some time. I will take a look at that list of issues during the weekend and see if there is anything I can handle on my own.

**Comment by wlbragg** [comment]
@gilbertohasnofb mixture is pushed. To keep the "travel" correct I extended the knob closer to the pilot as the knob itself grew in length and slightly in circumference (the amount of the knobs).

**Comment by wlbragg** [comment]
@gilbertohasnofb I'm wondering if the ring part with the knobs on it is to "thick/wide". Maybe should be thinner?

**Comment by wlbragg** [comment]
Also the throttle looks as if it also has some knobs on it, but maybe not as pronounced?

**Comment by gilbertohasnofb** [comment]
They look really good, much better than before, but I have a couple of requests of improvements if you'd have the patience:

1) yellow: the mixture bumps need to be triangular and maybe a tiny bit taller but not as much as I've drawn. Also there should be six and not eight bumps, I am sorry for telling you wrongly before... they are 60 degrees apart (see photo reference from OH-CTL below) green: the UV-mapping needs to go a bit up and right as the circle is not centralized
![image](https://user-images.githubusercontent.com/5700795/42654499-b5f6f244-8610-11e8-825e-9da801f93db5.png)
photo reference:
![image](https://user-images.githubusercontent.com/5700795/42654461-98a6b738-8610-11e8-85e1-6f7bb91d6c4b.png)

 
2) green: the larger cylinder object constituting the throttle could be a bit longer so just extend it a bit backwards, but keep the dimension the same (look at the purple contour at the bottom to see what I have in mind). yellow: the front object that look like a 'tyre' needs to be moved backwards as you can see its back half. Just move it backwards until the place where I draw the yellow pointed line.

![image](https://user-images.githubusercontent.com/5700795/42654223-dcc85026-860f-11e8-9c5b-a4c89329945d.png)

3) yellow: the front small cylinder of the mixture seems a bit too long comparing with our reference photo above, could you shorten it a bit, something like 30% shorter? green: would you consider improving the bases as well? see the photo I previously posted.
 
![image](https://user-images.githubusercontent.com/5700795/42654265-fb952b14-860f-11e8-905b-f0f6898ccd73.png)

> Also the throttle looks as if it also has some knobs on it, but maybe not as pronounced?

Nope, because those 'bumps' serve a purpose: they are there so that the pilot can differentiate between the levers without looking at them, avoiding you cutting the mixture and thus stopping an engine when you simply wanted an idle throttle. The standard is: throttle is always smooth, mixture has 6 bumps and the prop (for planes with variable pitch) has bumps inwards. This is a photo of a 182:

![image](https://user-images.githubusercontent.com/5700795/42654059-346afb40-860f-11e8-8191-d20f4a3e7d44.png)

(in the photo above it might look like the throttle has something on top but those are just reflections, I am a hundred percent sure they need to be smooth)

**Comment by wlbragg** [comment]
> the UV-mapping needs to go a bit up and right as the circle is not centralized

That is actually centered on the smaller ring. I think it is the ring behind it that gives it the appearance of being off-centered because of the white glare effect. So with that said, you have another suggestion. I can map the second ring differently, not using the white glare on it?

**Comment by wlbragg** [comment]
Pushed the next round, I don't like the mapping on the Mixture knob, the face where the "imitation glare" is.

**Comment by wlbragg** [comment]
Pushed the last changes you pointed out. The "glare" texture issue I think will need a texture edit, see below. I did correct the white on the back "hidden" side, the mapping was slightly off the texture and into the white.
I forgot to shorten the "closest to pilot" ring on the mixture you pointed out in the prior commit, so that is included in this one.
I still need to do the base upgrades for both controls.
![map](https://user-images.githubusercontent.com/11069680/42675133-5195c528-8638-11e8-9fab-7a7f73c84e85.jpg)

**Comment by gilbertohasnofb** [comment]
> Pushed the last changes you pointed out. Please verify the shape and size of the triangle bumps now.

@wlbragg Hmm, I think the bumps were looking better before. They are way too wide now. Compare what we have with this:

![](https://i.ytimg.com/vi/NGndkJ2JlnQ/maxresdefault.jpg)

Also, I just pushed a commit in which I removed those reflections. I also added a new texture which should be applied around the lever (where those triangular bumps are): 

![image](https://user-images.githubusercontent.com/5700795/42706607-4dd912d6-86cf-11e8-8cb2-299c387f12f6.png)

Once the model is improved, would you be able to map it and create a AO-map for us as well so that the bumps look better? With the AO-map applied it will look something like this:

![image](https://user-images.githubusercontent.com/5700795/42706629-608aa188-86cf-11e8-88a6-cefe1a1ed18e.png)

My texture modifications are only being applied to 4X-CHV. Once we are happy with the texture I will sync all liveries, so please make everything livery dependent.

**Comment by wlbragg** [comment]
@gilbertohasnofb 

>Hmm, I think the bumps were looking better before. They are way too wide now. Compare what we have with this:

You know your killing me, right?
I'm trying to avoid making the knob from scratch. The prior way you thought was too thin was made that way because I also thought this last way was to fat when I originally tried it. 

So now I split the difference, it is wider than the "too thin" one, but thinner than the to fat one! New mapping. Still need to do the base for both mixture and throttle.

**Comment by gilbertohasnofb** [comment]
I am so sorry for being picky on this one. On the plus side, your last push looks very good and I think we are done with the models! I also noticed the UV-mapping of the part containing the bumps seems to be ready, do you think you could bake a AOmap for it so that I can apply it to the textures? That will make the bumps more visible due to the shadows and stuff. Then I can also use that AOmap to fake the lightmap so we don't have to bother making that one again. 

> Still need to do the base for both mixture and throttle.

No rush! We are getting there :smile:

**Comment by wlbragg** [comment]
@gilbertohasnofb check this AO map. The Carb Heat part is probably better than what you have as well. I baked it in two passes to get the overlapping parts correct. I redid the Mixture UV map (the new texture part) as the way I had it didn't give you a valid AO map. I can make any changes you need and I still have to do the base. I may have to bake the light map unless you can figure it out with the AO.
![ao](https://user-images.githubusercontent.com/11069680/42959854-c17507c0-8b4f-11e8-8c40-0f28ce57ce0f.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg thanks for the AOmap but I think we have a small problem. The knuckles of the mixture lever are not matching the AOmap. In the image below, the green lines mark the steep changes of angles in the lever (i.e. the regions that should have a fairly large change in lighting) while the purple marks the places where the lighting is effectively changing with the current AOmap you posted above. Note that besides in the red arrow place, none of the other lines match.

![image](https://user-images.githubusercontent.com/5700795/42973000-5fccebe6-8ba9-11e8-8a0e-eb30969b6960.png)

We also have a problem with the light map which I don't think I can solve it myself: it seems the levers are mapped upside down so that the light map is inverted, i.e. as if the light is coming from the floor, see:

![image](https://user-images.githubusercontent.com/5700795/42973018-75c0fa78-8ba9-11e8-917f-d93f5fb0a2a8.png)

About the Radio knob shadow in the light map, I will fix that manually.

**Comment by gilbertohasnofb** [comment]
@wlbragg I just pushed some improved light maps for the EGT (which was pixelated with the white dome light) and for the panel with the new lever and knob positions.

**Comment by wlbragg** [comment]
>thanks for the AOmap but I think we have a small problem. The knuckles of the mixture lever are not matching the AOmap.

@gilbertohasnofb Shoot, that's my fault. I re-UV-mapped the Mixture and forgot to push that also, It will line up once I push a new c172p.ac and Blend. I will push that tonight with the base for the Throttle and the Mixture levers. Sorry, I am a bit distracted as of late.

>We also have a problem with the light map which I don't think I can solve it myself: it seems the levers are mapped upside down so that the light map is inverted, i.e. as if the light is coming from the floor,

Hum, that's odd. Let me finish the throttle and mixture bases first and is there any other instruments, levers or any thing else that we are still going to improve that will require light map modifications. If so, lets do all that first and then fix all the light map stuff, yes?

**Comment by wlbragg** [comment]
@gilbertohasnofb we need new textures for the throttle and mixture bases, see below:
Note, the NEW throttle hexagon nut is mapped to the avionics switch texture and needs its own texture. Both the throttle and mixture rectangle textures (for the bases) could be replaced with chrome circles instead of the rectangles they currently are mapped to.
I pushed the new mesh if you need to see it.

![mix](https://user-images.githubusercontent.com/11069680/42983730-e9f57e4c-8bad-11e8-8e68-81dde30044da.jpg)
![thr](https://user-images.githubusercontent.com/11069680/42983734-ec65f896-8bad-11e8-96a7-155c6740c1e3.jpg)

**Comment by wlbragg** [comment]
@gilbertohasnofb I just noticed in my light map blander file (also used for the AO maps) that the knobs and bases for the knobs have issues as to their locations. It looks like I have the old base mesh in their old positions and the new base mesh in their new positions, so quit frankly I am not sure what that AO map is going to give you. That may be the "upside down" issue with the light maps as well. So lets finish all the interior mesh work and then redo what needs to be fixed on the light map and the AO maps, OK?
We just need to keep track of the accumulating AO and light map corrections that will be needed.

**Comment by gilbertohasnofb** [comment]
> I re-UV-mapped the Mixture and forgot to push that also

But was the AOmap for the correct model or for the old one? I will test your commits later tonight.

> Let me finish the throttle and mixture bases first and is there any other instruments, levers or any thing else that we are still going to improve that will require light map modifications. If so, lets do all that first and then fix all the light map stuff, yes?

No rush. I think this is probably caused because we have been re-UV-mapping a lot these levers and perhaps the lightmap doesn't match it any longer. Later we can generate a new lightmap and AOmap for the panel_parts once all new models are ready and done and that should fix everything.

> we need new textures for the throttle and mixture bases, see below:
> Note, the NEW throttle hexagon nut is mapped to the avionics switch texture and needs its own texture. Both the throttle and mixture rectangle textures (for the bases) could be replaced with chrome circles instead of the rectangles they currently are mapped to.
> I pushed the new mesh if you need to see it.

The models look amazing, thanks! I will make the textures later tonight.

> So lets finish all the interior mesh work and then redo what needs to be fixed on the light map and the AO maps, OK?

No problems, that will involve only `panel_parts` and I can synchronize any manual alteration I might have made, so let's do as you say.

**Comment by gilbertohasnofb** [comment]
@wlbragg I love the new bases, I will make textures for them right now.

As for the AO map of the mixture lever, I am really not convinced about it. Here is how it looks like at the moment:

![image](https://user-images.githubusercontent.com/5700795/43018535-ebb0abea-8c51-11e8-8625-939288676e28.png)

The problem is that the dark and light parts still do not match at all with the bumps in the model. To test this, I painted each region in the image above with a different colour and watched in the sim and they are simply not matching it. Could you please double check how that is being mapped? I was hoping it would be mapped like this:

![image](https://user-images.githubusercontent.com/5700795/43018546-f34bc0a6-8c51-11e8-9d1e-0d657cb2d21c.png)

So that when you generate the AO map it would look like this:

![image](https://user-images.githubusercontent.com/5700795/43018553-f7cc2c74-8c51-11e8-96ed-832345ff452c.png)

with the contour to make it clearer:

![image](https://user-images.githubusercontent.com/5700795/43018564-fb673b76-8c51-11e8-8f59-d6850c40a683.png)

**Comment by gilbertohasnofb** [comment]
The bases are done, orange is for the throttle and purple is for the mixture:

![image](https://user-images.githubusercontent.com/5700795/43019034-7288171a-8c53-11e8-8cc1-fbff44a9b09a.png)

**Comment by wlbragg** [comment]
>I was hoping it would be mapped like this:

You're forcing me to learn a new technique of unwrapping seems :smile:. 

Time passes...

OK I found a video that showed me somewhat how to unwrap it like you want.
This is what it would look like if I use that technique.

![mix2](https://user-images.githubusercontent.com/11069680/43024826-1798d9ca-8c35-11e8-92fd-34167d05eaa4.jpg)

Now, with that said, what I  originally did, that you used, was to use the "Smart Unwrap", it's just way simpler and the mapping should work the same way only it is laid out less intuitively.
That looks like this.
![mix](https://user-images.githubusercontent.com/11069680/43024924-71d10c3c-8c35-11e8-8bed-e34ac36c9400.jpg)

and in Blender the shading looks like this
![mix1](https://user-images.githubusercontent.com/11069680/43024927-738579be-8c35-11e8-8a5c-e1ce551a2ac4.jpg)

But I agree it didn't look like this in the sim nor could you really see any of the AO that well.

So, I pushed the NEW mapping as you requested (picture 1) along with the re-mapped bases. Now the AO texture for the mixture is for sure wrong as it is still using the "Smart Unwrap". I will bake a new AO when we are all done with any panel_parts mesh improvements.

In sim it looks like this now. 

![thr](https://user-images.githubusercontent.com/11069680/43025333-f50872e2-8c36-11e8-94ab-49d40e778aec.jpg)
As you can see the mixture knob AO is wrong , to be fixed as soon as we are finished with the mesh edits.

**Comment by wlbragg** [comment]
@gilbertohasnofb is there other mesh objects that need created?
See Low Voltage LED #1096 and Sunvisors #1110

**Comment by gilbertohasnofb** [comment]
@wlbragg there is this: https://github.com/c172p-team/c172p/issues/1098

And if you feel like, these here also involve mesh work:

https://github.com/c172p-team/c172p/issues/1122
https://github.com/c172p-team/c172p/issues/1143
https://github.com/c172p-team/c172p/issues/1093
https://github.com/c172p-team/c172p/issues/1030
