### ISSUE TITLE
Gyroscope can still be heard

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1042]
![fgfs-screen-288](https://user-images.githubusercontent.com/10434911/38210165-848f5252-36ae-11e8-90bb-5088a19b0257.png)

From this angle, at a distance from 30 meters, the gyroscope is heard clearly, while the engine is extremely quiet. At 25 meters, the sound is normal.

**Comment by gilbertohasnofb** [comment]
> From this angle, at a distance from 30 meters, the gyroscope is heard clearly, while the engine is extremely quiet

@legoboyvdlp can you always reproduce this? I certainly can't, the gyro is extremely soft at that distance and unheardable if the engine is on. With the engine off, I can perceive it but extremely soft. At around 40m it disappears completely.

I think I need more info on how to reproduce this.

**Comment by legoboyvdlp** [comment]
Did you try at that specific angle? I'll attemp to reproduce.

**Comment by gilbertohasnofb** [comment]
I will try again. How sensitive to the angle is the problem? But frankly, there is no angle definition in the sound xml so this looks like a FG bug and not specific to this aircraft.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp I just tried again, 30m and attempting to get as close to that angle but I hear no problems. I can't hear the gyro with the engine on from any angle close to that (nor any other angle for that matter).

**Comment by wlbragg** [comment]
@legoboyvdlp @gilbertohasnofb 
I'm not hearing it either at any angle.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp please do check if you can reproduce this again and try to narrow down the steps to get there.

**Comment by legoboyvdlp** [comment]
Hi,
It seems that on my system the sound is bugged. If I pause and unpause the sound changes, the engine volume reduces and wind volume increases. So perhaps the gyroscope is audible after you unpause. Regardless, I think this can be closed as I couldn't reproduce it. If you like I can try once more?

**Comment by gilbertohasnofb** [comment]
> If I pause and unpause the sound changes, the engine volume reduces and wind volume increases. 

My system has the same issue so I suspect this is a FG problem. But do check if you can reproduce the gyroscope problem immediately after loading without pausing at all. If not, then I guess that's all we can do about that.

>  If you like I can try once more?

Please do. Thanks!

**Comment by legoboyvdlp** [comment]
Seems to be away.

**Comment by gilbertohasnofb** [comment]
Thanks for the info!
