### ISSUE TITLE
Wire antenna from tail fin to cabin roof

### ISSUE THREAD

**Issue by okroth** [c172p-team/c172p#1046]
are you sure that the C172P has that type of antenna?
As far as I know, the C172P uses the King KR-87 ADF receiver, and the antenna for this is a complex antenna (KA44 or KA44B) assembled from the two orthogonal ferrite beads for the magnetic part and a small amplified antenna for the electric reference. The KR-87 does not use a wire antenna for the phase reference.

So there shouldn't be a wire antenna along the airframe as in the preview pictures.
(There are pictures in the internet that show a wire, these may use another ADF)

**Comment by gilbertohasnofb** [comment]
I think @okroth might have a point, nearly 100% of the 172P in http://www.airliners.net/search?keywords=172p show no such wire antenna.

**Comment by onox** [comment]
The wire antenna could be disabled in `Models/c172p.xml` (if it's a separate object in the 3D model) with a comment that the KR-87 ADF uses a "complex antenna (KA44 or KA44B) assembled from the two orthogonal ferrite beads for the magnetic part and a small amplified antenna for the electric reference".

Is the current 3D model missing the antenna's that @okroth mentioned?

**Comment by legoboyvdlp** [comment]
This seems to be the antenna mentioned:
![image](https://user-images.githubusercontent.com/10434911/38415355-27e58048-3989-11e8-86af-c921d77c74c6.png)

But as noted, this aircraft has **both** of the antennas?

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp I see at least three things that could be antennas in the image above, plus the wire connecting the tail to the wings.

**Comment by wlbragg** [comment]
Some more reference.
https://www.youtube.com/watch?v=AC6_vgGRHLo

I read a description of the ADF antenna being in two parts, one part, the wire on top and the other part on the belly.

This may be a difficult thing to pin down. For one antennas design could change slightly over time for the same piece of equipment.

**Comment by okroth** [comment]
Nice video. Unfortunately it misses the ADF antenna.
Regarding the KR-87 and the way it uses the antenna, that works different to the way ADF is taught to flight students. In the two orthogonal coils the received magnetic field of the radio signal induces voltages that differ based on the direction between antenna axis and radio transmitter. As opposite directions deliver the same voltage pairs, the phase relationship between electrical field and magnetic field is used to decide between the two directions. The wire is the antenna for the electric field of the radio wave.

The KR-87 uses two 32Hz square quadrature waves to invert the magnetic signals and then adds them to the electric signal, which is then demodulated and decoded using some phase detectors, integrators etc. All the pre-amplifying, multiplexing and summing happens in the antenna assembly KA-44B. The advantage of that method is that it is more robust against signal strength variations, as the information is encoded into a phase relation instead voltage.

A plane without wire antenna has either no ADF or the KR-87 and KA-44B.
A plane with KR-87 has no wire antenna.
BTW... I have found and downloaded the installation manual and the maintenance manual for the KR-87...

**Comment by tonghuix** [comment]
See this video, jump to 5:17 directly, it shows every antenna which installed on c172.
https://www.youtube.com/watch?v=bhwM91QE66s

**Comment by okroth** [comment]
And it says at 6:48, the ADF sense and loop antennas may be a combined unit, what the KA-44B is.
The KA-44B is specific to the KR-87.

**Comment by wkitty42** [comment]
On 04/06/2018 11:26 AM, okroth wrote:
> A plane without wire antenna has either no ADF or the KR-87 and KA-44B.
> A plane with KR-87 has no wire antenna.
> BTW... I have found and downloaded the installation manual and the maintenance 
> manual for the KR-87...


ok, so the real question is "does our c172p have a KR-87 installed?"... IIRC, 
our craft is based on a certain RL craft that has additional liveries applied to 
it... otherwise it is the same as the specific RL c172p... again, IIRC...

**Comment by okroth** [comment]
Models/c172p.xml defines a model named kr87 that refers to Interior/Panel/Instruments/kr87-adf/kr87.xml which defines the King KR-87.
To me this looks like the KR-87 is installed

**Comment by wkitty42** [comment]
by jove, i think you're right :smile_cat: 

![20180406-c172p-kr-87-tso-01](https://user-images.githubusercontent.com/4641713/38447337-be15ee9a-39ca-11e8-8242-5abe93d32b23.jpg)

**Comment by gilbertohasnofb** [comment]
@okroth can you please confirm my understanding for this is correct:

1) we should remove the wire connecting the tail to the wings
2) we should add the following antennas which are missing to our aircraft (in orange):

![image](https://user-images.githubusercontent.com/5700795/43371414-6cc300f0-9389-11e8-99ce-e493ed2dc5e6.png)

I checked _many_ photos of model P's today and while nearly 100% do not have the wire, there is a lot of variation regarding the other antennas. So maybe this here is a good reference:

![](http://imgproc.airliners.net/photos/airliners/3/6/8/5036863.jpg?v=v46c7b2210e7)

Please confirm so we can start working on this.

**Comment by okroth** [comment]
Hi,

from Information manual, section 6 "Weight and balance list":
GPS antenna "bubble" centered on top of cabin 43.5" aft datum (firewall)
ADF antenna "soap" centered on bottom of cabin, 39.3" aft datum
Transponder antenna (shark fin) left side on bottom of cabin, 85.3 aft datum
COM1, COM2 antennas on top of cabin, 61.2 aft datum
VOR1, VOR2 antennas 253.4 aft datum
Marker beacon antenna (looks like a wedge) on bottom, 130.7 aft datum
ELT antenna on top of tail, 122.0" aft datum

all distances refer to the CG of the equipment.

-- 
Oliver

Am 30.07.2018 um 00:47 schrieb Gilberto Agostinho:

**Comment by gilbertohasnofb** [comment]
@okroth That's quite helpful but are you sure you are using the model P's POH? I am absolutely sure this model did not come with a GPS out of the factory so I am surprised you are mentioning the GPS antenna on top of the wing. I searched the POH for the keyword GPS and came out with zero results.

**Comment by okroth** [comment]
Hi Gilberto,

I am sorry, you are right; I have looked into a 172R IM.
Let me check if I can find the right one.

-- 
Oliver

Am 31.07.2018 um 13:54 schrieb Gilberto Agostinho:

**Comment by gilbertohasnofb** [comment]
@okroth Thank you so much for the help finding the correct information, I _really_ appreciate it!

**Comment by okroth** [comment]
Hi Gilberto,

found the right book, a 1998 European version (D-EACK):

GPS 1102mm aft datum
Transponder antenna 2200mm  aft datum
ADF antenna: 1143mm aft datum
DME - none
COM1, COM2 antenna: 1608mm aft datum
VOR1, VOR2 antenna: 5893mm aft datum
Marker beacon antenna 3338mm aft datum
ELT antenna 3099mm aft datum

-- 
Oliver


Hi,

from Information manual, section 6 "Weight and balance list":
GPS antenna "bubble" centered on top of cabin 43.5" aft datum (firewall)
ADF antenna "soap" centered on bottom of cabin, 39.3" aft datum
Transponder antenna (shark fin) left side on bottom of cabin, 85.3 aft datum
COM1, COM2 antennas on top of cabin, 61.2 aft datum
VOR1, VOR2 antennas 253.4 aft datum
Marker beacon antenna (looks like a wedge) on bottom, 130.7 aft datum
ELT antenna on top of tail, 122.0" aft datum

all distances refer to the CG of the equipment.

-- 
Oliver

Am 30.07.2018 um 00:47 schrieb Gilberto Agostinho:

**Comment by okroth** [comment]
Ahem...

just found out that this is a 172S
so put that away...

I continue digging

-- 
Oliver


Am 31.07.2018 um 14:28 schrieb Gilberto Agostinho:

**Comment by legoboyvdlp** [comment]
@okroth 
[Cessna_172_C172P-1982-POH.pdf](https://github.com/c172p-team/c172p/files/2245513/Cessna_172_C172P-1982-POH.pdf)
This is the POH we are using if it helps :)

**Comment by gilbertohasnofb** [comment]
What about this one? This one is searchable which makes it quite handy. 
[Cessna 172P POH without Supplements (N98456).pdf](https://github.com/c172p-team/c172p/files/2246462/Cessna.172P.POH.without.Supplements.N98456.pdf)

**Comment by wlbragg** [comment]
I think we already have the one but it will need to move forward.

![ant](https://user-images.githubusercontent.com/11069680/43680217-a1dd9a3c-97fa-11e8-8584-a75d392e4840.jpg)

The other two though I think must be identified as to which piece of equipment they go to and that we have that equipment. In other words I want to make sure all our equipment matches up with all the antennas we install.

**Comment by gilbertohasnofb** [comment]
I also would love the antennas to match everything we have but after spending hours chasing this information I simply gave up. Perhaps @okroth could help us make an informed decision (guess?) of which ones to include and where they should be.

**Comment by wlbragg** [comment]
Hum, the antenna I posted the image of is the transponder ant.
I'm re-reading the above thread. It may have enough info to make a logical assumption about the other two antenna.

**Comment by wlbragg** [comment]
Our ELT may not have an external antenna, we need to verify that.

>KR-87 ADF uses a "complex antenna (KA44 or KA44B) 

We are missing:

ADF antenna, "soap" (non-wire version)
Marker beacon antenna (looks like a wedge) on bottom

**Comment by wlbragg** [comment]
So I say we for sure...
remove the wire
do the ADF "soap" on bottom center under cabin
move the transponder ant to aft

potentially add...
marker beacon ant
elt ant

**Comment by gilbertohasnofb** [comment]
> Our ELT may not have an external antenna, we need to verify that.

Are there models without antenna?

**Comment by wlbragg** [comment]
>Are there models without antenna?

I  don't know. I mean the same as our GPS has a built in antenna VS an external antenna. Maybe the ELT was an after market "portable" addition, if they even have such a thing?

**Comment by wkitty42** [comment]
i think he was just using our hand-held GPS as an example of a device in the craft without an external antenna...

anecdote: as far as internal or external antennas go, i know of numerous vehicles with antenna that are hidden within the vehicle's body... we had a conversion van that had numerous antennas running parallel to the ceiling inside the vehicle... IIRC, there were six or seven different radios installed... the roof on this vehicle was fiberglass so there was no metallic shielding to get in the way of signals... the antenna were hidden and no one knew the radio equipment that was in the van... if they had, i'm sure the gendarmes would have been involved numerous times as would an automotive body repair shop :wink:

**Comment by wlbragg** [comment]
>i think he was just using our hand-held GPS as an example

Yes, I was using it as an example of why it's possible the ELT also wouldn't have an exterior antenna.

**Comment by gilbertohasnofb** [comment]
@wlbragg if the ELT antenna is the one just behind the back glass, I noticed that most model P's do have that. Take a look at this: http://www.airliners.net/search?keywords=172p

**Comment by wlbragg** [comment]
Done!

**Comment by gilbertohasnofb** [comment]
I am about to push, here are the new textures. They should be texture dependent since different liveries will have different antenna colours, ok?

![image](https://user-images.githubusercontent.com/5700795/43685453-399c2482-98ab-11e8-997e-7eeca5f788d6.png)

**Comment by gilbertohasnofb** [comment]
I am now syncing all other liveries and adding these to them with the correct colours for each antenna (according to the livery). I should push them all shortly.

Btw, I noticed a small bug: our VOR antenna has a hole

![image](https://user-images.githubusercontent.com/5700795/43685583-943abd7a-98ad-11e8-92d5-d6daef3ea85a.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg also please make sure the VOR antenna is livery dependent, that texture was present only on the 4X-CHV but I now added to all liveries and matched their colours.

**Comment by gilbertohasnofb** [comment]
@wlbragg one more question, what textures are the COM antennas (above the wings) mapped to?

**Comment by wlbragg** [comment]
![vhf](https://user-images.githubusercontent.com/11069680/43687427-9bbcba70-989a-11e8-960f-18613b95538f.jpg)

**Comment by gilbertohasnofb** [comment]
Ok, so I have made a mistake in my last push, I coloured those thinking it
was the VOR antenna. I will fix that, but first please do let me know if
the VOR antennas are mapped anywhere because if they are not then I can add
their textures to the same file.

**Comment by wlbragg** [comment]
@gilbertohasnofb they were all mapped to the same texture.

![vor](https://user-images.githubusercontent.com/11069680/43687763-be991ae2-98a0-11e8-908a-8e65afc4c8bf.jpg)

**Comment by wlbragg** [comment]
I forgot, the yoke cords need added to the light maps. There was a part of the yoke overlapping so I had to move it below.
![lm_yoke-l_new](https://user-images.githubusercontent.com/11069680/43687768-ef7ed926-98a0-11e8-901b-de6173e14d28.png)
![lm_yoke-r_new](https://user-images.githubusercontent.com/11069680/43687769-ef980162-98a0-11e8-8d85-4b7e1b801c28.png)

**Comment by wlbragg** [comment]
@gilbertohasnofb let me know when I can pull again and do the antenna mapping.

**Comment by wlbragg** [comment]
@gilbertohasnofb in you picture of the textures for mapping the antenna you have the far right side as "marker" (fin). It is actually supposed to be the transponder. The "marker" antenna, from what I understand is also a "fin" type. I think that is why they show two fins in some of the pictures. So, I will add on other "fin" antenna under the cabin, forward of the ASF antenna (soap). Be sure to account for it's texture as well.

**Comment by gilbertohasnofb** [comment]
@wlbragg Ok, so I will add a new texture for the VOR so that VOR and VHF are separate, ok? Please add the other fin and I will add a texture square for it later (I need to see it first in order to colour it properly). I will also try to fix that mixture LM issue and add the yoke cable. I will take a look at this all in a few hours.

**Comment by wlbragg** [comment]
OK, I will push the new fin shortly.

**Comment by wlbragg** [comment]
@gilbertohasnofb are all of these supposed to be livery dependent?

TransponderAntenna
MarkerAntenna
Antenna_ADF
Antenna_VOR
VHFAntenna
ELTAntenna

**Comment by gilbertohasnofb** [comment]
@wlbragg I will sync all liveries with these antennas so please make all of them livery dependent. It's better to do this than to be puzzled in the future. Here are the positions of the new VOR and Transopnder antennas:

![image](https://user-images.githubusercontent.com/5700795/43689948-a8e10e4a-98f9-11e8-8274-0b77f212d386.png)

I will push it soon, just need to add it to all liveries.

**Comment by gilbertohasnofb** [comment]
Sorry, forgot to add the VOR base:

![image](https://user-images.githubusercontent.com/5700795/43689967-149fd4e0-98fa-11e8-999d-5e67d35564d7.png)

**Comment by wlbragg** [comment]
Done!

**Comment by gilbertohasnofb** [comment]
@wlbragg The ELT antenna is not properly mapped. See:

![image](https://user-images.githubusercontent.com/5700795/43708852-54e97e02-9963-11e8-8c13-c5ff84b4a40f.png)

Part A should be black and part B should be brighter. See https://github.com/c172p-team/c172p/issues/1046#issuecomment-410513845 for the two rectangles I added, a black one marked as ELT wire and another fuselage colour marked as ELT base.

Also, there is a UV-mapping issue with 4X-CHV on the front end of the tail (see green arrow above).

All else looks good!

**Comment by gilbertohasnofb** [comment]
Look at the ELT antenna here for reference:

![](https://user-images.githubusercontent.com/5700795/43679356-c353f640-981b-11e8-83f1-5119b4e72ee7.png)

**Comment by wlbragg** [comment]
@gilbertohasnofb it's the glare, see...

![elt](https://user-images.githubusercontent.com/11069680/43731973-d3f596ba-9975-11e8-9cc2-372e2c8888a1.jpg)

**Comment by gilbertohasnofb** [comment]
You are right, I just zoomed in in the sim and it is the glare. Is it possible to diminish the glare of this antenna? Very minor thing, but would look better.

Also, talking of minor things, I found another hole:

![image](https://user-images.githubusercontent.com/5700795/43732214-dde705fe-99a8-11e8-8be3-7fb6f934ab9a.png)

And if you have a chance, please do take a look at that UV-mapping issue with the tail I mentioned above (green arrow in the post with the 'glared' antenna)

**Comment by okroth** [comment]
Correct

**Comment by wlbragg** [comment]
@gilbertohasnofb I fixed the ELT antenna issue. I reduced the specular reflection and rounded the tip (it wasn't missing, it just looked like it).
One other issue, look at the ELT through the back window (from above). It has a built-in antenna. Should we remove the built-in antenna?

![tail1](https://user-images.githubusercontent.com/11069680/43740249-534694e0-9990-11e8-8ae9-902b5fa57a49.jpg)

The tail mapping issue, now that is a can of worms. I think I about got it fixed but that entire tail section is a REAL MESS. Between the alignment of the two halves (left and right) and the rivets (bumpmap), it is really ugly. I've spent over an hour trying to figure out the mapping just to revert back to the original. I need you to change the texture slightly to finish it.

![tail2](https://user-images.githubusercontent.com/11069680/43740244-4f47b216-9990-11e8-97a1-66af486419b8.jpg)

**Comment by wlbragg** [comment]
@gilbertohasnofb I pushed my changes already.

**Comment by gilbertohasnofb** [comment]
> One other issue, look at the ELT through the back window (from above). It has a built-in antenna. Should we remove the built-in antenna?

That's not an antenna, that's a cable. It should go towards the antenna, could you try to deform it a bit so that it goes towards the back of the plane?

![image](https://user-images.githubusercontent.com/5700795/43740630-ae900bdc-99c3-11e8-9583-aa64ac226f41.png)
![](http://www.midwestflyer.com/wp-content/uploads/2011/12/406-ELT-Photos-Article-Web.jpg)
![](http://www.rv7blog.com/images/20061231_elt1.jpg)

> The tail mapping issue, now that is a can of worms. I think I about got it fixed but that entire tail section is a REAL MESS. Between the alignment of the two halves (left and right) and the rivets (bumpmap), it is really ugly. I've spent over an hour trying to figure out the mapping just to revert back to the original. I need you to change the texture slightly to finish it.

Excellent, let me take care of this real quick before you move back to the ELT.

**Comment by gilbertohasnofb** [comment]
@wlbragg done and pushed. That solved it thanks a lot!

**Comment by wlbragg** [comment]
Cool, I'll pull and fix the ELT wire to the antenna.

**Comment by gilbertohasnofb** [comment]
Super work with the ELT, love the simple solution.
