### ISSUE TITLE
BAT and ALT master switches should be interlocked

### ISSUE THREAD

**Issue by okroth** [c172p-team/c172p#1052]
When you switch ON the ALT master switch, the BAT is switched as well
When you switch OFF the BAT, the ALT is switched off too.
There are small tabs at the backside of the red rockers that move the other rocker accordingly.
Reason is to avoid that the alternator is on the electric network without the buffering battery.
![ces_s-1994-1-1a](https://user-images.githubusercontent.com/10168496/38447101-d24e1aa0-39fb-11e8-91ac-ac16c07b66e3.jpg)
You could implement this coupling in the animations

**Comment by gilbertohasnofb** [comment]
So let me see if I understand what you are suggesting:
* switching the alternator ON will also switch the battery ON if the latter was OFF
* switching the battery ON will not affect the alternator state
* switching the alternator OFF will not affect the battery state
* switching the battery OFF will switch the alternator OFF as well if the later was ON

Is that correct?

**Comment by tonghuix** [comment]
@gilbertohasnofb I think you are correct.

**Comment by okroth** [comment]
Yes,

that is the correct behaviour

**Comment by gilbertohasnofb** [comment]
Great, thank you so much.

@AmaluSusan you were looking for an issue to tackle, would you be interested in this one?

Also, we have just added a [CONTRIBUTING.md](https://github.com/c172p-team/c172p-detailed/blob/master/CONTRIBUTING.md) file to our repo detailing our preferences of style and how to contribute.

**Comment by AmaluSusan** [comment]
Yeah I’m interested.

**Comment by gilbertohasnofb** [comment]
Great, give me or @onox a shout if you need any help. Looking forward to your PR.

**Comment by wlbragg** [comment]
>There are small tabs at the backside of the red rockers that move the other rocker accordingly.

Looks like you can see the tab on the alt switch in the shot above. The logic you describe would be achievable with that "single" tab, (not that we need this visual for the sim as it is so small).

>Reason is to avoid that the alternator is on the electric network without the buffering battery.

This is interesting as normally, in a car,  the alternator is wired to the battery through the regulator. The is no method to isolate either one nor to turn off either one. Any idea why there is this option in an aircraft such as this?

**Comment by gilbertohasnofb** [comment]
@wlbragg I don't think I can see the tab in the image above, but as you write it's too small to bother to model anyway.

> Any idea why there is this option in an aircraft such as this?

I've seen at least one airclub checklist for the model P requiring you to have only the battery on while starting the engine, and then turning the alternator on only a bit later once the engine is running and stable. Also, I think you need to turn off the battery if you want to do an alternator check. But take all this information with a grain of salt.

**Comment by okroth** [comment]
If your engine fails, the alternator does not provide power, but needs current to feed the electromagnet in the rotor winding. This is approx 1.5 ... 2.5A which you would like to save with a 12.5Ah battery...
The alternator is never connected via the regulator, only six diodes are between the stator winding and the alternator relay. The regulator regulates the current in the rotor winding and such the strength of the magnetic field, and this way the generated voltage.
And regarding the voltage check: you turn the alternator off to see the voltage warning to come up.
One will never like to switch off the battery while the alternator is running as the battery is needed as buffer to stabilise the voltage should it rise too high.
That is the reason for the small tabs interlocking ALT and BAT switch.

**Comment by onox** [comment]
@AmaluSusan Do you still want to work on this? You could fix it in the animation files in `Models/` or you can use some `<logic>` elements in `Systems/instruments.xml`. In that case you use 2 `<logic>` elements (1 to turn on the battery when the alternator is on, and 1 to turn off the alternator when the battery is off). I prefer this approach over fixing it in the animations because there might be other code that programmatically switches the alternator/battery.

For the alternator, use: `<input><true/></input>` and `<enable><property>path/to/alternator</property></enable>` and `<output><property>path/to/battery</property></output.`.

For the battery you need to use `<false/>` instead.

**Comment by gilbertohasnofb** [comment]
@AmaluSusan Are you still interested in this issue? If so, try what @onox wrote above and we can also give you a hand if you need it.

**Comment by wlbragg** [comment]
@gilbertohasnofb I went ahead and did this.

**Comment by wlbragg** [comment]
@onox, I did it in the animation, I couldn't get the enable to work correctly, It was like they were fighting each other. I don't see where this is going to be changed anywhere else and besides that this is a mechanical system. If you did change the electrical through breakers or whatever, it wouldn't change the switches. So in this case I think it is more appropriate to do it in the animation.

**Comment by onox** [comment]
> It was like they were fighting each other.

They shouldn't be if you use `<enable>`.

> If you did change the electrical through breakers or whatever, it wouldn't change the switches. So in this case I think it is more appropriate to do it in the animation.

The breakers have nothing to do with it. Ideally all the logic (model [1]) that modifies the state of the mechanical system should be together in 1 unit/file. And the animations (view [1]) simply reflect the current state.

[1] https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller

**Comment by wlbragg** [comment]
Are you supposed to use a condition tag inside of the enable tag?

**Comment by onox** [comment]
Yeah I think so. In my experience with other models, when you use `<and>` or `<not>` for example you need a condition tag.
