### ISSUE TITLE
Nose gear should be disconnected to rudder pedal when airborne

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p#1068]
I read a book that shows

> During flight the nose wheel extends fully, bringing a lock mechanism into place which hold the nose wheel center and free from rudder pedal action.

So I convince that the nose gear should not controllable when airborne.

**Comment by okroth** [comment]
correct, the nose wheel is locked in straight direction and will not turn around its (nearly) vertical axis when airborne.
The connecting rods between the rudder pedal axles and the steering ring contain springs to allow rudder movement with blocked nose wheel steering.

**Comment by onox** [comment]
What if you make a slight turn and then lift the nose off of the ground? Does it jump to the neutral position or will it lock once you manually (with pedals) move it to the neutral position?

**Comment by okroth** [comment]
There is a flat spot at the oleo at which a lug on the torque link is pressed when the wheel drops down. 
![torque-link2](https://user-images.githubusercontent.com/10168496/39121597-66505d3c-46f2-11e8-8918-db5e1026faa1.png)

This centres the wheel, which can anyway deflected only by 10°left or right with rudder pedal input. It can turn up to 30°  like a shopping cart caster wheel. The centring mechanism is there to stop the nose wheel from flutter.

**Comment by gilbertohasnofb** [comment]
@okroth Many thanks for these reports, in particular with all the sources that you give! That's super appreciated.

> This centres the wheel, which can anyway deflected only by 10°left or right with rudder pedal input. It can turn up to 30° like a shopping cart caster wheel. 

I am having a bit of difficulties understanding the phrase above. Are you saying that the wheel on the ground can deflect only 10 degrees? If so, what does the 30 degree figure mean?

**Comment by okroth** [comment]
You can turn the nose wheel by 10° using the rudder pedals. It can turn further 20° by side force, e.g. when you brake left main gear wheel, the nose moves left, and the nose gear follows, similar to wheels on a shopping cart. However it will not turn more than 30° left or right. There is a sentence in the POH about this in the POH page7-12: "If the airplane is to be towed by vehicle, never turn the nose wheel
more than 30° either side of center or structural damage to the nose gear could result."

**Comment by gilbertohasnofb** [comment]
@onox what about this: what if the rotation of the nose wheel is controlled by a single property which is the result of the multiplication of the rudder displacement by another variable. This variable will be 1.0 when in the ground and smoothly go to 0.0 when the front WOW is `false` using a filter with a certain `max-rate-of-change`, so that the animation of the wheel will smoothly move to the centre if one takes off with a not centred wheel. Or is this a bit of an overkill?

**Comment by wlbragg** [comment]
>so that the animation of the wheel will smoothly move to the centre if one takes off with a not centred wheel.

I'm not so sure you need this smooth. Looking at the diagram (it's hard to tell), but it looks like (yellow) the main gear strut drops enough that the "yellow" piece might snap and lock the gear from moving, if I'm looking at this correctly. It's not clear what straightens the gear strut to allow this to happen.

**Comment by gilbertohasnofb** [comment]
But even a fast snap would look better animated, else it just teletransports to the correct position and will look like a bug. My 2 cents.

**Comment by okroth** [comment]
It's not snapping. When the oleo expands, the torque link straightens until the yellow part (stop lug) comes into contact with the flat rear side of the oleo end. As that is fixed, also the torque link, and as such the nose wheel is turned straight.
It may help to know that the rudder steering rods turn the steering collar which is rotating on the fixed upper oleo. The torque link then transfers to rotation of the steering collar to the lower oleo tube, where the fork carrying the nose wheel's axle is attached.

**Comment by HHS81** [comment]
The extension of steer angle is simulated in the c182s. The lock of the nose-wheel gear steering in flight is New to me,  never read anything about that.

**Comment by okroth** [comment]
Read here: https://www.mcfarlaneaviation.com/media/documents/torque-link-kit-eligibility.pdf, fifth page (numbered 120)

**Comment by legoboyvdlp** [comment]
Pull request on its way!

**Comment by legoboyvdlp** [comment]
Does the NWS need to be added to the flight recorder? I can't check if it already was at the moment.

**Comment by wlbragg** [comment]
Unfortunately my recorder is broken and I can't test, but the answer should be yes, at the least, any new property that is driving the animation needs to be added. Can you recall what properties you created and what properties changed in the animation?

**Comment by legoboyvdlp** [comment]
The property that should be recorded is whatever is rotating the nose wheel in c172p.xml. Once I get round to it, I'll add it in another pull request.

**Comment by dany93** [comment]
Could it be fdm/jsbsim/fcs/steer-pos-deg?

**Comment by wlbragg** [comment]
>Could it be fdm/jsbsim/fcs/steer-pos-deg?

Yes, it might be only that one property needed.
