### ISSUE TITLE
Improve the seats and remove headrests

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1069]
The seats in a typical 172 of this time do not have headrests, see the photo below of a 172P:

![image](https://user-images.githubusercontent.com/5700795/39217441-f3eb5d4c-4817-11e8-8fed-f462394f8d74.png)

@wlbragg we could 'borrow' the seat model from the c182s which does look better than ours, but we would need to do two things to adjust it: first, we would need to continue using our seat mounts which have a nice model and match the 172 reference images. Secondly, we would need to re-UV-map it to our current textures. Alternatively, we can simply remove the headrests and maybe add some few more polygons to the current seats.

**Comment by gilbertohasnofb** [comment]
Another reference:

![](http://orapweb.rcahms.gov.uk/coflein/A/AP_2005_1052.jpg)
![](http://www.directwfc.com/images/airplanes/64287_I.jpg)
![](http://www.directwfc.com/images/airplanes/9815L_I.jpg)
![](http://euram.at/shop/img/p/1/2/0/9/1209-thickbox.jpg)

**Comment by wlbragg** [comment]
I just did a search and the second image I came across shows seats with a headrest. In fact I saw close to as many with head rests as without. They were all 172p Skyhawk's. So it looks like they come both ways. With that said I'm not opposed to upgrading the seats eventually. I'm not sure I am the one to try to create them though, replace them with an existing model, maybe. Something else I am concerned about is reusing too much of the c182 model. I think we need to keep a distinct difference between the two. Also, after looking at the 182, those are also seats with a headrest?

**Comment by gilbertohasnofb** [comment]
> They were all 172p Skyhawk's

Are you sure about that? When I type 'cessna 172 seats' on Google most images have a headrest, but then again most images are from very modern 172 models such as the 172SP. Also, there is a bunch of images of older planes with _replacement_ seats which might have headrests, but those are not original. 

> Something else I am concerned about is reusing too much of the c182 model. I think we need to keep a distinct difference between the two. Also, after looking at the 182, those are also seats with a headrest?

I honestly don't see any problems of using stuff from the c182s, but you are right about the seat model used there: those are a more luxurious leather one with headset, not the trashy Cessna seat from early 1980. My mistake, I wrote this by memory instead of checking in the sim, so ignore the suggestion of using those models.

**Comment by ltoenning** [comment]
I just looked into the .blend file and quickly removed the headrest. 

![unbenannt](https://user-images.githubusercontent.com/1716810/39919662-a27000bc-5514-11e8-981d-f2c34173dd22.JPG)

Would that be like you want to have it?  (I left the headrest here on the right front seat just for comparison)

**Comment by gilbertohasnofb** [comment]
Guys, please always contact @wlbragg before doing _any_ 3D work, our Blender file is _extremely_ sensitive and it is not git friendly. We cannot have two different PRs both dealing with a same Blender file, else one of them will get ignored.

As for the seats, removing the headrests is a good start but I think we might need to improve the model a little bit, at least adjust the size (they are too low as Tong pointed out). 

@wlbragg and I are going to start working on a second round of improvements for the interior 3D model and texture so we will get to this issue eventually.

**Comment by wlbragg** [comment]
>We cannot have two different PRs both dealing with a same Blender file, else one of them will get ignored.

For clarity, using your local blend version to demonstrate a proposed change and posting the results is of course OK, it can actually be very helpful to whoever eventually does the Blender work and for discussion. But referring to what @gilbertohasnofb is pointing out, please don't make a blender change that you expect merged into master along with creating a PR for it without consulting first. It will have to be coordinated. Personally I encourage anyone that wants to get their teeth wet in Blender to go for it. We (I) could use the help, it's just as @gilbertohasnofb stated, it is a sensitive file that has many nuances that need to be adhered to and not at all GIT friendly.
I am in a continuous learning cycle every day with the organizational side of the mesh, texture and material settings. The worst thing is discovering a less than optimal setup after the fact and having to backtrack to try to fix it. Something I fear is going to bite me in the butt with the proposed AO and light maps we want to create.

**Comment by gilbertohasnofb** [comment]
@wlbragg given the size of the seats they might end up influencing the AO and light maps so I guess we also need to tackle this before baking new ones. Do you think you could take a look at it? Basically removing the headrest and making the back bit a bit taller would already suffice (note in the photos above how the seat goes as high as the glareshield, more or less). We could also make the seats a bit 'rounder' by adding a little bit more vertices, does Blender has an automated function to smooth complex objects? We could give that a try so that this would be very little work for you.

**Comment by wlbragg** [comment]
@gilbertohasnofb 
Yeah, I think it is all doable.

**Comment by wlbragg** [comment]
Because were doing this I want to get this part correct. Please examine this comparison and describe you impression of seat height, size, seat mounting frames height and size.

![seats1](https://user-images.githubusercontent.com/11069680/39971592-76975ade-56c3-11e8-8afe-5455f18a481e.jpg)

**Comment by gilbertohasnofb** [comment]
Great photo and angle!

* seat frames in the floor should be a tiny bit taller
* seat cushion should have an angle (front part pointing a bit upwards), otherwise thickness is good
* seat cushion needs to be moved upwards (by making the mounting frame taller)
* back support part should be quite taller, nearly reaching the glareshield height
* back side of back support model should be flatter than the front side
* there is a pocket but we don't need to model it if you think it's too much trouble

**Comment by wlbragg** [comment]
>back side of back support model should be flatter than the front side

Did you mean to say "FATTER" instead of "flatter"? Or are you talking about the shape?

**Comment by gilbertohasnofb** [comment]
I meant flatter, but it's just a small detail. Right now our seat is curved on the back side of the backrest while in the photo it's pretty much flat, but that's a veeery low priority thing.

**Comment by wlbragg** [comment]
OK, I see you said "back support" as in back rest, I missed that, gotcha!

**Comment by gilbertohasnofb** [comment]
Apologies for the broken English, for the second message I did look in a dictionary in order to make sure we were understanding each other :smiley:

**Comment by wlbragg** [comment]
@gilbertohasnofb 
What do you thing, I pushed it so you can see it live.
![st2](https://user-images.githubusercontent.com/11069680/39972192-701578b0-56cf-11e8-9e20-6192d9b4dddd.jpg)
![st1](https://user-images.githubusercontent.com/11069680/39972193-7035e9ba-56cf-11e8-9347-ac5d13689fe4.jpg)

**Comment by gilbertohasnofb** [comment]
> What do you thing, I pushed it so you can see it live.

That would be great. Just do a git pull before as I pushed two commits. And we really need to tackle https://github.com/c172p-team/c172p-detailed/issues/1106 still today as that is breaking the release. I would suggest stopping everything and going for that one on a clean branch. I can test it if we manage to fix in the next hour or so but tomorrow I will have a very early and busy day :sob:

**Comment by wlbragg** [comment]
@gilbertohasnofb 
>they are too thin

I will fix that.

>the pilot and copilot are not properly positioned any longer. 

I can change that.

>they look so oversized in comparison with our aircraft, is there a way of forcing these models and walker to be a bit shorter?

Should be able to. I'll look at that also.

**Comment by gilbertohasnofb** [comment]
Great!

> Should be able to. I'll look at that also.

Needs to do the same for all the pilot, copilot and walker models

**Comment by wlbragg** [comment]
@gilbertohasnofb I may have spoke too soon. This looks like it could be a nightmare. I will be really disappointed if we can't change our interior, like new or different seats, because of a pilot model that we don't even control. This is one of the main reason I absolutely hate using shared resources.
This human model system is somewhat complex, i had no idea. I'm still looking at the code and configuration. Do you know if it is the same model system used for the walker and the pilot/copilot models? Or are they two different model systems?

**Comment by gilbertohasnofb** [comment]
I think it's the same model for the pilot and walker, but I am not familiar with how they work. I also hate using these shared resourced, someone had once proposed improving these models but it's 4 years later and it never happened, since it's much more annoying to fix something in FGData than just here in our repo. Same could be said about our instruments: had they not being made local we would never had the same motivation to improve them (I redid the textures of virtually every single gauge). We could very well have a local copy and improve it for our needs and then see if people would like to merge them back. 

But that said, I know that @D-ECHO was working on some amazing models for his glider and he mentioned that he might want to replace the walker and default pilots with those. Maybe we could for the moment being just raise the pilot, copilot and passengers and live with them for a while.

@D-ECHO any news about those models?

**Comment by gilbertohasnofb** [comment]
@wlbragg See: https://github.com/viktorradnai/flightgear-ask21/issues/140

Perhaps it would be great to have a model without the hat and sunglasses as well (that outift look _very_ much made for a glider).

**Comment by wlbragg** [comment]
@gilbertohasnofb It's not as bad As I anticipated. It looks like there is one offset number to move everything around. Resizing though may be another story. We may have to live with the head poking through the wing!

**Comment by gilbertohasnofb** [comment]
No problems, we have lived with that for quite some time already. Let's hope those new models would arrive one day, they look so much better as well... 

I am off for today. Do check the new textures I pushed and see what you think of them and let me know if something is unclear. They might give you a bit of work re-UV-mapping everything but hopefully not too much.

**Comment by gilbertohasnofb** [comment]
> Our models appear to have the animation portion disabled. Anyone know why, or what is needed to enable them?

I think I did bring this up once many years ago and I suspect the reason is that animating the model involves a lot of work and fine tuning (e.g. the hands must be at the yoke all times, the foot should move together with the pedals) and nobody took this job up. But frankly, given how ugly these models are, I would wait a tiny bit more and see if the models get replaced before investing a lot of time on that.

**Comment by D-ECHO** [comment]
I haven't had any progress on these models unfortunately. A major problem is getting them into the correct position, I think there can be something done using armatures but I have never used this

**Comment by gilbertohasnofb** [comment]
That's a pity :disappointed:
