### ISSUE TITLE
Add Low Voltage LED to the Panel

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1096]
![](http://3.bp.blogspot.com/-cuJ9C1x7EI0/TkX8ER45PpI/AAAAAAAAKG8/N-akWc1MOdM/s1600/Cessna%20172%20Interior%20%285%29.jpg)

![](https://farm7.staticflickr.com/6195/6066184333_b3b1cc4a55_b.jpg)

To the right of the battery voltage indicator there should be a small red button or LED (not certain which) with the legend LOW VOLTAGE.

![](https://upload.wikimedia.org/wikipedia/commons/9/96/C172M-76panel.jpg)

I would appreciate anyone who knows about the 172 or has access to one giving some information about this - is it a light or a button? 

Apologies for scanty information, but this does not have to be added until enough is known about it and what it does...

**Comment by legoboyvdlp** [comment]
AFM or POH should have more information. 

https://www.pprune.org/archive/index.php/t-44013.html

This forum topic suggests it is a light which glows red.

**Comment by legoboyvdlp** [comment]
From pprune: https://www.pprune.org/archive/index.php/t-553380.html

The Cessna-style (+)(-) and (0) ammeter works because it is literally wired in series with the (+) battery lead wire, which is routed behind the panel between the Battery Contactor (operated by the Master Switch) and the Primary Bus Bar. When current is flowing from the bus bar into the battery, the ammeter shows a (+) deflection. If the alternator fails or is switched off with the ALT half of the Master Switch, current flows through the ammeter in the opposite direction - from the (+) terminal of the battery into the Primary Bus Bar - thus the needle is deflected the opposite direction towards (-) (also the ACU detects a low voltage condition and illuminates the "Low Voltage" warning light). If the battery charge is topped off and the electrical system is in happy equilibrium then the needle is vertical at (0), because no current is flowing either into or out of the battery.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp When adding images to issues, PRs or comments, do not just paste the link but use the following:

`![](link)` substituting `link` for the image url. This will display them as images here in GitHub.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Is that a button or a LED? The quote above talks of a 'Low Voltage warning light', and they do look like a cylindrical LED to me.

**Comment by gilbertohasnofb** [comment]
At around 7:00 in this video you can see that it is a LED. It's first on and then it goes off when the engine starts: https://www.youtube.com/watch?v=sLFX33Ogmus

**Comment by legoboyvdlp** [comment]
Right, thanks!

**Comment by wlbragg** [comment]
@gilbertohasnofb 

First pass at the Low Voltage LED.
Needs texture for the base and the lamp.
![led2](https://user-images.githubusercontent.com/11069680/43032141-6dad50da-8c75-11e8-9d9e-c6a9a9315087.jpg)
![led1](https://user-images.githubusercontent.com/11069680/43032142-6f6c3e04-8c75-11e8-9865-8e132cc904af.jpg)
![led](https://user-images.githubusercontent.com/11069680/43032149-94de5a0a-8c75-11e8-82a0-52592e9ce552.jpg)

**Comment by wlbragg** [comment]
Anyone want to volunteer to create the system logic for this?

**Comment by gilbertohasnofb** [comment]
@wlbragg I will add a texture for the LED lamp and for the metallic base. The model looks good but looks a bit too big for me. I think it needs to be half the current size. Look at those photos above and compare its size to the gauges around it.

**Comment by wlbragg** [comment]
I thought so too, I already reduced it a couple times to get to that size. I was having a hard tine judging it. OK, I'll reduce it some more.

**Comment by gilbertohasnofb** [comment]
@wlbragg I am only judging it from the image you posted, not from what you pushed. My sim isn't running due to my problems. So using your last screen shot, the LED should be smaller.

**Comment by gilbertohasnofb** [comment]
@wlbragg textures pushed to `panel_parts` on the top right corner:

![image](https://user-images.githubusercontent.com/5700795/43041470-a8a72ca8-8d59-11e8-99e5-b1e3a61de144.png)

The question is how do we make the LED turn brighter when on? Do we need a second texture which has a more intense red and much lighter?

**Comment by wlbragg** [comment]
>Do we need a second texture which has a more intense red and much lighter?

Yes, that is how I would prefer to do it.

**Comment by wkitty42** [comment]
On 07/21/2018 09:48 PM, Gilberto Agostinho wrote:
> The question is how do we make the LED turn brighter when on? Do we need a 
> second texture which has a more intense red and much lighter?

ummm... i don't understand... is there something wrong with using a procedural 
light here like is done for the beacons and strobes? why do people do this?

**Comment by gilbertohasnofb** [comment]
> Yes, that is how I would prefer to do it.

I will add a second bright red LED texture then. Maybe we can add a tiny bit of glare to it just like you did to the post lights, is that possible? 

> is there something wrong with using a procedural light here like is done for the beacons and strobes? why do people do this?

Procedural lights are excellent for exterior lights but would look absolutely out of place in the cockpit. This LED is weak and when lit you can clearly see its shape and texture. A procedural light would simply add a single light blob there.

**Comment by wkitty42** [comment]
On 07/22/2018 07:23 AM, Gilberto Agostinho wrote:
> As for implementing this, does anyone know under what conditions does this
> light turn on?

that was detailed higher in the issue... i know i read it just the other day... 
the talk was about the ammeter and how the needle points to the positive side 
when the battery is charging, to the negative side when draining and in the 
center when not charging or draining... this LED lights at a certain point of 
that process... draining, i think... it lights when draining to give you an 
indication of the drain... it goes off when there's no more drain...

i can't find the beginning of the issue in my email so i can't quote it from here...

**Comment by gilbertohasnofb** [comment]
@wkitty42 Thanks, I just saw that there are some sources above indeed. I will take a look at it all.

@wlbragg now that we have two textures, ON and OFF, how do I go about toggling them? And do let me know if that glare thing is possible similar to the post lights

**Comment by gilbertohasnofb** [comment]
@wlbragg I think this system is super simple, I believe the light goes on whenever the voltage is below the green arc (around 25 V) and when the battery is on. So all I need to implement this is to know how to toggle the LED on and off.

**Comment by wlbragg** [comment]
@gilbertohasnofb I'm modeling the second texture now and will give you the object names to toggle the lights shortly. Yes, I think I can add a procedural "glow" that will enhance the effect. I will also give you that name to add to the on/off toggle logic.

**Comment by wlbragg** [comment]
@wkitty42 another technique that I should probably use is a textranslate animation. On demand it simply moves the texture location from on place on the UV map to another place, thus no need for another object. But you have to deal with UV coordinates (a pain for me) to use it and I don't have any idea how it plays with any of the effects systems so I prefer using this other method.

@gilbertohasnofb I decided to try the textranslate because technically it is less overhead. So you can use whatever property name you want to create for the toggle to turn the light on and off. The property name will be used in the textranslate animation (pushing it now) and I will also use that property name for the procedural 'glow" once I know what you create. The textranslate animation is at line 1450 and is using 
/sim/model/material/instruments/factor
for testing. Change that property to the toggle property you create. That property should be 0 or 1.

**Comment by wlbragg** [comment]
@gilbertohasnofb sorry I took so long, I had to relearn some stuff and also had some distractions.

**Comment by wlbragg** [comment]
@gilbertohasnofb sorry for the confusion.
I assumed you are writing the code to check the voltage and when it is at a certain state you will turn a property of your choosing (you create the property) to on, as in the voltage is low and the light should be on now. All you have to do is replace 
/sim/model/material/instruments/factor
at line 1450 in Models/c172p.xml with your new property that you create and your done.
I was simply saying the property that your replacing (/sim/model/material/instruments/factor) is basically just a placeholder I used to test the animation logic.

**Comment by wlbragg** [comment]
@gilbertohasnofb there was an error in a comment in Models/c172p.xml that broke the sim. I am pushing the correction now along with the Love Voltage Glow line 1460
/sim/model/material/instruments/factor
needs to also be replaced with your new property.

**Comment by wlbragg** [comment]
@gilbertohasnofb I wonder if the on texture should be a brighter orange?

**Comment by gilbertohasnofb** [comment]
Sounds good, just push your modifications and I will take a look at the texture and code.

**Comment by wlbragg** [comment]
FYI: right now if you don't replace those two lines with your new property the Low voltage LED will light up if you turn the post lights to full intensity if you want to see what it looks like.

**Comment by gilbertohasnofb** [comment]
> Low voltage LED will light up if you turn the post lights to full intensity if you want to see what it looks like.

What do you mean by that? I went ahead and implemented the system but I am extremely confused by what you wrote. Are you saying that you tied the post light switch to the texture translate code as a way of me testing it?? If so please don't, I already implemented it properly and it's pushed now. The LED will light up if the voltage is above 0 (i.e. if there is something left in the battery to turn it on and if the BAT switch is on) but will turn off at 25 V (which is around the green arc). It's working as it should. Two things are missing though:
 
* the led should be lit in the night. Right now it's just a bright red texture during the day but it's not a real light
* it's still missing the glare effect 

I brighten up the colour a bit and darkened the off texture as well, but I think it's fairly similar to what I saw. Some of these LEDs are orange others are red, I think what we have now is fine. So do you think you can pull and take a look at these two things I mentioned?

**Comment by wlbragg** [comment]
>Are you saying that you tied the post light switch to the texture translate code as a way of me testing it?? If so please don't, I already implemented it properly and it's pushed now. so please don't, I already implemented it properly and it's pushed now. 

No worries, I'm not communicating this effectively. We're done I think. 

I added the procedural glow and some illumination when the lamp is on. If you have the Master Bat on and the Alt off either running or not the low voltage led comes on.
It looks good both day and night now.

**Comment by wlbragg** [comment]
>I did find a weird bug,

I see it too. It may have to do with the linking of the Master ALT and Bat switch. I'll investigate.

**Comment by wlbragg** [comment]
>It may have to do with the linking of the Master ALT and Bat switch. I'll investigate.

No, I don't think so. This may not be easy to isolate!

**Comment by gilbertohasnofb** [comment]
Ok, I will open a new issue for that.

**Comment by wlbragg** [comment]
@gilbertohasnofb I am getting a low voltage light on idle in the amphibious. I don't know if I maybe let the battery drain prior to this. I suppose letting it idle for awhile should charge the battery past the low voltage point if it is working correctly, yes?

**Comment by wlbragg** [comment]
@gilbertohasnofb I am getting low voltage at idle in all variations. Is this correct?

**Comment by gilbertohasnofb** [comment]
I will take a look at this.

**Comment by legoboyvdlp** [comment]
Ok - it says the same about low RPM on our POH -  light on seems normal especially with electrical load (turning the landing light on and alternator off momentarily is used to test this lamp!), at least for an older Cessna with plenty of wear and tear etc.

**Comment by legoboyvdlp** [comment]
> When current is flowing from the bus bar into the battery, the ammeter shows a (+) deflection. If the alternator fails or is switched off with the ALT half of the Master Switch, current flows through the ammeter in the opposite direction - from the (+) terminal of the battery into the Primary Bus Bar - thus the needle is deflected the opposite direction towards (-) (*also the ACU detects a low voltage condition and illuminates the "Low Voltage" warning light*).

**Comment by wlbragg** [comment]
@legoboyvdlp thanks, I thought it looked correct as the amp meter was below or at the edge of green.

**Comment by gilbertohasnofb** [comment]
@wlbragg I finally managed to reinstall FG and everything is running fine at the moment. So I had a look at this and I don't think the issue is how I implemented the low voltage light but the issue might be how the electric system is implemented. Should the voltage really be below the green arc at low RPM? If so then all good, if not then that's something to be fixed elsewhere. Also, another question: should turning avionics and lights on make any difference in the voltage itself or they only make a difference in the voltage consumption? Right now they seem to make no difference at all.

**Comment by wlbragg** [comment]
@gilbertohasnofb 

>Should the voltage really be below the green arc at low RPM? 

With the ALT on I would suspect not. With the ALT off, according to what @legoboyvdlp posted, yes.

I need to test one more thing and will get back with my final assessment, which as of right now is I think what I am seeing is the correct behavior.

**Comment by wlbragg** [comment]
>I finally managed to reinstall FG and everything is running fine at the moment. 

So glad to hear that. I know that can be really frustrating. I've had my fair share of reconfiguring lately.

**Comment by legoboyvdlp** [comment]
Actually, even with the alternator on it could be below the green arc at low RPM (600 - 1000) - thats just according to what I read on PPRune, and it might be incorrect.

**Comment by gilbertohasnofb** [comment]
> Actually, even with the alternator on it could be below the green arc at low RPM (600 - 1000) - thats just according to what I read on PPRune, and it might be incorrect.

This is what the POH of the model N (fairly similar to ours) says:

> Illumination of the low-voltage light may occur during
> low RPM conditions with a n electrical load on the system
> such a s during a low RPM taxi. Under these conditions, the
> light will go out a t higher RPM. The master switch need not
> be recycled since a n over-voltage condition has not
> occurred to de-activate the alternator system

But I think I might have implemented this wrongly. The POH states:

> LOW-VOLTAGE LIGHT ILLUMINATES DURING FLIGHT (Ammeter Indicates Discharge)

So from that I am now thinking that the LED should be bright when there is a discharge (Anmeter reading negative values) but nothing to do with voltage. It's confusing due to the label 'low voltage', which should be understood as 'battery discharging possibly leading to low voltage'. So perhaps I indeed need to improve the system. Nevertheless, it's clear that the light can be on during idle and even taxi, so that bit is fine.

**Comment by wkitty42** [comment]
On 07/26/2018 09:22 AM, Gilberto Agostinho wrote:
> But I think I might have implemented this wrongly. The POH states:

this thing is real easy...

the ammeter is wired in series between the battery and the circuits.

when there is no charging or draining, the ammeter needle points straight up on 
zero.

when there is more drain than charge, the ammeter needle leans to the right into 
the positive zone. this indicates there is a positive drain on the battery. this 
is when the low voltage light should glow. the more the drain, the brighter the 
glow.

when there is more charge than drain, the ammeter needle leans to the left into 
the negative zone. this indicates there is a charge being applied to the 
battery. any time the ammeter needle is less-than-or-equal-to zero, the low 
voltage light should be off.


i hope this helps ;)

**Comment by gilbertohasnofb** [comment]
@wkitty42 Thanks, that's exactly how I implemented it. The only confusion is that the label 'low voltage' is a bit incorrect, as the lights goes on even at nearly full voltage as long as it's draining, as you pointed out. But I think now it's all correct and this light will respond perfectly well to whatever future modifications we do to the electrical system given that it's logic is super simple: light is on if amps < 0.0 but only if volts > 0.0 (since we need at least something in the battery to turn it on).
