### ISSUE TITLE
Move tutorials to Hilo International Airport (PHTO)

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1097]
Move tutorials to Hilo International Airport (PHTO) as agreed in https://github.com/c172p-team/c172p-detailed/issues/1035

Tutorials will not have their airport changed in the future so this is the last time this move is necessary.

**Comment by gilbertohasnofb** [comment]
@dg-505 Would you be interested in working on this by any chance?

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Would you perhaps be interested in this issue once you are back from holidays?

**Comment by legoboyvdlp** [comment]
What would it involve?

I'll be back fully on Monday. :wink:

**Comment by gilbertohasnofb** [comment]
I believe it's just xml editing. Change the airport icao, runway numbers, frequencies for ATIS, park positions, check that the tutorial text is coherent with the current tutorials, etc. I think it shouldn't be too difficult though I never touched the tutorials myself.

**Comment by legoboyvdlp** [comment]
Working on this now.

**Comment by gilbertohasnofb** [comment]
Thank you!! We really need this work done for the next release so I _really_ appreciate you doing this! Let us know if you need any help, but as far as I remember the tutorial system shouldn't be too difficult to understand

**Comment by wkitty42** [comment]
On 07/03/2018 01:18 PM, Jonathan Redpath wrote:
> Working on this now.


yes, this is kinda important since the launcher is specifically adding support 
for the c172p tutorials at PHTO... at least one specific support mechanism is 
listing the location for the tutorial in the launcher's location history so they 
can easily be selected and you start in the proper place for your chosen tutorial...

**Comment by legoboyvdlp** [comment]
It's a slow process, particularly since the position of each instrument changed, so I have to recalibrate all the tutorial markers.

**Comment by wkitty42** [comment]
On 07/03/2018 04:27 PM, Jonathan Redpath wrote:
> It seems if a park pos is specified, the lat / lon in the tutorial does not work 
> - can anyone confirm?


this may be related to the launcher and how it feeds the parameters to the 
sim... there's ongoing work in this area...

how are you selecting the lat/lon? in the launcher location tab or by entering 
them in the additional settings or maybe on the command line?

where are you specifying the selected parking space??

are you building/using the latest version of FG in next?

**Comment by gilbertohasnofb** [comment]
> It's a slow process, particularly since the position of each instrument changed, so I have to recalibrate all the tutorial markers. The altimiter one is complete for a start.

Thanks for taking your time to do this, I forgot that the recent panel changes will have affected the cockpit positions.

> It seems if a park pos or runway is specified in the launcher, the lat / lon in the tutorial does not work - can anyone confirm?
> This means I cannot test the taxiing tutorial properly.

What launcher do you use? I am still using FGRun. How exactly can I try to reproduce the problem?

**Comment by legoboyvdlp** [comment]
I use the standard launcher (QT).

Select a parking position, then try to start the taxiing tutorial. It didn't move the aircraft for me.

**Comment by wkitty42** [comment]
On 07/03/2018 06:45 PM, Jonathan Redpath wrote:
> I use the standard launcher (QT).


i do, too...


> Select a parking position, then try to start the taxiing tutorial. It didn't 
> move the aircraft for me.

can you give steps to recreate? what, exactly, did you set/select in the launcher?

are you starting with the craft secured?

which tutorial are you trying to use?

where does the tutorial expect you to be located?

**Comment by legoboyvdlp** [comment]
As I told you, I selected the general aviation ramp parking position at PHTO. It does not matter if the aircraft is secured, since the tutorial system handles that, setting the state correctly. When I select the taxiing tutorial or the preflight and startup tutorials too - though I did not test them, it should move me from the parking position to the specified lat / lon, but it did not.

**Comment by wlbragg** [comment]
@legoboyvdlp you may need to make a branch and upload your progress so we can test and follow along with you. Otherwise I have no way to duplicate your state.

**Comment by wkitty42** [comment]
On 07/03/2018 07:40 PM, Jonathan Redpath wrote:
> As I told you, I selected the general aviation ramp parking position at PHTO. It 


i must have missed that... sorry...


> When I select the taxiing tutorial or the preflight and startup tutorials too
> - though I did not test them, it should move me from the parking position to
> the specified lat / lon, but it did not.

i forgot that it could move you like that... i thought you were saying you 
couldn't move the craft like normal... like the craft was still tethered and the 
wheel chocks were still set...

i just tested master and the taxi tutorial definitely moved me from KRDU to 
PHTO... i also spawned in at PHTO Ga_Parking (not GA_Hangers), loaded the taxi 
tutorial, and it did move me again... i don't know what you've got... do you 
have a branch available for testing?

ugh, you'll probably already have it figured out by the time i write this :lol:

**Comment by legoboyvdlp** [comment]
@wkitty42 
Why would they move you to PHTO though? Were you using my tutorial files? The old ones were in Spain 😉 guessing you meant LELL. 
I did make a branch, see PR #1146

**Comment by wkitty42** [comment]
On 07/04/2018 10:29 AM, Jonathan Redpath wrote:
> @wkitty42
> Why would they move you to PHTO though? Were you using my tutorial files? The
>  old ones were in Spain 😉 guessing you meant LELL.

:LOL: you are right... i was not using your files... just what is already in 
master...

LEBL or LELL, i got moved somewhere and i assumed it was PHTO... PHTO is like 6 
hours behind me so still dark there when it is noon here... i was surprised to 
see the tutorial adjusted the time of day so we were running it during daylight 
hours... but i guess that didn't happen like i thought... i need more c0ffee and 
the sim needs to tell us where we're teleporting to! :LOLOLOL:


> I did make a branch, see PR #1146


thanks, i'll try to check it out and see what i find...

**Comment by wlbragg** [comment]
It appears to work for me as well. Is there something specific your doing, like maybe starting at a particular parking position at PHTO VS some other airport? I tried starting at both a hanger and a parking spot at KEQU then turned on the tutorial and it took me somewhere els. I was trying the "taxi" tutorial and it did take me to what looked like PHTO lined up ion the runway.

**Comment by wlbragg** [comment]
Try clearing your c172p aircraft-data cache and see if it corrects your issue.

**Comment by wlbragg** [comment]
OK, I just tried starting at PHTO "General aviation" parking spot. I tried taxiing and it stayed where I was. I then tried "Takeoff" and it took me to the runway and lined me up.
So if that is the correct behavior then that is working for me.

However I just tried starting at KEQA and then started the taxiing tutorial and it put me on the runway at what appeared to be PHTO. So that wasn't correct.
But I went back into the launcher on a subsequent session and neither "runway" or "parking" radio was selected.
I selected runway, started the sim at KEQA, selected tutorial "taxiing" and it took me to the correct parking spot location for the taxiing tutorial. 
So I would have to say there may be a glitch with the launcher interface. I need to try to duplicate the condition so it can be reported to James.

**Comment by wlbragg** [comment]
It appears that if I select and airport and a start  location and then hit the back button, and select a different airport the location radios are blank, as in no default. Is this the same for others?

Does anyone have the latest fix for the launcher and is it still behave this way?

**Comment by legoboyvdlp** [comment]
> I was trying the "taxi" tutorial and it did take me to what looked like PHTO lined up on the runway.
That's exactly what happens. It should set you to the ramp, not the runway. 

However... I did have a thought as to why. Let me check something quick...

**Comment by legoboyvdlp** [comment]
> It appears that if I select and airport and a start location and then hit the back button, and select a different airport the location radios are blank, as in no default. Is this the same for others?

Does anyone have the latest fix for the launcher and is it still behave this way?

No - it had the runway radio selected, assuming I understood how you reproduced it correctly. My version of FlightGear is from 6/29/18.

**Comment by legoboyvdlp** [comment]
ok, so basically, I removed the <airport-id>PHTO</airport-id> from line 16 of the taxing tutorial. I then started at KMKE. I selected the taxing tutorial, I expected it to relocate me to 

```
<latitude-deg>19.71731272</latitude-deg>
<longitude-deg>-155.0597483</longitude-deg>
```

Instead, it sent me to 25L at KMKE. It seems that the tutorials ignore the lat / lon.

When I added <airport-id>PHTO</airport-id> back then it sent me to PHTO, but on runway 21 -> not the specified lat/ lon as I expected.

**Comment by wkitty42** [comment]
On 07/04/2018 12:30 PM, wlbragg wrote:
> It appears that if I select and airport and a start location and then hit
> the back button, and select a different airport the location radios are
> blank, as in no default. Is this the same for others?

i've seen similar in the last few days... i don't remember how it used to work, 
though... i tend to move through the updates too fast to remember what it did 
last week...

i will confirm that there is some oddities with the latest launcher code... i've 
been testing lat/lon location entries and my starting altitude is no longer 
being passed like it was... i can't select from the location history on the 
summary tab and other weird things...


> Does anyone have the latest fix for the launcher and is it still behave this way?


i almost alway shave the latest code here... i'm always updating to the latest 
code and FGAddon craft as soon as their update reports appear in the commitlogs 
mailing lists...

**Comment by wkitty42** [comment]
On 07/04/2018 01:12 PM, Jonathan Redpath wrote:
> I expected it to relocate me to
> 
> |<latitude-deg>19.71731272</latitude-deg> 
> <longitude-deg>-155.0597483</longitude-deg> |
> 
> It seems that the tutorials ignore the lat / lon.


did the tutorials ever work with lat/lon? or did they always have to be done 
with an airport and a parking place?

there has been some recent work done in the lat/lon area with regard to the 
various formats that can be used... we've had the HUD fixed up some time back 
for lat/lon stuff there... now that code has been fixed up again so it can be 
used for inputting lat/lon in those various forms...

i don't know if one of the newer formats would work??

19.71731272N
155.0597483W

**Comment by dany93** [comment]
@wlbragg wrote

> It appears that if I select and airport and a start location and then hit the back button, and select a different airport the location radios are blank, as in no default. Is this the same for others?

Does anyone have the latest fix for the launcher and is it still behave this way?

Compilation from yesterday.

I tried several combinations (C172P):
- selected an airport, a runway, hit the back button,
selected another airport, a runway,
Fly ==> Battery, Avionic ON, radio frequencies appear (not blank)
- same by selecting a parking.

Was it the right thing to do?

**Comment by legoboyvdlp** [comment]
> did the tutorials ever work with lat/lon? or did they always have to be done with an airport and a parking place? there has been some recent work done in the lat/lon area with regard to the various formats that can be used... we've had the HUD fixed up some time back for lat/lon stuff there... now that code has been fixed up again so it can be used for inputting lat/lon in those various forms... i don't know if one of the newer formats would work?? 19.71731272N 155.0597483W

Yes, they did - that's how the taxiing tutorial worked. Years ago it worked at KHAF

**Comment by wlbragg** [comment]
@legoboyvdlp I've posted to the dev list, lets see where it lands.

**Comment by legoboyvdlp** [comment]
Thanks!

I can't check at the moment or post / reply, but the specific issue seems to be that the latitude and longitude in the <preset> tags of the tutorial are ignored. 

I postdd a test case above, if nobody beats me to it, i'll copy it to the list in the morning. G'night!

**Comment by wlbragg** [comment]
>ok, so basically, I removed the PHTO from line 16 of the taxing tutorial. I then started at KMKE. I selected the taxing tutorial, I expected it to relocate me to
<latitude-deg>19.71731272</latitude-deg>
<longitude-deg>-155.0597483</longitude-deg>
Instead, it sent me to 25L at KMKE. It seems that the tutorials ignore the lat / lon.

@legoboyvdlp I just tried it and it did place me at the above lat and lon. But before it works I have to make sure the QT Launcher radio buttons in the location tab are set to either Runway or Parking. If they are both unselected, then it sets me at
-155.058
19.721
lined up on the runway.

I am convinced it is a QT  Launcher bug.

You can verify this by making sure one of the startup locations in the QT launcher is set to either Runway or Parking. Then one your into the sim and then choose the taxiing tutorial it places you where you have the lat/lon set for.

**Comment by legoboyvdlp** [comment]
@wkitty42 I just updated my FlightGear.

Didn't you or someone else show a new UI for the location page? I'm not seeing it, just seeing the usual page. I thought you posted a screenshot that had checkboxes for the airspeed, etc...

![image](https://user-images.githubusercontent.com/10434911/42340471-012e75ae-8088-11e8-8ffb-016bf904264c.png)

**Comment by legoboyvdlp** [comment]
I also still am unable to reproduce the radio button bug.
 - However - the build number is still 3037, so perhaps the nightlies are not being updated? What build are you all on?

**Comment by wkitty42** [comment]
On 07/05/2018 02:17 PM, Jonathan Redpath wrote:
> @wkitty42 I just updated my FlightGear.
> 
> Didn't you or someone else show a new UI for the location page? I'm not
> seeing it, just seeing the usual page. I thought you posted a screenshot that
> had checkboxes for the airspeed, etc...

yes, i only see it when i use lat/lon in the location tab's search bar... after 
you put them in and hit enter, the map screen comes up and they're there at the 
bottom... heading, altitude, speed, offset, etc...

/me looks at your image...

hey, look at that! you have them at the bottom in the grey bar... can you tell 
what your FG version info is from F10->Help->About please?

**Comment by wkitty42** [comment]
On 07/05/2018 02:23 PM, Jonathan Redpath wrote:
> I also still am unable to reproduce the radio button bug.
> 
>   * However - the build number is still 3037, so perhaps the nightlies are not
>     being updated? What build are you all on?


i just updated for the h377 of it... i think i pulled 5 of more yesterday... my 
location tab still looks the same as it did the other day when this feature was 
refined... i'm guessing that some tabs will look slightly different on different 
OSes...


********** 2018-07-05 14:58:09 -0400 **********
********** Total elapsed update and compile time is 0 days 0 hours 7 minutes 43 
seconds **********

PLib:    a542b8a03f8de1fe844af6ab4734b64d11e272e9
OSG 3.4: 1f89e6eb1087add6cd9c743ab07a5bce53b2f480
Simgear: 0e9e5f77cceddf4a1c9a67c1283c3d29a9f2436a
FGFS:    b24ba303dca8e57306d353327a189cde94e93e58
FGData:  6a6c054c0edf60926646a09a83046971bdd0a620
FGAddon: r3323 | lbrenta | 2018-07-03 18:17:29 -0400 (Tue, 03 Jul 2018)

**Comment by legoboyvdlp** [comment]
Actually, I think the Windows nightlies are not being updated, as the latest on Jenkins is 3048. Regardless, there is 10 days before James comes back. Meanwhile I can do the other tutorials.

I'll be leaving for about ten days myself on Monday - but I do plan to bring my laptop, and I will have internet access via mobile although I might not be able to pull or push to avoid a very expensive bill!

**Comment by wlbragg** [comment]
@legoboyvdlp in case you haven't seen this yet.

>Wiping /sim/presets is doable, I coded it up.
>But the actual issue is more subtle - the tutorials aren’t setting all the flags they need. To explain, there are some ‘foo-requested’ flags which are needed to make the reposition case unambiguous.
>So I think the real fix is the C172 tutorials should be audited to ensure they set presets/runway-requested=true presets/airport-request=true and so on
>This will ensure the position init code does the right thing regardless of the previous state.
?Is that acceptable?

>Kind regards,
James


>Anyway, the critical properties are:
	/sim/presets/airport-requested
	/sim/presets/runway-requested
	/sim/presets/parking-requested
.. all of which are bool and should be set if the corresponding property contains valid data for the next reposition.

**Comment by legoboyvdlp** [comment]
Great! Are those tags new in FG 2018?
Back home and back at work 😄

**Comment by wlbragg** [comment]
@legoboyvdlp 
No, I guess we didn't know about them. I added those tags locally and they worked, you still need to add them to the repository files and test them on your end.
Welcome back! Hope you had a great vacation.

**Comment by legoboyvdlp** [comment]
Hello,
Do we need the pattern tutorial? I really don't feel like spending the hours and hours it would take to fly the pattern, get the latitude, and painstakingly adjust and correct it. But if you think it needs done, I can do it...

**Comment by wlbragg** [comment]
@legoboyvdlp I think we should provide it as it is a very important part of beginning instruction for pilots. :sad

You really think it will take a long time to reproduce?

**Comment by legoboyvdlp** [comment]
It probably would if its anything like the taxiing tutorial, unfortunately.

**Comment by wlbragg** [comment]
@legoboyvdlp I just took a quick look at it and it looks like it is all heading cues, so it may not be as bad as you anticipate. There is a lat/lon cue at the end to exit.

Don't take this as me volunteering, but if you decide you don't want to spend the time to update it, I will because I think it is that important.

**Comment by legoboyvdlp** [comment]
I didn't test it yet, but its uploaded. That was rather quicker than I thought 😂

**Comment by wlbragg** [comment]
After I looked at it and I saw it was mostly heading cues, I didn't think is should be that difficult. I'm glad it turned out to be the case or my name would be mud right now, ha!

I'm board at the moment so I will test it right now.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp I can't tell you how much I appreciate you taking this issue, this is one of those that we really must tackle before the release. Thanks a lot!

**Comment by legoboyvdlp** [comment]
One error I did find is that with the directional gyro offset at the value it starts up with there is a 20 deg value between what you are told to fly and the actual heading when there is no offset - that actual heading is the same as the heading of the magnetic compass. Perhaps I had twisted the knob round once ages ago and that offset was saved accidentally on exit if it is a persistent property but I would like someone to check my heading cues to be sure they are right. Does 220 on the bug take you straight out from the runway?

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp I believe the correct value is 221. According to [this page](https://www.airnav.com/airport/PHTO):

> RUNWAY 21
> [...]
> 210 magnetic, 221 true

![fgfs-screen-003](https://user-images.githubusercontent.com/5700795/43045247-0907762c-8dad-11e8-931a-d926e75fbb76.png)
![fgfs-screen-004](https://user-images.githubusercontent.com/5700795/43045248-093c6f08-8dad-11e8-83a6-a502ea289915.png)

**Comment by wlbragg** [comment]
@legoboyvdlp 
Any chance your board enough to do
Create tutorials for float variants #1054

**Comment by gilbertohasnofb** [comment]
Closed via #1146

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp as far as you are concerned all work on the tutorials is done or is there still some work left?

**Comment by legoboyvdlp** [comment]
Apart from float tutorials I'd call this fully done!

**Comment by dloeckx** [comment]
Not sure if this is the right place to comment... It took me quite some searching, but I found out that my plane isn't positioned at the location indicated in the xml at the start of the taxiing tutorial, yet - as mentioned above - on the runway. Using Flightgear 2020.3.11 on a Macbook Pro (M1 chip), yet I had the same issue on an older (early 2015) Macbook Air a few months ago. Happy to help debugging!

**Comment by wlbragg** [comment]
Interesting, nothing has changed in the aircraft tutorials as far I know. But I am seeing an error in the log...
Failed to find a parking at airport PHTO:Slab44
Funny thing is though, the tutorial mentions nothing about Slab44, it only sets the aircraft at a lat and lon. But it also looks like it is not setting the aircraft at the correct lat and lon as indicated in the tutorial. That would be the first thing to check I suppose, where on the airport is the starting position of...
latitude-deg 19.71731272
longitude-deg -155.0597483

And is ...
latitude-deg 19.71717163
longitude-deg -155.0594903
indeed at the start of the taxiway?

This issue is closed so we need to make a new issue. I'll do that and move this information to the new issue.

**Comment by wlbragg** [comment]
@dloeckx 
See
https://github.com/c172p-team/c172p/issues/1387
