### ISSUE TITLE
Add a lighter hole to the cockpit

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1099]
This is just a fun little detail 😁 A 12V DC output.

![image](https://user-images.githubusercontent.com/10434911/39923803-19a2d22e-551d-11e8-84f5-bf5f8be09cb9.png)

On the old Cessnas when smoking was allowed, it was also marked LIGHTER:

![image](https://user-images.githubusercontent.com/10434911/39923840-3772dbdc-551d-11e8-8359-0e98170061bc.png)

**Comment by onox** [comment]
Can this be fakes by modifying the texture? Do we have normal maps already?

**Comment by legoboyvdlp** [comment]
It would probably look strange and 2D unless done very well but that is an option.

**Comment by wlbragg** [comment]
I should be able to cut this in easily enough. I suppose we need to do any of this mesh work before we do the AO map.

**Comment by gilbertohasnofb** [comment]
Yeah, texture is not the best option.

> I should be able to cut this in easily enough. I suppose we need to do any of this mesh work before we do the AO map.

Possibly yes, though I think it will not affect the textures that much. It's up to you, but I can manage with the current AOmap.

**Comment by wlbragg** [comment]
Well like an idiot I cut in the perfect lighter and when testing it in the sim discovered I used the image that didn't have the flaps selector for the positioning so it is covered by the flap selector. I have to do it again. But that lead to this discovery. What do we want to move where?
![lighter](https://user-images.githubusercontent.com/11069680/39947149-76699948-5536-11e8-8a79-68242baa4b77.jpg)

**Comment by gilbertohasnofb** [comment]
I think we want to move the flaps a bit left and the heat and air levers to the right, look at the OH-CTL picture above

**Comment by gilbertohasnofb** [comment]
Though it doesn't need to be precise. Just the heat and lever would be fine, they should be to the right of the yoke line

**Comment by wlbragg** [comment]
I'm going to be away for awhile. I should have this and the AO map by morning.

**Comment by wlbragg** [comment]
>I think we want to move the flaps a bit left

@gilbertohasnofb actually this images that shoe a flaps lever have it a little farther right than we do. It is centered below the right edge of the radio stack panel. So if anything the flap lever should move right also?
I'll see if I can move the vent knobs right and the lighter enough right that we can still move the flap part right if we choose to, or leave it where it is.

**Comment by wlbragg** [comment]
![plug](https://user-images.githubusercontent.com/11069680/39953606-38ac30fe-5575-11e8-8c0a-5cc0e8ec00df.jpg)
![plug2](https://user-images.githubusercontent.com/11069680/39953607-3f6023b0-5575-11e8-842b-a37e01878be5.jpg)
@gilbertohasnofb 
This image on the texture sheet with a slight modification could work well for the lighter port.
![lighter](https://user-images.githubusercontent.com/11069680/39953642-03385294-5576-11e8-9054-e7a4b2104b6c.jpg)
You can see the mapping above but I can of course scale any of the rings and surfaces (back and side walls) mapping to fit whatever you do for the image,
I marked up this below to give you an idea of how I would prefer to map it, Fell free to take liberty to do as you see fit. I was simply trying to convey how we could map it using an existing image with some modification. Note: I'm  not implying we use that space, only a copy of that texture placed in a space somewhere else on that texture sheet.
![lighter2](https://user-images.githubusercontent.com/11069680/39953566-4e5ddca0-5574-11e8-9b00-f61488d1b634.jpg)
Note: the space between the lighter port and the vent knob leave room for the labels per the reference images.

**Comment by gilbertohasnofb** [comment]
@wlbragg I liked the new positions of flaps and levers, that's all good with me. About the texture, I added a new one to `panel_parts.png`, see:

![image](https://user-images.githubusercontent.com/5700795/39957621-e30c093e-55ed-11e8-9f55-d0b24f889abe.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg Actually I added the metallic texture for the mic mount on the same `panel_parts.png` file. See: 
![image](https://user-images.githubusercontent.com/5700795/39957655-58e3d290-55ee-11e8-8fc1-e3b300ac6d28.png)

Pushing it now.

**Comment by gilbertohasnofb** [comment]
And please do not make them livery dependent as I only pushed them to the default livery for the moment being.

**Comment by wlbragg** [comment]
@gilbertohasnofb perfect, thank you!

**Comment by wlbragg** [comment]
@gilbertohasnofb I am just about to throw this computer through the window. Why would the new lighter port texture act like it is part of the livery system? Did you not add both the mike_mount and the light port graphics only to the default texture sheet? I mapped them exactly the same, I added them to the interior effect definition only and no where else. The mike mount is consistent through the liveries, but the light port act like it is livery dependent because it looses all texture in every livery except the default?  They are set up identical in every way! What the hell am I forgetting to do or not to do? I even cleared my airplane data cache.

**Comment by wlbragg** [comment]
OK, it's just really bugging me that it is behaving badly and for no reason that I am aware of. I'll move forward. It's consumed over an hour already. It took most of that time to figure out it was a livery issue. I wasn't getting the texture change in the light hole no matter what I did and it finally dawned on me I was in a livery. As soon as I went to default, the change showed up. I was swapping normals, remapping, reassigning materials, you name it. That is why I was ready to get violent. O think I have anger management issues!

**Comment by gilbertohasnofb** [comment]
I completely sympathize, I also have a hard time leaving something aside if I don't completely understand it. Nothing drives me crazier than a Heisenbug :rofl: 

> That is why I was ready to get violent. I think I have anger management issues!

So I will be very carefully reporting bugs to you tonight and in the next days! :wink:

**Comment by gilbertohasnofb** [comment]
@wlbragg I just pushed a new commit in which I added the lighter and mic mount to the `panel_parts` file in all liveries, so you can make them texture dependent. I also removed that 1 cent coin as I commented elsewhere.
