### ISSUE TITLE
Pocket on the bottom right of the panel is missing

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1100]
There is a pocket or cupboard in the panel on the right:

![image](https://user-images.githubusercontent.com/5700795/39926498-4d7804f2-5527-11e8-920f-81904e3b3308.png)

**Comment by wlbragg** [comment]
>I will take care of this 'pocket' in the bottom right hand side of the panel via textures. I will add that to all panels on the next round of works.

Sure you don't want me to also model it in the mesh? It's not a big deal. I can even animate it so we have a working "glove box".

**Comment by gilbertohasnofb** [comment]
@wlbragg I am pushing a new `panel_parts` adding now a texture for the black plastic lock of this pocket, see: 

![image](https://user-images.githubusercontent.com/5700795/39972252-2d1e4472-5703-11e8-8b62-0d7d2908c89c.png)

so do a git pull before continuing with anything else on that branch

**Comment by gilbertohasnofb** [comment]
Two comments:

![fg](https://user-images.githubusercontent.com/5700795/40025066-64d910ca-57c8-11e8-963b-528c0324ff96.jpg)

1) isn't the pocket door a bit too thin? 
2) where id the texture to the pocket come from? I would think it's best to map it to a new texture.

**Comment by gilbertohasnofb** [comment]
So that it can also show up in the AOmap (then when you bake the `panel_parts` just remember to open the pocket)

**Comment by wlbragg** [comment]
I actually mapped it to the Radio Stack plate (behind the radio stack). I did that because that texture space is really irrelevant for maps of any kind because it is covered (for the most part) by the radios. Also the pocket (glove box) is not included in any effect because you can't have shadows moving across it anytime it is closed or it may not look right. There is no way to tell it to only show shadows if it is open so we just don't include it in any effect.  Also the glove box is a separate mesh from the panel mesh so it could be removed from any effect, it had to be a separate mesh, Almost all of the "hidden" compartments, glove box, oil compartment, front wheel well, etc are done this way. But if you want to make a texture for it I will certainly map it to it.
As far as the thickness of the door, Yeah, I can make it thicker.
Some styles of "glove box" doors look more like below. I don't know what this one is actually supposed to look like.
![box](https://user-images.githubusercontent.com/11069680/40025947-fd1b0d6e-5798-11e8-94a7-88963c1b6c0a.jpg)

**Comment by wlbragg** [comment]
So you want to us an AO map for the interior of the box?

**Comment by gilbertohasnofb** [comment]
Yep, so that the bottom part is a bit lighter than the walls, and the walls will have a diagonal shadow like this:

![image](https://user-images.githubusercontent.com/5700795/40026055-bff723a4-57cb-11e8-9ab3-0d8c5eaff3e7.png)

**Comment by gilbertohasnofb** [comment]
I will make a texture for you. Would this be fine?

![image](https://user-images.githubusercontent.com/5700795/40026122-fd340e44-57cb-11e8-80d6-ac69b2a9d3e8.png)

I will add to `panel.png`

**Comment by gilbertohasnofb** [comment]
BTW I just think the pocket door should be thicker but it looks like it doesn't have those bits on the side, see this one from a C182:

![](https://www.picclickimg.com/d/l400/pict/321719749975_/Cessna-182-Glove-Box-Door.jpg)

**Comment by wlbragg** [comment]
@gilbertohasnofb I'm back. I thought you already did this texture but after pulling I see you haven't, Yes, by all means I map it.

**Comment by gilbertohasnofb** [comment]
@wlbragg great, I will take care of this tomorrow then

**Comment by gilbertohasnofb** [comment]
Just pushed a texture to `panel.png`, this is the layout (hopefully it won't be too confusing):

![image](https://user-images.githubusercontent.com/5700795/40149013-094ec69e-5969-11e8-8a1f-17481332b1f0.png)

**Comment by wlbragg** [comment]
@gilbertohasnofb looks good, thanks.

**Comment by gilbertohasnofb** [comment]
@wlbragg Here is an idea: what if we put the GPS model inside the glove box when it's not being used? And then clicking on it while inside the glove box would add it to the panel and clicking back in the empty glove box space would put it back there? (that is, the interior of the glove box would be a large click spot). Just an idea of making use of the new feature :smile:

**Comment by wlbragg** [comment]
Yes, great idea! Now we actually get to use our glove box.

**Comment by wlbragg** [comment]
I can copy only the shell as a new model and use that for inside the glove box.

**Comment by gilbertohasnofb** [comment]
@wlbragg Great! I think this sounds like a fun feature :smile: 

> I can copy only the shell as a new model and use that for inside the glove box.

That sounds like the best approach. The question is how to put the GPS back in the glove box, as I don't think that should be done by clicking on the gps itself in the panel but rather in the empty space in the glove box somehow.

**Comment by wlbragg** [comment]
What about a we make the interior shell of the glove box an object.
We also make the model of the GPS and another copy of the interior shell of the glove box another separate object. Then we can use, or toggle, a select animation on the two different models with their ow tool tips, one saying something like "Clik to mount GPS" and the other saying "Click to put away GPS".

**Comment by gilbertohasnofb** [comment]
That sounds excellent!

**Comment by wlbragg** [comment]
If you are understanding and want to write the animation I can do the modeling. We just need to know the name of the two objects, how about GPSMount and GPSUnmount?

**Comment by wlbragg** [comment]
It's simple enough I can do the code if you have no time.

**Comment by gilbertohasnofb** [comment]
Sure, I can deal with the animation, that should be just a few lines of xml. Could you please let me know once the two objects are pushed to the branch?

**Comment by gilbertohasnofb** [comment]
I will leave in around 1 hour so if we have this done soon I can do it straight away or I can code that later in the evening. But also feel free to do the code, I don't mind either way :smiley:

**Comment by wlbragg** [comment]
The empty glovebox is already called "glovebox", so it will be glovebox object to close and I'll name the gps+glovebox shell gloveboxfull

**Comment by gilbertohasnofb** [comment]
@wlbragg Hmm, the thing is that I don't feel comfortable pushing a code before I can test it, so I would need the `gloveboxfull` object to make sure all is right. Else there is the danger we need to do a `rebase` and that's always unpleasant.

**Comment by wlbragg** [comment]
I'll go ahead and do the code. I just finished with the modeling. It's only a few lines, two select animations. If your around in a couple minutes you can check it out.

**Comment by wlbragg** [comment]
Well actually a little more complicated as we have to tie in the real GPS display logic.

**Comment by gilbertohasnofb** [comment]
I think we just need to make sure that whenever we click on the `glovebox` object, the GPS is set to OFF before being hidden away and replaced by the gps model inside the box. That GPS model could be a second object which has no screen and whose buttons do not work, since it will be inside the box and we don't want those clickspots and everything.

**Comment by gilbertohasnofb** [comment]
Let me think about that, I will see if I find a simple subtle sound which
could also be used for the control lock. We could also have a sound for the
checklists, a bit like the sound of flickering pages on a book. I will see
what I can come up later

**Comment by wkitty42** [comment]
On 06/15/2018 12:29 PM, Gilberto Agostinho wrote:
> Let me think about that,


record the thump sound heard when easily tossing a cell phone into an empty 
glove box in a car... it should be "close enough" ;)


> I will see if I find a simple subtle sound which could also be used for the
> control lock.

as above, use the click of the knob of the car glove box when opening it and the 
thump click sound when one closes the glove box... they should also be "good 
enough" :)


> We could also have a sound for the checklists, a bit like the sound of
> flickering pages on a book. I will see what I can come up later

that might be cool...

**Comment by gilbertohasnofb** [comment]
@wlbragg I love what you did with the GPS. I will work on the sounds.

**Comment by gilbertohasnofb** [comment]
@wlbragg I noticed that as soon as you click on the pocket lock to open it, the lock goes super dark. This is particularly noticeable on dusk. What can be causing that? See:

![fg-0](https://user-images.githubusercontent.com/5700795/41921140-17897770-795a-11e8-9f41-379444a3703a.jpg)
![fg-1](https://user-images.githubusercontent.com/5700795/41921141-17bc4b46-795a-11e8-98ee-b80008a4dc2b.jpg)

**Comment by wlbragg** [comment]
I'm pushing a fix for this, let me know if it actually fixes it. It has to be removed from the shadow effect as it is rotated. I think that is the only fix, so no shadow on it now.

**Comment by gilbertohasnofb** [comment]
Yes that solves the problem. And lack of shadow in such a small object isn't a problem IMO. Thanks for the fix!
