### ISSUE TITLE
Improve trim wheel

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1109]
Our trim wheel model could do with some improvements. In particular, the details around the trim are have spherical shapes: 

![](https://user-images.githubusercontent.com/5700795/39957515-24d70f8c-55ec-11e8-995b-0a1e552d3091.png)

While in our model they are rather cubic:

![fg](https://user-images.githubusercontent.com/5700795/40207650-903510ea-5a2d-11e8-8d2e-4b276a0908f2.jpg)

**Comment by tonghuix** [comment]
I think the round balls should more far away from each other.

**Comment by wlbragg** [comment]
OK, I decided to do it tonight before I called it quits for the night. If you actually count the knobs you'll see that it is one off from the photo. It's going to have to be close enough. I did all the practicing my little old heart cold take. :smile: 
![trim](https://user-images.githubusercontent.com/11069680/40223533-037c3252-5a49-11e8-8f16-5f4127250895.jpg)

**Comment by wlbragg** [comment]
I gotta say, I thought after I looked at the first pass that it indeed looked like they were too many knobs. But after counting that first one's knobs it is actually 9 or 10. The photo has the same, so I am not so sure it was any more or less accurate than the final version. Looking closely at the design of the wheel, I think part of the deception is the disk itself, It's a bit thinner and has a rib at the outside edge of it. The difference between the original and the one I did may be throwing our perception off.

**Comment by legoboyvdlp** [comment]
>  I did all the practicing my little old heart cold take. 😄

Don't kick the bucket just yet, you are invaluable to the c172p 🤣 
Nice work as always!

**Comment by gilbertohasnofb** [comment]
@wlbragg I think you last screenshot above looks amazing, let's use that layout! I think that _looks_ better and closer to reality than just counting the knobs. Our whole model is not that precise concerning sizes and thickness so invariably we will run into these sort of things. My vote is to use your work from the screenie above.

As for the texture, I will take care of that later today.

**Comment by wlbragg** [comment]
Well gang, I got on my computer today for the first time only to discover overnight my Linux distro decided to loose its network capability so I had to boot up on my Windows partition, YUCK! I realized I hadn't booted into Windows in over two years. So I am going to be incapacitated until I either fix my Linux install or reinstall it. I guess I must have lost a file or two to corruption, only thing I can think went wrong. I may be able to copy the network stuff over from a full install disk and maybe get lucky and get it back up. Otherwise it is a reinstall, which isn't the end of the world other than it's a pain in the arss. So that's where I'l be for at least a day or two. Dumb ass computers, How you loose a file in the middle of the night for no apparent reason is beyond me. I rarely shut down, only if I have to, so it was just sitting there doing nothing and decided to stop working. At least I know it is software and not hardware.

**Comment by gilbertohasnofb** [comment]
@wlbragg Oh that sucks, sorry for the issues you are having! I am also on Linux and I boot to Windows very seldom. Good luck fixing it and take your time, we are not in a rush with anything here.

**Comment by gilbertohasnofb** [comment]
I pushed a new texture for the trim to all panel_parts, see: 

![image](https://user-images.githubusercontent.com/5700795/40260131-f43f9286-5af0-11e8-80a1-02341fc4c254.png)

And by the way, where is this part of the microphone mapped to? I can't find it in panel_parts

![image](https://user-images.githubusercontent.com/5700795/40260144-0910f6a0-5af1-11e8-9ab0-7136c31b1e5e.png)

**Comment by gilbertohasnofb** [comment]
It could and if that's it then it's all fine with me, I just would like some confirmation.

**Comment by legoboyvdlp** [comment]
Since wlbragg isn't here to check in Blender, you could test by modifying that part of the texture in gimp - eg painting it black. If the microphone changes colour then it is correct ;)

**Comment by gilbertohasnofb** [comment]
I know, I was just frankly lazy to do that :laughing: But I just tested and indeed that's the texture, so it's all good.

**Comment by wlbragg** [comment]
@onox thanks, tried it.
Turns out I have everything I need to continue work under Windows. It's just a bit slower and not as well organized. So I can still do some work until I get motivated enough to sort out my Linux distro.

**Comment by gilbertohasnofb** [comment]
@wlbragg can you confirm we can close this one? I believe you are done with remodelling the trim wheel right?

**Comment by wlbragg** [comment]
Yes, as far as I am  concerned, it's finished.
