### ISSUE TITLE
Add sunvisors above the pilot and copilot seats

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1110]
We could add sunvisors above the pilot and copilot seats:

![](https://www.inflightpilottraining.com/wp-content/uploads/2015/06/Cessna-172-Interior-Inflight-Pilot-Training.jpg)

They could be adjusted using click and drag, so that their position can be adjusted to any angle like in the c182s. Actually we could even use that model as a base but the 172p should have non-transparent sunvisors.

**Comment by gilbertohasnofb** [comment]
Here is a better picture:

![](https://cdn.airplane-pictures.net/images/uploaded-images/2017/8/18/949535.jpg)

**Comment by wlbragg** [comment]
@gilbertohasnofb 
First pass for the sun visors.
Not sure where you want to add the textures. As you can see I am currently using panel_parts. I don't know if this particular texture is used for something or not. We need a texture for the visor rods as well.

![visor2](https://user-images.githubusercontent.com/11069680/43032936-ca15bb30-8c86-11e8-9d72-934ac882d22b.jpg)
![visor1](https://user-images.githubusercontent.com/11069680/43032937-cf244222-8c86-11e8-8ff8-31e6234902bf.jpg)
![visor3](https://user-images.githubusercontent.com/11069680/43032939-d2d2f22e-8c86-11e8-81e2-4ff795147edf.jpg)
![visor4](https://user-images.githubusercontent.com/11069680/43032941-d5424654-8c86-11e8-9cd6-af6213d15a56.jpg)

**Comment by wlbragg** [comment]
Who wants an animation job?

**Comment by gilbertohasnofb** [comment]
@wlbragg I am having some big issues with my computer which might require a full reinstall of everything... this means I might not be able to work in the next few days. But as soon as I am able I will deal with all these textures. 

Some comments though:

* that texture you used is the checklist pocket texture I believe. It does look good, but the light maps might be screwed up if we keep them this way. We could test it though and see how them look, and if they look fine then there would be no reason not to use them. Else I will need to find some empty space to add the new ones.
* I will add some metallic texture for this as well.

**Comment by wlbragg** [comment]
>Who wants an animation job?

Too late, I am almost finished with the animation.

**Comment by wlbragg** [comment]
@gilbertohasnofb I hope you get you CPU straightened out without too much trouble. I know that can be a real pain in the neck, good luck!
No worries!

**Comment by gilbertohasnofb** [comment]
@wlbragg I spent the day fixing my CPU and is still not over... all of this because I tried plugging an HDMI monitor and my NVIDIA driver on Linux went mental. Anyway, about the texture, they are done but there was no place in `panel_parts` so I added them to `interior` as that also make sense. See top left corner:

![image](https://user-images.githubusercontent.com/5700795/43041477-f866596c-8d59-11e8-84b9-f1c85a2c2738.png)

pushing it now

**Comment by gilbertohasnofb** [comment]
@wlbragg I just managed to fire up FlightGear once again. The sunvisors look really good! We just need to adjust their position and size a bit. The pilot should be able to comfortably see the thermometer if the visors are up. I think the visors should be shorter (that is, not come that close to the thermometer in the horizontal) as well as be raised a bit). See these two photos are reference for adjusting the model:

![](https://camo.githubusercontent.com/6f6c9d09e22af3f79e43cf905854c6f6a525ad5f/68747470733a2f2f63646e2e616972706c616e652d70696374757265732e6e65742f696d616765732f75706c6f616465642d696d616765732f323031372f382f31382f3934393533352e6a7067)
![](http://www.cruik.org/blog/ventubes/ventube-out.jpg)

**Comment by wlbragg** [comment]
Good deal, thanks for the better image. I couldn't tell where exactly to put them or how big to make them with only that other picture as a reference. I think I have a better idea now, thanks.

**Comment by gilbertohasnofb** [comment]
@wlbragg Fantastic work, looks absolutely perfect! Love the animations.

**Comment by wlbragg** [comment]
I just discovered I need to limit the forward visor rod swing in the float variants as it allows the visor to hit the reinforcement bars.

**Comment by gilbertohasnofb** [comment]
Nice catch. When implementing this, do test changing from the default version to the float version while having the sunvisor in the forbidden place for the float, as to confirm it will change.

**Comment by wlbragg** [comment]
Done, I simply limited the range of movement slightly over all to account for the float variants. It wasn't worth adding logic specific to the float variant only.

**Comment by gilbertohasnofb** [comment]
Works perfectly well :clap:

**Comment by legoboyvdlp** [comment]
The visors have some texture stretching on the top face:
![image](https://user-images.githubusercontent.com/10434911/43518543-52612096-9584-11e8-8b9f-612e62bfd01a.png)

closeup:
![image](https://user-images.githubusercontent.com/10434911/43518551-59af28d4-9584-11e8-85fd-369a5e65231c.png)

**Comment by wlbragg** [comment]
:fearful:

**Comment by gilbertohasnofb** [comment]
@wlbragg I just pushed an improved texture for the sunvisors using the photos I posted before as reference. Looks better IMO.
