### ISSUE TITLE
Improve toggle 3D models

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1111]
When viewed a bit sideways (e.g. from the copilot seat) the toggles do not look too good, see:

![image](https://user-images.githubusercontent.com/5700795/40260281-a599f030-5af1-11e8-9c16-1f6ea0878ce8.png)

It's as if they are missing part of the model. This is how they look in RL:

![image](https://user-images.githubusercontent.com/5700795/40260332-f1877eb8-5af1-11e8-99b2-198ad7890e0a.png)

**Comment by wlbragg** [comment]
New toggle switch ...
![primbase](https://user-images.githubusercontent.com/11069680/41053220-8f81753c-6980-11e8-8e05-66751bc89cf6.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg I also think we need to move all of our toggles a tiny bit backwards,  looking at that photo you can see that the half which is 'in' almost doesn't stick out of the panel at all.

**Comment by callahanp** [comment]
I wish I could get shots like that straight on with a small ruler in the
picture.
This one is good for the view from the side, but straight on would be good
for grabbing measurements.


I've been looking at pics and estimating, based on positioning a straight
line through the instruments to the lower panel, but accurate positioning
is problematic

**Comment by gilbertohasnofb** [comment]
@wlbragg I just had a look on what we have in our working branch but the toggles are still not fixed, see:

![fg](https://user-images.githubusercontent.com/5700795/41217203-0f750eb2-6d4f-11e8-91eb-53ca8b5c2e3c.jpg)

1) the green mark shows that the toggles are still sticking out too much. They should stick out perhaps half or even a third of that

2) the ON position is not symmetrical to the OFF position. The purple angle should be 0 degrees.
