### ISSUE TITLE
Missing property /engines/active-engine/damage_allowed

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1119]
![image](https://user-images.githubusercontent.com/10434911/40838721-64745bc6-6597-11e8-8528-99e2dea30ef9.png)

I could not reproduce, but I added some code to engine.nas, which the reporting user tested and confirmed that it works.

I will open a branch and PR shortly.

**Comment by onox** [comment]
I can't read the text in the screenshot. Can you upload a screenshot in which the text is readable?

**Comment by wkitty42** [comment]
On 06/03/2018 10:18 AM, onox wrote:
> I can't read the text in the screenshot. Can you upload a screenshot in which 
> the text is readable?


that was my problem, too... i just didn't say anything because i thought it had 
already been handled and applied...

**Comment by legoboyvdlp** [comment]
No, that is what the reporter on Discord sent me. But, it is the proprrty which I mentioned that is missing.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Do you know what commit caused this issue? Is this related to the engine damage work that you previously did or is it something new?

**Comment by legoboyvdlp** [comment]
Yes, it was that work.
I thought I fixed this already?

**Comment by gilbertohasnofb** [comment]
I haven't test it, I am just going through opened issues. If this was fixed then you can close it.

**Comment by legoboyvdlp** [comment]
I don't know, was there a merged pull request for this issue?

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Sorry, I forgot you don't have access to close issues. I think in your case you always need to make sure that when you open a PR you write 'Fixes #xxxx" where xxxx is the issue number. But no worries, I am closing this now.
