### ISSUE TITLE
Enhance Electrical System

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1123]
While this probably ties in with an earlier issue, it would be good to actually simulate the electrical buses etc, and connect the various circuit breakers to the appropriate bus. The electrical system is quite simple. I'll post the relevant POH below.

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/41432767-d853c474-700e-11e8-947e-fd258eba03ce.png)

**Avionics Bus:** 

![image](https://user-images.githubusercontent.com/10434911/41432665-9ee6911c-700e-11e8-9529-e4e0e8f79333.png)

![image](https://user-images.githubusercontent.com/10434911/41432694-b1b2adee-700e-11e8-93ce-d13fd40f3041.png)

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/41432822-00708c6c-700f-11e8-9524-da897c77e32b.png)

![image](https://user-images.githubusercontent.com/10434911/41432839-0e0e3950-700f-11e8-9ba2-432836440921.png)

![image](https://user-images.githubusercontent.com/10434911/41432851-1819da44-700f-11e8-91cf-a8445a40405b.png)

**Comment by legoboyvdlp** [comment]
**Ground Service Plug (electrical system)**
This is an external power unit, an optional addition.
This will involve adding a placard to the aircraft:
![image](https://user-images.githubusercontent.com/10434911/41433646-77e846b6-7011-11e8-8724-748fc7bbdbba.png)

adding a 3D model to the cowling: 

![image](https://user-images.githubusercontent.com/10434911/41433682-92533592-7011-11e8-91a7-9739dbdef4ae.png)


and simulating it in the electrical system:

![image](https://user-images.githubusercontent.com/10434911/41433692-9aaa0c70-7011-11e8-9048-8b13c3d58ddc.png)

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp thank you so much for the screenshots of the concerning passages, these help immensely!

**Comment by legoboyvdlp** [comment]
Does the ground service plug door need modelling in the lower left cowling? 

I had a look at the electrical system and as far as I can see it is pretty much complete, so if there isn't anything else to be added this could be closed. 

The only thing is the avionics switch closing automatically if the breaker trips, but that is very very minor.

**Comment by gilbertohasnofb** [comment]
> Does the ground service plug door need modelling in the lower left cowling?

Not too sure I understand what you mean, do you mean where the cable enters the nose? If so, I have a confession: I simply imported those ground equipments from the c182s and I don't know how they should interact with the 172 :scream: do we know if we have such a plug door and if so where exactly it is located?

> The only thing is the avionics switch closing automatically if the breaker trips, but that is very very minor.

What do you mean if the breaker trips? You mean that pulling the avionics breaker will cause the switch to move down? We can fix that easily.

**Comment by legoboyvdlp** [comment]
I quote, roughly,  if an electrical malfunction occurs, and the avionics circuit breaker should open, electrical powrer to the avionics will be interrupted and the switch will move automatically to the off position. 

And lol, don't worry... I did the same thing for the external heater! :joy:

**Comment by gilbertohasnofb** [comment]
> I quote, roughly, if an electrical malfunction occurs, and the avionics circuit breaker should open, electrical powrer to the avionics will be interrupted and the switch will move automatically to the off position.

I wonder if this happens only in a malfunction or if the switch would also move if the pilot themselves would pull the breaker. If it's the latter case then a simple logic switch would do, else we don't have malfunctions implemented for the electrical system yet.

> And lol, don't worry... I did the same thing for the external heater! joy

It's our secret then :wink:

**Comment by legoboyvdlp** [comment]
I would guess that the switch flips anytime the breaker trips, whether due to malfunction or voluntary action although that is not specifically stated. I'd say simulate that way until we have any other information about it.

**Comment by gilbertohasnofb** [comment]
Cool, I will make a PR for that.

**Comment by legoboyvdlp** [comment]
I suppose if there isn't anything to do we can close this.

**Comment by legoboyvdlp** [comment]
I suppose if there isn't anything to do we can close this.

**Comment by gilbertohasnofb** [comment]
Yeah, I think our electric system is quite well implemented. Thanks for all the info you posted about the electric system from the POH, lego.
