### ISSUE TITLE
Small sound improvements

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1126]
Add sounds to:

* clicking on the checklist
* glove box open/close
* GPS mount/dismount
* control lock on/off

**Comment by gilbertohasnofb** [comment]
Yes, they are in that mega PR since the reason I started working on those were the new glove box and GPS mount/dismount features implemented there.

**Comment by wlbragg** [comment]
I'm fine with getting this "massive" PR closed up and starting a new one for the rest of the miscellaneous related issues. I have one more push to make and I will freeze there barring any cleanup needed.

**Comment by gilbertohasnofb** [comment]
Agreed, but I think we need to solve all things that we touched. This means solving those questions about the lights and solving the 3D knob position and textures for the static knob. Then we would merge this and move on into improving the other levers in a new PR together with whatever is left, how is that for you?
