### ISSUE TITLE
P-factor (propeller effect)

### ISSUE THREAD

**Issue by dany93** [c172p-team/c172p#1130]
I'm proposing a P-factor value which (hopefully) will be closer to reality. The previous one was much too weak, almost unnoticeable.

The P-factor is a propeller effect which makes the aircraft steer or yaw leftwards with AoA at high RPM (or steer with any apparent-wind misorientation). It adds to others such as the spiraling propwash effect, although on tricycles the spiral propwash effect is predominant when rolling before takeoff, whereas the P-factor becomes more efficient at climbing (due to AoA).
[Asymmetric Thrust Explained](http://www.qmfc.org/school/asym.htm)

An other improvement (I think) is that this implementation enables me to decrease the spiraling propwash effect while having this well known leftward yawing at low speeds, high AoA (rolling for takeoff, climbing).
Then, the (previous) strong tendency to steer left at very start of rolling, full thrust, is considerably decreased. In particular, even the amphibious no longer needs differential braking to hold the aircraft in line.

Please @algefaen, I would be very pleased if you could test it with these proposed values.

If you wish to test with other settings or analyze by selectively canceling the effects, the key-values are (for 180 hp engine)
- The P factor in c172p.xml, `<engine> / <thruster>`
line 620
`                <p_factor> 60 </p_factor>`
(must be set before launching, not very convenient but still easy),

- The spiral propwash, which can be set in the simulator:
fdm/jsbsim/aero/coefficient/spiral-propwash-coeff
or in c172p-set.xml,
line 1055
`                    <spiral-propwash-coeff type="double">0.25</spiral-propwash-coeff>`

I've set these values in order to try being in (qualitative) accordance with [your report](https://github.com/c172p-team/c172p/issues/1114#issuecomment-397380057), to get some effect when climbing.
As they are,
- at takeoff, 20% right rudder is needed at very start of rolling, quickly decreasing to 10%,
- at climbing at 60kt, about 20 to 25% right rudder is needed to keep the slip-ball centered.

In fact, those are estimations and I'd like to know if they fit your subjective opinion, if you can.

If you are not sure at this day, don't worry, you can see that the values are very easy to change in the code if needed later. The harder is in-flight testing.
For now the first question is, is it an improvement? (even with not definitive values)

**Comment by algefaen** [comment]
I noticed that when setting the p_factor to 60, going full throttle with brakes on pushes the nose so much down (for some reason?) that it breaks the nose wheel. I think that's a bit of a showstopper. )=

**Comment by wkitty42** [comment]
On 06/20/2018 11:17 AM, algefaen wrote:
> I noticed that when setting the p_factor to 60, going full throttle with brakes 
> on pushes the nose so much down (for some reason?) that it breaks the nose 
> wheel. I think that's a bit of a showstopper. )=


you can't strengthen the nose wheel gear in the damage code? that'll also allow 
for slightly harder landings but maybe the gear has been too weak anyway? i've 
seen it break on taxiways just by driving over the center line... that was a 
while ago, though...

**Comment by algefaen** [comment]
It's not just the leg breaking too easily, the nose is really pulled down a lot, it's very close to a prop strike. I found a reference video: https://www.youtube.com/watch?v=aqggWcd-uMg - you'll see that the nose is pulled down a little bit, maybe a bit less than before doing the p_factor mod. Nowhere near as much as with the mod.

**Comment by dany93** [comment]
I've found the reason: too low damping on the **main** gears, which gave huge oscillations.
Now, I'm out of time, I'll go on later.
I'll also increase the nose gear spring coefficient.

**Comment by dany93** [comment]
Done.
- Nose gear: increased spring coefficient and damping,
- Main gear: increased damping.

**Comment by algefaen** [comment]
Hehe, nope, still very strange. If I'm on the ground and have a gentle crosswind from the left and give full power, it lifts the nose gear entirely off the ground and rests against the tail. If the crosswind is from the right, it pushes the nose to the ground, and even managed to lift one of the main gears. It seemed to cause some weird slipping effect in the air as well. This P-factor-effect of crosswind component that affects the pitch axis seems entirely out of whack. I'm guessing there's an oversight in JSBSim where they use the angle between "air flowing through the propeller vector" vs "propeller vector" and don't account for the amplitudes - a tiny crosswind of 3kts should have almost no effect, but it does.

**Comment by algefaen** [comment]
I hacked JSBSim to remove the vertical component of p-factor. It's no longer affected by tiny crosswinds and is much more stable on the ground, and while the climbing and in slow-flight I think it requires an appropriate amount of right rudder. I wouldn't want to apply that hack though... There must be something wrong with the logic in JSBSim that either makes the vertical component during high AoA not contribute enough, or the effect of wind on the ground contribute way too much.

**Comment by wkitty42** [comment]
On 06/22/2018 03:46 PM, algefaen wrote:
> I'm guessing there's an oversight in JSBSim where they use the angle between
> "air flowing through the propeller vector" vs "propeller vector" and don't
> account for the amplitudes - a tiny crosswind of 3kts should have almost no
> effect, but it does.

are you using the new JSBSim code that's just been imported into FG next (aka 
2018.3.0) or no?

**Comment by algefaen** [comment]
I'm off on vacation for a couple of weeks by the way, flying and skydiving in the mountains. ^_^ ... don't expect much testing from me for a while.

**Comment by algefaen** [comment]
@wkitty42, yes, flightgear next 6d83e6.

**Comment by dany93** [comment]
Looking at the JSBSim calculation, I knew that the P-factor exaggerates the crosswind contribution but I didn't know that is was so much.
I hope that the JSBSim team can solve that.

**Comment by bcoconni** [comment]
@dany93 
> I knew that the P-factor exaggerates the crosswind contribution but I didn't know that is was so dramatic.

It does not come as a surprise to me since the P-factor effect in JSBSim is using the tangent of the angle which, as we all know, is infinite when then angle is equal to 90°. I guess we can use the sinus of the angle instead but I would prefer to discuss the details on the JSBSim project page if you don't mind (to keep the log of our discussions in the right place).

Could you please fill a new issue on the JSBSim project page (and link it to this issue) ?

Thanks.

**Comment by dany93** [comment]
Thank you @bcoconni for your attention.
Of course, I intended to fill a new issue in the JSBSim project but I was taking time to think about it, in order to understand the code calculation (as much as I can) and, if possible, bring propositions to help.

**Comment by dany93** [comment]
Done.
[P-factor: strong pitch moment with aircraft stopped in crosswind #78](https://github.com/JSBSim-Team/jsbsim/issues/78#issue-335100403)

**Comment by dany93** [comment]
After discussion, @bcoconni found and pushed the [82cc3893d commit ](https://github.com/JSBSim-Team/jsbsim/commit/82cc3893d70b625de0914796e73b0b9eea340828) in FG, which greatly improves (solves?) this behavior.
The aircraft holds up to 12 - 15 kt crosswind.

To be tested and observed more...

But please, pay attention: I've discovered and described a [bug in JSBSim](https://github.com/JSBSim-Team/jsbsim/issues/89#issue-338615597) which makes the aircraft with brakes "ON"  pitch and jump on the nose wheel if very close to an accurate crosswind. Better to keep away 5 or 10 deg from it to do these tests.

**Comment by algefaen** [comment]
I think this is pretty good now. Tested using 64f3c1 of flightgear next and 63b66a of issue-1130. 

Btw., I randomly hit the "90 degree crosswind" glitch you mentioned. Pretty annoying. But that's not triggered by the p_factor-changes, right?

**Comment by dany93** [comment]
I hope that you had good holidays and pretty flights.

> I think this is pretty good now

Good news. After maybe a bit more observation, if you find that the p-factor with this value of 60 (combined with propwash effect) is correct at takeoff and low speed, and at rest with 15 kt crosswind, we can consider asking for a merge. Letting (temporarily?) my `sin(angle)` idea in the fridge. Possibly for later if necessary.
OK?

> But that's not triggered by the p_factor-changes, right?

I think that I can respond "no" with almost no hesitation:
- I tested this on 4 aircraft, some of them which  have no or very weak p-factor,
- It is also seen with the engine stopped,
- Also with the Boeing 707, which has, of course, no p-factor.
