### ISSUE TITLE
Strobe lights dim or too weak

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1137]
Would someone like to verify if our strobe lights have gotten too dim? Is it just me or my system or are they dimmer than they used to be?

If they appear correct to everyone else we can close this. They really seem dim to me.

**Comment by gilbertohasnofb** [comment]
Looks fine to me: 

![image](https://user-images.githubusercontent.com/5700795/42133596-c9dd199a-7d24-11e8-8d4e-fa934d30f098.png)

Do you see it too weak on some particular time of the day or weather perhaps?

**Comment by wkitty42** [comment]
On 07/01/2018 01:08 AM, wlbragg wrote:
> Would someone like to verify if our strobe lights have gotten too dim? Is it 
> just me or my system or are they dimmer than they used to be?

someone on the forums was talking about doing MP via machine1<->machine2 and 
wanting to fly with their son... their problem was trying to locate each other 
when it starts getting dark... i made a few suggestions they could use (CTRL-M 
map, infrared filter) but i also did load the craft in the sim and look at the 
exterior view... our beacons and strobes do seem to be dimmer or maybe they have 
moved?... i don't know...

**Comment by wlbragg** [comment]
>you think the strobe is too weak on some particular time of the day

@gilbertohasnofb yeah, it was after dark, clear skys. At first I questioned if I even had them on, then when I realized they were on after studying the wingtip for a couple seconds it seemed like they should be considerably brighter. The glare from the nav lights mostly drowned them out.
I don't think they can be made to appear brighter without changing their size though, can they?

**Comment by gilbertohasnofb** [comment]
> I don't think they can be made to appear brighter without changing their size though, can they?

@wlbragg I am not familiar with how the light system works. But if you find a way of increasing their brightness then feel free to tweak it to your liking. Also, the problem with MP that @wkitty42 describes above might be related not to the strength of the light itself but how quick the dimming curve is applied over distance. Is this dimming by distance configurable by us or hardcoded in ALS?

**Comment by wlbragg** [comment]
>the problem with MP that @wkitty42 describes

I am aware of that conversation as well and it may be related, but this is in single player at night I observed how weak the effect is.
Look at night from the front offset from center by 10-15 deg.

It is a better visual in the daylight. It's like the nav lights at night are merging with it and muffling the effect.

**Comment by gilbertohasnofb** [comment]
@wlbragg I can still see the strobes during the day even at 150m away in helicopter view, but do feel free to increase the effect if you feel like. I do find it a bit weak as well.

>  It's like the nav lights at night are merging with it and muffling the effect, 

Yes, that's how I see as well. We could try increasing the strobe light size and see how that looks.

**Comment by wlbragg** [comment]
@gilbertohasnofb I'll test a bit more and see if I still think something needs to be done. I'm hesitant to increase the size, But these strobes are suppose to get you attention. This is where the animated world physics don't mirror the real world.

**Comment by algefaen** [comment]
It's a bit strange that the white navlight is whiter than our strobes, strobes should have a very high color temperature I think. This is a shot from behind where you see the navlight as a very white dot and the strobes as slightly warmer and bigger:
![image](https://user-images.githubusercontent.com/12012409/42597735-0e627f3c-855a-11e8-93f8-135325a572fd.png) ... maybe that's because there's no "procedural light" for the strobes, which makes it not use the same ALS thingmabobs?
 
When testing by flying away from an airport, it looks like the nav lights go out first (which is fine), but then the strobes disappear before the beacon. That seems wrong, the strobes should have the longest range. A hack that seems to work for me is to make the strobe light object bigger in the .ac file. I modified the 0.70834 to 1.70834 and I got a much better strobe range.

**Comment by algefaen** [comment]
(I believe we can use the "light-near", "light-far" etc. modifiers to reduce the visual size of the light even if we adjust up the size of the object..? To compensate so that it looks identical, just had a better range?)

**Comment by wlbragg** [comment]
>maybe that's because there's no "procedural light" for the strobes,

While I was working on the "glare" procedural lights I noticed there is supports for the strobes as well. I'll see if I can hook that up and we can compare.

**Comment by wlbragg** [comment]
@gilbertohasnofb 
OK, I hooked up the ALS strobes. I adjusted the nav left and right slightly (close range). I made them not so large so the ALS strobes has a better effect. I think it looks much better. I am pretty sure I accounted for everything such as wing damage and non ALS implementation users.
The only thing I haven't tested for is multilayer. I might try to get the user that brought this to our attention to participate  in that testing.
I apologize for including this in the current PR but started down that path before I realized it might be best to start a new PR for it. But I think we will be OK.
Again, please be sure to pull changes before continuing any work.
I got your last push incorporated as well.

**Comment by wlbragg** [comment]
I tested multiplayer and after a couple minor changes it is working fine. Big improvement in visibility. I think people should be happy with it now.
