### ISSUE TITLE
Tooltip for the dome light is incorrect

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1142]
Issue slipped through:
![image](https://user-images.githubusercontent.com/10434911/42178548-bf9ecf6e-7e28-11e8-80f1-590700c046fd.png)

The _WHITE DOME LIGHT_ and _WHITE DOME INTENSITY_ positions should be reversed 😉

**Comment by wlbragg** [comment]
Duuu!, thanks @legoboyvdlp I'll fix it in the Glass panel effect PR.

**Comment by wlbragg** [comment]
Also the Wjite typo.

**Comment by wlbragg** [comment]
Done!
