### ISSUE TITLE
Magnetic compass missing reference line

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1148]
Our magnetic compass is missing reference line which is used to read the value. This is the model in real life:

![](https://studentpilotnews.com/files/2017/01/Compass-Errors-YT-Thumbnail-2.jpg)

and here is a screenshot of ours:

![](https://user-images.githubusercontent.com/5700795/43045248-093c6f08-8dad-11e8-83a6-a502ea289915.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg Do you think you could add that whitish line to the 3D model in the very centre of the readout window? The texture actually does have the white line but I can add a larger white square to it if you need for mapping.

**Comment by wlbragg** [comment]
Done.
