### ISSUE TITLE
Ammeter is the wrong model

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1151]
Our ammeter is the wrong model. The 172 model P did not have a gauge showing the voltage, it was just an ammeter showing only the electric current. This is how it looks:

![](https://cdn.shopify.com/s/files/1/1712/9813/products/IMG_5924_80242706-b63f-4b3a-a03d-3b858e28c584_grande.JPG?v=1513264238) 

I checked at least 20 photos and 100% of all model P's had this same model and none had a gauge for the voltage. So should we remake this model?

Some reference shots:

![](http://imgproc.airliners.net/photos/airliners/2/4/9/2532942.jpg?v=v40)
![](http://imgproc.airliners.net/photos/airliners/5/9/3/1702395.jpg?v=v40)

**Comment by gilbertohasnofb** [comment]
@wlbragg Would you be up to model this new gauge? I can create the textures.

**Comment by gilbertohasnofb** [comment]
@wlbragg using the first photo as reference (the one with blue background) I created and pushed a new texture. Top left is the texture for the needle, top right for the recess, bottom left for the metallic mount for the needle, bottom right for the bottom part of the needle.

**Comment by gilbertohasnofb** [comment]
See: 
![image](https://user-images.githubusercontent.com/5700795/43279939-693ed974-9107-11e8-8443-9e2edf72d3e1.png)

**Comment by wkitty42** [comment]
On 07/26/2018 12:33 PM, Gilberto Agostinho wrote:
> Our ammeter is the wrong model. The 172 model P did not have a gauge showing the 
> voltage, it was just an ammeter showing only the electric current.


IMHO, yes it should be re-made... there is a huge difference between an ammeter 
and a voltage meter... a really huge difference ;)

we'll still need the voltage code, though... then the ammeter would be driven by 
the amperage difference being drawn between the battery drain and the alternator 
charge...

**Comment by gilbertohasnofb** [comment]
Agreed. We took care in checking sources for all our gauges and it is my belief that this is the very last one that needs fixing in order to have an absolutely coherent cockpit of a model P. Shouldn't be too much work I think and the result will be worth  it.

**Comment by callahanp** [comment]
I've got a gauge in my home cockpit that has voltage and amps.  Will the voltage property still be present and accurate after this change?

**Comment by gilbertohasnofb** [comment]
@callahanp Hi Pat, see my answer [here](https://github.com/c172p-team/c172p/issues/38#issuecomment-408268434):

> the property `/systems/electrical/volts` will still be in use and will have the correct voltage value. The only difference is that our cockpit will no longer have a gauge displaying that value. But as long as you use that property in your cockpit you should be fine.

**Comment by wlbragg** [comment]
This is done.
The new center point for the rotation is
x=-0.36922
y=-0.40925
z=-0.15108
The two objects that get added to that rotation are
Ptr
PtrTip

**Comment by wlbragg** [comment]
I cut the glass out and checked the interpolation table. As far as i can tell this is completely finished.

**Comment by gilbertohasnofb** [comment]
@wlbragg The new model looks _so_ good, thank you so much. I manually improved the light map and added the missing tick to the 0 position to the texture. I also fixed the interpolation table, the extreme values of the new ammeter is 60 amps and not 40 amps. Also, the interpolation was inverted. I think it's all good now.
