### ISSUE TITLE
Add black panel behind broken wing

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1155]
I think we should add a simple black panel behind the broken wing. Currently you can see the wing interior through the holes but that doesn't look very good, that should be pitch dark. Here is what we have:

![image](https://user-images.githubusercontent.com/5700795/43460349-4595015a-94c8-11e8-86cf-fdf35ddf88c8.png)

And this is what I propose:

![image](https://user-images.githubusercontent.com/5700795/43460356-4a327260-94c8-11e8-85c4-1a09a475e749.png)

a simple black object behind the broken wing structure on each wing should do the trick.

**Comment by wlbragg** [comment]
@gilbertohasnofb good catch except I am sure I already had discovered that issue when I was working on it and I thought I did indeed make a blocking panel.

I'll take a look.

**Comment by wlbragg** [comment]
Wow, that is really bizarre. I guess I didn't. How is it you can remember doing something you never did?

**Comment by gilbertohasnofb** [comment]
I just pushed my commit. And I have another one coming up soon.

**Comment by gilbertohasnofb** [comment]
Done.

**Comment by wkitty42** [comment]
On 07/31/2018 01:15 PM, wlbragg wrote:
> Wow, that is really bizarre. I guess I didn't. How is it you can remember doing 
> something you never did?


when the broken wings were introduced, there was discussion about how the 
interior of the broken parts should look... it was plain before and then some 
internal guts were added... maybe a rib beam with holes cut in it was added to 
dress it up slightly? is this black panel to be added behind that exposed rib 
beam or am i remembering things from the past that never happened, too??


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by gilbertohasnofb** [comment]
@wlbragg can't the black panel be much closer to the wing structure? This is how it looks now, notice how the black panel does not cover all holes:

![image](https://user-images.githubusercontent.com/5700795/43513884-d4e12fe2-9576-11e8-9245-934b9aefc6d2.png)

**Comment by wlbragg** [comment]
Yes, but a wing is hollow?

**Comment by gilbertohasnofb** [comment]
The question is what the dark panel is simulating. In my view, the amount of light inside the structure would be negligible and it would simply look nearly pitch dark through all holes. See for instance:

![](https://d2rormqr1qwzpz.cloudfront.net/photos/2016/04/27/87456-tracker-fold.jpg)

Or even:

![](http://www.fastacraft.com/images/hydrofoil.jpg)

This looks like a 172. Notice how much darker the inside is even though the whole bottom part of the wing is missing and thus light can enter. With the bottom part it would look really dark:

![](http://www.aerotech-uk.co.uk/wp-content/uploads/2013/09/G-OVFR-Wing.png)

**Comment by wlbragg** [comment]
@gilbertohasnofb I went ahead and move the panels closer to the end. I also UV mapped them to the metal texture and assigned them a new material that is really dark. So in the right  light they will look like a dark metal panel, but mostly they just look dark. The flaps can't really be changed because they are not damaged, so the dark panel needs to somewhat blend with the end of the flaps which is lighter.

![dam](https://user-images.githubusercontent.com/11069680/43545193-cf020e6a-959a-11e8-8126-b694dec3c061.jpg)

**Comment by gilbertohasnofb** [comment]
That looks good, I will test it in the sim. Another option that crossed my mind now would be to map the interior side of the wings to a fully black color, this way we wouldn't need a panel at all I think (unless some object perforates the wing). But I think this is looking good!

**Comment by gilbertohasnofb** [comment]
Just tested it, it looks excellent.
