### ISSUE TITLE
Remove shadow effect from radio digits

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1156]
I don't think the radio digits should be affected by the shadow effect since they emit light themselves. Under the same RADIO LT settings, compare these two situations:

1) no shadow, all digits have the same light intensity:

![image](https://user-images.githubusercontent.com/5700795/43460507-bca5d648-94c8-11e8-90e9-a0eeeb8123c3.png)

2) under COMs and NAVs under shadows are dimmer, ADF is still bright:

![image](https://user-images.githubusercontent.com/5700795/43460528-c9fc4c3c-94c8-11e8-892e-1a9176e52d20.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg If this is difficult to see in the post above, open each image to a different tab in your browser and flick between them. The difference will then become obvious.

**Comment by wlbragg** [comment]
Done!
