### ISSUE TITLE
Interior door handle animation is wrong

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1157]
Interior door handle animation is wrong, see this video at 0:24: https://www.youtube.com/watch?v=kfGN_QEg1UU

We need to fix the following: 
* the pivot point for the interior handle is in the middle of the object, not in the back. We may need to 'carve' a bigger hole in the doors in order to accommodate the  movement
* the interpolation table should include more items as the movement of the door is very snappy and includes two stages. 
* when closing the door, the door handle animation should not take place.

**Comment by gilbertohasnofb** [comment]
Solved the last item and pushed already. I am now going to fix the animation for the exterior handle.

**Comment by gilbertohasnofb** [comment]
@wlbragg I also adjusted the animation of the external door handle. Just like in a car, that handle will be flicked when opened the door, not held open.

But I need a favour in order to improve these animations. When opening the door from the interior, one would obviously use the interior handle. But when closing the door, I imagine they would use this part here to grab the door:

![image](https://user-images.githubusercontent.com/5700795/43476557-cb0cf4be-94f0-11e8-9f2e-f4ef5f3d63be.png)

This object is the same object as the door so I can't pick it. Could you please separate it from the door and give me the names so that I can enable it when the doors are opened and disable the metallic internal handle?

**Comment by legoboyvdlp** [comment]
Did you make it rotatable 180 degrees as the real one seems to be? Sorry - unable to test right now.

**Comment by gilbertohasnofb** [comment]
No, I made it 110 degrees like in the video, in two stages. First around 70 degrees, second 110. It's very similar to the video.

**Comment by legoboyvdlp** [comment]
ah ok - I assumed that the handle could travel the whole 180 degrees - otherwise, why would they have a hole that would allow it to do that?

![image](https://user-images.githubusercontent.com/10434911/43478258-54456ed8-94f5-11e8-9a9f-283cd170a900.png)


Obviously, to actually open the door, it is evident you only need to pull the handle part of the way, just as you only pull the door handle of many cars part of the way to open it - however, it seems that this handle can travel the whole way if you particularly wanted to? Admittedly I only watched a few seconds of the video when the man was actually moving the handle, so maybe I missed something :)

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp maybe the handle does rotate 180, but the handle is not a slider but a fixed animation. I replicated exactly as in the video which shows the pilot opening it by rotating the handle only by around 110 degrees. My animation is identical to the video and looking quite good, I believe.

**Comment by gilbertohasnofb** [comment]
@wlbragg Also, the non-metallic handle (the one I asked you to make a separate object) should be moved considerably backwards as in the photo below (but still reachable by the pilot from this seat, obviously):

![](http://airplanesusa.com/wp-content/uploads/2017/02/030.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg Ok, I am done with my commits for the moment. These are the modifications I did:

* merged the door closing/opening due to airspeed
* better animation for the interior metallic door handles when opening the doors
* interior metallic door handles do not move when closing the doors
* better animation for all exterior door and baggage door handles
* exterior door and baggage door handles do not move when closing doors

Once you modify the position of that other internal handle and make it a separate object (the one for closing the door) I will add a condition to only use it for closing and only use the metallic one for opening. Just give me a shout when that's done.

**Comment by wlbragg** [comment]
If I move it backwards you know you have to change the AO and the light map, you OK with that?

**Comment by wlbragg** [comment]
@gilbertohasnofb the door straps are separated and relocated. Their names are...
doorintstrapleft
doorintstrapright

We need to redo the AO light map and even the texture. It would be nice to add the metal ends. I can improve the strap is you think we need to.

**Comment by gilbertohasnofb** [comment]
Great, I implemented the logic and I tweaked the AOmap of the 4X-CHV livery. I also added the new texture to the `interior.png` of 4X-CHV to the strap (please make it texture dependent, I will sync all liveries at the end) and also added it to the lightmap. The texture should look like this one:

![](https://camo.githubusercontent.com/30a260522b1571bfa09828c42bc70d62edc0e48e/687474703a2f2f616972706c616e65737573612e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031372f30322f3033302e6a7067)

So the strap is made out of some plastic material with metal corners. I added it to the bottom left corner of `interior.png`:

![image](https://user-images.githubusercontent.com/5700795/43514349-f31ee52a-9577-11e8-8b8e-af3d0eb26ff8.png)

**Comment by legoboyvdlp** [comment]
The strap is pretty dark - even at maximum screen brightness at noon with the dome light on I could barely see it with the 4X-CHV livery. The D-EEQA livery with the red/white cockpit made it easier to see. Hopefully those texture updates will fix that?

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp the new texture is pretty bright so that will definitely make it easier to see.

**Comment by gilbertohasnofb** [comment]
Looks great, I will see if I can improve the texture a bit more.

**Comment by gilbertohasnofb** [comment]
I improved it a bit, pushing it soon.
