### ISSUE TITLE
Window handle base seems to be double mapped

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1159]
Window handle base seems to be double mapped. Not the handle itself but the base (circle behind it). I suspect this because when the red flood light is on, it has a very strong red glow while nothing around it is even remotely red.

![fgfs-screen-001](https://user-images.githubusercontent.com/5700795/43554556-0cd12120-95ed-11e8-9f92-566d880d4f6e.jpg)

@wlbragg I have already pushed a new texture for this object and updated the lightmap to fix this issue, just map each of the bases to these, please:

![image](https://user-images.githubusercontent.com/5700795/43554722-ed9b45dc-95ed-11e8-904f-9b37a6463501.png)

**Comment by wlbragg** [comment]
Done!
Yes they were mapped with something else.
