### ISSUE TITLE
Animate water rudder cable

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1167]
Animate water rudder cable. Right now clicking on it instantaneously move it from DOWN to UP position (and vice-versa).

**Comment by gilbertohasnofb** [comment]
@wlbragg This might be something you'd be interested since you are working on the pontoon tutorials.

**Comment by wlbragg** [comment]
If anyone has time to animate that using the same techniques as say the primer, please do. I don't think I am going to have the time. I may be able to get to it, but it will be way down on the priority list.

**Comment by gilbertohasnofb** [comment]
I will try to do this tonight.
