### ISSUE TITLE
Sun Visor Mapping

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1168]
![image](https://user-images.githubusercontent.com/10434911/43911893-8dba143e-9bf8-11e8-8343-8e69475592bd.png)

Sorry - still not quite right! 😀

**Comment by legoboyvdlp** [comment]
This is also quite streaky:

![image](https://user-images.githubusercontent.com/10434911/43911967-cab1d14c-9bf8-11e8-99ed-217901a367d9.png)

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp That would be nice to get fixed but I also I think that's quite minimal, so I will let @wlbragg decide.

**Comment by wlbragg** [comment]
I'll take a look.

**Comment by wlbragg** [comment]
I fixed the texturing strips on the steps, any farther needs to be done with the texture itself.

Same for the visors, I lined up the bottom and side edge, but not the top and side edge, that I think requires a texture change or more mapping than I want to partake in at the moment.

These changes are pushed to the cowling PR Add cowl plugs #1166
