### ISSUE TITLE
Improve flap sound

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1171]
- separate flap lever (click) and motor sounds (you could move the lever without electrical power, and that should make a click)
- find a new motor sound - I found a public domain one somewhere from a Cessna but never could find it again, it is an electrical whining noise if i recall correctly. YouTube might help to compare any sounds you find against.

If nobody beats me to it I'll have a search for sounds and if possible implement this.

**Comment by gilbertohasnofb** [comment]
I will take a look, but I am having quite a lot of work right now and since we already have a flap sound this will be low priority, ok?

**Comment by gilbertohasnofb** [comment]
I partially worked on this on https://github.com/c172p-team/c172p/pull/1169. We already had a very soft click sound when the lever moved even when the flap motor was off. But I've made it a bit louder and replaced with a better sound. I could not find a reference for the motor sound, could you please try to find the one you mentioned? Also if this reference has a click sound I can better judge if what I just created is good or not.

**Comment by gilbertohasnofb** [comment]
Oh, those are not GPL friendly... :sob: they are so good. I will try to recreate them at some point then.
