### ISSUE TITLE
Throttle lever does not move all the way in

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1180]
This is the full throttle position with the new lever:

![image](https://user-images.githubusercontent.com/5700795/44062209-51d31b6a-9f53-11e8-8155-889ea6cefde1.png)

Throttle lever does not move all the way in. At full throttle the black part should be touching the back side, just like the mixture.

**Comment by gilbertohasnofb** [comment]
@wlbragg do you think you could take a look at this? Should be easy enough to fix in Blender or via xml.

**Comment by wlbragg** [comment]
@gilbertohasnofb I'm going to push this fix to a miscellaneous-issues-cleanup PR I will make when done.
Along with the cowl plug changes.

**Comment by gilbertohasnofb** [comment]
Sounds good.
