### ISSUE TITLE
Vents are too light

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1184]
![image](https://user-images.githubusercontent.com/10434911/44354383-a2092b80-a4a1-11e8-8bfc-c35206ece5e1.png)

![image](https://user-images.githubusercontent.com/10434911/44354411-b0efde00-a4a1-11e8-89f0-6e06274a4274.png)

Seems this got broken along the way?

**Comment by wlbragg** [comment]
@legoboyvdlp could you be more specific, I'm not sure what your referring to? If it is the color, that I think is the texture color.

**Comment by legoboyvdlp** [comment]
I was referring to the black stripe which I thought was a UV error?

The light gray texture also looked similar to the default AC3D material as well.

**Comment by wlbragg** [comment]
Oh, the black strip is the vent hole or opening. That part is correct.

**Comment by gilbertohasnofb** [comment]
@wlbragg how do you feel if I would darken the texture of the vents a bit? They are now too white in comparison with the rest of the cockpit. Could you point out to me where they are mapped to?

**Comment by wlbragg** [comment]
The vents are a bit of a mess UV mapping wise.
![uventuv](https://user-images.githubusercontent.com/11069680/44490557-356a6a00-a624-11e8-8ea1-99a9f4962fdc.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg I will create a branch for this and push a fix soon

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Thanks for reopening this. I changed the title to match what I am working on.
