### ISSUE TITLE
FDM: Too much adverse yaw

### ISSUE THREAD

**Issue by Octal450** [c172p-team/c172p#1188]
First off, the FDM feels very good, but the adverse yaw from rolling is just far too much. When you put a roll input, far too much adverse yaw happens, even when trying to coordinate the turn with the pedals. The issue is most noticeable at low speed (where there is arguable too much p-factor also). Compared to the real plane, it feels like far too much to remain control.

Best Regards,
Josh

**Comment by onox** [comment]
@dany93 ^^

**Comment by dany93** [comment]
This is an endless issue....

My references: (at least part of them, a few ones that I can remember after so many convolutions)
- [Megginson's tables](http://www.megginson.com/Aviation/roskam-coefficients.html#sec.data)
- [advices from okroth 18 April 2018](https://github.com/c172p-team/c172p/issues/1047#issuecomment-382449833) (issue #1047)
- [this video](https://www.youtube.com/watch?v=UV8xcm5xsuo) (adverse yaw). According to this video, I think that the adverse yaw is correct (at least close to).
- [algefaen' agreement 11 july 2018](https://github.com/c172p-team/c172p/issues/1130#issuecomment-404294369)  (issue #1130) on the P-factor.

Personally, I think that the FDM is perfectly controllable. And I like its behavior. My opinion is partly based on subjective feelings, but not only (see my references above). I also have the feeling that the slip ball behavior is realistic (this is connected to the adverse yaw in particular).

As I have no access and no experience on a real c172 (differently from you) I suggest that:
- (very important) you ask other pilot opinions to ascertain your impression, to be sure about that must be changed.
- then, that you adjust the relevant coefficients to fit your feelings, test the results and propose them here.

Please don't forget, if you change some coefficients, to check that your changes does not degrade something else (like crosswind landing capacity, forward side-slip, stall and spin behavior, flat spin,...).
Cross coupling of the effects after changing coefficients is a quite hard and time consuming issue.

**Comment by it0uchpods** [comment]
Alright, I'll let you know, thanks.
J

**Comment by dany93** [comment]
Also, @tigert[ wrote](https://github.com/c172p-team/c172p/issues/947#issuecomment-360999442) (Spiraling propwash effect #947):

> Yeah, right rudder is needed. Also it is present on climbing and turning to left crosswind leg (low speed, climbing turn to left) where you need no left rudder at all — or actually you just slightly ease the right rudder a to keep the ball centered.

**Comment by Megaf** [comment]
Is this useful at all?
[Report.pdf](https://github.com/c172p-team/c172p/files/2342562/Report.pdf)

**Comment by dany93** [comment]
Thank you @Megaf.
It can be useful. At least, interesting. Some  more data.

**Comment by Megaf** [comment]
What kind of information would be useful? @it0uchpods can provide feedback and hands on information and I can try to find some documentation on something.

**Comment by gilbertohasnofb** [comment]
@dany93 can we close this one?

**Comment by dany93** [comment]
@gilbertohasnofb 
Yes.
