### ISSUE TITLE
FG 2018.3.1 RC branching

### ISSUE THREAD

**Issue by wkitty42** [c172p-team/c172p#1194]
I couldn't find an issue directly related to the upcoming FG release so I've created this one. We can keep it or not after any discussion is completed.

Please catch up on the FG dev mailing list thread titled "Release management for 2018.3". Specifically this conversation which I understand to mean that we need to get our latest work into FGData in the next less-than 8 days.

> On 08/31/2018 07:38 AM, Torsten Dreyer wrote:
>> James Turner <james@flightgear.org> schrieb am Fr., 31. Aug. 2018 um 12:43 Uhr:
>>>     On 31 Aug 2018, at 11:43, wkitty42@gmail.com <mailto:wkitty42@gmail.com> wrote:
>>>>
>>>>     if we're having a release in September, which is less than 24 hours away,
>>>>     shouldn't we basically already be in a frozen state and beta/RC testing
>>>>     now? can we really get proper testing done in less than 4 weeks if we're
>>>>     looking for release at the end of September? history doesn't seem to
>>>>     support this :(
>> 
>>     The release is in October :) We starting the process on September 8th (well,
>>     continuing it, since we were already planning and discussing this for some
>>     months)
> Yeah - cutting the release branches should mark the start of the freeze. We (a.k.a. me)  trigger the -rc from the release branches.
> I can do the branching, this is completely scripted and only takes a few minutes, if one knows how to use them.
> 
> Please add the c172 updates /before/ we branch. We ususally cherry-pick into the release branch which effectively doubles the commit.
>

**Comment by onox** [comment]
@stuartbuchanan @zakalawe Branch [release/2018.3](https://github.com/c172p-team/c172p/tree/release/2018.3) has been created.

**Comment by stuartbuchanan** [comment]
Thanks guys.  I've just committed this to fgdata.

I've spotted a couple of issues - I'll mention them on-list.

-Stuart
