### ISSUE TITLE
Console message: "unrecognized LOGIC token or"

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1203]
To fix:
replace line 979 in c172p.xml:
`<test logic="or" value="gear/gear-pos-norm">`

with 

`<test logic="OR" value="gear/gear-pos-norm">`

**Comment by wlbragg** [comment]
@gilbertohasnofb  @legoboyvdlp Does this need to be add to the Release as a bug fix?

**Comment by gilbertohasnofb** [comment]
@wlbragg Yes. And I will be checking everything you wrote in 2 minutes.
