### ISSUE TITLE
Add auto mixture to the standard autostart in c172p.nas

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1206]
I created an fcs_function outputting the property /fdm/jsbsim/engine/auto-mixture in c172p-engine.xml to use in the "on approach" state to insure (best we can) that the aircraft will start when in this state, regardless of elevation.

It is simple to use...
~~~
var auto_mixture = getprop("/fdm/jsbsim/engine/auto-mixture");
setprop("/controls/engines/current-engine/mixture", auto_mixture);
~~~

I totally forgot to do this when I created it but think it is a good idea. Unless of course we don't want to let autostart work in higher altitudes. :fearful:

**Comment by gilbertohasnofb** [comment]
> Unless of course we don't want to let autostart work in higher altitudes. fearful

I think we want the autostart function working in all situations we can, if I could I would have it working even under water or if on the Moon! :rofl:

**Comment by wlbragg** [comment]
This should be ready to merge after testing.
