### ISSUE TITLE
Rudder Trim

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1217]
The POH of a 1982 Model P which I have suggests rudder trim is an option, _apart_ from the manual rudder trim tab that can only be moved on the ground:

![image](https://user-images.githubusercontent.com/10434911/46860616-b49c4300-ce08-11e8-907c-409d345856d3.png)

I am not certain if the cockpit control moves the manual tab (i.e. should adjust the permanent rudder trim factor we have) or is separate (should be SUMMED to the permanent rudder trim factor)

The manual tab is this part:
![image](https://user-images.githubusercontent.com/10434911/46860706-e7ded200-ce08-11e8-940d-993dfd4b93c2.png)

According to Figure 7-1, the rudder trim control is a wheel exactly like the elevator trim, but mounted below the elevator trim at 90 degrees.

This feature is probably not common, but is definitely an option.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp I think we already had this discussion before. We have added the rudder trim tab model to the rudder (the little fin) but, if I remember correctly, both @wlbragg and @dany93 agreed that we would not implement this functionality. The argument was something along the lines that this is something that tends to be set by mechanics and not pilots and it's not something that people would change often/at all. I personally think such option can end up doing more harm than good, since it has nearly zero useful functionality and could generate a million new bug reports ('why my aircraft turns so much on the groundz??')

**Comment by dany93** [comment]
If I remember well, the argument was about a rudder-trim setting which could be made only on the ground (by manually bending the manual tab, done by mechanics, normally).
Here, @legoboyvdlp is speaking of a rudder trim which can be set by the pilot from the cockpit (like the elevator trim). Doable in flight.
But I agree with @gilbertohasnofb, I'm not sure it would add much.

_An aileron trim from the cockpit would be more useful for the comfort (particularly because our joysticks have more or less strong return springs), but it does not exist on the real one._

**Comment by gilbertohasnofb** [comment]
Oh I completely misread it. Sorry guys, I'm multitasking a lot lately and I am reading a million texts every day. About the rudder trim from the cockpit, I think the absolutely vast majority of 172P's out there do not have such system. I personally don't see the point of implementing it.

**Comment by wlbragg** [comment]
I'd have to side on is it "realistic", is it a common feature in this model/year aircraft? If so, then yes I think we should offer it. If not then the manual tab is OK.
Also I think we discussed the option of a GUI option to "manually" trim the "manual trim tab" as if the mechanic did this for you.
My opinion on that is I am on the fence. We probably will never add an option to change the timing of the engine, is this the same kind of thing, to low level? Or even as @dany93 pointed out, the lack of the aileron trim feature in the real thing, there is a manual way to adjust this, I doubt we will ever offer that either.
But what if all those options existed? What fun for the ultimate enthusiast.
So I am on the fence when it comes to any of these options, I could go either way.

**Comment by legoboyvdlp** [comment]
The feature definitely does exist for the 1982 Model P - and I posted a screenshot of a 1981 Model P with it included. Regardless, I must admit it is rather uncommon to find rudder trim in any model P.

**Comment by legoboyvdlp** [comment]
http://www.cessna172club.com/forum/ubbthreads.php?ubb=showflat&Number=226050:

'I have factory installed rudder trim in my 1982 172P Skyhawk II, works great, luv it !'

'Mine does not have a tab on the rudder like my elevator trim does. 

The adjustment is a knob, it would be manually moved horizontally, spring loaded with notches.

Couple 3 or 4 each side of center(or neutral), little rudder trim, little more rudder deflection and a little more for severe yaw correction...

The knob is located just above the fuel selector in the center of the consol adjusted notch by notch in a horizontal direction with a small, round, black knob.

I will photograph next time I am in the hangar.'

**Comment by gilbertohasnofb** [comment]
> What fun for the ultimate enthusiast.

What fun for us addressing bogus bug reports in the forum!

> We probably will never add an option to change the timing of the engine, is this the same kind of thing, to low level? Or even as @dany93 pointed out, the lack of the aileron trim feature in the real thing, there is a manual way to adjust this, I doubt we will ever offer that either.

This. I personally feel that these features are over-the-top. The rudder trim slider is way over the top for me, but I am on the fence about the feature @legoboyvdlp is proposing, particular after his last post.

> '[...] I will photograph next time I am in the hangar.'

I guess he is not posting the photo after 3 years. We would need to find a photo of the cockpit knob.

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/46883144-f77e0b00-ce48-11e8-8e0e-436cb46ebf72.png)


This appears to be a 1981 model?

**Comment by wlbragg** [comment]
Interesting, I wondered how they could make that safe. Only 2 ticks either way. I guess you get used to looking out for it as you do for elevator trim.
If you all decide we want to add it, I can do the modeling.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Great, thanks for the research. @wlbragg I am game if you are, I can make textures if you feel like modelling it. We should then add an option to the aircraft menu similarly to the digital clock. And someone has to code it all as well, but should be fairly simple.

**Comment by legoboyvdlp** [comment]
I can do the coding in that case? :)

**Comment by gilbertohasnofb** [comment]
deal! :smile:

**Comment by wlbragg** [comment]
@legoboyvdlp I'll use RudderTrimKnob for the object and I can do the animation and effects of the interior knob while I am modeling it as I will have all the numbers (5 stops = -2 to +2).
You can use that same object properties for the fdm control base.
I'll make the rest of the cockpit visual as RudderTrimBase for the optional on/off.

>I am not certain if the cockpit control moves the manual tab (i.e. should adjust the permanent rudder trim factor we have) or is separate (should be SUMMED to the permanent rudder trim factor)

We will need to verify what this looks like as I want to model the exterior as well.

@gilbertohasnofb we will need the textures on the appropriate .png, if you can do that and add it to the fog-and-frost PR I will have it available to use. Again I need to use the fog-frost PR for the mesh work :(

**Comment by gilbertohasnofb** [comment]
> Again I need to use the fog-frost PR for the mesh work :(

Or we can wait a bit before jumping into another project. I think we should finish the frost and seat mounts first, merge that PR and then start working on this.

**Comment by gilbertohasnofb** [comment]
I will be home in a couple of hours and then I will sync those livery textures, are you working on something on that branch or can I simply push my stuff when I get home?

**Comment by wlbragg** [comment]
You can push when ready. Yours is the last commit.

**Comment by wlbragg** [comment]
@gilbertohasnofb and yes, we can finish this up and merge and start again with a new PR for the rudder trim.
I have a little bit more mapping to do on the seats and then the view movement code.
I will test the fog/frost in the sim in the mountains and see what that looks like in real time and either approve or ask for a better artist rendering. I suppose it is better than what we already have, but would like some one else to confirm that.
After all that we can merge.

**Comment by dany93** [comment]
For the trim steps, mind the sensitivity.
The current value (preset) for the rudder trim is 0.02 (very sensitive for the slip-skid-ball).

**Comment by legoboyvdlp** [comment]
@wlbragg if you do the 3D part in the frost / fog branch (to avoid doing mesh changes in another branch), I can do the coding part in a new branch, into which I will merge master as soon as frost fog is merged?

so, as such: 

![image](https://user-images.githubusercontent.com/10434911/47020626-b4c27880-d151-11e8-9bbe-94efcb7a172d.png)


hopefully that diagram helps to show what I mean?

**Comment by wlbragg** [comment]
@legoboyvdlp OK, lets do this.

**Comment by wlbragg** [comment]
@gilbertohasnofb here is the texture work layout. You can add it to either the frost/fog branch or the PR @legoboyvdlp  is going to create for the code. 
It would be easier for me if it were in the frost/fog branch so I can wrap up the mapping now instead of waiting. But not critical either way.

Looks like it should be added to two different textures,
panel_parts.png
![uv-panel_parts](https://user-images.githubusercontent.com/11069680/47111669-bf484500-d219-11e8-9e73-f9020d1eed32.png)

**Comment by wlbragg** [comment]
@gilbertohasnofb 
Note the uv layouts should be to scale for overlaying in Gimp.
The Base portion is made to be visible or hidden, so when you do the texture maybe you can make it match or fade with the original background, however you decide to do that.
The only special request is that the recessed hole that the slide bar and knob rotates through needs to be black or very dark. I still may have to cut it into a new object and do it with the material settings.
![ruddertrimbase2](https://user-images.githubusercontent.com/11069680/47112386-cb350680-d21b-11e8-99fc-6bd2d21926d2.jpg)

**Comment by wlbragg** [comment]
@gilbertohasnofb if you decide to place any texture in a better location on the page, that is not a problem, I can move the mapping so long as the proportions don't change considerably.

**Comment by wlbragg** [comment]
@legoboyvdlp 
The only object names to deal with are 
RudderTrimKnob
RudderTrimBase
You can make them both will be hidden or visible on demand in the GUI.

I'll go ahead and add both objects to the interior effects and code the rotation of RudderTrimKnob.

**Comment by wlbragg** [comment]
Here is what I have with my less than stellar temporary texture applied.
![ruddertrim1](https://user-images.githubusercontent.com/11069680/47128283-3d2a4180-d256-11e8-9847-226011ca4300.jpg)
![ruddertrim2](https://user-images.githubusercontent.com/11069680/47128284-3e5b6e80-d256-11e8-824b-874e40ab0884.jpg)

**Comment by wlbragg** [comment]
@legoboyvdlp 
The property for adding to the rudder trim is
controls/flight/rudder-trim-knob
it has a range of 6.8 to -6.8 with steps of 3.4

So I think the easiest solution is to do a table like below and add it to the following property of
controls/flight/rudder-trim
That way the mechanic can physically adjust the trim tab (controls/flight/rudder-trim = 0.02) to whatever they want and still add or subtract the .001 steps with the knob (controls/flight/rudder-trim-knob).
~~~
<table>
  <independentVar>controls/flight/rudder-trim-knob</independentVar>
    <tableData>
      -6.8    -0.002
      -3.4    -0.001
       0.0     0.000
       3.4     0.001
       6.8     0.002
    </tableData>
</table>
~~~

**Comment by wlbragg** [comment]
@gilbertohasnofb FYI: I'm posting my temporary texture for your reference. Hopefully it will give you a feel for the layout and how the texture fits it. It's not very good, I'm hoping your artistic talents can improve this.
![trim-rudder](https://user-images.githubusercontent.com/11069680/47131168-d8c1af00-d262-11e8-88a4-174180a310ad.png)

**Comment by dany93** [comment]
> that is if this proves to be enough per @dany93 suggestion

Important: I don't know for the real one, only pilots or the POH can say.

If you add a cockpit setting, I would have expected a larger max amplitude. Let's say  at least +/- 0.04 or 0.05? By steps 0.001, but larger amplitude. You can easily test the effect by manually setting `controls/flight/rudder-trim` in the properties (in stabilized flight, whatever the stabilized conditions you wish to test) and observe the slip ball. Or the `instrumentation/slip-skid-ball/indicated-slip-skid` property.
Is the real one by 3.4 steps (with notches, like the flaps), or is it continually (closer to the elevator trim setting)? The white squares being marks only for help? As it very likely drives a cable, the positions might be on a continuum. Even if this has to be translated by small steps for us.

**Comment by wlbragg** [comment]
OK, I was going by the assumption that the marks were hard stops and they were the only choice. In that scheme the 3.4 was for the animation reaching those marks precisely in 2 steps left and 2 steps right, nothing more. The table was to show how I would put those animation stops together with the actual rudder trim settings and still allow for 0 cockpit trim control to = mechanics .02, or whatever the mechanic adjusted the default trim to.
I also was operating off the assumption that what @dany93 indicated about the value of .001 would be a big step. Now it looks as I may have read that wrong and maybe then he's  suggesting that as a very small incremental step to a max range of potentially to 0.1.

For my part I only need to know if the rudder trim knob has 5 hard stops or needs to be like the elevator?
@legoboyvdlp can do the rest in the FDM portion.

 Also I should ask the question, is this the rudder trim mechanism we want to use or maybe we should have the other type I have seen that looks like a smaller horizontal version of elevator trim?

**Comment by legoboyvdlp** [comment]
The POH suggests there are detents - however, the lever can take any position between OR at the detents. So, I'd say its like the elevator trim - except, you can put the lever in a detent, and to move the rudder trim form there you have to lift the lever up to clear the detent.

**Comment by dany93** [comment]
> ( the value of .001)... he's suggesting that as a very small incremental step to a max range of potentially to 0.1.

Correct.
0.001 is a small step, necessary for accuracy. Small effect.
0.4 or 0.5 or 0.1 (???) is the max range.

**Comment by legoboyvdlp** [comment]
As for the second question, it mentions a bungee connected to the rudder control system, probably something like this?
![image](https://user-images.githubusercontent.com/10434911/47166320-d491a200-d2f3-11e8-89cc-16cfba59642e.png)

probably, 

So I think the effect is within the rudder control system - i.e., applying a force to the standard rudder control, not by the mechanic's tab. 

I don't think there is a horizontal tab either - I think its more that the neutral position of the rudder is changed?

**Comment by wlbragg** [comment]
>Also I should ask the question, is this the rudder trim mechanism we want to use or maybe we should have the other type I have seen that looks like a smaller horizontal version of elevator trim?

>I don't think there is a horizontal tab either - I think its more that the neutral position of the rudder is changed?

@legoboyvdlp I think I confused you. What I was asking is related to the interior trim knob style. Do we want to use a different style of trim control? Instead of a lever use a rotating knob like the elevator uses?

**Comment by wlbragg** [comment]
@legoboyvdlp FYI: the bungee picture and explanation satisfies my exterior rudder control mechanism. I think I will leave that up to users imagination for now.

**Comment by dany93** [comment]
> I think its more that the neutral position of the rudder is changed?

In this case, yes.
The bungee is is a cheap way to implement a kind of trim. Obviously easy to install into an existing system, much more easy than a cable + tab.

>  the effect is within the rudder control system - i.e., applying a force to the standard rudder control, not by the mechanic's tab

Yes for applying a force to the rudder control system (upstream), but it can (may) be complementary to a pre-set on the ground of a mechanic's tab.
In fact, I don't know. My first idea was to match the neutral position with the center mark in the cockpit, but as the bungee is a very inaccurate (not very mechanical) system, I don't know...

**Comment by legoboyvdlp** [comment]
Ah, ok.

I think the best way to simulate this is to <sum> the rudder input and rudder trim input (plus the adjustable tab's input)? That should be sufficient.

**Comment by legoboyvdlp** [comment]
As for the lever, the real cockpit control is this:
![image](https://user-images.githubusercontent.com/10434911/47167961-96967d00-d2f7-11e8-8e42-c131d5b91223.png)

(I don't personally see any detents. I think the lever can take any position between min and max.)

**Comment by dany93** [comment]
> I think the best way to simulate this is to the rudder input and rudder trim input (plus the adjustable tab's input)?

I would say, yes.
Sum of these three components (clipped to +/-1  :wink: ). Like the current trim is.

**Comment by wlbragg** [comment]
OK, I set 100 steps 50+ and 50- on the control knob. So the table will look like this...

-6.8    50*x
...
0.0     0.00
...
 6.8    -50*x

And we are going with what I already created for the interior rudder trim model. It actually fits well with the elevator style as the round ball on the end ascetically matches the elevator knobbies.

**Comment by dany93** [comment]
Rather than a 101 step table, wouldn't it be easier to use a `property-adjust` command and steps?

**Comment by wlbragg** [comment]
I'm not sure I  am following you. Here is the knob animation I used and it works well for the operator. You can drag or hold the mouse down (left or center button).
~~~
<animation>
        <type>knob</type>
        <object-name>RudderTrimKnob</object-name>
        <property>controls/flight/rudder-trim-knob</property>
        <factor>1</factor>
        <drag-direction>horizontal</drag-direction>
        <offset-deg>0</offset-deg>
        <center>
            <x-m>-0.521  </x-m>
            <y-m> 0.00061</y-m>
            <z-m>-0.56081</z-m>
        </center>
        <axis>
            <x>0</x>
            <y>0</y>
            <z>1</z>
        </axis>
        <action>
            <binding>
                <command>property-adjust</command>
                <property>controls/flight/rudder-trim-knob</property>
                <factor>0.136</factor>
                <min>-6.8</min>
                <max>6.8</max>
                <wrap>false</wrap>
            </binding>
        </action>
        <hovered>
            <binding>
                <command>set-tooltip</command>
                <label>Rudder trim: %3.2f</label>
                <tooltip-id>rudder-trim</tooltip-id>
                <property>controls/flight/rudder-trim-knob</property>
            </binding>
        </hovered>
    </animation>
~~~

**Comment by wlbragg** [comment]
Note: the hovered is not going to be correct, i think I will need to use the sum of your FDM total that you will be using for the rudder trim.

**Comment by wlbragg** [comment]
You can interpolate it, yes?

**Comment by wlbragg** [comment]
@legoboyvdlp  the short answer is no, I don't expect you to do a 100 entry table. I wasn't even thinking about that being a possibility.

**Comment by dany93** [comment]
> i think I will need to use the sum of your FDM total that you will be using for the rudder trim.

Yes. This adds a term to the already existing rudder trim, to give the final rudder trim value.

> I'm not sure I am following you

What you show is the animation. The rudder-trim-knob **position**.
I think that's compatible, maybe the same as I suggested:
The added cockpit **trim** term would be proportional to the rudder-trim-knob **position**, by  a `<command>property-adjust</command>` and not a 101 step table.
And yes, you can see it as an interpolation.

I guess that it can also be set by mouse clicking? (+/- 0.001 steps).

**Comment by wlbragg** [comment]
Oops, didn't look at the post name, sorry Dany, I thought that was Lego.
OK, let me look at the
~~~
<command>property-adjust</command>command>property-adjust</command>
~~~
Off the top of my head I don't know how it fits the knob animation.

**Comment by wlbragg** [comment]
@dany93 can you use an interpolation "table" in an FDM function?

**Comment by legoboyvdlp** [comment]
Is 6.8 degrees the actual angle of the lever? Where does this figure come from?

**Comment by wlbragg** [comment]
Yes, it is the rotation of the lever to both extremes.

**Comment by wlbragg** [comment]
This is what I had in mind
~~~
<fcs_function name="ruddertrim2 trem">
    <function>
        <sum>
            <input>controls/flight/rudder-trim</input>
            <table>
                <independentVar lookup="row">controls/flight/rudder-trim-knob</independentVar>
                <tableData>
                    -6.8   -0.05
                     0      0
                     6.8    0.05
                </tableData>
            </table>
        </sum>
    </function>
</fcs_function>
~~~

**Comment by wlbragg** [comment]
I may be using the wrong rudder-trim property as your example suggests.

**Comment by dany93** [comment]
Currently, the `controls/flight/rudder-trim` is the one which is preset at 0.02 in the -set.xml file (line 585).
That is, the 'mechanics' tab, set on the ground.

**Comment by wlbragg** [comment]
OK, so my example above should work correctly?

**Comment by wlbragg** [comment]
The feel of the rudder trim knob is pretty good at 100 steps. It could potentially be reduced some if others think it is not sensitive enough. Dragging could be a little better and also the mouse up/down or mouse scroll could be slightly faster.
If we can do the conversion from rudder-trim-knob 6.8 to rudder-trim value in the FDM like the examples, then we can tune the knob animation however we want. I

**Comment by wlbragg** [comment]
After further testing of the animation, I wouldn't go lower than 50 steps. It a little faster to the limits yet the steps are still not too noticeable. But 100 is smoother and I think matched the elevator trim feel the best.

**Comment by wlbragg** [comment]
Hum, controls/flight/rudder-trim is not used anywhere in our FDM. Is it a tied property directly to FG source?

**Comment by wlbragg** [comment]
:fearful: That was not my intention, more out of curiosity than anything. No, nothing is committed yet. I've been trying to put it all together in the FDM unsuccessfully. I'm sure you will be able to figure it out though
I did notice though that it looks like the property controls/flight/rudder-trim is being calculated in the FG source, rolled into
~~~
<aerosurface_scale name="Rudder Control">
                <input>fcs/yaw-trim-sum</input>
                <gain>0.01745</gain>
                <range>
                    <min>-16</min>
                    <max>16</max>
                </range>
                <output>fcs/rudder-pos-rad</output>
            </aerosurface_scale>
~~~
So somehow you have tie only the new table date into this function. I think controls/flight/rudder-trim is already included and thus does not need to be added into the new function.

**Comment by legoboyvdlp** [comment]
Thanks for the help :smiley:

Should I do this on the frost-and-fog branch? It's not... really to do with frost and fog, but I understand working across branches in Blender is definitely not desirable.

**Comment by dany93** [comment]
Observe
 (variation with rudder-trim between -1 and +1, rather 0.2 to 0.5,
 and rudder setting):
```
controls/...
flight/rudder-trim,
fdm/jsbsim/fcs/...
yaw-trim-cmd-norm
yaw-trim-sum
rudder-control
rudder-pos-deg
rudder-pos-rad
rudder-position-normalized
```
What I think is to be done: (c172p.xml, lines 813...)
Guessed per observation, not tested.
```
            <summer name="Yaw Trim Sum">
                <input>fcs/rudder-cmd-norm-filtered</input>
                <input>fcs/yaw-trim-cmd-norm</input>
                <input>fcs/yaw-trim-cockpit</input>
                <clipto>
                    <min>-1</min>
                    <max>1</max>
                </clipto>
            </summer>
```
`fcs/yaw-trim-cmd-norm` is equal to controls/flight/rudder-trim, (mechanics stab)
`fcs/yaw-trim-cockpit` is your cockpit setting contribution.

**Comment by wlbragg** [comment]
Unrelated issue. I think we have a problem with the autopilot. My elevator trim starts slowly changing  from its initial setting to .23 as soon as I turn on the autopilot.

**Comment by dany93** [comment]
Are you sure that it is a problem?
The autopilot uses the rudder trim (and the rudder value) to hold the altitude.
0.23 is the approximate value for the rudder trim at cruise (about 115 - 120 kt).
Try another velocity (lower velocity) and see.

**Comment by wlbragg** [comment]
OK, maybe not a problem then. I wasn't sure how it worked. Can you use only heading ctrl and no altitude control? It seems even if I have "Alt" off VS is displayed and the trim dial still moves to add trim.

**Comment by legoboyvdlp** [comment]
I think the KAP140 holds VS anytime the autopilot is on and no other alt mode is selected?

**Comment by wlbragg** [comment]
OK, thanks!

**Comment by legoboyvdlp** [comment]
To confirm, how much should the knob adjust the trim?

+- 0.005 either way?

(0.015 - 0.025)?

**Comment by wlbragg** [comment]
@legoboyvdlp I basically have this entire issue finished locally. You want me to go ahead and make a branch and PR for it?
Then all you have to do is test, test, and test some more?

**Comment by legoboyvdlp** [comment]
Sure, that's fine :smiley:

**Comment by dany93** [comment]
Why not as long as you don't change it ? (or I've not understand well?)

**Comment by wlbragg** [comment]
Two things...
1) If you select not to use the rudder trim option in the GUI then the mechanics rudder-trim should be set to back to the default of 0.02 and the combined summer for rudder trim should be set to the default without the trim option, as well as the fcs/yaw-trim-cockpit property needs to be set to 0. I forgot to take care of this.
2) If you use rudder trim option then whatever setting you have it set to when exiting the sim should either be persistent or not?

**Comment by wlbragg** [comment]
Note to myself: the rudder trim hover tool tip is currently not updating on the fly, see method employed by elevator trim as it is working correctly.

**Comment by wlbragg** [comment]
I'm not at home right now so I can't really respond reliably right now. I think what your asking for is fine as I originally was going to use the original textures.

**Comment by gilbertohasnofb** [comment]
@wlbragg Great, let me know and I can push the texture for you.

**Comment by wlbragg** [comment]
@gilbertohasnofb go ahead and push those textures when you have the time.

**Comment by wlbragg** [comment]
@gilbertohasnofb I don't think that is going to work. For one, the label and the background is one object, it is all called RudderTrimBase. I tried to use that portion of that texture and the resolution was really bad for some reason.

**Comment by wlbragg** [comment]
@gilbertohasnofb I don't know that we will be happy with the resolution of the base background?

![trim](https://user-images.githubusercontent.com/11069680/47392119-421d4400-d6e1-11e8-8ceb-88b0f5ca5625.jpg)

**Comment by wlbragg** [comment]
This is basically doing what you asked. I mapped the background to that area above the elevator trim.

**Comment by gilbertohasnofb** [comment]
Once you mapped it and you are satisfied, I will sync the textures and colour the leather bit accordingly.

**Comment by wlbragg** [comment]
Arg, this is being difficult. How about this, can you make the label fit like this?

![uv-rudder-trim](https://user-images.githubusercontent.com/11069680/47404452-faafab80-d712-11e8-9c82-2282cde2906c.png)
![uv-rudder-trim1](https://user-images.githubusercontent.com/11069680/47404458-fedbc900-d712-11e8-84cf-f3bc982ffca9.png)

**Comment by gilbertohasnofb** [comment]
> Arg, this is being difficult. How about this, can you make the label fit like this?

I think we are nearly there, just one more iteration and we will get this done. I think I can squeeze the texture where you recommend it, let me give it a try and push a new version.
