### ISSUE TITLE
Magnetos switch: improve knob animation

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1226]
Use knob animation to allow manipulation of the starter with the mouse. I suggest:

Clicking the switch in BOTH should move it to start, releasing it back to both. Right clicking should move it anticlockwise to RIGHT. 

Clicking the switch in off, left, or right should move it clockwise, right click anticlockwise.

The scroll wheel up / down should move it as well - but it should only move it between BOTH, LEFT, RIGHT, AND OFF.

This can be accomplished with the knob animation's <release> and separate animations for when it is in Both / start and when it is in left / right / off, using condition elements.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp thanks for adding the issue and tackling it too! As for labelling issues, we normally add either a `bug` or `enhancement` label whenever appropriate. Sometimes neither will be appropriate but 99% of the time one of them is :smile:

**Comment by onox** [comment]
What's the precise change to the switch? Doesn't it already use a knob + pick animation? See https://github.com/c172p-team/c172p/blob/master/Models/Interior/Panel/Instruments/magneto-switch/magneto-switch.xml

**Comment by gilbertohasnofb** [comment]
> What's the precise change to the switch? 

Right now, only the `s` key will move the magneto key from BOTH to START position, as it needs to be held for a short while before the engine starts. I believe what @legoboyvdlp proposes is to allow the user to use the left mouse click to also move from that position, so that holding the LMB when the key is at BOTH position would move it to START and thus start the engine.

**Comment by wlbragg** [comment]
Left mouse already works from both to start! it is just a very small click spot.

**Comment by legoboyvdlp** [comment]
What part specifically do you click for that @wlbragg?

**Comment by wlbragg** [comment]
Put the cursor over the "Start" text and nudge it in a widening circle until you find the sweet spot and the tool tip changes to "Starter".
