### ISSUE TITLE
Aiucraft state is not saved when quitting

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1228]
Aiucraft state is not saved when quitting by clicking on the X icon on the FlightGear window or when using Alt+F4. @it0uchpods wrote that there are actually some workarounds for this:

> 1st way: force aircraftdata save when setting changed
> 2nd way: write and load settings via XML (useful for multiple -set files)

Any opinions on this?

**Comment by it0uchpods** [comment]
If you want an example, see my Warrior. It's settings save in an XML, to share across variants, previous versions saved via a forced aircraftdata.

If you want me to put infos or directions on how to implement either, let me know.

Josh

**Comment by dany93** [comment]
I agree [with Thorsten](https://forum.flightgear.org/viewtopic.php?f=4&t=25157&sid=7f8290a9d48a930dcd47692c7e8f367f&p=337978#p337988)

> I suppose the general convention is that closing the Window is meant as a kill command [....] while 'quit' is a shutdown command...
[....]
Killing processes without need is a bad user habit

**Comment by gilbertohasnofb** [comment]
@it0uchpods I think you might have misunderstood what is our state saving feature. We are basically saving the position of every knob, button, lever, etc. so there is no dialog for that.

**Comment by it0uchpods** [comment]
I don't see the point of that, but yeah, then I don't see the solution for that.

**Comment by gilbertohasnofb** [comment]
> I don't see the point of that

You mean you don't see the point of saving the aircraft state? If so, the answer is realism. If you leave a switch at a certain position it will remain so next time you load the sim, just like in RL. It's a neat feature which is present in most (all?) study-level aircraft in other sims.

**Comment by it0uchpods** [comment]
> It's a neat feature which is present in most (all?) study-level aircraft in other sims.
I have yet to see this implemented in any study level sims, I've flown a lot of study level craft.

OK, I kind of get it, but not entirely.

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
An Airbus you would probably expect the other crew to leave it in a transit state or cold and dark if overnight.

A Cessna that you fly yourself, if you leave it this way it makes sense that it stays that way, nobody else touched it since you flew it?

**Comment by gilbertohasnofb** [comment]
Also, it makes sense that the frequencies do not keep resetting every time you take your Cessna for a flight, or your preference of radio volume, use of headphones/external mic/mute, etc. Same for heading in your OBS, altimeter settings, etc.

**Comment by wlbragg** [comment]
This stuff will go hand in hand with the up coming state work. I propose the aircraft state will always be saved regardless of any setting (thus no need for a setting in the GUI). The key is the choice at startup. There will be a "Last State" which will be where you left off and then any other states we want to include or make available. This will require us controlling the cache to the extent that we get to choose what persistent data gets loaded, not whatever is persistent gets loaded. The original saved data (aircraft data, archived data, etc., "persistent data") will change to be data that needs to be persistent and loaded every time. Data that needs to be a choice to load will need to be explicitly stored by us using a different system where we choose when it gets loaded, or more importantly when it sets properties.
