### ISSUE TITLE
Nose wheel steering moves when testing rudder

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1235]
When you press the rudder to test it, the nose wheel steering also moves. Is this an issue, or would it also do this in real life?

**Comment by dany93** [comment]
As every part of this system (rudder pedals included, of course) is connected by cables, rods, rigid levers, I would say that it is normal.
The nose wheel is disconnected only in flight (with no weight on it).

**Comment by dany93** [comment]
IRL and from my experience (Ultralights) you cannot really rotate the rudder more than a very small angle (mainly cable play) because the nose wheel, on the ground with weight, is hard to rotate.
Very differently from the elevator and ailerons.
