### ISSUE TITLE
AI knob rotates infinitely

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1237]
AI knob rotates infinitely (in both directions)

![image](https://user-images.githubusercontent.com/5700795/48349493-515a3680-e67c-11e8-8554-0437bf89ea67.png)
![image](https://user-images.githubusercontent.com/5700795/48349499-54552700-e67c-11e8-966f-26d322c21d94.png)
![image](https://user-images.githubusercontent.com/5700795/48349503-56b78100-e67c-11e8-9037-7386d03c2d29.png)
![image](https://user-images.githubusercontent.com/5700795/48349505-58814480-e67c-11e8-88e2-cef00185448c.png)
![image](https://user-images.githubusercontent.com/5700795/48349511-5a4b0800-e67c-11e8-8aba-271bb47d5887.png)
![image](https://user-images.githubusercontent.com/5700795/48349515-5c14cb80-e67c-11e8-8941-422169a97b17.png)

**Comment by wlbragg** [comment]
Anyone know what the limit is supposed to be?

**Comment by gilbertohasnofb** [comment]
From wikipedia:

> An adjustment knob, to account for the pilot's line of vision, moves the aircraft up and down to align it against the horizon bar.

From this, I would imagine that the offset will not be very large. I would suggest starting the engine so that the AI is centred and then moving the viewpoint up and down and checking what values of offset we need to compensate for those. Perhaps +10 to -10 would be enough.

**Comment by wlbragg** [comment]
Right, perhaps a little bit past the seat adjustment limits if that is enough.

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/48574934-71058f00-e908-11e8-914b-698efdbfd032.png)

I think when the panel was moved up the AI face was not moved (or the animation wasn't?)

This is with horizon offest zero: the AI needs to be offset -2 units to show correctly:
![image](https://user-images.githubusercontent.com/10434911/48574992-95616b80-e908-11e8-8d2a-57ec1b424599.png)

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp nice catches. @wlbragg could you adjust these things in the model? The AI default offset (i.e. `0`) should be at the correct position for the default view.

**Comment by wkitty42** [comment]
On 11/15/18 2:36 PM, Gilberto Agostinho wrote:
> @legoboyvdlp nice catches. @wlbragg could you adjust these things in the
> model? The AI default offset (i.e. |0|) should be at the correct position for
> the default view.

this may not be involved but what happens when you move your seat via the new 
multi-position seat stuff? the AI will be off a little bit depending on your eye 
view... that is expected... just tossing this in to make sure nothing has been 
overlooked ;)

**Comment by wlbragg** [comment]
I'll work on it tomorrow.

**Comment by legoboyvdlp** [comment]
> this may not be involved but what happens when you move your seat via the new
multi-position seat stuff? the AI will be off a little bit depending on your eye
view... that is expected... just tossing this in to make sure nothing has been
overlooked ;)

I didn't touch my seat in that screenshot, so that's not the issue.

**Comment by gilbertohasnofb** [comment]
@wlbragg we could try setting an arbitrary limit and close this. From the initial screenshots, I think that anything between minus 15-20 would suffice. I cannot imagine this part moves more than this in RL. What do you think?

**Comment by wlbragg** [comment]
@gilbertohasnofb OK, yeah, I may have dropped the ball on this. Can you take a look at the code?

**Comment by gilbertohasnofb** [comment]
Sure, I will see if I can fix this.
