### ISSUE TITLE
JSBSIM Tag errors (2018.4)

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1241]
2018.4 now has more strict checking of JSBSIM tags. The aircraft still starts fine but with these console errors:

> In file C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c172p/Systems/c172p-hydrodynamics.xml: line 585
<sum> only has one argument which makes it a no-op.
Its argument will be evaluated but <sum> will not be applied to the result.

> In file C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c172p/Systems/c172p-heat.xml: line 351
<sum> only has one argument which makes it a no-op.
Its argument will be evaluated but <sum> will not be applied to the result.

> In file C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c172p/c172p.xml: line 1121
<product> only has one argument which makes it a no-op.
Its argument will be evaluated but <product> will not be applied to the result.

> In file C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c172p/c172p.xml: line 1145
<product> only has one argument which makes it a no-op.
Its argument will be evaluated but <product> will not be applied to the result.

**Comment by wlbragg** [comment]
Thanks for looking at this @legoboyvdlp I've been wanting to do this but haven't updated yet. I'll take a look at the sections and see what's up.

**Comment by wlbragg** [comment]
@andgi would you please look at this one. I assume you didn't want the "SUM" tags but not knowing for sure, you should be the one to look at this. Also I'm sure you would want to know about this for the rest of the code your responsible for in you other aircraft.

**Comment by wlbragg** [comment]
@onox same thing, I assume you don't need the sum here or you left something out?
~~~
        <fcs_function name="heat/future-cabin-rel-humidity">
            <function>
                <sum>
                    <quotient>
                        <sum>
                            <product>
                                <property>heat/non-humans-airflow</property>
                                <property>/environment/relative-humidity</property>
                            </product>
                            <product>
                                <property>heat/humans-airflow</property>
                                <!-- Human breath: 35 C with 95 % RH -->
                                <value>95.0</value>
                            </product>
                        </sum>
                        <sum>
                            <property>heat/non-humans-airflow</property>
                            <property>heat/humans-airflow</property>
                        </sum>
                    </quotient>
                </sum>
            </function>
        </fcs_function>
~~~

**Comment by wlbragg** [comment]
@dany93 last two, same thing here in the FDM, I don't know if there is a missing parameter or if it pulls directly from the table (if that is possible syntax wise?
~~~
        <function name="aero/function/kCDge">
            <description>Change_in_drag_due_to_ground_effect</description>
            <product>
                <table>
                    <independentVar>aero/h_b-mac-ft</independentVar>
                    <tableData>
                          0.0000    0.4800
                          0.1000    0.5150
                          0.1500    0.6290
                          0.2000    0.7090
                          0.3000    0.8150
                          0.4000    0.8820
                          0.5000    0.9280
                          0.6000    0.9620
                          0.7000    0.9880
                          0.8000    1.0000
                          0.9000    1.0000
                          1.0000    1.0000
                          1.1000    1.0000
                      </tableData>
                </table>
            </product>
        </function>

        <function name="aero/function/kCLge">
            <description>Change_in_lift_due_to_ground_effect</description>
            <product>
                <table>
                    <independentVar>aero/h_b-mac-ft</independentVar>
                    <tableData>
                          0.0000    1.2030
                          0.1000    1.1270
                          0.1500    1.0900
                          0.2000    1.0730
                          0.3000    1.0460
                          0.4000    1.0280
                          0.5000    1.0190
                          0.6000    1.0130
                          0.7000    1.0080
                          0.8000    1.0060
                          0.9000    1.0030
                          1.0000    1.0020
                          1.1000    1.0000
                      </tableData>
                </table>
            </product>
        </function>
~~~

**Comment by wlbragg** [comment]
@andgi are you saying that all three values are supposed to be multiplied together?
Why the 
~~~
<value>1.0</value>
~~~ 
here?

**Comment by andgi** [comment]
On Wed, 28 Nov 2018, wlbragg wrote:

> 
> @andgi are you saying that all three values are supposed to be multiplied
> together?
> Why the
> 
> <value>1.0</value>
> 
> here?

Yes, all three values inside the product-element are multiplied together.
Why the 1.0 is there can be questioned but, OTOH, it might be a place to 
adjust the coefficient up or down, though it, at the moment, doesn't do 
anything.

Cheers,
Anders
-- 
Anders Gidenstam
Email: anders(at)gidenstam.org
WWW: http://www.gidenstam.org

**Comment by dany93** [comment]
@wlbragg wrote
>  last two, same thing here in the FDM
```
        <function name="aero/function/kCDge">
        <function name="aero/function/kCLge">
```
At quick test, it seems that deleting the four `<product> ... </product>` tags is the thing to do, it works as well.
(I don't have 2018-4 yet, I don't see the error lines in the console)

It is a true mistake, these `<product>` tags make no sense. They might be useful in a development context, with a (common) test factor added.The worst is that it has been copied and pasted like this on several aircraft FDMs.

**Comment by wlbragg** [comment]
OK, thanks @andgi and @dany93 I'll fix those in a new PR. @andgi I think I am going to remove the 1.0 line as it servers no purpose and is confusing without a comment for its purpose as possibly a testing or tuning feature.

**Comment by onox** [comment]
@wlbragg You can remove the `<sum>` in the code block you mentioned.
