### ISSUE TITLE
Too much turn-to-the left tendency at takeoff and climbing.

### ISSUE THREAD

**Issue by dany93** [c172p-team/c172p#1260]
This issue is connected to this one by @legoboyvdlp  and @it0uchpods . https://github.com/c172p-team/c172p/pull/1256#issue-253643544
I hope they can join it.
I have preferred opening a new issue starting back from the master version. This will avoid polluting the git history with features like reversing the proposed wrong roll-moment-due-to-rudder code and less important ones that are still to be discussed.
Also, I would prefer that we change not too many things at a time, that we work more analytically.

We have a newcomer in the french forum, newcomer in FG. He also noticed that the aircraft is pulling too much to the left, which confirms @legoboyvdlp  and @it0uchpods opinions. I invited him to join us in this discussion because he has a 20 years experience in C172 piloting, which means that his feedback should be valuable. All the more that @tigert and @algefaen no longer respond. He still has to discover FG a bit and he is waiting for rudder pedals to be delivered.

~I will prepare a pull request as a starting point.~
Done PR #1261 (change P-factor from 60 to 15).

:warning: :warning: :warning: DO NOT MERGE YET! :warning: :warning: :warning:

**Comment by it0uchpods** [comment]
Works for me.

I tested my theory with yaw_beta, and found that to have enough to counteract the roll, would make the craft unstable in roll manuevers. So the solution would more advanced modelling.

**Comment by dany93** [comment]
I also had this impression by doing this same test.

**Comment by it0uchpods** [comment]
I am glad we are on the same page.
I'll let you know if I find anything.

**Comment by dany93** [comment]
Done PR #1261 (change P-factor from 60 to 15).

If possible, suggestions please:
- change one parameter at a time,
- preferably selectively test its effect by canceling another that can have a similar effect (e.g. P-Factor values with spiral-propwash = 0).
- check the rudder deflection needed with both at 0 or very close to 0.

**Comment by dany93** [comment]
With P-factor = 15,
180 hp
I climb at (slip-ball centered):
60 kt with rudder = 0.15 (pilot alone), 0.09 (with co-pilot),
70 kt with rudder = 0.11 (pilot alone), 0.06 (with co-pilot).

**Comment by algefaen** [comment]
The subjective feeling of having to apply to apply _a lot_ of right rudder in slow-speed climbs might be related to the forces involved rather than the actual rudder pedal movement, with slipstream etc. pushing back through the pedals. It's hard to say, I wish I had more concrete evidence.

For those who are testing this, remember to make sure that rudder and aileron trim are set to the default values. It's probably something that many of us has tweaked but might have forgotten about.
