### ISSUE TITLE
Taxing tutorial has bug around cowl plug removal

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1263]
See: https://forum.flightgear.org/viewtopic.php?f=25&t=35473

What I discovered so far is that if the cowl plug is in place, on every other tutorial start it won't be removed and the tutorial fails.
It appeared to not matter whether or not the rest of the items were checked or not, and it was only every other time you tried to run the tutorial with the cowl plugs in place.

**Comment by gilbertohasnofb** [comment]
hmm, this is a weird one. I will try to reproduce it soon.

**Comment by gilbertohasnofb** [comment]
@wlbragg do you have any suspicion of what might be causing this?

**Comment by wlbragg** [comment]
No, that is as far as I got. I'd have to start from that bit of knowledge and just keep running it and observing properties I guess.
