### ISSUE TITLE
Gather a list of features and bugs we fixed in 2020.1

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1273]
We should gather a list of all the new features, major changes, and bugs we fixed. Please create a list (use \* to create bullet points) here.

**Features:**

* new sounds for rolling and tire screeching on both paves and gravel surfaces
* replaced the KX165 with the KX165A radio which supports 8.33 frequencies
* new mooring locations
* `f` shortcut now toggles flashlight

**Fixes:**

* fixed xy-plane and missing texture error messages
* corrected a segfault caused when you lower and then raise the amphibious gear on land
* turn coordinator gyros breaker was not hooked up
* fix amphibious gear control breaker logic
* amphibious gear switch now does not triger repair timer while pontoon damaged
* initialization of new traversing property which is may prevent issues on some systems
* fix strong pitch oscillations at rest with brakes on and with pure crosswind
* fix Nasal error due to a typo in avionics.nas
* changing xml version to 1.0 in xml file headers as this is the supported version
* radio tutorial now requires the user to turn on the battery and avionics switches
* fixed minor spelling mistake in preflight tutorial

Do not forget to update `NEWS.md` before creating the release. See https://github.com/c172p-team/c172p-detailed/wiki/Release-process-and-versioning

**Comment by gilbertohasnofb** [comment]
I've updated the title to 2020.1 since it's been ages since we last had a release!

**Comment by gilbertohasnofb** [comment]
@wlbragg @legoboyvdlp @dany93 @wkitty42 @Juanvvc I've seen some emails about a new release in the mailing list, does anyone know when this is going to happen? I've been swamped by emails lately and I have not been reading them very closely. But if there are plans for a new release we should ask for a merge into FGData right?

**Comment by legoboyvdlp** [comment]
> So this will be 2018.3.5.

As ever, if there’s other bug-fixes on the branches (I’ve seen at least one for JSBsim already included), **or anything else (eg the C172P),** they can still go into 2018.3.6 or whatever - now the infrastructure is running again, making builds is not hard. (If there’s a fix ready to go, I there is also time to get it into 2018.3.5, in principle, but I’m planning to press the button really quite soon)



Emphasis mine, any fixes ready to go can go ahead for the next version (but needs to be done pretty much in the next day or so)

**Comment by dany93** [comment]
@gilbertohasnofb 
Yes. James is planning to do an updated "stable" LTS release 2018.3.5.

[This thread.](https://sourceforge.net/p/flightgear/mailman/flightgear-devel/?viewmonth=202003&viewday=22). [Flightgear-devel] Releases, see the **first message by James , 2020-03-22 11:36:03**
**James turner** wrote (excerpts)
> I'm going to be making an updated LTS release soon
> So this will be 2018.3.5.
> As ever, if there’s other bug-fixes on the branches (I’ve seen at least one for JSBsim already included), or anything else (eg the C172P), they can still go into 2018.3.6 or whatever
> Later, an unstable release 2020.1
> (If there’s a fix ready to go, I there is also time to get it into 2018.3.5, in principle, but I’m planning to press the button really quite soon)
> Next, I propose to make an unstable release, partly to end the 2019.1 / 2019.2 confusion. So this would be 2020.1
> I am deliberately /not/ setting a date to make the LTS release, though ‘before FSWeekend’ would make sense [1], i.e approximately two years after 2018.3

**Comment by gilbertohasnofb** [comment]
Ok, are there any last minute fixes we need to do? And can you guys help me out filling the list of features and bugs we fixed?

Finally, why is this new version of the stable release called 2018.3.5??

**Comment by dany93** [comment]
I think this is because 2019.1.1, which still is the official release in "Download Central", had bugs, and 2019.2 was only in SourceForge. To get rid of this confusion, but I don't know why 2019.2 could not be the stable release.

**Comment by gilbertohasnofb** [comment]
Thanks for the info, Dany. I still find it super messy but that's possibly just me :smile: 

As for our release, can I go ahead and prepare it? Does anyone still need to finish anything? If so, let me know asap so that we can get this merged into FGDATA.

**Comment by wkitty42** [comment]
i cannot think of anything that's stopping us... if all the recent work is complete, i'd say let's get it in...

**Comment by gilbertohasnofb** [comment]
Version 2020.1 has been released, writing @stuartbuchanan now. Thanks all for the contributions!

**Comment by legoboyvdlp** [comment]
Great :)

**Comment by wlbragg** [comment]
Thanks guys, I've been mostly unavailable as of late!

**Comment by gilbertohasnofb** [comment]
No worries, @wlbragg. I hope you are all healthy and safe in these scary times.
