### ISSUE TITLE
Nasal error in tiedowns

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1274]
@wlbragg @gilbertohasnofb 

`Nasal runtime error: No such member: end_point
  139.56 [ALRT]:nasal        at C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c172p/Nasal/tiedowns.nas, line 112
  139.56 [ALRT]:nasal        called from: C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c172p/Nasal/tiedowns.nas, line 93
  139.57 [ALRT]:nasal        called from: C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c172p/Nasal/tiedowns.nas, line 142
  139.57 [ALRT]:nasal        called from: C:/Users/redpa/Documents/Programs/FlightGear 2018.3.0/data/Nasal/globals.nas,`

In tiedowns.nas, `me.end_point` has no default value.

**Comment by wlbragg** [comment]
@legoboyvdlp @gilbertohasnofb 
I am getting it as well. This was a nasal file that was changed in https://github.com/c172p-team/c172p/pull/1269/commits/a552abb7f526dd9622091c741977ad4ee49f3094
All I did was to remove four set listeners out of a setlistener for FDM-init. Putting it back fixed the error. So I guess we put it back. I verified the only code casing the segfaults was in the light-manager so it shouldn't be a problem.
