### ISSUE TITLE
Improve the KR87

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1279]
@ pfefferCode reported these potential bugs in the adf radio KR 87:

1. The rotating knobs seem to rotate the anticlockwise (wrong direction), clicking on it.

2. ~The standby frequency is not displayed after a click on "FRQ"-Button (always 200 is shown).~ user says issue disappeared

3. If on the right display the time is shown, the knob should directly change the active frequency, see: <https://www.bendixking.com/en/~/media/bendixking/files/006-18110-0000_5-kr-87-pilot-guide.pdf> page 44: "While FLT or ET is displayed the “in use” frequency on the left side of the window may be changed, by using the frequency select knobs, without any effect on the stored standby frequency or the other modes. This feature is especially useful when searching for stations with unknown frequencies."

4. If on the right display the standby freq is shown, it does not change, when clicking on the knob. Nevertheless, the standby freq is changed as a click on the "FREQ"-Buttons transfers it (the chnged freq) to the active freq.

5. ~I could not start the clock, it always shows "2:00". Should that already work?~ user says issue disappeared

6. Long pressing the "SET/RST"-Button should change to count-down mode (see page 43 in https://www.bendixking.com/en/~/media/bendixking/files/006-18110-0000_5-kr-87-pilot-guide.pdf ). Is that implemented?

7. Turning the inner knob should not overflow to the hundrets of kHz, see:

> With “FRQ” annunciated, the standby frequency is selected using the frequency select knobs which may be rotated either clockwise or counterclockwise. Pull the small inner knob out to tune 1’s. Push the smaller inner knob in to tune 10’s. The outer knob tunes the 100’s and the 1000’s up to 1799<
    Source: Pilot's Guide on KR 87, p. 42.

8. Improve the 3D model and texturing and confirm that the functionality matches the real KR87

**Comment by gilbertohasnofb** [comment]
As reported in the dev-list. I did not have the time to try to reproduce it yet.

**Comment by pfefferCode** [comment]
I retried, and can only reproduce some:
2. und 5. seems to be ok now. I do not know, how I ran into these problems. 
 
But I have another one in the ADF panel:
6. Long pressing the "SET/RST"-Button should change to count-down mode (see page 43 in https://www.bendixking.com/en/~/media/bendixking/files/006-18110-0000_5-kr-87-pilot-guide.pdf ). Is that implemented?

**Comment by pfefferCode** [comment]
and another one:
Turning the inner knob should not overflow to the hundrets of kHz, see: 
>With “FRQ” annunciated, the standby frequency is selected using the frequency select knobs which may be rotated either clockwise or counterclockwise. Pull the small inner knob out to tune 1’s. Push the smaller inner knob in to tune 10’s. The outer knob tunes the 100’s and the 1000’s up to 1799<
Source: Pilot's Guide on KR 87, p. 42.

**Comment by gilbertohasnofb** [comment]
@pfefferCode Thanks. I still did not have the time to check these. Perhaps @legoboyvdlp or @wlbragg would be interested in taking a look as well. I have updated the first post as to include the new bugs you found as well as cross the ones you can't reproduce any longer.

**Comment by legoboyvdlp** [comment]
Right - there are two variants here. I need a bit of help - 

![image](https://user-images.githubusercontent.com/10434911/59445339-64420e80-8df7-11e9-92cf-4bc8d241421a.png)

or 
![image](https://user-images.githubusercontent.com/10434911/59445370-72902a80-8df7-11e9-9966-b2fb1aa2b3c8.png)

We have the second one. I am not sure, I think the top one is the "Silver Crown Plus"?

Anyone any idea what the differences are?

**Comment by gilbertohasnofb** [comment]
Visually, the differences are minimal:

![image](https://user-images.githubusercontent.com/5700795/59448415-fe588580-8dfc-11e9-99cf-6d93865c98f0.png)

From the point of view of operation, I can't find any information about the differences. From what I gather, they are absolutely the same. Bendix apparently released a 'silver crown' line for all their radios. I would not bother too much with that.

**Comment by legoboyvdlp** [comment]
Ok - one is the plus, one isn't. I'll try and find the differences of the plus... Thanks!

I asked Josh but his pipers have an ancient ADF... even older than this with a mechanical display!
