### ISSUE TITLE
Engine quitting at idle

### ISSUE THREAD

**Issue by D-ECHO** [c172p-team/c172p#1303]
I'm not entirely sure about this one as I have never flown a 172 IRL, but I think the engine should not just quit when reducing the throttle to idle?

**Comment by dany93** [comment]
I don't understand....
It does not, the engine does not stop  when reducing the throttle to idle???

Did you check the mixture?

**Comment by D-ECHO** [comment]
mixture full, not in a 0g state vor similar...



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: dany93
Betreff: Re: [c172p-team/c172p] Engine quitting at idle (#1303)
Datum: 04.11.2019, 18:56 Uhr
An: c172p-team/c172p
Cc: D-ECHO, Author



I don't understand....
It does not, the engine does not stop when reducing the throttle to idle???

Did you check the mixture?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/c172p-team/c172p/issues/1303?email_source=notifications&email_token=ANTLS244PGIR4ER6GXQNKCTQSBO57A5CNFSM4JIWTPCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDAES4Q#issuecomment-549472626> 
, or unsubscribe

**Comment by gilbertohasnofb** [comment]
@D-ECHO could you try to explain better to us how to reproduce this? What was the weather? Also did you check if you have fuel contamination on?

**Comment by gilbertohasnofb** [comment]
Great! Happy to hear it was just that :smile:

**Comment by wlbragg** [comment]
Carb ice rears its ugly head. What too much realism? :smile:
