### ISSUE TITLE
Typo in avionics.nas

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1304]
I found a typo in avionics.nas line 166 (semicolon). I can't believe that nasal error has been there all this time and no one noticed.

I also noticed my local copy did not have it and is showing it as a "new" change, to add the semicolon over what I pulled from the repo (master,branch). Meaning it wasn't me that introduced it?

**Comment by gilbertohasnofb** [comment]
> Meaning it wasn't me that introduced it?

It doesn't matter who introduced now that we fixed it, but it seems the semicolon was introduced by this commit of yours: https://github.com/c172p-team/c172p/commit/1c8ff816d7c8a24a2c4fb77084a7f3c38771f42d

**Comment by wlbragg** [comment]
>It doesn't matter who introduced now that we fixed it,


I agree.

Thanks for tracking it down. I was really curious how I had a clean copy without the simicolon, yet master and release branch had it. I must have fixed it locally without realizing it was pushed to repo.

Thanks for merging. I'll backport and notify mailing list.

**Comment by gilbertohasnofb** [comment]
No worries, thanks for spotting the typo and fixing it!

**Comment by wlbragg** [comment]
@zakalawe this is finished and backported into https://github.com/c172p-team/c172p/tree/release/2019.1
Commit Id 300023cbde836286f2c5e3b5940680dabf095682

**Comment by zakalawe** [comment]
@wlbragg thanks, just merged this to the FGData 2019.1 branch.
