### ISSUE TITLE
Compositor - disable shadow does not hide reflection model ?

### ISSUE THREAD

**Issue by slawekmikula** [c172p-team/c172p#1307]
When using new (experimental) compositor branch of the Flightgear project there is some issues with shadows. When using compositor the shadow is calculated differently. In this situation when aircraft have some shadow technique created there is an issue with this, because the shadow objects are opaque. Normally (e.g. cessna 182) it can be disabled by entering the aircraft options and select to disable shadows. In C172 disabling shadows still keeps something (reflections?) in the view. See pictures below. It would be good, when there is some kind of option to disable this or combine this with option to disable shadows. 

I know that, this is not issue for current stable version of FG, but it can be good for testing Compositor with the default aircraft.

![external](https://user-images.githubusercontent.com/157701/71312548-8e226080-242c-11ea-8f5e-2c08dc041493.png)

![internal](https://user-images.githubusercontent.com/157701/71312549-8e226080-242c-11ea-9500-bece100bc765.png)

**Comment by wlbragg** [comment]
@slawekmikula 
I'm  not sure what it is your seeing with the glass. I'll set up a compositor version of the c172p and see what I get and if I can figure out what is causing the issue. I assume the shadow your referring to is the exterior shadow which of course has nothing to do with the windows.

Are you getting the dark glass regardless of whether you disable the shadow or not?

If nothing else maybe I can start a new branch for a compositor version.
It may be after the holidays before I can get to it.

**Comment by wlbragg** [comment]
@slawekmikula
I fired it up in my compositor build and I think it's the normal map that is causing part of the exterior issue also the glass reflection. Notice the color of the wheels. I didn't have time to check the log for sure. The interior glass reflections could be the rest of the interior issues, as in the effect is not ported yet. Again, I didn't look at the logs yet. But for now, if you comment out all the exterior effects (lines 573 to 674) including the glass reflections (685 to 691) and all the glass interior effects (916 to 944), you get a reasonably decent looking rendering that will work until we can sort some of this stuff out.

**Comment by slawekmikula** [comment]
Thanks for commenting. Understood. It is not a showstopper for me, but I've reported it in any case. Maybe combining to disable this effects along with option to disable shadows or add another option would be the case. Anyway, it's only here for future reference.

Logs:
27.54 [ALRT]:input      can't find "Compositor/Effects/shadow-vol.eff"
29.89 [ALRT]:input      can't find "Compositor/Effects/exterior/dirt-fuselage.eff"
30.17 [ALRT]:input      can't find "Compositor/Effects/exterior/dirt-wing.eff"
30.21 [ALRT]:input      can't find "Compositor/Effects/exterior/bumpspec.eff"
30.24 [ALRT]:input      can't find "Compositor/Effects/exterior/exterior-glass-reflection.eff"
30.24 [ALRT]:input      can't find "Compositor/Effects/interior/c172p-interior-glass-front-sides.eff"
30.24 [ALRT]:input      can't find "Compositor/Effects/interior/c172p-interior-glass-reflection-front.eff"
30.24 [ALRT]:input      can't find "Compositor/Effects/interior/c172p-interior-glass-back.eff"
30.24 [ALRT]:input      can't find "Compositor/Effects/interior/c172p-interior-glass-back-sides.eff"
30.24 [ALRT]:input      can't find "Compositor/Effects/interior/interior-glass-reflection-panel-front.eff"

**Comment by wlbragg** [comment]
@slawekmikula 
I created a compositor test branch that we can use to start configuring the c172p to work with the compositor.
So far I made the following changes that gets us to a point we can at least fly the aircraft.
Full path to the aircraft folder to all the local effect definitions, ie;
any effect that starts with Effect/interior... or Effect/exterior... becomes
Aircraft/c172p/Models/Effect/interior...
or
Aircraft/c172p/Models/Effect/exterior...
That gives us most if not all the glass effects back as well as some other effects.

Also, for now,  I had to disable the normals map in the bumpspec.eff file
~~~
<normalmap-enabled type="int"> 1 </normalmap-enabled>
~~~
becomes
~~~
<normalmap-enabled type="int"> 0 </normalmap-enabled>
~~~

This actually takes care of almost everything except a few incidental shader issues such as spotlights, dirt and the ubershader. But the rendering actually looks pretty good with these simple changes.

See https://github.com/c172p-team/c172p/tree/Issue-1307

Compositor based shader and effect patches and porting will be greatly appreciated and can be posted here.

**Comment by wlbragg** [comment]
![c127p-comp](https://user-images.githubusercontent.com/11069680/71326618-e73cd380-24c2-11ea-9d87-371d85de613b.jpg)

**Comment by slawekmikula** [comment]
Thanks for this work. I'll check it on my HW (intel and nvidia 840M). As for shader/effects sorry, but this is beyond my paygrade (i'm working on other things in FG in free time). But maybe someone could take this issue as a starting point.

**Comment by slawekmikula** [comment]
So far so good :) Thanks. On my HW it works OK right now.

**Comment by wkitty42** [comment]
remember, too, that Compositor isn't complete and is missing some parts... there's some more updates in the pipeline that are waiting for one of the T's to review and set for merging... then there's some eff and frag supposedly in the pipe behind them once the updates are in...

i do remember something about craft specific effs and frags not being found right now... you can check with Icecode on discord for more details if needed...
