### ISSUE TITLE
Multiplayer: Immat/Registration not showing

### ISSUE THREAD

**Issue by hbeni** [c172p-team/c172p#1339]
I have spotted a problem in the c182s (see https://github.com/HHS81/c182s/issues/178#issuecomment-728837255) where the custom registration is not showing in multiplayer aircraft.

The bug seem to also appear at the c172p (reproduced on current master 121a280a111c8df3).
I ported the custom immat feature over from the 172 some time ago.

Left: Local Aircraft instance; right: remote instance viewed trough ORCAM (ATC aircraft) in a localhost LAN test.
(Note 1: that the text- texture behaves the same as the c182s: the immat _is_ shown somehow, but whats seeable is heavily distorted garbage; please see my linked comment above where this is visilby better. Its very faint here, watch the black dots right of the mouse pointer, thats the remaining bits of the immat-texture.
Note 2: also, this is not clipped by the fusealge, but a texture problem somehow)
![grafik](https://user-images.githubusercontent.com/13608602/99385100-c4808e00-28d0-11eb-9843-763f298833de.png)

**Comment by hbeni** [comment]
Probably already reported: https://sourceforge.net/p/flightgear/codetickets/2130/

**Comment by wlbragg** [comment]
Thanks for the report and info! I'll dig into it too, as soon as I get the time.

**Comment by hbeni** [comment]
For the C182S/T i ported the external registrration to use Canvas. This also gives some more control on the font, color and size of the registration writing:
https://github.com/HHS81/c182s/pull/351/commits/220fa82bfa266379ae62a9f6b86a182002848323

Basicly, i converted the .ac model to only have one plane for the registration, instead of a single for each letter.
Then a nasal creates a new texture and replaces the texture of those plane.
Replacing directly the livery texture didn't work (as was also found out at the hackatron).

Maybe this is also of use for the C172p.

**Comment by wlbragg** [comment]
Thanks @hbeni
We should do the same. I'll take a look at what you did, thanks.

**Comment by hbeni** [comment]
Added a PR that fixes this :)
