### ISSUE TITLE
Nasal error: Battery fail

### ISSUE THREAD

**Issue by HHS81** [c172p-team/c172p#1352]
with the current c172p and the nightly-builds, the engine won´t start, battery is at 0%. No loading possible.

Error message:

 `84.06 [ALRT]:nasal      Nasal runtime error: nil used in numeric context
   84.06 [ALRT]:nasal        at C:/Users/Heiko/FlightGearBuild/fgdata/data/Aircraft/c172p/Nasal/electrical.nas, line 49
   84.06 [ALRT]:nasal        called from: C:/Users/Heiko/FlightGearBuild/fgdata/data/Aircraft/c172p/Nasal/electrical.nas, line 90
   84.06 [ALRT]:nasal        called from: C:/Users/Heiko/FlightGearBuild/fgdata/data/Aircraft/c172p/Nasal/electrical.nas, line 167
   84.07 [ALRT]:nasal        called from: C:/Users/Heiko/FlightGearBuild/fgdata/data/Aircraft/c172p/Nasal/c172p.nas, line 13
   84.07 [ALRT]:nasal        called from: /sim/bindings/menu/binding[107], line 1`

**Comment by wlbragg** [comment]
@HHS81 
Can you give me anything more to go on, What steps you took to end up here? This is referring to being in or using replay?

**Comment by HHS81** [comment]
This happens when batterystate is empty = zero. 
Using autostart engine fails
Manual start fails
--> both with the error message above
Using the EPO doesn´t load the battery.

When deleting the saved aircraft parametres, battery is back to 100% and everythings works a s fine. 

Drain the battery until 0; save this and launch FGFS again- you should get the same error.

No using of replay.

**Comment by wlbragg** [comment]
OK thanks, if you get a chance could you post what your line 49 in Nasal/electrical.nas is?

**Comment by wlbragg** [comment]
Well that was rather strange, I was testing a separate user issue and exited the sim with bat power still available, restarted and I got the error above, so yeah, there is some kind of weird, new, behavior. So my line 49 should be the same as yours, thus I don't need it anymore.

**Comment by wlbragg** [comment]
@HHS81 and anyone else following this.
This is a nasty little bug that cropped up here and I really have no idea where it came from.
Here is what I discovered so far.
There are two different percent of battery charges being saved into the aircraft-data cache that appear to be causing this issue.

systems/electrical/battery-charge-percent
systems/electrical/battery-charge-percent/a

If both these entries are in the saved data cache then we get the nasal error and that is what is breaking the craft from that point forward. I don't think it has anything to do with a drained battery as it is doing this for me if I simply start the sim, turn bat on and exit the sim, then restart.

If I delete either entry from the cache then I don't get the error.
The line the error reports has nothing to do with the error so it is a false report, like some kind of scrambled data.
I can't locate the any code that refers to systems/electrical/battery-charge-percent/a anywhere in the code base.

This is what gets saved to the data cache that is causing the issue..
~~~
<systems>
    <electrical>
      <save-battery-charge type="bool">false</save-battery-charge>
      <battery-charge-percent n="0" type="double">0.9546761793</battery-charge-percent>
      <battery-charge-percent n="0">
        <a type="double">0.9955642608</a>
      </battery-charge-percent>
    </electrical>
  </systems>
~~~

This code in a gui and in a filter is suspect to me ...
~~~
            <group>
                <layout>hbox</layout>

                <!-- Small left padding -->
                <group>
                    <layout>vbox</layout>
                    <padding>6</padding>
                </group>

                <group>
                    <layout>vbox</layout>
                    <checkbox>
                        <halign>left</halign>
                        <label>Connect GPU to aircraft</label>
                        <live>true</live>
                        <property>/controls/electric/external-power</property>
                        <enable>
                            <property>/sim/gpu/enable</property>
                        </enable>
                        <binding>
                            <command>property-toggle</command>
                            <property>/controls/electric/external-power</property>
                        </binding>
                        <binding>
                            <command>dialog-update</command>
                        </binding>
                    </checkbox>                        
                    <text>
                        <halign>left</halign>
                        <label>Battery charge: xxxx %%</label>
                        <format>Battery charge: %3.1f %%</format>
                        <live>true</live>
                        <property>/systems/electrical/battery-charge-percent-100</property>
                    </text>
                </group>
~~~
and
~~~
    <filter>
        <type>gain</type>
        <gain>100.0</gain>
        <input>
            <property>/systems/electrical/battery-charge-percent</property>
        </input>
        <output>
            <property>/systems/electrical/battery-charge-percent-100</property>
        </output>
    </filter>
~~~

The /systems/electrical/battery-charge-percent-100 is used in the QUI but created in a filter. It just seems odd to me but might be harmless.

Does anyone know how you get a new data cache entry that exists nowhere in the code, I'm referring to the following?
systems/electrical/battery-charge-percent/a

**Comment by wlbragg** [comment]
@HHS81 what version of the c172p did this happen in for you, fgdata or something else?

**Comment by wlbragg** [comment]
One more note to myself mainly!
I worked on this portion of the electrical code for the fg1000 version, I needed a backup battery so I extended that portion of the code that allows for something like...
/systems/electrical/battery-charge-percent/battery-charge-percent/a
/systems/electrical/battery-charge-percent/battery-charge-percent/b

I need to switch git repo's to check exactly, but that code is not mingled with this code as far as I know.

**Comment by wlbragg** [comment]
@HHS81
Can you tell me if you ever installed or flew the fg1000 version of the c172p?

**Comment by wlbragg** [comment]
I think I answered my question to @HHS81, you had to have the fg1000 variant in the loop in order to get this error. It has to do with how the variants load cached data.
I think what might be happening is that if you use the c172p variant it creates cashed data, then if you use the fg1000 variant it also saves cache data that is incompatible with the c172p cache data. Then load the c172p again and it somehow pics up the portion of the fg1000 variant cache data that is incompatible. I don't know why this is happening. What is really strange is it only picks up half of the incompatible data.

**Comment by HHS81** [comment]
> 
> 
> @HHS81
> Can you tell me if you ever installed or flew the fg1000 version of the c172p?

I don´t think so, but I`m not sure.

**Comment by wlbragg** [comment]
@HHS81 
Thank you for discovering this. It is corrected now and shouldn't be an issue in the future. It definitely was only happening in the fg1000 branch. Please update that branch and delete any c172p aircraft-data cache, there could be one entry for every variant. After that you won't have any more problems with it.

**Comment by wlbragg** [comment]
As far as I am concerned, this issue can be closed unless, @HHS81 reports back in the negative.
