### ISSUE TITLE
Gather a list of features and bugs we fixed in 2020.4

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1356]
We should gather a list of all the new features, major changes, and bugs we fixed. Please create a list (use * to create bullet points) here.

Features:
* Compositor Clustered Shading Lights

TODO
Fixes:

TODO
Do not forget to update NEWS.md before creating the release. See https://github.com/c172p-team/c172p-detailed/wiki/Release-process-and-versioning

**Comment by wkitty42** [comment]
the new KAP140 would also be listed, right? i guess after it is fully applied...
and the fix for the craft being unable to move without toggling the damage property? something to do with tutorial usage...

**Comment by legoboyvdlp** [comment]
Yes, but clustered shading is the only thing that will be merged in the next few days. Anything else before today is already on 2020.3 or else on a branch. :)

**Comment by wkitty42** [comment]
ahhhh, yes... i got a little mixed up i think...

**Comment by legoboyvdlp** [comment]
**Features:**

* Add support for the FG1000
* Add 2020.4 clustered shading lighting support
* Add support for aerotow to allow gliders to be towed by the C172P
* Add revised and improved KAP140

**Fixes:**

* VOR/NAV guages: add missing yellow ticks and OBS label
* VOR/NAV guages: fix localizer needle rotation center
* Correct typos in the 'Flying the Pattern' tutorial
* Fix parking brake binding on joysticks; improve the parking brake control
* Fix issue where the engine wouldn't quit after a plane crash
* Fix issue where external views would break after switching airports
* Re-add the default mouse action when in a viewfrom view mode.



@wlbragg @wkitty42 @Megaf anyone got anything else?

**Comment by wlbragg** [comment]
Let me go through this list and what I know and see if I have anything to add.

**Comment by wlbragg** [comment]
@legoboyvdlp 
You pretty much nailed the new stuff as far as the list goes. Reading the list doesn't do the amount of upgrading, refactoring and new features justice though. But it is what it is. There were so many subtle changes in so many areas, like I said, the list doesn't do it justice. The FG1000 variant was so multifaceted, I guess that is why the list seems anticlimactic.

I added a couple fixes and reworded the fg1000 verbiage to better describe the depth of the FG1000 addition.

I'm done with it. Thanks you so much for all your help getting this release tagged.

**Comment by wkitty42** [comment]
AFAICT the list of updates/fixes seems to be ok...

**Comment by legoboyvdlp** [comment]
I hope I did everything right ... please confirm, should be a tag + release for version 2020.4, a branch for 2020.4 and now master is on 2020.5 ....

**Comment by wlbragg** [comment]
Yeah, looks good to me. I am really happy we have the start of an 172sp in the base. Thanks again for all your help.
