### ISSUE TITLE
NAV gauges missing yellow tick marks

### ISSUE THREAD

**Issue by hbeni** [c172p-team/c172p#1359]
Same issue as with the c182s: https://github.com/HHS81/c182s/issues/393

The NAV/VOR gauges should have little yellow triangles at the 12 and 6 position as reference for the OBS rotation:

![grafik](https://user-images.githubusercontent.com/13608602/110935142-50f70680-832f-11eb-9329-7e26fa89fde0.png)

**Comment by hbeni** [comment]
Fixed by https://github.com/gilbertohasnofb/c172p-detailed-liveries/pull/4
![grafik](https://user-images.githubusercontent.com/13608602/112549821-b2eb4d80-8dbe-11eb-88a9-cf073d6ca400.png)

**Comment by hbeni** [comment]
I forked and will make a proper pull request soon.
Looks like i need a change to the model as well, and the vor2 markings are off a little.

Please stand by

**Comment by wlbragg** [comment]
Thanks, I'll look at this in the next few days and merge.
