### ISSUE TITLE
typos in Cessna C172P Flying Pattern tutorial

### ISSUE THREAD

**Issue by aboim2** [c172p-team/c172p#1363]
I think I found some typos in Cessna C172P tutorial "Flying the Pattern"

Downwind section we can read.

"we turn **left** again...", should be "we turn **right** again..." as the pattern is done to the right
when the tutorial is running the ATIS voice is saying the same thing

further ahead "...drop one notch of **flat**.." and I think should be "...drop one notch of **flaps**.."

![fgfs-20210529184920](https://user-images.githubusercontent.com/12051636/120082005-5f47f980-c0b8-11eb-9b33-28d87cfb0bf5.png)

**Comment by wlbragg** [comment]
Thank you @legoboyvdlp @Megaf  @aboim2
