### ISSUE TITLE
External views break when switching airports.

### ISSUE THREAD

**Issue by Megaf** [c172p-team/c172p#1374]
External views, such as Helicopter View and others, break when you use Select Airport in sim, to go to a different airport.
Might be related to #1373 

Video showing the issue.
https://www.youtube.com/watch?v=5acOygRYRUg
Or, if you prefer, on Odysee.
https://odysee.com/FlightGear_Camera_Bug_Demonstration

**Comment by wkitty42** [comment]
On 7/4/21 3:59 PM, Megaf wrote:
> External views, such as Helicopter View and others, break when you use Select 
> Airport in sim, to go to a different airport.

it is broken with other craft? try it with the UFO... if is it broken there, 
then i suspect it is a core breakage...

**Comment by Megaf** [comment]
C172 specific.

**Comment by wlbragg** [comment]
Same issue. When you switch to the external view the flag /sim/current-view/can-change-z-offset is set to true. Then when you do a relocation the c172p-mice.set code loads and is allowed to execute because the condition is true.
We need tb find a flag that can condition the c172p-mice.set code to not execute in the event of a relocation .The other question is, exactly why was this c172p-mice.set code created?

**Comment by wlbragg** [comment]
@Megaf 
You can comment out line 1184 in c172p-main.xml
~~~
        <!--mice include="c172p-mice.xml"/-->
~~~
and eliminate both issues at the same time. I don't know what other issue it might create, but maybe you will notice and can let me know what it is that that code is doing.

**Comment by wlbragg** [comment]
Ok, this one is on me, it's the seat view code. I'll see if I can get it sorted out.
No need to comment out the code mentioned above. I have a fix for that I will push after some discussion as to why the original logic didn't work.

**Comment by wlbragg** [comment]
@Megaf this is corrected and awaiting @legoboyvdlp to test and merge.

**Comment by Megaf** [comment]
Thanks, @wkitty42 and @wlbragg helping with the investigation and quick actions.

**Comment by Megaf** [comment]
Fixed.
