### ISSUE TITLE
Tiedowns make the plane jump around

### ISSUE THREAD

**Issue by hbeni** [c172p-team/c172p#1383]
Hi there,
we found an issue with the tiedowns at the c182s (which we ported over initially from the c172p).
Under some circumstances the plane starts to oscillate wildly. We found out that this is linked to FDM framedrop which will mess up the PID that calculates the forces.

For the c182s we switched the force calculation to use a simple `<table>`.
Additionally we refactored the tiedown-breakage code from nasal to XML.
See the changes here: https://github.com/HHS81/c182s/pull/447.

I think they are quick and straightforward to port back here, only the lat two commits seem to apply here:
- https://github.com/HHS81/c182s/pull/447/commits/7dc7e9c16c60c70b7a80129db3653f0e0183a13e
- https://github.com/HHS81/c182s/pull/447/commits/395ed94a8bdc0c4205d5d3e61f3d71a45da9fa56

**Comment by wlbragg** [comment]
Great, thank you. I saw you were working on this. I'll check it out shortly.
