### ISSUE TITLE
Textures not power-of-two

### ISSUE THREAD

**Issue by MariuszXC** [c172p-team/c172p#1390]
4.77 [ALRT]:io         mipmapping: texture size not a power-of-two: /opt/fg/myHangar/Aircraft/c172p/Models/Interior/Panel/Instruments/gear/breakers-switches.png
4.77 [ALRT]:io         mipmapping: texture size not a power-of-two: /opt/fg/myHangar/Aircraft/c172p/Models/Effects/interior/lm_gear-breakers.png
9.46 [ALRT]:io         mipmapping: texture size not a power-of-two: /opt/fg/myHangar/Aircraft/c172p/Models/Exterior/rbf/rbf.png

Will submit a fix soon.

**Comment by wlbragg** [comment]
Thanks, I thought we had that fixed, but may be a regression.
