### ISSUE TITLE
Missing effects (in 'next')

### ISSUE THREAD

**Issue by MariuszXC** [c172p-team/c172p#1397]
After yesterday's MP event I found some warnings in a log. Details below.

c172p$ git show-branch --sha1-name master
[f8349ff2] Merge branch 'c172p-team:master' into master

flightgear$ git show-branch --sha1-name next 
[b216658ba] AI improved entry into parking (heading and postition)

3475.98 [WARN]:general   /opt/fg/simgear/simgear/debug/ErrorReportingCallback.cxx:82: Error:not found from shader/effect::Couldn't find Effect:Aircraft/c172p/Models/Effects/interior/lm-interior-fuel-selector.eff
        
 3475.98 [WARN]:general   /opt/fg/simgear/simgear/debug/ErrorReportingCallback.cxx:93: Error:not found from shader/effect::couldn't find base effect to inherit from:Aircraft/c172p/Models/Effects/interior/lm-interior-fuel-selector
        Path "/opt/fg/myHangar/Aircraft/c172p/Models/Interior/Panel/c172p-panel"
 3475.98 [WARN]:general   /opt/fg/simgear/simgear/debug/ErrorReportingCallback.cxx:82: Error:not found from shader/effect::Couldn't find Effect:Aircraft/c172p/Models/Effects/interior/lm-interior-fuel-selector.eff
        
 3475.98 [WARN]:general   /opt/fg/simgear/simgear/debug/ErrorReportingCallback.cxx:93: Error:not found from shader/effect::couldn't find base effect to inherit from:Aircraft/c172p/Models/Effects/interior/lm-interior-fuel-selector
        Path "/opt/fg/myHangar/Aircraft/c172p/Models/Interior/Panel/c172p-panel"
 3475.98 [WARN]:general   /opt/fg/simgear/simgear/debug/ErrorReportingCallback.cxx:82: Error:not found from shader/effect::Couldn't find Effect:Aircraft/c172p/Models/Effects/interior/lm-interior-fuel-selector.eff
        
 3475.98 [WARN]:general   /opt/fg/simgear/simgear/debug/ErrorReportingCallback.cxx:93: Error:not found from shader/effect::couldn't find base effect to inherit from:Aircraft/c172p/Models/Effects/interior/lm-interior-fuel-selector
        Path "/opt/fg/myHangar/Aircraft/c172p/Models/Interior/Panel/c172p-panel"
 3475.98 [WARN]:general   /opt/fg/simgear/simgear/debug/ErrorReportingCallback.cxx:82: Error:not found from shader/effect::Couldn't find Effect:Aircraft/c172p/Models/Effects/interior/lm-interior-fuel-selector.eff
        
 3475.98 [WARN]:general   /opt/fg/simgear/simgear/debug/ErrorReportingCallback.cxx:93: Error:not found from shader/effect::couldn't find base effect to inherit from:Aircraft/c172p/Models/Effects/interior/lm-interior-fuel-selector
        Path "/opt/fg/myHangar/Aircraft/c172p/Models/Interior/Panel/c172p-panel"
 3475.98 [WARN]:general   /opt/fg/simgear/simgear/debug/ErrorReportingCallback.cxx:82: Error:not found from shader/effect::Couldn't find Effect:Aircraft/c172p/Models/Effects/interior/lm-interior-fuel-selector.eff
        
 3475.98 [WARN]:general   /opt/fg/simgear/simgear/debug/ErrorReportingCallback.cxx:93: Error:not found from shader/effect::couldn't find base effect to inherit from:Aircraft/c172p/Models/Effects/interior/lm-interior-fuel-selector
        Path "/opt/fg/myHangar/Aircraft/c172p/Models/Interior/Panel/c172p-panel"

**Comment by wlbragg** [comment]
I'm limited on time for the next week or so but I think this error is corrected here on the master dev version and also the most current release tag. I asked for net to be updated from our master and I don't think it ever was.
