### ISSUE TITLE
Add a winter kit (cowl grill), expand icing effects

### ISSUE THREAD

**Issue by DaSovietPotato** [c172p-team/c172p#1398]
Today I was flying around in the rocky mountains and I faced a comical problem, the plane engine is unable to keep a decent temperature. Normally this wouldn‘t be a problem within the simulation, however my engine died on landing and I could not get it started to clear the runway until I used the external heat. Normally in real life, cowl blocks would be used to reduce the amount of air flowing through the engines to allow them to stay warm. I think that It would be a good option to add Cowl Blocks somewhere in the aircraft options menu.

**Comment by wlbragg** [comment]
Hi @DaSovietPotato 

I think the description of what you explain here may be a bit off. When you say "until I used the external heat", are you talking about the carb heat control? If so this is the correct solution. On a long approach in icing conditions it is recommended to use the carb heat. It prevents the carb from icing.
The c172p simulation only simulates that condition. I don't remember off hand the exact logic of the code that simulates this.

My questions are...

In Real Life...

Does warming the engine in this manner (using airflow restrictions/cowl blocks) keep the carb from icing.
Why is this method used VS the carb heater?

It seems a bit risky to me to use such a method to control and issue that the carb heater was designed to prevent.

Are you a real-life pilot with experience in this issue? Can you enlighten us?

**Comment by DaSovietPotato** [comment]
Hello, when I was referring to external heat I was referring to the external heat in the ground services tab. As far as flying was concerned, it was not humid enough for carburetor icing to occur but simply cold. The use of cowl blocks is in no way intended to replace carb heating as they accomplish related but completely different tasks. The use of cowl blocks is normally used to ensure that the engine is able to stay within the operating range on extremely cold days, they are commonly used on air cooled engines in places like Canada. A similar device exists for the 2CV to allow for the heater to work. The use of cowl plugs would indirectly help the carb heater to work more efficiently because of the higher engine temperature. I am not a pilot, however I have experience working in cold temperatures where similar measures to cowl blocks are usually taken. I hope that this answers some of your questions about the matter.

**Comment by wlbragg** [comment]
Hi @DaSovietPotato 

Are they used while flying ore strictly on the ground?

I'm not very familiar with the ground services tab, but I will take a look at it. I was not aware that the ground services were temperature dependent.

I don't think it would be difficult to add functionality to account for extra heat because of air flow restrictions.

**Comment by DaSovietPotato** [comment]
The cowl plugs are installed on the ground and remain for the entire flight. If I remember the airflow is simulated in the engine simulation, but I am not entirely sure.

**Comment by wlbragg** [comment]
@dany93 

Any idea as to what to influence in the FDM or engine parameters to accomplish the effect of restricting airflow?
Do we have any property I can tie adding one or two block/plugs to that would simulate heating the engine up.

I guess I am asking if there is something already available, or would we need to make this system. I know we already have oil temp. Maybe I can look at that and system to get ideas of what to use for this. I was hoping you might be able to direct me to where I need to look. I think I won't have any issue with the logic once I know where to look, if there is a where.

One other thing, the cowl plugs option in the GUI isn't working because the conditions for using it. There are two conditions
engines/active-engine/running =  false
engines/active-engine/rpm = 0

For some reason even at cold and dark aircraft conditions the rpm is reading positive. It is actually winding up slowly starting at 0,00273...... What is that all about? It won't matter once I implement this and it doesn't really matter now because I can change the condition to something like engines/active-engine/rpm < 1.
But I really want to know why some of these properties are active when they should be static.
engines/active-engine/rpm
engines/active-engine/mp-osi
engines/active-engine/oil-pressure-psi
engines/active-engine/egt-degf

**Comment by dany93** [comment]
@wlbragg >Any idea as to what to influence in the FDM or engine parameters to accomplish the effect of restricting airflow?

I would look at [JSBSim Engines (FGPiston)](https://wiki.flightgear.org/JSBSim_Engines#Parameter_definitions), **Cooling factor**.
`<cooling-factor> {number} </cooling-factor>`
_(don't know, I've never used it)_

**Comment by dany93** [comment]
>For some reason even at cold and dark aircraft conditions the rpm is reading positive. It is actually winding up slowly starting somewhere around 0.00273
I don't understand, I have them at 0, by the FG Properties or by the JSBSim ones.
![image](https://github.com/c172p-team/c172p/assets/11994061/4f858e6b-e634-4fb5-b617-6c9a525a54f3)

**Comment by dany93** [comment]
@DaSovietPotato wrote
>Normally in real life, cowl blocks would be used to reduce the amount of air flowing through the engines to allow them to stay warm

Weird... For me (not a C172 pilot IRL), the cowl plugs are only in place on the ground. Not used when flying, differently from the 2CV.
https://www.aircraftspruce.com/catalog/pspages/cowlplugs.php
 "remove before flight" streamer
Some aircraft (Douglas DC3) have such systems to control the temperature in flight.

**Comment by DaSovietPotato** [comment]
The winterization kit in this article is what I had in mind when discussing cowl blocks. https://www.aopa.org/news-and-media/all-news/2020/january/flight-training-magazine/how-it-works-winterization-kit

**Comment by wlbragg** [comment]
@DaSovietPotato I think the winterization kit is worth pursuing, especially if we have physical engine reaction to temperature. Do we? Can you describe exactly what effect your seeing that the cold, or extreme cold, has on our modeled simulation? I'm a bit fuzzy on what to look at or for under these extreme conditions.

The c182 has a "Winterization Kit" option. I want to look at it and see what their interpretation is.

**Comment by wlbragg** [comment]
@dany93 

This is what is happening as soon as I load the sim.

https://github.com/c172p-team/c172p/assets/11069680/38635f70-25cb-4ab5-b983-784d00b5d573

**Comment by dany93** [comment]
OK. This is not exactly cold and dark. You have the Battery, ALT and avionics ON.

With these manually set ON, I have most, almost all of the temperatures fluctuating, like you.
Except:
carb-icing-rate = 0,
fuel-flow-gph=0,
indicated-oil-pressure-psi = 0,
oil-pressure-psi = 0.

I confirm rpm = 0.

Temperature fluctuations can come from the ambient temperature fluctuations.
For the others in your video, I don't know.

**Comment by wlbragg** [comment]
Oh, wow. I didn't even notice, wasn't paying attention. OK, still the power to the aircraft shouldn't limit the cowl blocks from being in place. So I guess the change in the condition isn't a problem. If the aircraft engine is cranking then the rpm will always be > 1. 
I need to remind myself to look at the code that dislodges the chocks and make sure that is robust.

As far as the winterisation kit, the c182 looks like it models a good system for it. I will take their leed and finish this issue with a winterization kit.

I also noticed in the c182 they have condition for things such as the winterization kit being available based on conditions that require the power being off. Not a good choice in my opinion, especially as it was an unintended consequence.

**Comment by hbeni** [comment]
> The c182 has a "Winterization Kit" option. I want to look at it and see what their interpretation is.

It is laid out in the poh i think, and basicly its a plate mounted behind the spinner which blocks part of the cowling air intake. This reduces cooling airflow and thus makes the engine warmer.

**Comment by wlbragg** [comment]
> power should not be a constraint here

Right, I understand the reason you picked the properties. In theory they should work. It's just that I get this unexpected movement in some of those properties. When I initially posted about it being "Cold and Dark" @dany93 pointed out I had the batt on, not cold and dark. But since them I discovered the batt or electrical power had nothing to do with it.

**Comment by dany93** [comment]
@wlbragg wrote
>The c182 has a "Winterization Kit" option. I want to look at it and see what their interpretation is.

POH 172S (552SP, 8 July 1998)
PDF 193 / 384 (p.7-23)
>No manual cowlflap cooling system control is required.

PDF 311 / 384 (p.S8-3)
>The winterization kit consists of two cover plates (with placards)
which attach to the air intakes in the cowling nose cap, a placard
silk screened on the instrument panel, and insulation for the
crankcase breather line. This equipment should be installed for
operations in temperatures consistently below 20'F (-7"C). Once
installed, the crankcase breather insulation is approved for
permanent use, regardless of temperature.

**Comment by wlbragg** [comment]
I'm well into implementing this. I am using the c182 implementation which seems to work well. The difference is I am only using the cowling air intake portion of it. They add 3 components together, winter git (cowl grill), icing around the intake and and cowl flaps. I think cowl flaps are controlled with a switch (flaps below the cowling) and I have never heard of them used on the 172p. Doesn't mean they can't be or aren't used. I just haven't heard or read it anywhere as of yet.

I may end up adding the icing part though. They appeared to model it well. including extra weight through the use of a pointmass, aircraft/c182t/c182t.xml line 107. I just didn't totally understand that system, (the code used). You might take a look and see for yourself. The totals function for the three systems are in aircraft/c182t/c182t.xml line 1110. I started at the totals and work backwards from there to understand the three contributing systems.

I tested their implementation by flying in -0 celcius and applying the winter kit. It slowly changed the monitored temp in the aircraft. I'm pretty sure they used the same property you suggested.

**Comment by dany93** [comment]
@wlbragg wrote
>I think cowl flaps are controlled with a switch (flaps below the cowling) and I have never heard of them used on the 172p. 

[This message](https://github.com/c172p-team/c172p/issues/1398#issuecomment-1676919323)
>POH 172S (552SP, 8 July 1998)
PDF 193 / 384 (p.7-23)
>No manual cowlflap cooling system control is required.

**Comment by wlbragg** [comment]
Does the POH give a operational oil temp number or range.
Chat GPT says 160°F to 220°F (71°C to 104°C)

At -13 celsius oil temp is  is running at about 111.8 f
Installing the winter kit brought it up to 155.6 f which is not quite at the low end of chat GTP's information. The cooling effect can be adjusted to make it go a bit higher, This was setting the cooling factor from .514 to .25. I can try setting it to .20.

The provided information about the cowl grill shows it has a plate that looks to be adjustable? or maybe they have different size plates for different amounts of air restriction.

**Comment by wlbragg** [comment]
@dany93 
Setting the cooling effect to .20 VS .25... 

Default
@ .514 cooling rate, 120 ias, -13celsius = 111.8f

Winter Kit Installation
@   .25 cooling rate, 120 ias, -13celsius = 155.6f
@   .20 cooling rate, 120 ias, -13celsius = 174.3f

@   .20 cooling rate, 120 ias,  29celsius = 207.6f - simulated 85f weather with the winter kit installed

**Comment by wlbragg** [comment]
@hbeni 

Do you remember how you tested the icing system, the one that adds ice to the various aircraft surfaces? 
What is the best weather settings to promote icing?
Did you program any visual clues other than possibly the glass frost system? Was there any correlation to the glass getting frost and the aircraft icing occurring?

Did you assign all the various iced surfaces to only the one pointmass?

**Comment by wlbragg** [comment]
@dany93 depending on @hbeni answers to the above questions, feel free to play with adding drag from other iced surfaces that are as of now not really accounted for.

From what I could tell it is only weight added to one pointmass for any surface with ice. I wouldn't mind breaking that out to the various surfaces with more pointmass locations and adding the drag increases and possible lift reductions from the various surfaces to the FDM aerodynamics.

These are the areas modeled to collect ice...
~~~
                <iceable>
                    <name>Wing</name>
                    <sensitivity type="double">1.0</sensitivity>
                    <output-property>/fdm/jsbsim/ice/wing</output-property>
                </iceable>
                <iceable>
                    <name>Stabilizer</name>
                    <sensitivity type="double">1.0</sensitivity>
                    <output-property>/fdm/jsbsim/ice/stabilizer</output-property>
                </iceable>
                <iceable>
                    <name>Propeller</name>
                    <sensitivity type="double">0.5</sensitivity>
                    <output-property>/fdm/jsbsim/ice/propeller</output-property>
                </iceable>
                <iceable>
                    <name>Windshield</name>
                    <sensitivity type="double">0.5</sensitivity>
                    <!-- not relevant for fdm, ignore output-property -->
                </iceable>
                <iceable>
                    <name>Fuselage</name>
                    <sensitivity type="double">0.3</sensitivity>
                    <output-property>/fdm/jsbsim/ice/fuselage</output-property>
                </iceable>
                <iceable>
                    <name>Pitot tube</name>
                    <sensitivity type="double">1</sensitivity>
                    <salvage-control>/systems/pitot/salvage</salvage-control>
                    <output-property>/systems/pitot/icing</output-property>
                </iceable>
                <iceable>
                    <name>Static</name>
                    <sensitivity type="double">0.3</sensitivity>
                    <output-property>/systems/static[0]/icing</output-property>
                </iceable>
~~~

**Comment by wlbragg** [comment]
@dany93 
Just incase you tried to test the icing system, I inadvertently left out the property switch that enables it. It is now working, at least partially. I haven't verified any influence on the FDM yet. Bt the icing machine is working.
An easy environment to test is to use live metar, then switch to manual and change clouds to SCT006 and temp to 3/2 Take of and as soon as you enter clouds you will see the ice surface properties go active and accumulate ice.
You can monitor fdm/jsbsim/ice/... to see it in action.
The c182 does model at least cowling icing visuals. I think it is the dirt shader they are using. I haven't finished installing that yet. Hopefully by the end of the day today we will also see the visual effect of icing in the the c172.
Hats off to the c182 team though, it is a really good start to a complete icing system. Well done!

**Comment by wlbragg** [comment]
Can anyone verify the engine exhaust smoke particle effect is different than it used to be? I think it is much more pronounced then it used to be. Something is not right with it?
![fgfs-20230816210955](https://github.com/c172p-team/c172p/assets/11069680/205160ed-eba8-405d-a077-7a84050b7b21)

**Comment by dany93** [comment]
@wlbragg 
I tried (? tested is not the appropriate word...) your icing system.
Very impressive, even if I didn't understand everything.
It seems that the maximum severity is for negative temperatures in Celsius, close to 0°C.
I've had several losses of control, loss of speed or stall and spin. I think it's rather due to drag or turbulence, not the weight of the ice. Once, the engine almost stopped.
Visually, I don't know. The first time I thought I saw a difference, the second time I didn't...

**Comment by dany93** [comment]
@wlbragg wrote
>Can anyone verify the engine exhaust smoke particle effect is different than it used to be? I think it is much more pronounced then it used to be. Something is not right with it?

I have this (with "Autostart")
![exhaust](https://github.com/c172p-team/c172p/assets/11994061/a8df88db-7a34-4063-bdaa-e8b6d5f9f379)
I can't compare, I don't remember having observed it. But it seems good, nice.

Obviously different from your picture.

**Comment by wlbragg** [comment]
>Visually, I don't know. 

They use a graymap for the ice graphics. It is incredibly well gone! I'll have to make one for the c172p layout. All you'll see until I make one is the default dirt mask with a color change to white. It just adds white to every surface, not like this wonderfully done visual for the c182. It takes awhile to start showing up, less time in the c182 because it is tuned with the mask.

![ice](https://github.com/c172p-team/c172p/assets/11069680/c9663fb5-4544-4e00-b885-ddf7db68d052)

**Comment by hbeni** [comment]
One thing I still wonder is: how fast icing gets to be a problem in real life?

Is our model „too agressive“? (or too forgiving)?

**Comment by wlbragg** [comment]
>Is our model „too agressive“?

I really don't know, but it feels right to me. If your in ice, it doesn't take long to really build up. Especially at 140 kts. I think we might be able to find info on what to expect in these types of conditions.

**Comment by wlbragg** [comment]
@dany93 

I pushed the ice masks, so if you fly through clouds for any length of time during icing conditions, you should notice the ice on all the leading edge of the aircraft. I didn't test and observe all the variants for the ice visual, like skies and floats. So if you notice  any that don't look good, let me know.

**Comment by dany93** [comment]
@hbeni wrote
>One thing I still wonder is: how fast icing gets to be a problem in real life?

That's a real question... I dont' think one of us (among 3 or 4) has this experience.
How fast and how strong effects?

I also had instrument failures (airspeed, altitude, vertical speed indicators). Which is a real danger in reality.

After thinking a bit more:
I didn't think of it in my tests, but part of my observations (loss of airspeed, engine semi-failure) can also be due to carburetor icing (which was already modeled in the c172p).

Anyway, even if imperfect, this addition is a real improvement. Thanks for your work and thought.

**Comment by hbeni** [comment]
> Anyway, even if imperfect, this addition is a real improvement. Thanks for your hard work and thought.

Yes!
And dont forget to implement the alt static port system, as pulling that knob helps to mitigate some of the icing consequences (like stuck altimeter or Airspeed indicator)

**Comment by wlbragg** [comment]
@dany93 

After searching the piton system, I see nothing indicating we ever modeled the heater, I assume because we never modeled the icing for it. Can you confirm?
The c182 gave you partial acknowledgment for the piton system and they improved upon it for their icing system in Systems/indicated-airspeed.xml
~~~
<!--
    Pitot implementation
    taken from from c172p, thanks dany93.
    enhanced by B. Hallinger for c182s
    failure due to pitot icing  by H. Schulz 
-->
        
        <switch name="/systems/pitot/heating">
            <output>/systems/pitot/heating</output>
            <default value="0"/>

            <test logic="AND" value="1">
                /controls/anti-ice/pitot-heat EQ 1
                /systems/electrical/outputs/pitot-heat GT 20
            </test>
        </switch>
        
        <kinematic name="/systems/pitot/heat-applied-norm">
            <input>/systems/pitot/heating</input>
            <traverse>
                <setting>
                    <position>0</position>
                    <time>0</time>
                </setting>
                <setting>
                    <position>1</position>
                    <time>30</time>
                </setting>
            </traverse>
            <output>/systems/pitot/heat-applied-norm</output>
        </kinematic>
        
        <switch name="/systems/asi/pitot-serviceable">
            <output>/systems/pitot/serviceable</output>
            <default value="1"/>
	    
            <test logic="OR" value="0">
                /sim/model/c182s/securing/pitot-cover-visible EQ 1
 	     /systems/pitot/icing GT 0.03
            </test>
        </switch>	
	
        <switch name="/systems/pitot/salvage-control">
            <output>/systems/pitot/salvage</output>
            <default value="1"/>
	    
            <test logic="OR" value="0">
               /systems/pitot/heat-applied-norm LT 0.3
            </test>
        </switch>
~~~

Assuming all of the above is true, I am adding their implementation for the heater to our piton system.

**Comment by wlbragg** [comment]
@hbeni or @dany93 if you know, what is the pitot/salvage-control for?

**Comment by dany93** [comment]
@wlbragg wrote
>After searching the piton system, I see nothing indicating we ever modeled the heater, I assume because we never modeled the icing for it. Can you confirm?

I also think that the Pitot heating has never been modeled.

**Comment by wlbragg** [comment]
OK, I just pushed the pitot heater system. The only thing I question is the speed at which the heater melts the ice and restores the system. It may be accurate, it is a small instrument and I suppose a good amount of voltage applied to it might melt any small accumulations of ice.

I have a hard time testing the failure for the ASI though, I really am not sure what I am supposed to see. I assume being on a level flight path with AP would help notice the difference in airspeed.

**Comment by wlbragg** [comment]
Next up, static port. I don't know that we ever activated te alt static port. I'm not sure ho that system would work.

**Comment by wlbragg** [comment]
> I only remember having worked on the indicated airspeed for the instrument.

That makes sense as to what it was for, the pitot cover implementation.

**Comment by wlbragg** [comment]
@dany93 through time the Blender files in dev have been broken apart into a few various files supporting the .ac files in the model. Things were moved around, like breakers and switches and many other object were added to one file and never removed from the original file. They would only be hidden, or more accurately marked to not save on export. I am responsible for much if not all of it. It would be really easy for someone not familiar with the Blender and .ac files to get confused and unhide those objects. I did this in the short term as an effort to not delete an object accidently when moving things around. I think it is time to actually remove these hidden (marked to not export) objects out of the Blender files so future developers don't get confused if they ever work on the models. I'm going to do it in this issue and PR as I have already made a couple small changes to the blend and .ac files.

**Comment by wlbragg** [comment]
OK, this is really close to finished, I think just testing some more is all that is needed.

The following systems were added and activated. I also did a quick test of them all and they appeared to operate correctly.

Pitot icing and heater
Static port icing and alt static port capability
Aircraft surfaces icing

GUI install Winter Kit Cowl Grill

GUI enable conditions modified for 
Install Winter Kit
Put Cowl Plug
Enable Damage

Cleaned up Blender files in dev repository files

Misc cleanup of a couple files where I noticed some unused and unreferenced aliases

Removed the duplicate Avionics switch (again)

**Comment by hbeni** [comment]
Speaking of the pitot, in the c182 the pitot heat switch also heats the stall vane.
It may be a good occassion to model that too (if ice forms on the leading wing edge, the stall horn gets iced=inop)

**Comment by hbeni** [comment]
> @hbeni or @dany93 if you know, what is the pitot/salvage-control for?

No idea out of my head.
Would need to do a recherche.

**Comment by dany93** [comment]
> @dany93 wrote
>> I only remember having worked on the indicated airspeed for the instrument.
 
@wlbragg wrote
> That makes sense as to what it was for, the pitot cover implementation.

No.
It was for taking into account the instrument error.
See POH 180hp 552SP and 160hp 1982, p.6-9 (Airspeed Calibration, Normal Static Source).

**Comment by dany93** [comment]
@wlbragg wrote
>... pitot heater system. (...) the speed at which the heater melts the ice and restores the system. (...) I suppose a good amount of voltage applied to it might melt any small accumulations of ice quickly.

POH 180hp p.7-41:
> The heated pitot system consists of a heating element in the pitot tube, a 5-amp switch/breaker labeled PITOT HEAT

(it's not a clue for the melting time...)
