### ISSUE TITLE
Clarification: Is this model already used on the standard FGFS, or is it an add on?

### ISSUE THREAD

**Issue by namoscagnm** [c172p-team/c172p#1399]
Hi, I am new to FGFS.

Before installing FGFS I had the impression that this github add is an add-on. Now that I installed it I have the impression that this github is already the default model of the FGFS.

Could you please clarify if this is an add-on or the default?

In case its an add-on, could you write on the readme how to install it?
In case its already the default but the github version is (potentialy) newer, could you please add to the readme how to update it?

I think that lots of people would benefit from this information.

Thanks!

**Comment by wkitty42** [comment]
yes, this is the model that is in FG... when FG is going to cut a new release, if we have changes to the craft, we make a tag on working code and ask FG to merge that tag...

the only reason one would want/need to manually download this model and use it is if they like dancing on the edge of a razor blade and want the latest alpha/beta code which may or may not be complete...

**Comment by dany93** [comment]
Hi @namoscagnm 

You can not strictly _update it_. You have to download and install it separately.
I presume you are under Windows OS, with a 2020.3 FGFS version.
What you can do is to download the .zip from github (master branch, Code), then unzip it into a folder of your choice.
After that, you give the path to this folder in the launcher. In 'add-ons', 'Additional aircraft directories'.
The Launcher list will display two C172P, you choose. Double click to display which version (the path).

FGFS will probably display a warning message about the 2020.4 FGFS expected version, but it should work. Apart maybe for a few new functions.
