### ISSUE TITLE
Force invert-mouse-wheel = true

### ISSUE THREAD

**Issue by PlayeRom** [c172p-team/c172p#1401]
FG gives us a choice if we want the mouse wheel to work in reverse (menu "File" -> "Mouse Configuration" -> "Reverse mouse wheel direction" which sets the `/sim/mouse/invert-mouse-wheel` property). So why in Cessna we are forced to use reverse mouse wheel? I mean instruction in the c172p-main.xml file:

```
<!-- Fix scrolling direction of knobs -->.
<mouse>
    <invert-mouse-wheel type="bool">true</invert-mouse-wheel>.
</mouse>
```

This instruction causes my autosave file to be overwritten and I have to uncheck "Reverse mouse wheel direction" every time (I prefere without reverse). I also didn't noticed any problem with knobs after removing this instruction at all.

**Comment by wlbragg** [comment]
I don't understand why this changes anything to do with autosave, can you explain? As far as why invert is hardcoded, I have no idea. You would have to dig through the commit history and see if you can find any comments on it.

**Comment by wlbragg** [comment]
@wkitty42 your pretty good at searching stuff, do you know how to run a keyword search over commit history?

**Comment by dany93** [comment]
This is an endless issue.

As for rotating a knob, a potentiometer, or the magneto key, people are divided (CW or CCW vs wheel scrolling).
As for a value, many people prefer that it increases when they push the scroll wheel.
These two are often contradictory.

In its current setting, the mouse scrolling is counter intuitive for the throttle, mixture, flap lever. Also (IMO) the elevator trim.

**Comment by wlbragg** [comment]
@dany93 
"Counter intuitive" are you of the opinion that the hardcoded invert is responsible for the default direction being counter intuitive? Does anyone know how c172 rotation defaults compare to other aircraft? I'll have to fire FG up and see what the knobs feel like. But from my minds perspective I think scroll forward should increase any knob and scroll back to decrease. Would this be most people's opinions?

**Comment by dany93** [comment]
@wlbragg 
> "Counter intuitive" are you of the opinion that the hardcoded invert is responsible for the default direction being counter intuitive? 

It depends on what you are calling "the default direction" (= current direction?) and "the "hardcoded invert" (= `<invert-mouse-wheel type="bool">true</invert-mouse-wheel>` ?)
But for example, scrolling forward makes the throttle or mixture levers moving backwards. This is obviously counter intuitive.
Also, scrolling forward making the flap lever moving downwards is counter intuitive.

@wlbragg wrote
>  I think scroll forward should increase any knob and scroll back to decrease. Would this be most people's opinions?

@dany93 wrote

> As for a value, many people prefer that it increases when they "push" the scroll wheel.

Thus, I agree.

**Comment by PlayeRom** [comment]
@wlbragg I honestly don't know, but it does :) It looks like first the config from autoseave is loaded and then the one from the aircraft, which overwrites the autosave.

@dany93 Maybe I do not understand something, but I think it makes no sense to talk about who prefers what, because as I wrote in the FG options you can choose what you prefer, what is saved in the autosave, only I do not understand why the C172P forces its own setting over autosave.

In my case, `invert-mouse-wheel = false` means that when I turn the wheel forward, the throttle increases the thrust. Therefore I prefer this behavior. Unfortunately the aircraft always sets it to `true`. I tested with 2020.3.13 and `next` on Linux Mint.

My workaround it's add `--prop:/sim/mouse/invert-mouse-wheel=false` to the command line. So out comes the fun of who gets to overwrite who last :)

**Comment by wkitty42** [comment]
On 5/10/22 1:26 PM, dany93 wrote:
> @wlbragg <https://github.com/wlbragg>
> 
>     "Counter intuitive" are you of the opinion that the hardcoded invert is
>     responsible for the default direction being counter intuitive?
> 
> It depends on what you are calling "the default direction" (= current 
> direction?) and "the "hardcoded invert" (= |<invert-mouse-wheel 
> type="bool">true</invert-mouse-wheel>| ?)
> But for example, scrolling forward makes the throttle or mixture levers moving 
> backwards. This is obviously counter intuitive.
> Also, scrolling forward making the flap lever moving downwards is counter intuitive.

FWIW: i understand the problem and it is a tricky one to handle...

> @wlbragg <https://github.com/wlbragg> wrote
> 
>     I think scroll forward should increase any knob and scroll back to decrease.
>     Would this be most people's opinions?
> 
> @dany93 <https://github.com/dany93> wrote
> 
>     As for a value, many people prefer that it increases when they "push" the
>     scroll wheel.
> 
> Thus, I agree.

now, consider this... you're looking at a document... line 1 is at the top and 
line 100 is at the bottom... which way do you scroll your mouse wheel to move 
down to line 100? you "pull" it toward you thus making the line numbers get 
larger... if you push the wheel, the line numbers get smaller... same for web 
pages... pushing the wheel takes you to the top of the page whereas pulling the 
wheel takes you down the page...

in regards to radio knobs, if i push the wheel, i expect the frequency numbers 
to get smaller and pulling the wheel makes them get larger... this is in the 
same way that the line numbers in a document get larger or smaller...

in regards to the throttle, flaps and other similar levers, i expect to push the 
wheel to make the levers/slides move away from me and pulling the wheel would 
bring them back toward me...

it sounds like the code should be multiplying by -1 in some cases (levers and 
slides?) while not multiplying in others (turning the knobs)... this way, 
pushing the wheel would make the radio knobs turn CCW while also pushing the 
wheel would make the lever/slider move away from you... i just don't know which 
ones need to be multiplied by -1 and which do not... if we even have that kind 
of control in the craft's code...

**Comment by wlbragg** [comment]
@PlayeRom 
@dany93 commented on the popularity of scroll directions because I asked about it. I understand what your saying about it not really mattering as it is supposed to be offered as a choice by FlightGear's main menu. I don't know why it is hardcoded other than to assume it was done so to make radio dials that were also part of that commit work in a certain way. 
@wkitty42 I guess I need to get in the c172 and see for myself how all the knobs, dials and sliders behave compared to your reasoning and analogy.
One thing that might be a fix is to make the invest option available in the c172p menu. Although that seems redundant. I agree that an aircraft should avoid overriding a setting that is typically a choice in the main FG settings.

**Comment by dany93** [comment]
My impression is that deleting or commenting in c172p-set.xml
```
<mouse>
    <invert-mouse-wheel type="bool">true</invert-mouse-wheel>.
</mouse>
```
would solve most of these issues.

**Comment by dany93** [comment]
@PlayeRom wrote
> @dany93 Maybe I do not understand something, but I think it makes no sense to talk about who prefers what, because as I wrote in the FG options you can choose what you prefer

It does make sense because you invert everything. Which cannot match everyone's preference.
Thus, the endless issue.

**Comment by dany93** [comment]
See [this message](https://github.com/c172p-team/c172p/issues/1330#issuecomment-675147597) from @onox.
And the rest of the conversation in the [same issue](https://github.com/c172p-team/c172p/issues/1330).
And Pull #1332

**Comment by hbeni** [comment]
Because this came up again in the forums:
https://forum.flightgear.org/viewtopic.php?f=4&t=43060&p=429616#p429616

A possible and „clean“ solution could be:
- remove the overwrite of the core setting, so user choice is respected and persisted
-  at setting `false:`
  - make all knobs rotate to the right when pushing the mouse wheel
  -  make the levers go down / to you when pulling the mouse wheel
- add aircraft option to
  - reverse knob direction
  - reverse lever direction
- make it so that the core setting inverses the aircraft options

The result is a sane default which is completely customizable by the user.
