### ISSUE TITLE
Suggestion: Do automated testing to ensure that changing JSBSIM values doesnt break previous flight behavior

### ISSUE THREAD

**Issue by namoscagnm** [c172p-team/c172p#1402]
Hi, everybody. I was following the thread #1364 and saw that its sometimes a risky endeavor to change JSBSIM values to match pilots feedback (see for instance here: https://github.com/c172p-team/c172p/issues/1364#issuecomment-867623489 from @dany93). The main risk is to suffer some side effects which will mess with some previous flight characteristics in an undesired way. 

I have a suggestion on how to reduce this risk, as follows:

If we could establish a system which could get some performance factors from the airplane (like best L/D, max range, behavior to some inputs) automatically in a way that we can make automated tests on them. With this, any unexpected change would be caught by the test routines immediately, on which the developers could act before putting the aircraft in production code.

For instance, there could be some automated test script saying:

-When aircraft is at:

> isa atmosphere
> Throttle is 80%
> Mixture is full rich
> Flaps is 0
> Trim is at 0.0x

-Then:
There should be a rudder value that lets the fight leveled (within some tolerance)

If we change afterwards some P-value or whatever value in the hope that it will best match some pilot experience and we break the criteria above, the test would catch it immediately before putting the code in production. As we build more and more tests, it gets quicker and quicker to tweak the airplane in a safe way.

In software development this is called automated testing and is a standard practice.

Is it possible to do this currently? If no, which parts of flight gear would have to be changed to enable this? Would it be on the FG C++ code, or in some FG nasal script, or is it on the airplane side?

I really think that doing automated tests would allow us to preserve previous achieved fidelity of simulation and allowing more feedback from pilots to be implemented quickly.

I think this would be a healthy discussion.

Thanks!

**Comment by dany93** [comment]
Hi @namoscagnm 

Your suggestion is interesting but IMO extremely difficult to implement.
Firstly for the code, secondly for which criteria are to be considered, and how to evaluate the result.

Even your (simple?) example
 
> For instance, there could be some automated test script saying:
(.......=
-Then:
There should be a rudder value that lets the fight leveled (within some tolerance)

Usually done by flight tests (in FG of course), much more difficult to calculate in a general case.

And it is worse for complicated behaviors like _felt_  roughness at controls, stall and spin behavior, how to measure the adverse yaw ([this issue](https://github.com/c172p-team/c172p/issues/1378)) ...

**Comment by namoscagnm** [comment]
Hi, @dany93 

1) For the code, I believe that the JSBS executable could just be called directly, be fed with the c172 xml files, and a (maybe Python) script would read the output and assert it.

2) About the criteria to be considered and how to evaluate the result: As you said, its not possible to test everything, but its possible to find out things which are easy to test and which are useful. For behaviors like "roughness" of controls, its probably better to let it to a manual test. II think that easy and useful automated tests would be the ones related to the chapter 5 (Performance) of the 172 POH, as they are in table format and has deterministic values. For instance Figure 5.5 (maximum rate of climb) says that:
For flaps up, full throttle, 2400lbs weight and sea level, 76kias and 20deg Celcius, the rate of climb is 685 fpm.

An automated test for this would be something like (thats Python-like code what I will show now):
```

environment.press=(29.92, inHg)
environment.temp=(20,celsius)


aircraft.weight=(2400,lbs)
aircraft.controls.flap=(0,deg)
aircraft.engine=running
aircraft.engine.throttle=100%
aircraft.engine.mixture=100%
aircraft.engine.carburettor=false

aircraft.speed=(76, kias)
aircraft.yawangle=(0,deg)
aircraft.rollangle=(0, deg)
aircraft.pitch=fixedspeed(76, kias)

JSBSIM.simulate(aircraft, environment)

assert aircraft.rateofclimb==(685,fpm) 
```

assert is already builtin in Python in the pytest lib.

There are two options when setting the controls: 
1- I can make it as complicated as I want (for instance, flaps will not go down if hidraulic is broken), but 
2- we could also bypass this difficulty and just ask the FDM to believe that the flaps are set. 

On the first option the test would detect for us if the the hydraulic is modelled wrong, but I think its too much trouble. Easier would be the second option.

As you see, this can be made as complex as we want, but for the beginning we could explore the solutions which are easy and useful.

ps: I just just wondering if checking those constraints that we find on the POH Performance section via automated tests should be developed as a feature of JSBSIM, and not of the aircraft itself.

Please, share your thoughts on that :)

**Comment by dany93** [comment]
@namoscagnm

I understand better what you are meaning.

> I just just wondering if checking those constraints that we find on the POH Performance section via automated tests should be developed as a feature of JSBSIM, and not of the aircraft itself.

I fully agree, this was my idea after reading your last message.
This project is not a c172p issue, it is a JSBSim one. To be discussed with the JSBSim team, where you will find people much more skilled than me on this subject.
I see it as a tool, embedded or something like AEROMATIC.

Can it be, should it be embeddable in C++ JSBSim, I don't know.

Sorry, I might give general, more or less interesting thoughts on this, but I can't help. Well above my coding skills.

The possible use by aircraft modellers (who are not experts in computer language) would depend on its complexity and the more or less limited scope in results.

However, you are right, a need exists. I had an example, the drag vs airspeed (form drag + induced drag): the final result is not only drag, but the best glide-ratio airspeed. It is very cumbersome to test, needing many changes in FDM inputs and measurements if only done by trial and error.  For that, I remember having done a calculation spreadsheet based on JSBSim calculations. Very specialized.

**Comment by wkitty42** [comment]
FWIW: the idea of automated testing is sound but, in the case of FG craft, there is no building of anything craft related so there's really no where for automated testing to be inserted into the process... at best, a script could be developed and used that would assist with testing tuning but it should be noted that this would not be done all that often... certainly not once the FDM has been created with the proper numbers contained within it... it isn't like the FDM changes a lot and needs updating all the time...

**Comment by namoscagnm** [comment]
> FWIW: the idea of automated testing is sound but, in the case of FG craft, there is no building of anything craft related so there's really no where for automated testing to be inserted into the process... at best, a script could be developed and used that would assist with testing tuning but it should be noted that this would not be done all that often... certainly not once the FDM has been created with the proper numbers contained within it... it isn't like the FDM changes a lot and needs updating all the time...

Hi, @wkitty42 . Once the FDM has the proper numbers, yes, we dont need to change anything. However, some data dont have real life approved input, its just fine tuning (playing with values) until they match some expected behavior. As you can imagine, matching one behavior doesn't mean we are unintentionally not matching lots of others behaviors unexpectedly.

To ensure that playing with values dont break some aircraft performance unintentionally, having this feature would be very useful.

**Comment by namoscagnm** [comment]
> @namoscagnm
> 
> I understand better what you are meaning.
> 
> > I just just wondering if checking those constraints that we find on the POH Performance section via automated tests should be developed as a feature of JSBSIM, and not of the aircraft itself.
> 
> I fully agree, this was my idea after reading your last message. This project is not a c172p issue, it is a JSBSim one. To be discussed with the JSBSim team, where you will find people much more skilled than me on this subject. I see it as a tool, embedded or something like AEROMATIC.
> 
> Can it be, should it be embeddable in C++ JSBSim, I don't know.
> 
> Sorry, I might give general, more or less interesting thoughts on this, but I can't help. Well above my coding skills.
> 
> The possible use by aircraft modellers (who do not need to be experts in computer language) would depend on its complexity and the more or less limited scope in results.
> 
> However, you are right, a need exists. I had an example, the drag vs airspeed (form drag + induced drag): the final result is not only drag, but the best glide-ratio airspeed. It is very cumbersome to test, needing many changes in FDM inputs and measurements if only done by trial and error. For that, I remember having done a calculation spreadsheet based on JSBSim (analytical) calculations. Very specialized.

Hi, @dany93. I have opened a suggestion under JSBSIM to implement this. It would be very helpful if you could give your concerns there. For instance, it was very important that you pointed out that no skills in programming should be required for this from the aircraft developer. I didnt think of this before.

So, feel free to write on the JSBSIM explained the needs of an average aircraft developer.

Here is the link:

https://github.com/JSBSim-Team/jsbsim/discussions/634#discussion-4105177

**Comment by namoscagnm** [comment]
Moved to JSBSim github, see:
https://github.com/JSBSim-Team/jsbsim/discussions/634#discussion-4105177
