### ISSUE TITLE
User boarding procedures causes a strange tiedown effect

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1403]
From Jimis Hol on the FlightGear developers mailing list https://sourceforge.net/p/flightgear/codetickets/2741/

> Untying wings and tail, occasionally, cause plane to drop down instead of raising up.
> It is a minor bug, for my opinion, but starts to be annoying once someone notice it.
> I fly C172, i save the state of craft when i quit and when i start a flight i always get out as walker to do my preflight checklist. I always secure my plane and tie it down in ground, so i find it tied down and secured when i start the game. I randomly peek passengers and baggage. I open doors and let them in by editing the 'fuel and payload' window. During the load the plane drops, a little, naturally toward ground because of the added weight.
> The bug is that ropes that tie the plane towards the ground prevent plane to drop down as much it wants. (That seems against physics because ropes can not transfer force that points inward to them. They cannot be pushed, they can only be pulled.) So, when i untie the plane i have the strange behavior. Left wing drops down when i untie it, right wing do the same when i untie it and tail drops in a much more degree when it is untied.
> That happens only when one had loaded weight while the plane was secured. If one loads the plane, then ties it and then unloads it, the normal behavior of ropes come back. For every rope he unties he sees the plane's frame to raise up.
> Tie and untie the plane without changing its weight between, does not make the plane move down or up in obvious matter. If it moves seems to move in the right direction. Load while plane is unsecured, tie it and then untying has the right or neglectable effect. But load it while it is secured and you will notice that ropes prevent it from dropping down pushing it up, contrary to what is expected. They do not pull it towards the ground.
> 
> P.S. I play release/2020.3
> Thank you.

I think this will require someone to look into the physics of the tiedown code and see if we can account for this type of user procedures.

**Comment by wlbragg** [comment]
See https://github.com/c172p-team/c172p/issues/1383

**Comment by wlbragg** [comment]
@dany93 

I am going to implement the c182 changes in https://github.com/c172p-team/c172p/issues/1383

While I am at it I want to work this issue, I have an idea how to solve it.

I want your opinion on rearranging the GUI as follows.
![ground-equp](https://github.com/c172p-team/c172p/assets/11069680/eb8d1e9c-857e-4dca-8d3a-cb0e55f8d11d)
What do you think? What about the "Control Lock" would that be better left where it is or moved as well? I feel it makes more sense to have the tidowns, chocks, and plugs in the Ground Equipment GUI than where they are now?

**Comment by dany93** [comment]
@wlbragg wrote
>I feel it makes more sense to have the tiedowns, chocks, and plugs in the Ground Equipment GUI than where they are now?

Not absolutely, but it can make sense. They are not exactly "Ground equipment" (hence possible hesitation).
>What about the "Control Lock" would that be better left where it is or moved as well?

This piece is in the cockpit, better IMO to let it where it is in the GUI. Not at all a "Ground Equipment".

**Comment by wlbragg** [comment]
>Not absolutely, but it can make sense. They are not exactly "Ground equipment"

Agreed.

I wonder if the ties and chock usually go with the aircraft or stay on the ground or in the facilities? That could make the difference for me. I could see it depending on the circumstances.

My other thoughts were to shorten the "Aircraft Menu" and that was one group of items that could possibly move to "Ground Equipment". 

As far as this issue, I tested it and I cannot get the behavior described above. So there really isn't any way for me to test any changes I might make. I thought of how I could accomplish it, but it seems messy and hacky. I would set listeners for any weight changes to the aircraft and reset the ties upon any change. I'm not sure what I mean by "reset" them though. I don't know if a condition such as turning  /fdm/jsbsim/damage/repairing EQ 0 on and off would be "resetting" the forces? Any idea where you would reset the force applied, or how that works?

~~~
<switch name="fcs/tiedown-left-magnitude">
            <output>external_reactions/tiedown-left/magnitude</output>
            <default value="0"/>

            <test logic="AND" value="fcs/tiedown-left-magnitude-pid">
                /sim/model/c172p/securing/tiedownL-visible EQ 1
                /fdm/jsbsim/damage/repairing EQ 0
            </test>
        </switch>
~~~

@dany93 If you can't observe the described behavior, then I would call this issue closed.

**Comment by dany93** [comment]
@wlbragg wrote
>I wonder if the ties and chock usually go with the aircraft or stay on the ground or in the facilities? That could make the difference for me. I could see it depending on the circumstances.

I'd rather say that they go with the aircraft, which will need them if it goes in another airport.
I don't hesitate for the cowl plugs, ties, pitot plugs. They must be with the aircraft and could be lost otherwise.
For the wheel chocks, we can hesitate because it makes an extra weight and takes place.

**Comment by wlbragg** [comment]
I'm closing this issue as fixed. I do not observe the undesired behavior when implementing the described procedure.
