### ISSUE TITLE
Flighgear Menu Item C172->About this Aircraft - The URL works, but redirects from a personal account on github to the team

### ISSUE THREAD

**Issue by callahanp** [c172p-team/c172p#1413]
In c172p/gui/dialogs/C172p-about.html, line 166 links to a personal account on github.

<script>fgcommand("open-browser", props.Node.new({"url":"https://github.com/Juanvvc/c172p-detailed/"}));</script>

Clicking on the  link gets you: https://github.com/c172p-team/c172p

Do you think this should be changed to reflect the current URL?

<script>fgcommand("open-browser", props.Node.new({"url":"https://github.com/c172p-team/c172p/"}));</script>

**Comment by wlbragg** [comment]
Yeah, the Juanvvc link is a redirect to the main repository. We could go ahead and change it to a direct link.
