### ISSUE TITLE
FG1000 refactor lighting and position of kap140, amphib gear ctrl, elt and hobbs 

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1430]
@dany93

This is finished. It rearranges the fg1000 panel features of the fg1000-KAP140 and to a lesser extent the FG1000-GFC. Also finishes some interior lighting effects that were missing, including...

KAP140
Amphibian Gear Control
Amphibian Gear Control Breakers

Both dome lighting lightmaps and rheostat material panel lighting.

Ready to merge.

**Comment by wlbragg** [comment]
Make sure Bat switch to on and the gear control breakers are pushed in (right below the gear control).

The dome lights need Bat switch to on, Cabin Pwr12v switch on panel to on, both knob on the ceiling (by the light) turned up.

**Comment by wlbragg** [comment]
I am not sure that the amphibian gear is starting up with the gear extended? I know I had it start up several times with the gear retracted. So I need to fix that here I guess before we merge. Beware, it does seen to take a few seconds to knotice the gears are moving after throwing the gear lever.

**Comment by dany93** [comment]
>Make sure Bat switch to on and the gear control breakers are pushed in (right below the gear control).
The dome lights need Bat switch to on, Cabin Pwr12v switch on panel to on, both knob on the ceiling (by the light) turned up.

With these switches "ON", everything is right.
But I had never noticed this. I guess all of them are usually "ON" with Autostart (they should).

**Comment by wlbragg** [comment]
Two more things.

All variants...
I think we need to change the amount of time it takes to drain the battery with certain conditions. I was sitting here with the sim running and the amphibian on the runway, not running but with the dome light set to full on. I got distracted for a few minutes and when I came back the battery was dead. I think you should get way more than a few minutes out of a battery using only the dome lights. I want to research and revisit the battery drain logic.

FG1000 specific...
Speaking of battery, I know the emergency bat system is supposed to click on if there is a disruption to the main bat system. So would that include draining the main battery? If so I need to actually add some logic to trip the stby bat when power is not coming from the main bat. I didn't really write any system for the stby bat other than it is powered and recharged. It's still on the todo list. I needed more research on how it works.

**Comment by dany93** [comment]
>Speaking of battery, I know the emergency bat system is supposed to click on if there is a disruption to the main bat system. 

I don't know. But in the G1000 manual (p.14) I read:

> **Reversionary Display Operation**
> In the event of a display failure, the G1000 System automatically switches to reversionary (backup) mode. In
reversionary mode, all important flight information is presented on the remaining display in the same format
as in normal operating mode.

However, I think you are going too far, to a system excessively complicated taking into account its importance in our context.

**Comment by wlbragg** [comment]
>I think you are going too far, to a system excessively complicated taking into account its importance in our context.

I was thinking about it in the context of the failure system.

**Comment by wlbragg** [comment]
I did some digging and I am using a amp draw of 3.6 per dome light, which may be a little high, but maybe not. According to my understanding calculates to around 4 hours on a 30Ah battery which is what I am using in the fg1000. So i am going o dig into the electrical again and see where the extra drain is.

**Comment by wlbragg** [comment]
@dany93 

I'm done with this. I found some issues that must have happened with the  "Effects and Material animations must come after knob animation" PR. That PR broke the radio lighting dimmer knob for the kap140, dme and kr87 in the default c172p. I happened to notice it when I was doing the fg1000 instrument lighting. It's all fixed now as far as I can tell. What wasn't working, was the dimmer knob wasn't dimming the digits or the button lighting. We set it up a long time ago so that when you turned down the intensity of the lighting on the radio stack instruments, once you got to all the way to the lowest setting the buttons on all the instruments would not be illuminated but the digits would be. The effect for the digits was you could dim and brighten them, but you could never turn them down so far that you could no longer see them. For example, if you start at full brightness and you start turning the brightness down, when it got to 0 the digits would turn back on to a bright setting instead of going off. That functionality was broke on those instruments, now its working again.

Also, I screwed up a while back and reverted a merge you did ("Effects and Material animations must come after knob animation"). I thought I reverted the revert, but I noticed in the logs I was getting all those error messages about the material and effects animation duplicating the knob rotations. So I checked master and sure enough, that PR was no longer a part of master. So I reverted the revert and all is well. I just wanted you to know in case you get any strang conflicts when pulling from master. If you do, you may have to start over and just pull a completely new and fresh master. But the commit history is preserved and everything is correct.

So, as I said in the beginning, I am done with this and your free to merge.

Oh, one more thing, I started to change the color of the kr87 digits to match the kap140 in the fg1000. But then I noticed it was the kap140 that didn't match any of the instruments in the default aircraft so I changed the kap140  to match everything else. Not a big deal, I just thought it looked funny to have different colored instrument digits.

**Comment by dany93** [comment]
> So I reverted the revert and all is well. I just wanted you to know in case you get any strang conflicts when pulling from master...

I git pulled an update into my master from origin/master ( 8bb5f554eb ) and everything is clean. I no longer get the "material and effects animation duplicating the knob rotations" in the terminal.

**Comment by dany93** [comment]
Only tested on the default aircraft:
- The "Instrument lighting" knob works as expected. By the mouse scroll wheel or the horizontal displacement.
- "Radio lighting" effect:
The displayed values (%) change as expected, by the scroll wheel or the vertical displacement.
Effect on lighting:
Oil Temp / Pressure and RPM change as expected.
But it is a bit weird for the NAV /COM instruments (COM, ADF, DME, AP). If I displace downward or scroll for down, the illumination decreases (as expected), then increases again. Despite the value (%) remaining at 0. There is an issue when the value (kind of) goes through 0 then below.

I can more or less get what I wish but I often have to fiddle a bit.

**Comment by wkitty42** [comment]
On 8/1/23 10:12 AM, dany93 wrote:
> I can more or less get what I wish but I often have to fiddle a bit.


with ALS or no?

ISTR some difference with lighting depending on if ALS was used or not... like 
the gauge lights would be black or very dark without ALS unless one of the 
rendering sliders was set to a certain point... i think... thus my question "ALS 
or not"...

i guess i should also add "what are your rendering sliders set to?" because they 
may play into this...

**Comment by dany93** [comment]
> On 8/1/23 10:12 AM, dany93 wrote:
 I can more or less get what I wish but I often have to fiddle a bit.

[wkitty42](https://github.com/wkitty42) wrote
>with ALS or no?

With ALS "ON".

**Comment by dany93** [comment]
On FG1000 kap140 variant:
Same issue with STBY knob.
For the ADF lighting. If I displace or scroll for down, the ADF illumination decreases (as expected), then increases again. Despite the value (%) remaining at 0. There is an issue when the value (kind of) goes through 0 then below.

No issue for the "steam" (round) instrument lighting.

**Comment by wlbragg** [comment]
>But it is a bit weird for the NAV /COM instruments (COM, ADF, DME, AP). If I displace downward or scroll for down, the illumination decreases (as expected), then increases again. Despite the value (%) remaining at 0. There is an issue when the value (kind of) goes through 0 then below.

That is the correct behavior. That's what I tried to explained in my post. I don't remember who originally discovered that it needed to be that way and set it up. I just know it was either report or researched that it needed that odd behavior. I'm sure the discussion is in the closed issues somewhere.

So what your seeing is the expected behavior as far as it was programmed. It might be nice to verify the behavior is accurate to the real life behavior. I assumed it was a real life behavior back when it was first introduced.

**Comment by wlbragg** [comment]
Oh wow, I just caught a mistake we made back then or there is another breakage.

>The engine instrument cluster (if post lights are installed), radio equipment, and magnetic compass have integral lightning and operate independently of post or flood lightning. 

The magnetic compass, we missed it or it is n longer working.

What you should see overall is as follows.

When you displace the instrument lighting knob the following should be affected...
engine instrument cluster (that was defined later on to be the oil temp/pressure and the rpm gauge)
radio equipment (radio stack)
magnetic compass
This "special" set of equipment  lighting is referred to as **INTEGRAL LIGHTING**. 
I don't think the magnetic compass is hooked up to the integral lighting any longer (I'll fix that)

At 0% instead of turning the radio lights completely off we have the "special" daylight configuration, so that the digital displays of all radios are at maximal intensity, but no backlight is activated on the buttons.

**POST LIGHTING** is the glowing of all the gauges on the panel, not any of the radio stack.
Right or wrong we have post lighting also illuminate the engine instrument cluster with integral lighting.

**Comment by dany93** [comment]
@wlbragg wrote
>That is the correct behavior. That's what I tried to explained in my post

Now, I understand. Sorry and thank you.

**Comment by wlbragg** [comment]
I am going to add the magnetic compass integral lighting and then you can merge.
![c172p-lighting](https://github.com/c172p-team/c172p/assets/11069680/abcab934-afb1-4c1d-8f6b-b44853c8430c)

**Comment by dany93** [comment]
OK, whenever you like.
Thank you for your explanatory pictures.

Do you know the meaning of "Post" in "Post Lighting"? Like the lampposts on the edges of a garden?

**Comment by wlbragg** [comment]
No, not really, other than I am pretty sure they are bulbs in the casings of the gauge itself. I finished fixing the magnetic compass lighting. I'll push it here shortly.

**Comment by wlbragg** [comment]
It's done, ready to merge.

**Comment by wlbragg** [comment]
@wkitty42 cool, thank you for that. Should we model the post, ha, just kidding!

**Comment by callahanp** [comment]
I've bought a KI225 ADF indicator on ebay, which I took apart to see how
the bezel was constructed.  This revealed how the lighting works on the
instrument.

There are two lamps, not one, in the upper corners, about .927 inches from
a vertical center line, and 1.375 from a horizontal center line.  An
acrylic prism behind the front glass lens reflects light from the lamps
onto the dial and illuminates the airplane graphic on the front side of the
outer prism.  I can post 3d models and drawings of the bezel and the outer
lens and prisms on the flightgear wiki if anyone wants to see them.

-Pat
