### ISSUE TITLE
Exiting sim saves persistent variant data which loads on next startup regardless of variant selected

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1435]
@wlbragg 
I got this several times at launching (10 or more, with some changes in the method).
The aircraft appears like this
(for the first one, I guess that I checked "Spawn at seaport if available" after the sim start)
![c172p-bug-launch2](https://github.com/c172p-team/c172p/assets/11994061/f3d75bb3-45ef-4a66-a7f1-0fe52888fcc6)
![c172-bug-amphib-launch3](https://github.com/c172p-team/c172p/assets/11994061/bd7c0418-d340-4eff-9ed4-a1c852d38c21)

At least one way to get it:
("Save state of aircraft between sessions" is **unchecked**)
- Launch with --aircraft=c172p
- Select amphibious,
- "Go Now"
- Quit
- Again, Launch with --aircraft=c172p

The 3D model is the default one in accordance with --aircraft=c172p, but the FDM contact reference is the amphibious one. As displayed in the GUI.

**"Go Now" seems to be the way to repeatedly get the bug.**

Not blocking, can easily be recovered (in the sim) by selecting "Default" if above ground, or by selecting "Float" if above water.

Akin to this observation ([this message](https://github.com/c172p-team/c172p/issues/1433#issuecomment-1665898050))
@dany93 wrote
>Once, from ground to ground relocation the amphib floats appeared in a first step drowned in the ground, with "Default" option checked in the GUI. However, back to correct after selecting the Amphib option in the GUI.

**Comment by wlbragg** [comment]
The issue is in mooring.nas and the persistent data system.

It is used for a couple different user selected actions.

It has a listener that fires on /sim/signals/fdm-initialized to check for controls/mooring/automatic and controls/mooring/allowed. If those flags are set to true the aircraft is configured for water landings and takeoffs, which means the property fdm/jsbsim/bushkit is set to either 3 or 4 and there is an associated water port to the startup ICAO.
If this is all true the fdm/jsbsim/bushkit property is cached (aircraft.data.add("/fdm/jsbsim/bushkit");)  and the fgcommand("reposition") command is issued so the aircraft restarts and you are started at the water port.

When using the Go Now button the exact same conditions are met and the same actions are taken.

The problem is arising because in both cases the property fdm/jsbsim/bushkit is cashed. On the next load if you select any variant other than the last session, the cached data fdm/jsbsim/bushkit overwrites the current variant the user selected selected and while the variant set file =sets up for one thing the cached data is set for something else.

There is no easy answer for this. If you allow the saved fdm/jsbsim/bushkit to determine the loading then the variant you select means nothing.
But if you select a variant, currently in the above situations, the cached data is overriding the users intent.

**Comment by dany93** [comment]
@wlbragg 
Partially fixed, correct for this procedure = my last one, previously giving the bug)
> - Launch with --aircraft=c172p
> - Select amphibious,
> - "Go Now"
> - Quit
> - Again, Launch with --aircraft=c172p

But with this procedure (Including "Go to airport"):
 - Launch with --aircraft=c172p
 - Select amphibious,
 - "Go Now" (--> correct, amphib on water)
 - Select Airport
 - Go to Airport
 
"Go to Airport": done from KSFO (water) to another airport (LFOH) or back to KSFO (tarmac).
 gives amphib on the tarmac partially drown in the ground.

![c172-bug-gotoairport](https://github.com/c172p-team/c172p/assets/11994061/597f4c11-e76b-4e3f-869a-078150861822)

**Comment by wlbragg** [comment]
I didn't test that, this may be more difficult.

**Comment by wlbragg** [comment]
@dany93 

OK, I think this is pretty well solved. The exception is the fg1000 variants. They actually work the same way and are repositioning and reinit correctly, but the frame rate appeared to drop drastically on either a reinit or reposition of the fg1000, regardless of the undercarriage. I think maybe it is not clearing the original instance of the fg1000 and thus loading it 1, 2, or more times, each time you reinit/reposition it is duplicating itself. Maybe you can verify that noted behaviour. I only tried it a couple times and that was the impression I got.

So if you have a chance you can test all you did before and verify that those parts are corrected. In the meantime I will take a look and see if there is a way to clear out the existing fg1000 system if a reinit/reposition occurs. If indeed that is what is going on.

**Comment by dany93** [comment]
@wlbragg wrote
>So if you have a chance you can test all you did before and verify that those parts are corrected

Tested. My [procedure above](https://github.com/c172p-team/c172p/issues/1435#issuecomment-1669176728) with "Go to Airport" works (the aircraft appears on the tarmac, correct on its wheels with the amphib).
Otherwise, the procedure with "Go Now", "Quit" and launch again (which worked) still works.

I will test the FG1000 with relocation.

**Comment by wlbragg** [comment]
Go ahead and merge, I'll do another issue for fg1000 issue.
Thanks!

**Comment by dany93** [comment]
@wlbragg 
I think that merging this work under this issue title would be better. It is solved, it was not a FG1000 issue.

After that, either reopening the https://github.com/c172p-team/c172p/issues/1421 issue or opening a new issue. At your preference, if you feel the work to do now can go under the https://github.com/c172p-team/c172p/issues/1421 title.

**Comment by wlbragg** [comment]
I'm going to create a new issue and PR for the fg1000. I think I already fixed it. I think it will be cleaner to do it as a new issue. The https://github.com/c172p-team/c172p/issues/1421 thread was quite long and complex.

I'll have it posted and the PR pushed shortly after I test myself. I can't be confident that I get the old cache bug as sometimes I didn't have it. So you will need to verify that I didn't reintroduce the old issue.

**Comment by wlbragg** [comment]
@dany93 

In case of any confusion, I am done with all of it. Both PR's should be ready to go. Push order would be the PR associated with this issue https://github.com/c172p-team/c172p/pull/1436 then https://github.com/c172p-team/c172p/pull/1438

**Comment by wlbragg** [comment]
This should have closed automatically, I formatted the auto-close on PR #1436 incorrectly. 

It reads Fixes issue #1435
Should have read Fixes #1435
