### ISSUE TITLE
Save/restore  system not working

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1441]
The save/restore system is broken because of a few properties that are only valid under certain variant applications. Needs type checking of some properties per variant for fg1000 vs non glass variant.

**Comment by dany93** [comment]
With my current understanding, I don't see what I can check....

Unless you prefer otherwise, I let you decide to merge or not.

**Comment by wlbragg** [comment]
It was not functioning before and now it does, so that is good enough for me. I'll merge, thanks.
