### ISSUE TITLE
Cowl plugs are non-operable

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1444]
The cowl plugs option in the GUI isn't working because the conditions for using it are not met. There are two conditions
engines/active-engine/running = false
engines/active-engine/rpm = 0

Even under cold and dark aircraft conditions the rpm is reading positive. It is actually winding up slowly starting somewhere around 0.00273...... 

So to repair the bug, engines/active-engine/rpm = 0 needs to be changed to engines/active-engine/rpm< 1

**Comment by dany93** [comment]
Can you read [my message](https://github.com/c172p-team/c172p/issues/1398#issuecomment-1675830952) here?

**Comment by wlbragg** [comment]
@dany93 

The "Repair" button uses the following conditions to enable it

/gear/gear[0]/rollspeed-ms < 1.0
not /engines/active-engine/running
/engines/active-engine/rpm = 0

So I am afraid it would fail under the same condition the cowl plugs failed on.
Also the /gear/gear[0]/rollspeed-ms would be failing if it were = 0 because it is also oscillating at a micro level.

The cowl grill will also use these type of conditions.

I propose any GUI options with the enable option using these types of properties be changed to...

/controls/switches/magnetos = 0
/controls/switches/master-bat = 0
/controls/switches/master-alt = 0

or even more simply

not /engines/active-engine/running

if we want a hard option to undeniably deny activation under certain conditions it is going to require some overkill, so to speak.

To use WOW we have to check for as many as 25 different gear configurations, if you use every possible wheel. You could reduce that to maybe 5 or 6 if you use only one wheel of any individual type of undercarriage variant.
If the WOW is true, the rollspeed is always oscillating < 1 or slightly, even with the parking brake on.
So regardless, it's not an = 0 but a < 1
Same issue with the RPM always oscillating at a value something less than 1

We could write a filter to account for any or all the above and still use just one output property?

But is this overkill when we can simply use
not /engines/active-engine/running
or
/controls/switches/magnetos = 0
/controls/switches/master-bat = 0
/controls/switches/master-alt = 0

**Comment by dany93** [comment]
>The "Repair" button uses the following conditions to enable it
(...)
So I am afraid it would fail under the same condition the cowl plugs failed on.

I never noticed this issue by using "Repair".
At worst, it can be worked around by unchecking "damage".

**Comment by wlbragg** [comment]
Handeling in #1398
