### ISSUE TITLE
KAP140 uses same static port as the exterior port, configure static ports

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1447]
@hbeni  @HHS81  @dany93 

Does the KAP140 have its own internal sensors? If so then it should not be using static[0]/pressure-inhg[0] as it appears to be. It should use it's own isolated port.
Or the aircraft instruments and the icing system should use static[1]/pressure-inhg[1].

It appears we are adding a "mythical" interior static port static[1]/pressure-inhg[0] to the system when in reality that should be the port the AP is using.

Otherwise the AP is also being iced during an icing condition and we never switch it off the bad port as it is hard tied to static[0]/pressure-inhg[0]

We use /systems/static-pressure-inhg-selected for instruments but as far as I can tell we are still using static[0]/pressure-inhg[0] for the KAP140.

Also  "Alternate source is from cabin, see POH p. 7-42" does anyone know where this reference came from and exactly what it is referring to? Is it meant to be the AP or something else?

See
~~~
    <static>
        <name>static</name>
        <number>0</number>
        <tau>0.1</tau>
        <!-- Side-slip angle influence only. Type 2 will also give AoA
             influence. See Docs/README.systems.
        -->
        <type>1</type>
        <error-factor>0.2</error-factor>
    </static>

    <static n="1"> <!-- Alternate source is from cabin, see POH p. 7-42 -->
        <name>static</name>
        <number>1</number>
        <tau>0.1</tau>
        <type>0</type>
        <error-factor>0.35</error-factor>
    </static>
~~~

**Comment by wlbragg** [comment]
That leads to another potential issue. The GFC700 also most likely is using port 0, I hope it is configurable if it also has its own sensors. I'll have to ask Stuart about it.

Maybe it is easier to change the aircrafts exterior port to 1 and also the icing system to act on port 1 VS 0?

**Comment by hbeni** [comment]
> Also "Alternate source is from cabin, see POH p. 7-42" does anyone know where this reference came from and exactly what it is referring to? Is it meant to be the AP or something else?

IIRC I found that i the POH of the C182s when I implemented this.
The port is somewhere inside the cabin (where exactly I don't know, but otoh I think it does not matter much - the main point is: its susceptible to the venturi effect (which the 182 models).

If the KAP uses a built in static port or not, I don't remember currently. I would say no, as I configured it to use the planes static system[1]: `systems/static-pressure-inhg-selected` in `kap140-config.xml`.
Mabye we should revisit the kap handbook, but I'm pretty sure I did this. And I rmember the handbook says, you are not allowed to use the KAP with the alt-static-air knob pulled.


----
[1] https://github.com/HHS81/c182s/blob/master/Systems/static-sources.xml

**Comment by dany93** [comment]
@wlbragg wrote
>Also "Alternate source is from cabin, see POH p. 7-42" does anyone know where this reference came from and exactly what it is referring to?

I see Alternate **static** (pressure) source, POH 180hp  p. 5-10, 7-11, 7-41. I understand it as a **static pressure intake inside the cabin** (center panel). It is in case the main static source (outside) in clogged. 
The pitot pressure (dynamic) needs such a static source, normally outside. The altimeter and VSI normally use this same source. In case yhis source is clogged, the alternate static source is used.
(I'm wandering: do I understand well your question?)

**Comment by hbeni** [comment]
> If the KAP uses a built in static port or not, I don't remember currently.

Regarding the questoin I quickly grepped the git log and found [commit 780929b81](https://github.com/HHS81/c182s/commit/780929b81) which answers that question.

> Date:   Fri Mar 5 20:41:58 2021 +0100
>     KAP140 uses airplane's static system (source: Bendix installation manual, chapter 2.3.2 on p. 2-2)

**Comment by wlbragg** [comment]
p.s. 

>And I rmember the handbook says, you are not allowed to use the KAP with the alt-static-air knob pulled.

If this is true, then we aren't conforming to the POH?

**Comment by wlbragg** [comment]
CAUTION
For two axis installations the static port on the rear of the
KC140 is designed to float to ensure alignment with the static
port on the mounting rack. Do not attempt to tighten the
mounting screws for the KC140 static port.
WARNING
FOR TWO AXIS INSTALLATIONS REMOVAL OF THE KC 140
FROM ITS MOUNTING RACK IN THE AIRCRAFT PANEL OPENS
THE STATIC AIR SYSTEM TO THE AIRCRAFT CABIN. AFTER
REINSTALLATION OF THE KC140, VERIFY THAT THE STATIC
AIR SYSTEM COMPLIES WITH F.A.R. 91.411.

Sounds like its own port to me?

**Comment by wlbragg** [comment]
According to chat GPT (3.5)

Does the kap140 have its own static port?

No, the KAP 140 is an autopilot system developed by Bendix/King (now part of Honeywell). It doesn't have its own static port. The static port is a component of the aircraft's pitot-static system, which provides air pressure information to various instruments in the aircraft, including the altimeter, airspeed indicator, and vertical speed indicator. The autopilot, like the KAP 140, utilizes this data from the pitot-static system to perform its functions, but it doesn't have its own dedicated static port. It relies on the accurate air data provided by the aircraft's pitot-static system.

Can it use the alt tatic port system?

The KAP 140 autopilot system, as of my last update in September 2021, does not have the capability to directly use an alternate static source. The alternate static source is typically used by pilots in case the primary static source becomes blocked or contaminated, affecting the accuracy of the pitot-static instruments. It's primarily used for manual flying and instrument reference.

The KAP 140 autopilot relies on the aircraft's pitot-static system to receive accurate airspeed and altitude information, which it uses for its autopilot functions. If the aircraft's pitot-static system is compromised, it can impact the accuracy of the data the autopilot receives and potentially affect its performance.

How does it hook into the pitot system?

The KAP 140 autopilot system interfaces with the aircraft's pitot-static system through its control and interface wiring. It doesn't have a physical connection to the pitot tubes or static ports themselves but rather receives airspeed and altitude data through the aircraft's avionics and sensor systems.

Here's a simplified explanation of how it typically works:

    Airspeed Data: The autopilot receives airspeed information from the aircraft's airspeed indicator (ASI), which is part of the pitot-static system. The ASI measures the difference between the ram air pressure from the pitot tube (which senses dynamic pressure due to the aircraft's forward motion) and the static pressure from the static port (which senses atmospheric pressure). This information is processed by the aircraft's avionics and sent to the autopilot.

    Altitude Data: The autopilot receives altitude information from the aircraft's altimeter, which is also part of the pitot-static system. The altimeter measures the atmospheric pressure at the aircraft's current altitude and converts it to a display of altitude. This altitude data is used by the autopilot to maintain a desired altitude during its operations.

The KAP 140 autopilot uses this airspeed and altitude data to perform functions such as maintaining a specific altitude, capturing and tracking a selected altitude, holding a specified vertical speed, and following programmed flight paths, among other capabilities.

It's important to note that the specific wiring and interfaces can vary depending on the aircraft and avionics configuration. Pilots and technicians should refer to the aircraft's and autopilot's documentation for detailed information on installation, wiring, and interfacing procedures.

So if it interfaces with the aircraft's pitot-static system through its control and interface wiring, then when you use the alt static port switch which those systems, it also would be effectively using the alt static port information as well, correct?

Yes, you're correct. If an aircraft has an alternate static source (often referred to as the "alternate static air" switch), and the switch is activated, it can affect the air data received by both the aircraft's instruments and any systems that interface with the pitot-static system, including the KAP 140 autopilot.

When the alternate static source is selected, the system bypasses the primary static port and uses an alternate source for static pressure. This is typically used when the primary static source becomes blocked or is otherwise unreliable due to factors like ice accumulation or other obstructions. The alternate static source is usually located in a less vulnerable position on the aircraft.

So, if the alternate static source is selected, both the aircraft's instruments and the KAP 140 autopilot would use the alternate static pressure for their calculations. This could affect the accuracy of airspeed and altitude data, which could, in turn, impact the autopilot's performance in maintaining altitude and airspeed. Pilots need to be aware of these effects and the appropriate procedures for using the alternate static source.

**Comment by wlbragg** [comment]
And the kicker!

**Why does the manual refer to the following if it doesn't have its own static port?
 "For two axis installations the static port on the rear of the
KC140 is designed to float to ensure alignment with the static
port on the mounting rack. Do not attempt to tighten the
mounting screws for the KC140 static port."**

I apologize for any confusion caused. It seems I might have provided inaccurate information in my previous responses. Based on the information you've provided from the manual, it appears that the KAP 140 might indeed have a static port or at least a reference to a static port alignment.

The specific details of the KAP 140's installation and interface with the aircraft's systems can vary depending on the model of aircraft and avionics configuration. If the manual mentions a static port on the KAP 140 unit and provides instructions for its installation and alignment, it suggests that the autopilot does indeed interface with the aircraft's pitot-static system in some way.

In light of this information from the manual, I recommend following the instructions provided in the manual for proper installation and alignment of the KAP 140 unit's static port. If you have access to the aircraft's documentation and the KAP 140 manual, you should refer to those resources for accurate information about how the autopilot interfaces with the pitot-static system and any related components.

**Comment by wlbragg** [comment]
https://www.reddit.com/r/flying/comments/7zcl4m/cessna_172s_nav_iii_static_ports/

Still looking!

**Comment by wlbragg** [comment]
Definitive proof from the KAP Pilot's Guide
https://www.bendixking.com/content/dam/bendixking/en/documents/document-lists/downloads-and-manuals/006-18034-0000-KAP-140-Pilots-Guide.pdf 

pg.14

KC 140 Two Axis
Computer/
Controller/
Annunciator 
contains computer
functions, mode
control buttons,
and annunciations
in a single unit.
Also contains
static pressure 
sensor and 
accelerometer.

**Comment by wlbragg** [comment]
It looks like the Single Axis may not have a static port? Maybe that is where all the confusion comes from? We are using the Two Axis version?

**Comment by wlbragg** [comment]
I'm really leaning towards 3 static ports.

KAP140 uses its own isolated port with a static-pressure-inhg-venturi value.
The aircraft instruments use the exterior and a seperate interior port with its "static-pressure-inhg-venturi value" for the alt system.

**Comment by wlbragg** [comment]
Actually you can just use /systems/static[1]/pressure-inhg-venturi for the AP. It would be the same number as doing a seperate port 2 and deriving the pressure using the same venturi function. If you have failures for the static ports, then you might want a 3rd port.

**Comment by wlbragg** [comment]
Something else, we are changing the error rate of the static port on the interior port, I assume that was for the same reason you eventually made a venturi effect filter. It seems like that is a duplicate effort?

**Comment by hbeni** [comment]
Iirc i have read the manual and found that the kap140 connects to the planes static system. Did you check the manual reference i provided?

The ventury effect is caused by air flowing around the plane, which alters the pressure by airspeed. This will also affect altimeter, vs and airspeed readings on the respective gauges when alt-static-port is in use. Hence the correction table in the planes poh.
Just hook all instruments to a „selector“ property and use a filter or so to decide which of the source is used (either the rxternal one or the one from the cockpit, with the venturi effect applied). This is all already modelled correctly in the c182.

btw airspeed: chatgpt is wrong, the kap140 has no clue how fast the plane is going.

**Comment by wlbragg** [comment]
>Iirc i have read the manual and found that the kap140 connects to the planes static system. Did you check the manual reference i provided?

Yes I did and the only mention I could find [is what I posted](https://github.com/c172p-team/c172p/issues/1447#issuecomment-1686776767). Which really isn't clear.

Did you look at the [Pilots Guide](https://github.com/c172p-team/c172p/issues/1447#issuecomment-1686822220) straight of their website? It definitively states the Two Axis AP has its own static port.

>The ventury effect is caused by air flowing around the plane, which alters the pressure by airspeed. This will also affect altimeter, vs and airspeed readings on the respective gauges when alt-static-port is in use

As far as the interior static error setting being different than the exterior port, can you explain why, I don't think your understand what I am questioning. You change the interior port error setting, why? You also use the venturi filter on it, not on the exterior port, only on the interior port, again, why? I submit, it may be a mistake, like originally someone used the error change to simulate the venturi effect on a static port inside the cabin. Then later on someone actually made a filter and computed the effect using the venturi filter? Please consider? Why both?

**Comment by hbeni** [comment]
Sorry, may have sounded rude… was not my intent (typing from phone and its late)

I made the venturi effect to precisely simulate the expected effect. I think it is not the same as an error value.
And only the cockpit port shows the venturi effect, not the exterior one(s). (Btw the exterior port also is sensitive to other things like slip, which the interior one is not). trying to simulate vebturi with the error in the outside port is wrong imho.

**Comment by wlbragg** [comment]
Also, don't forget you mentioned 
>And I rmember the handbook says, you are not allowed to use the KAP with the alt-static-air knob pulled.

As it is right now, that is effectively what happens if you pull the alt static knob. Unless you know not to use it, it is still connected to that system and is indeed what will be used.

**Comment by wlbragg** [comment]
Thank you for taking the time to try to explain .I can tell by a couple of your replies I have not been clear. I will attempt to be precise.

>The venturi effect comes from air flowing around the cabin, producing a pressure offset somewhat proportional to airspeed.

I was understanding what it is was all along. That is why I am questioning the error value, because I can't think of any other reason for it other than it is a cheat for simulating the venturi effect.

>(Btw the exterior port also is sensitive to other things like slip, which the interior one is not). trying to simulate vebturi with the error in the outside port is wrong imho.

I agree, I was in no way trying to suggest otherwise. I was only trying to understand why there was both an error value and a venturi calculation. We know why the venturi effect was modeled It is for cabin differential pressure and is correct in my opinion. If you have no recollection as to why the error value is added though I submit it may have been added originally because of the potential inaccuracy of a port in the cabin (ie: cabin differential pressure). If so, then I think the error value might not be appropriate. I probably won't change that opinion unless I have reason too, as in a good explanation as to what the error value is for.

Regarding the static port to use.

The older analysis you refer to is interesting. I am getting old, not remembering those detailed discussions is a bit off putting.
After going through the discussion again, I feel better about the choice but once again I didn't see anything really definitive, only vague clues.

We know there is a static port on the Two Axis, why is it there (rhetorical)? It could be for installations where there is no exterior port available. Other information does indeed sound like the KAP is connected to an alternate source, not alt static, but an exterior to the KAP's sensor.
I did some more searching and it is clear that autopilots in general are hooked into various external static port configurations. That alone makes me more comfortable with this decision. 

Thanks again for taking your time to explain what we have discussed before, it takes me forever to search for and bring forward past information. I appreciate it. It is interesting that this question resurfaced because I was looking at it from the perspective of the first time analyzing the system. From the same place you so graciously pointed me to when you did it for the first time as well.  We both had the same questions and landed on slightly different opinions. Which you have swayed my opinion to land closer to yours.

So the only item left I would like to put to bed is...

Please consider the venturi VS error argument I make again, and if you know, try to explain what you think the error value might be for? If you don't know why it was added, do you know who added it?

Thanks for your patience! I get that this may be over analyzing something not entirely significant.

**Comment by dany93** [comment]
@wlbragg, @hbeni 
Thank you @hbeni for your patience.

I see one or two items where I can try to explain, not add more to your explanations, @hbeni, just explain differently. 
Just tell me if I add trouble, I will stop.

@wlbragg wrote
>We know there is a static port on the Two Axis, why is it there (rhetorical)? It could be for installations where there is no exterior port available

There is no static port on the OneAxis, it doesn't need it. Just a compass information.
There is **one** static port on the Two Axis, which does need information on altitude (based on pressure).

[The Aircraft Pitot Static System : Pressure Instruments](https://aerotoolbox.com/pitot-static-system/#pressure-instruments)

The KAP 140 static port **input** is connected to the **aircraft static port** (sensor). The same as the other instruments, same tube and pressure. Normally, the "alternate" valve is such that the aircraft **external** static port is the one connected.
If the aircraft external aircraft static port has a failure, you switch the valve for the alternate (internal) static port. The instruments give informations prone to errors due to the Venturi effect. In this case, he KAP is also connected to the alternate source: you should not use it, or you are informed that it's at your own risks.

@wlbragg wrote
>I was only trying to understand why there was both an error value and a venturi calculation

In the current explanations, I see no other error than the Venturi effect. If the aircraft manufacturer gave you an altitude calibration chart, you can use it to correct your instrument readings. It gives the error due to Venturi. The KAP140 can be lost, it must not be used even if it has an information.

**Comment by hbeni** [comment]
> If so, then I think the error value might not be appropriate. I probably won't change that opinion unless I have reason too, as in a good explanation as to what the error value is for.

I agree.
To add, I really now wonder why we have an error value at all. What does it do? And why do we need it?
Shouldnt we set the error for all ports to zero?

**Comment by wlbragg** [comment]
>That should maybe be our next step: find out what that error item really does (source code?)

Yes, that was my thought as well.

**Comment by hbeni** [comment]
Looking at https://sourceforge.net/p/flightgear/flightgear/ci/next/tree/src/Systems/static.cxx

There is also a wiki entry: https://wiki.flightgear.org/FGproperties/Systems/static

-The error factor seems to just affect type=1 and type=2 static ports
- type=0 (i used that for the internal port) is always „perfect“ ie. error=0
- error just gets applied as product to the final value
- tau parameter configures the responsiveness of the filter (so should be higher for the internal port?)

**Comment by davidmegginson** [comment]
In any case, you can probably ignore it for the KAP-140 for now, and play with it later. If the KAP reads its own pressure from inside the plane (like some transponders do), then than should be modeled as a separate static system.

Note also that the KAP-140 is a rate-based autopilot, so it needs to react differently in the lateral axis than attitude-based autopilots. It will have a bit of a lag while it detects a change turn rate, and might also be clamped to rate 0.9 like the S-TEC autopilots were. It's very noticeable when flying -- they feel a bit sloppy (but before AHRS, rate-based autopilots were the only option that was independent of the vacuum system, so they were literally a life-saver).

**Comment by hbeni** [comment]
Hi David,
what exactly is the error property meant for?
What is its effect?

**Comment by davidmegginson** [comment]
As I mentioned, I don't remember exactly after a couple of decades. It could have been any of the reasons I mentioned in my previous comment. IRL, all static ports have errors: https://www.faa.gov/air_traffic/publications/atpubs/aip_html/part2_enr_section_1.7.html

**Comment by hbeni** [comment]
Thanks David, I hoped that you could clarify what the source code is meant to do.
https://sourceforge.net/p/flightgear/flightgear/ci/next/tree/src/Systems/static.cxx

```c++
        if ( (_type ==1) || (_type == 2) ) {
            mach = _mach_node->getDoubleValue();
            pt = p_new * pow(1 + 0.2 * mach*mach*proj_factor*proj_factor, 3.5 );    //total pressure perpendicular to static port (=perpendicular to body x-axis)
            qc_part = (pt - p_new) * _error_factor ;                            //part of impact pressure to be added to static pressure (due to sideslip)
            p_new = p_new + qc_part;
        }
```

As it looks for me like this, can you confirm?
- the code does calculate the total pressure in `pt`.
- then it calculates the difference in total pressure and the new pressure to be stored; and applies an error value to that (into `qc_part`).
- The resulting error value `qc_part` ist then applied to the final value.

In essence this `error_factor` is just an linear offset proportional to the difference; so the reading is "off" a little, and this "off" ammount is stable but proportional in magnitude to the total pressure difference.
I could imagine this to model some system-immanent-permanent-sensoring failure, but nothing dynamic like icing/blocking... we don't have a runtime prop to set the error factor, so this is static to init time (thus bound to the system itself).

-----

So my conclusion would be:
- the error factor is meant to define a sensor-specific sensing error, inherently in the system.
- We do it right how we simulate icing (via `serviceable` to block the sensor)
- We do it right how we simulate the cockpit port, except for these two minor additions:
  - venturi effect should be honor vents, doors and windows open. This should probably decrease the tau value so the filer adapts more quickly
  - with closed windows etc the tau should be a little slower than the outside port

**Comment by wlbragg** [comment]
>I could imagine this to model some system-immanent-permanent-sensoring failure, but nothing dynamic like icing

I agree. Maybe an opportunity for developers to add a known error for a particular product or aircraft.

>my conclusion would be

I agree, we still don't know why an error value is used in any of the static ports. That might have been the place for a comment on the original authors part when adding the error value. So we would know the reason for it. I would be disappointed to find out, down the road, that this was just an arbitrary decision.

**Comment by hbeni** [comment]
The wiki says:
> The "error-factor" should be between 0.2 and 0.7. Setting it to 0 equals a "perfect sensor". A setting of 1 means the whole (projected on static port face) impact pressure is applied. This is not realistic as usually there are more than one static pick-up points and so the pressure increase gets "flattened". 

But thats not directly what I would guess from the code. Or that is what this difference-calculatoin with `qc_part` is about.

**Comment by hbeni** [comment]
> Wonderful, we have a reason. But how do we apply that to an "interior" port that is not in the wind at all?

`error=0`, like already implemented implicitely by `type=0`.

----


> Does the KAP's port and internal sensor work together? Can you use only the port and not the sensor? Can you used only the sensor and not the port? I'm hung up on this because it makes a huge difference whether you use the static line or the isolated interior sensor.

I think the KAP has a static port connector on the back side. This connects to the planes static system. At the KAP side, there is a sensor, measuring the pressure on the KAPs port (so either it senses the cabin pressure, like in the warning when its not properly connected, or the pressure in the pipe, when properly connected to the system.
So, I think the KAPs sensor is _always_ used because its the technical item that can tell the KAP which pressure is there. And the port is the thing that is either connected to the static line or not.

> Is there a detailed "installation" guide and schematic for the KAP?

Yes, there is an installation manual on the net. That is where i concluded the above information from.
(see the link in: https://github.com/HHS81/c182s/pull/379#issuecomment-791627709)

**Comment by wlbragg** [comment]
>so either it senses the cabin pressure, like in the warning when its not properly connected, or the pressure in the pipe, when properly connected to the system.

I had that thought as well, It is as good an explanation as any.

I didn't look at the code and what you posted didn't show it. type=0 excludes the error value from being computed? If so, changing the error-factor to 0 instead of leaving it a 0.35, which is what it is set to now, changes nothing? Again, if so, I am changing our implementation of the interior port error-factor to 0 so there is no confusion.

**Comment by wlbragg** [comment]
I looked at the code and see type 0 excludes any of the location pressure alterations. So I answered my own question. I think the alt port error-factor should be changed to 0 just for clarity. In the case of the c172p also should be commented as this is one of the first aircraft new developers might access for examples.

**Comment by hbeni** [comment]
> I looked at the code and see type 0 excludes any of the location pressure alterations. So I answered my own question.

https://github.com/c172p-team/c172p/issues/1447#issuecomment-1689643279 :wink: 

> I think the alt port error-factor should be changed to 0 just for clarity

I think that too, and just did that for the c182.

I also increased (after playing a little with that) the lag of the sensor a little for the cabin static port (`<tau>0.3</tau>`) to approximately simulate the pressure lag adapting the cabin pressure to the outside one with closed windows/doors/vents.
