### ISSUE TITLE
Multiplayer: No Compositor lights visible

### ISSUE THREAD

**Issue by hbeni** [c172p-team/c172p#1460]
Compisitor lights (NAV, Taxi, Landing, strobe, beacon) not visible on remote planes in multiplayer

(C182s affected too: https://github.com/HHS81/c182s/issues/518)

**Comment by wkitty42** [comment]
On 11/2/23 7:17 AM, Hbeni wrote:
> Compisitor lights (NAV, Taxi, Landing) not visible on remote planes in multiplayer
> 
> (C182s affected too: HHS81/c182s#518 <https://github.com/HHS81/c182s/issues/518>)

my first question is if the remote systems that do not see the lights are 
running a compositor capable FG... it may be that the "cones"(?) are transmitted 
but cannot be rendered due to lack of compositor pipeline...

**Comment by hbeni** [comment]
Yes, whitnessed it myself

**Comment by hbeni** [comment]
Hm just tested this locally, and it worked for the C172p:

![grafik](https://github.com/c172p-team/c172p/assets/13608602/e1ad0ac9-5be4-460e-b8c3-e0f832eec87e)
