### ISSUE TITLE
KX165A: Add manual squelch mode

### ISSUE THREAD

**Issue by hbeni** [c172p-team/c172p#1477]
See: HHS81/c182s#546

**Comment by hbeni** [comment]
At least there is a prop for it, and also one for signal quality. So I strongly assume yes, there is squelch support.

Will play with it soon, then we know for sure.

**Comment by wlbragg** [comment]
>One thing In want to know if the c++ code generates static with squelch=0. If not we would need some core addition.

Yes, this would make even more sense then.

**Comment by hbeni** [comment]
@wlbragg tested this.
Hearing static when disabling squelch needs a core patch; see
https://sourceforge.net/p/flightgear/codetickets/2846/
