### ISSUE TITLE
Mismatch trim wheel step size to default

### ISSUE THREAD

**Issue by hbeni** [c172p-team/c172p#1502]
When the mouse is in "flight control mode" the trim step size is `0.01` (just move the mouse wheel "one click").
This comes  from the `mice.xml` (lines 87ff) definition file of FGData.

But when operating the trim wheel using the mouse wheel in "click mode", the step size is `0.001`.
This comes from the c172s own definition of the interior animation.

I think it should be more consistent and using the FGData step size?

**Comment by dany93** [comment]
If I remember well, 0.01 step size is too coarse for a good control of the trim. At least for the aileron trim (maybe for the elevator too).

**Comment by hbeni** [comment]
I opened a PR against FGData to fix this in the core:
https://sourceforge.net/p/flightgear/codetickets/2880/

**Comment by hbeni** [comment]
> If I remember well, 0.01 step size is too coarse for a good control of the trim and letting go of the controls.

Another tought: If it is too coarse, shouldn't the FDM be tunes to respond more properly in this regard?

**Comment by dany93** [comment]
The FDM criteria is that the elevator must be able to reach the stall AoA at full deflection.
0.01 step for the trim is too coarse with this setting, the stall AoA at full deflection is a FDM constraint.

**Comment by hbeni** [comment]
My reasoning/questioning was this: If `/controls/flight/elevator-trim` is a factor 10 too coarse, then it could maybe be scaled down before handed over to jsbsim.

But im unsure If that is the correct approach.
Probably the fix to fgdata is the more correct approach.
Meanwhile James did respond and said he will merge; so I think this here can be closed.
