### ISSUE TITLE
Rudder trim: Lever travels too much

### ISSUE THREAD

**Issue by hbeni** [c172p-team/c172p#1515]
-1.0 / +1.0 are the normalized maximal values for full deflection.
The lever has 90° then.

**Comment by hbeni** [comment]
I assume this is hard wired in the FDM somewhere. 0.18 is max rudder trim, and we need only a bit of rudder to counter that.
Probably this is right, but I cant tell for sure.


I detected this when testing my joystick, where I was able to override the models rudder trim quite a bit.

**Comment by wlbragg** [comment]
If you want to adjust it to what you think or specs indicate, by all means go ahead. I added the "optional" rudder trim component and I am sure I did not look at specifications for travel of either lever or the rudder.

**Comment by hbeni** [comment]
Filed a PR that just limits the rudder-trim. Not changed the FDM trim effect as I can't tell if this is realistic.

**Comment by wlbragg** [comment]
Yeah, the only thing I would question is filter VS FDM? It may be the correct fix regardless. @dany93 are you still around for comments on this? If we don't hear from @dany93 I will go ahead and merge this. Thanks for working on it.
