### ISSUE TITLE
Magnetic Compass: Simplify

### ISSUE THREAD

**Issue by hbeni** [c172p-team/c172p#1517]
Simplify magnetic compass code to use c++ based pitch/roll values for the disc

See:
- https://sourceforge.net/p/flightgear/codetickets/2904/
- https://github.com/HHS81/c182s/pull/601

(:warning: this is exclusive to 2020.4 only, not to be backported)

**Comment by wlbragg** [comment]
@hbeni Same question here, did something chang c++ side that indicated we need to get rid of the filter for this. I don't know who or why these filters are being used?

**Comment by hbeni** [comment]
The same comment aplies; in short:

>did something chang c++ side that indicated we need to get rid of the filter for this

=> yes
