### ISSUE TITLE
Add defrost vent pattern

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#202]
We can use the fog effect overlay or mask to add a defrost pattern on the windshield to simulate defrost air hitting the windshield stronger at certain spots. This is something I eventually want to add. Thorsten gave us the ability to add this effect and to date I don't know if anyone has used it.

**Comment by gilbertohasnofb** [comment]
That would be cool!

**Comment by tigert** [comment]
There are two slots in the front of the glareshield like this:
```
|      ======              ======       |
```

..which blow air. This where a small clearing opens when you put on cabin air and the engine runs. Remember there is no blower like on cars, so if the engine is not running, nothing really happens.

When the engine runs, it pulls air from the right side of the fuselage if I remember correctly, there is a small opening "door" against the slipstream. Even if you stand still, the propeller blows in some air and it clears it, but it takes a while, so nothing like "20 seconds to clear" - more like minute or two, and even longer if there is ice.

The holes also have adjustment knobs to close / open them I guess, but they are usually just open and I've never really touched them in practice.

**Comment by wlbragg** [comment]
My first attempts to use the overlay failed. I may need some help on this one. Has anyone used the mask overlay?

**Comment by onox** [comment]
The wiki says:

> The red channel in my_mask.png controls the strength of fogging, full red corresponds to maximal fogging, no red to zero fogging. This allows to selectively model the position of heaters in the cockpit. Use /environment/aircraft-effects/fog-level to adjust the actual amount of fog runtime. 

But how do we make a difference between heaters on and heaters off? If the heaters are off, you want the [mask](https://github.com/onox/707/blob/470d20b3d0d916ec1c59f360560c348c83facdf0/Models/Effects/interior-glass-right.eff) to be red [everywhere](https://github.com/onox/707/blob/470d20b3d0d916ec1c59f360560c348c83facdf0/Models/glass-mask.png), but when the heaters are on (or in our case, heated air is redirected to the two slots) you would need a different mask where the red channel is almost 0 where the slots are. So ideally we should have two masks (when only considering the fog/frost effect) and have a property that controls the mixing.

Is that correct or am I misunderstanding how the red channel should work?

**Comment by wlbragg** [comment]
I'm not sure we will have that kind of control. My understanding is we have one mask made in such away that when the heat or air is turned on a completely fogged window will appear to defrost or defog first near the vents because the red channel is weaker there.

**Comment by wlbragg** [comment]
I actually worked on this the other day again. I made some progress but was stopped when I discovery our windows needed to be textured. When I textured them I lost the reflections. I messed around with it for a few hours and eventually gave up. I was able to texture the window and get the mask to show, but it had many issues

**Comment by onox** [comment]
I have tried to modify the mask in the 707, and it seems that the frost indeed just fades away sooner. So one mask should be sufficient then.

**Comment by onox** [comment]
(From #961) See https://github.com/c172p-team/c172p-detailed/issues/910#issuecomment-280856815

**Comment by wlbragg** [comment]
This is the mask Piper Archer CV is using for the effect

![window-mask](https://user-images.githubusercontent.com/11069680/45920655-371a8e00-be6d-11e8-8079-6c18e10b8660.png)

This is my test mask with the proper UV mapping for our windshield.
![windshield](https://user-images.githubusercontent.com/11069680/45920688-ca53c380-be6d-11e8-8f1c-8b49bbbea1dc.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg what are the name of these files, please?

**Comment by wlbragg** [comment]
Here is what I have so far. There is a plenty of room for improvement. If you want I can push  a branch with this test case so you all can mess around with it and I can also explain what I know about it and what all I think needs to be done and modified. It's actually a bit complex as to what all is involved with this.
This was the first round before I did a couple minor edits of the masks and textures.
![fgfs-screen-005](https://user-images.githubusercontent.com/11069680/45924356-baff6500-bec3-11e8-9289-0471e99e0b60.png)
![fgfs-screen-006](https://user-images.githubusercontent.com/11069680/45924357-baff6500-bec3-11e8-8345-f5fc112f939b.png)
In these next two I added some white background along with the ice streaks to get a better glare effect.
![fgfs-screen-008](https://user-images.githubusercontent.com/11069680/45924361-de2a1480-bec3-11e8-94cb-3786b1e0090f.png)
![fgfs-screen-009](https://user-images.githubusercontent.com/11069680/45924363-dff3d800-bec3-11e8-8e78-083ddb3813da.png)

**Comment by wlbragg** [comment]
I think the defrost pattern could be improved. Not only the shape but the density. Right now there is almost no color where the defrost or vent air blows. So you will never have fog or frost there. It needs to have at least some so when fog or frost is at its highest level you would have some covering that area. But then as the glass started to clear the portion that is less strong would clear first and give the effect of the air vent bowing on that spot. It's kind of hard to explain.
What was needed to do this is two textures.
This one (windshield.png) is the fog and ice mask with the air vent pattern.
![windshield](https://user-images.githubusercontent.com/11069680/45924388-bb4c3000-bec4-11e8-9575-4f43b2e12c29.png)
This one (glass-alpha.png, see the dot below this text) is the alpha layer the glass in blender is mapped to. I get no glass reflections without it. The amount of alpha transparency dictates the strength of the reflection the glass has.
![glass-alpha](https://user-images.githubusercontent.com/11069680/45924408-0ebe7e00-bec5-11e8-9206-7425bd13b6a6.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg thanks for starting to work on this. First, I am still a bit confused about the channels, are you sure that yellow image from the piper is what gives the ice effect on the glass? That image...:

![image](https://user-images.githubusercontent.com/5700795/45929081-cb0b5900-bf44-11e8-88c3-e0342c364efa.png)

... has information only in the blue channel. All pixel values in the red and green channels are both 1.0, and the blue channel has some weird marks but which are not the ice patterns, see a closeup of the blue channel only here:

![image](https://user-images.githubusercontent.com/5700795/45929098-f8580700-bf44-11e8-86de-6f349665f1fb.png)

So is the Piper perhaps combining this image above with another one in order to create the effect below?:

![](https://camo.githubusercontent.com/88eccf3f1933b334acb4ab726b87e889072337cb/687474703a2f2f7a6c73612e6769746875622e696f2f70697065722d6172636865722f696d616765732f66656174757265732f636f636b7069742d66726f73742e706e67)

Also, about the screenshots you posted such as this:

![](https://user-images.githubusercontent.com/11069680/45924356-baff6500-bec3-11e8-9289-0471e99e0b60.png)

That is looking better IMO, but it has two problems: 
1) the ice patterns are still gigantic, I think we need to scale them at least to 0.25 of their current value
2) I am not completely convinced about the 'hole' in the ice pattern just above the panel. What I like about the Piper is that the ice is present in patches all over the cockpit making it look really realistic.

**Comment by wlbragg** [comment]
Let me start by saying, like everything in programming there are usually more than one way to to a task, I think that is the case here.

>are you sure that yellow image from the piper is what gives the ice effect on the glass?

I didn't explain this very well. You are correct that the "ice pattern" does not come from the yellow image. Only the "smudging" and the overall additional "glare" on the glass. The ice effect I am relatively sure is coming from the default ice mask in fgdata.

This is the UV layout on the piper glass. 
![piperuv](https://user-images.githubusercontent.com/11069680/45930487-92f51d80-bf26-11e8-8984-25740a300988.png)

I think this is how the yellow mask would be applied. Note the windshield is upside down.
![piperuvmask](https://user-images.githubusercontent.com/11069680/45930557-49590280-bf27-11e8-91c6-6286e9e965c0.png)

I need to look at this a little closer, you have help me to see something technical I was missing and I think there is a step i am taking that needn't be done. But that doesn't change much only the part where I talk about reflection strength.

I also now understand how the ice patten is being applied on the piper. Here are the differences between the piper and what we are trying to do.

Again it is important that you understand what colors do what here.

red channel = fog (NO GLARE EVER from the fog channel)

blue channel = overlay mask
In our case the ice streaks and overall glare. Also in our case the lack of blue in an area indicates the vent pattern.
In the piper case only the ice smudge and overall glass glare.

see ALS Technical Notes...
>The blue channel of my_mask.png is reserved for an overlay pattern which will be drawn in an optionally specified <overlay-color> vector (white in the example xml above) - the primary function is to render damage on the glass, but with a different color, also dirt or an alternative more finely controlled frost pattern can be used. 

This is important to understand...
The piper is using the default ice and fog mask and thus no control over the heat vents. They are applying on top of the default ice mask some more overall blue channel noise to get more glass glare and some smudge marks.
We are "replacing" the default ice and fog mask so we can control the heat vent pattern and can do the same thing the piper does only we can control every aspect of the overlay mask layout and all its functionality. Including the ice streak shape and amount. This is where I would like help from artists group to make the mask. My test mask should give you the basics of what needs to be done.
Note: I notices some enhancements I was trying to do to my test mask ended up on the green channel and thus are doing nothing. They should have been on the blue and red channel.

Technically this is the difference in how we have control and the piper left it up to the default effect.

Piper...
~~~
<texture n="2">
      <image>Models/Effects/window-mask.png</image>
      <type>2d</type>
      <filter>linear-mipmap-linear</filter>
      <wrap-s>clamp</wrap-s>
      <wrap-t>clamp</wrap-t>
      <internal-format>normalized</internal-format>
    </texture>
    <use-mask type="int">1</use-mask>
    <overlay-color type="vec3d" n="0">1.0 1.0 1.0</overlay-color>
~~~
Piper effect says...
use window-mask.png on top of default fog and ice and display it as the color 1,1,1 (white).

c172p...
~~~
<texture n="2">
	    <image>Aircraft/c172p/Models/Effects/interior/windshield.png</image>
	    <type>2d</type>
	    <filter>linear-mipmap-linear</filter>
	    <wrap-s>clamp</wrap-s>
	    <wrap-t>clamp</wrap-t>
	    <internal-format>normalized</internal-format>
    </texture>
    <use-mask type="int">1</use-mask>
    <overlay-alpha type="float"><use>/environment/aircraft-effects/frost-level</use></overlay-alpha>
    <overlay-color type="vec3d" n="0">1.0 1.0 1.0</overlay-color>
    <frost-level>0</frost-level>
    <use-overlay>1</use-overlay>
    <overlay-glare type="float"><use>/environment/aircraft-effects/overlay-glare</use></overlay-glare>
~~~
'not" in order of calling..
use-mask =1
    I think this is just turning on the effect overall
frost-level = 0
    don't use the default ice
use-overlay = 1
    use the windshield.png overlay mask instead
overlay-alpha = use - /environment/aircraft-effects/frost-level
    use frost level property to control ice alpha
overlay-glare = use - /environment/aircraft-effects/overlay-glare
    use overlay-glare property to control glare brightness

fog is still controlled by the default effect except where the windshield.png overlay mask red channel has less than 100% red alpha. (I don't think I am stating this correct)

>notice how the glass gets bright when direct sun is hitting it on the piper. In our aircraft, it's the ice patterns that get bright.

Right again, look at the 4 screen shots I posted of my test. Compare the first two against the second two. Notice how not only the ice but more of the overall glass has glare on it in the second two. 

>the ice patterns are still gigantic, I think we need to scale them at least to 0.25 of their current value

I totally agree, I didn't say that exactly, but that is what I meant by...
>There is a plenty of room for improvement

>I am not completely convinced about the 'hole' in the ice pattern just above the panel.

We are on the exact same page here as well. That is also what I meant by...
>the defrost pattern could be improved. Not only the shape but the density. Right now there is almost no color where the defrost or vent air blows. So you will never have fog or frost there. It needs to have at least some so when fog or frost is at its highest level you would have some covering that area. But then as the glass started to clear the portion that is less strong would clear first and give the effect of the air vent bowing on that spot. It's kind of hard to explain.

In my version it is to dramatic because there will never be any ice or fog there. When the ice or fog level is at its highest there should be ice and fogging in that hole, only when the heat/air
has been blowing for awhile should you see it start to clear up in the hole first. To accomplish that the hole in the texture mask needs more red color overall and more white ice streaks, both colors fainter than what is on the rest of the glass area though so you get the effect of it thawing out as the air blows on the glass.
The pattern of the vents should be a little different as well (the black areas). This was derived from the j3cub and I think it maybe has a center vent only. I can't remember exactly but ours has two or three spaced out across the bottom.

Apologizes for being long winded but this stuff is difficult to express.

**Comment by wlbragg** [comment]
Here are all the UV layouts...
back-interior
![c172p-back-interior-uv](https://user-images.githubusercontent.com/11069680/45931568-7dd3bb00-bf35-11e8-8959-41db8d938ab3.png)
front-interior
![c172p-front-interior-uv](https://user-images.githubusercontent.com/11069680/45931569-7dd3bb00-bf35-11e8-930f-e8e28629267f.png)
left-window-interior
![c172p-left-window-interior-uv](https://user-images.githubusercontent.com/11069680/45931570-7dd3bb00-bf35-11e8-8156-6f2c6b053495.png)
right-window-interior
![c172p-right-window-interior-uv](https://user-images.githubusercontent.com/11069680/45931571-7e6c5180-bf35-11e8-9eef-ae975d653f3e.png)
sides-interior
![c172p-sides-interior-uv](https://user-images.githubusercontent.com/11069680/45931572-7e6c5180-bf35-11e8-9465-ad82422cdef7.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg thanks for all the information, I really appreciate you taking your time to explain this so thoroughly! I just have some questions about the defrost pattern: what is supposed to cause the defrost pattern in the middle of the front glass in our aircraft, is that  when the hot air lever is > 0% or is there something else controlling it? And if it's controlled by that lever, then wouldn't it be a problem to bake it directly in the mask? E.g. if the pilot has the hot air set to 0% and frost happens, shouldn't it also happen in the 'hole' that you created? Hope this makes sense.

**Comment by wlbragg** [comment]
>what is supposed to cause the defrost pattern in the middle of the front glass in our aircraft, is that when the hot air lever is > 0% or is there something else controlling it?

Technically yes. Right now the frost and fog accumulation and removal is controlled by several factors.
heat and air vents
windows and door positions
persons in the aircraft
environmental factors
So yeah, there is a bit of an issue to permanently bake vent pattern in the overly mask if your not using the heat and air to defrost/defog.
It would be considered "normal" to use the heat/air blower to clear up a fogged or frosted windshield. You would probably do so in most cases.
The air temperature change in the cabin also reduces the fog and frost overall on all surfaces. 
I guess that is a limitation of the design and we either live with the limitation or don't use the defrost effect.
Thinking about it a bit...
Let me try a couple things to see if there is anyway to switch from mask to default on the fly. That might help this case if possible.

**Comment by legoboyvdlp** [comment]
May I ask if it is theoretically possible to extend the effect to include dirt, bugs, etc using that overlay mask or are we already using all the channels? 

If so that can be added in conjunction with the dirt effect later - I can do that work myself hopefully.

**Comment by wlbragg** [comment]
Good news, we can control the "fog" portion of the vent mask selectively using it when the vents are open, but not the ice. However if we pattern the ice carefully we should be able to achieve the effect we want anyway as the ice would theoretically take more time to defrost than the fog. So even if there is still a slight layer of ice in the vent area, the fog being reduced in that area is still going to look really effective.

The blue channel is used for the dirt/broken glass, etc. so no, it won't be possible to do both and control them individually. Maybe we can use the exterior glass for dirt?

**Comment by wlbragg** [comment]
>Good news, we can control the "fog" portion of the vent mask selectively using it when the vents are open, but not the ice.

With that said it would require a hand off from no vent pattern to the effect with the pattern before the fog started to defrost or you will get a sudden jump from no vent pattern to a potentially substantial vent pattern. Some kind of coordination as to when you could switch over to the effect with the vent. Not allowing that switch if it is at the wrong time in the thawing process.
Another way to look at this is, I thought I read somewhere there is always at least some amount of air movement through the vents even when shut down. We could just assume it always is going to effect those areas that the vent air flows over.
I think we will have to see how much flexibility we have and a lot of it I think will depend on the mask and how well it is designed.

**Comment by legoboyvdlp** [comment]
> thought I read somewhere there is always at least some amount of air movement through the vents even when shut down. We could just assume it always is going to effect those areas that the vent air flows over.

That sounds similar to what happens in cars albeit thats a very very minimal flow. Since the air comes through a door in the side which would be pretty much flush with the cowling you probably wont much air at all if the air knob is pushed all the way in. 

Also, should the upper left / right vents affect the frosting / fogging? I'd imagine it would make the glass locally colder, thus increasing frosting? Not sure about fogging.

**Comment by wlbragg** [comment]
Here is a video of what I have so far.
I've created 4 of the 6 masks. I'll post all 6 when finished and please anyone that wants to modify and experiment with the masks, go for it. That is what this is for. It isn't meant to be the final product. But it is the correct layout for each one and the effect code is implemented.
https://www.dropbox.com/s/j4ox731r54wc2k1/2018-09-23%2019-27-05.mp4?dl=1

**Comment by gilbertohasnofb** [comment]
That is looking really good! But would it be too much trouble to try to make those ice patterns a bit larger again? I like the new effect but I miss seeing those, I think it's just a matter of fine tuning it. But it looks wonderful!

**Comment by wlbragg** [comment]
I just pushed everything, feel free to experiment with the masks in Gimp. You'll easily see how they are arranged. Because the glass is broken down to 6 parts you could customize different smudges and such on each piece of glass.
I left the environmental property ties commented out so you can test strengths for yourselves using...
/environment/aircraft-effects/fog-level
/environment/aircraft-effects/frost-level

@gilbertohasnofb these masks are not intended to be a final product. I think they could be much better. However with the tests I have already performed and posted I think we all have a good idea as to what we need to make them better. I'm hoping the best artist amongst up steps up and makes some really nice. professional masks. Most of the work is done as fas as setting up the effects framework and Gimp mask templates.

**Comment by gilbertohasnofb** [comment]
That's excellent, I will try to have a look at this as soon as I can, possibly over the weekend. Thanks again for all the hard work!

**Comment by wlbragg** [comment]
FYI: The masks are wrong, all the white needs to be 100% blue. I'm not sure when I switch it but I just now noticed while trying to create a better mask.

**Comment by wlbragg** [comment]
I'm not very skilled at color channel manipulation. As I read the docs, the red channel controls the fog. So red on black or alpha should give you the mask for fog and the defrost vent pattern.
The blue channel is the ice and so blue on black or alpha should give you ice. I am getting ice to show on the fog only selection in the sim. I think that is because I don't have the channels separated correctly.

**Comment by wlbragg** [comment]
OK, I finally got one correctly implemented. It is the front windshield (windshield.png).
![fgfs-screen-023](https://user-images.githubusercontent.com/11069680/46103230-f042d600-c195-11e8-81c0-7cacfb4cea17.png)

I have a thought on the defrost vent pattern and how strong or weak we make it. My thoughts are that we can allow some fairly intense icing, which looks really compelling if conditions support it, so long as the defrost vent pattern at the lower portion of the windshield is fairly strong so you can still see out the windshield even at maximum fog and ice levels.

**Comment by legoboyvdlp** [comment]
Nice work!

**Comment by wlbragg** [comment]
Thanks @legoboyvdlp but I think these could be a lot better. This is my attempt at smudging.
![fgfs-screen-028](https://user-images.githubusercontent.com/11069680/46115047-f8f9d300-c1ba-11e8-9d4a-88df454c58e5.png)

**Comment by wlbragg** [comment]
I need to correct a previous statement.

>red channel = fog (NO GLARE EVER from the fog channel)

What I meant to say here is we have no control over how much glare can be introduced to either the default ice or fog effect, it is a set calculation we have no control over. If you want to control glare you have to do it in the blue channel.

**Comment by wlbragg** [comment]
My next attempt at fog and ice masks. At least these are correct channel assignments now. it is all pushed to the PR branch.
I added a bit of smudging. While I feel this is an acceptable outcome, I still think a professional artist could produce much more compelling results.
Something that still needs to be verified is the fog and frost numbers the fog and frost system is capable of producing and verifying that they are in line with the visual we expect to see.
My concern is that 0-1 for fog appears to potentially be too little fogging if that is the limit the system is capable of producing and to verify the frost 0-1 is also the limits of the frost. The frost number appears to be more in line with the amounts of coverage I expect if 0-1 is the limit.
https://www.dropbox.com/s/vs668gjnrk2dqfs/2018-09-27%2013-30-05.mp4?dl=1

One other thing I want to do is to remove the hard line of the defrost vent pattern on the front side windows. I figured the air from the vents might have a little bit of influence on those areas but made it to hard edged.
Also maybe go back and ad a little defrost pattern to the locations the wing vents would blow on.
I think we need to default the aircrafts heat and air to be in a configuration that would support the vent patterns I propose. If possible to default the heat and air settings to maintain a stable atmosphere in the cabin. This would help to reduce the likelihood of users adjusting these vents and thus in most circumstances help keep the fog and frost visual effect consistent with the air vent configuration. Opening vents should always reduce the fogging and frost at a greater rate than not open.

FYI: keep in mind the creation of the ice and smudging of the same is a all or nothing proposition. It is impossible to go back in and change the overall look of this such as size or density without completely redoing it. It is the nature of how it is created in Gimp at least.

**Comment by wlbragg** [comment]
Well I missed a great opportunity to test this in a real life situation. I was flying out of Juneau AK transporting 3 hunters and a load of equipment to a hunting camp VIA float plane to a small lake up in the mountains. I had  to traverse a range by gaining and dropping in altitude rapidly to get to the destination. At the extreme altitude changes I got both icing and fogging . Unfortunately I was using the master branch without the new frost/fog. I'll try it again with the correct branch and will have a good comparison to judge my artwork.

**Comment by wlbragg** [comment]
>I'm confused, do you have a master branch in your real life and

Sorry, that's because I am confusing. I meant I had the opportunity to see the fog and frost develop in a "simulated" real life application. I was just flying the aircraft like I was on a trip and hit the right conditions. Because I was using the master branch and not the fog/frost test branch I saw the old fog and ice patterns VS the new ones. It would have been nice to see the new fog/ice develop slowly like it did and get a really good feel for what it looks like as it happens in the sim. Verses testing it with manual stages I have to set by intervention in the property tree.
It's not the same doing it manually as it is when the sim does it because the conditions are correct. When the simulation does it it is gradual and you can use the heat and air or windows to try to control it, like you would in real life. Just a better way to experience it and get a feel for how good or bad it is.

**Comment by gilbertohasnofb** [comment]
Ah I understand what you meant now, all clear. I would love to hear from @onox concerning this.

**Comment by onox** [comment]
> >    One thing I noticed that I was not happy with is that the heater/vent seemed to acerbate the frost/fog. That shouldn't happen, at least where the air is blowing on the windscreen. Maybe the other surfaces that the air isn't blowing on directly. Anyone care to comment on this?
>
> Wasn't it @onox who worked in the first system? Perhaps he could have some advice. I am thinking this could be due to moisture in the air that comes from the vent? But just guessing, maybe our implementation is not correct.

The system does _not_ simulate air blowing on the wind screen. So the implementation is simply missing. It just simulates the temperature and humidity in the cabin and depending on the temperature of the windscreen, you see fog or ice.

See https://github.com/c172p-team/c172p/blob/master/Systems/c172p-heat.xml#L490-L558

We take `heat/cabin-dewpoint-degc - heat/surface-temp-degc` and integrate it. Below the integrator we set the set the fog and frost levels.

If I look at the code:

1. The summer could be modified by adding a 3rd `<input>` property (let's call it `heat/the-new-third-property` for this example). This property should have a value between -0.5 and 0.0. (if you want a bigger range, you can add a 2nd summer which sums the new property + `heat/surface-dewpoint-diff`.

2. To the switch below the summer you need to add a new test case:

```xml
            <test logic="AND" value="1">
                heat/the-new-third-property LT 0
                heat/moisture-norm LE 0
            </test>
```

**Comment by onox** [comment]
And the reason the implementation is missing is because there was no ALS effect (mask) to show the air blowing against the windscreen and no knob to open/close the defrost outlets.

**Comment by wlbragg** [comment]
The effect that I am questioning is when applying heat to the cabin the fog increases. typically when applying heat to the cabin, in say a car, the fog decreases. It decreases quickest where the air vents blow on the windscreen but it also decreases overall and eliminates pretty much all the fogging on all the windows. In this simulation the heater has a tendency to increase the fogging effect and the message indicates that this is to be expected as it suggests you turn the heat down or open a window until the fog subsides or dissipates.
I'll study what @onox wrote and see if it addresses this issue.

**Comment by wlbragg** [comment]
I am getting closed to being finished with the fog and frost.
To test frost and fog manually you will need to comment out ground-effects.xml lines 395-443 and use
/environment/aircraft-effects/fog-level
/environment/aircraft-effects/frost-level
to set the levels.
I will push the final effects along with the temporary seat key assignments here shortly.

**Comment by onox** [comment]
@wlbragg You could also try to adjust https://github.com/c172p-team/c172p/blob/master/Systems/c172p-heat.xml#L304 to speed up how fast the surface temperature of the windscreen changes.

**Comment by wlbragg** [comment]
Thanks @onox, I'll review this tomorrow or lat tonight.

To whomever would be concerned, I am finished with the fog and frost textures. They were never intended to be the final versions as I was hoping someone with better artistic skills and more knowledge of getting the most out of drawing programs would step p and create these. If you all think it is better than what we already had (which was the default and no vent patterns) then so be it. But I have no problem with anyone that thinks they can improve these graphics.

**Comment by legoboyvdlp** [comment]
They look great - far better than what we had before :smiley:

**Comment by wlbragg** [comment]
After reading back through this I am not finished with this, I need to dissect what @onox wrote and implement it so the heater simulates the defogging/defrosting of the windscreen.

**Comment by onox** [comment]
@wlbragg Did you manage to fix the 2 issues?

**Comment by wlbragg** [comment]
No, not yet. I've been pressed for time as of late. Hopefully after the Thanksgiving Holiday I can get back on it and get it done.

**Comment by legoboyvdlp** [comment]
Is there anything I could do to help on this?

**Comment by wlbragg** [comment]
If you can figure it out in the code. As it is written now, adding hot air to the cabin increases the fogging. There is even a warning triggered about it in the code. Typically turning on the air/heat (defrost) should actually drive the fog number down, not up. if you have a completely fogged window and turn the air over the windshield on you should see the fog start to dissipate. As this happens, with the new masks you will see the areas around the vents clear first.

What needs to be accounted for is when you turn on the defrost air that blows over the windshield, it needs to drive the fogging number down. See @onox explanations above.

**Comment by wlbragg** [comment]
@onox 
OK, I think I have part of this figured out, but I have a couple questions.

Are these the proper place to set the total limits for for and frost?
I want a max value for /environment/aircraft-effects/fog-level of 1.6
and a max /environment/aircraft-effects/frost-level of 1.
~~~
        <pure_gain name="heat/moisture-fog-level">
            <input>heat/moisture-norm</input>
            <gain>1.6</gain>
        </pure_gain>

        <pure_gain name="heat/moisture-frost-level">
            <input>heat/moisture-norm</input>
            <gain>1.0</gain>
        </pure_gain>
~~~

I don't understand this following code block because I see no heat/cabin-air-temp-degc property in the tree, only a directory?
~~~
<switch name="heat/fog-level">
            <default value="heat/moisture-fog-level"/>
            <test logic="AND" value="0">
                heat/cabin-air-temp-degc LE 0
            </test>
        </switch>

        <switch name="heat/frost-level">
            <default value="heat/moisture-frost-level"/>
            <test logic="AND" value="0">
                heat/cabin-air-temp-degc GT 0
            </test>
        </switch>
~~~

This is very hard to test, but for anyone interested in testing this, use a positive value of fdm/jsbsim/heat/artificial-fog-increase to increase fog. Now I assume that if the temperature is freezing then you should also get frost. Unfortunately I was not able to get the frost. @onox can you explain this?
If you tune the artificial-fog-increase to a value that causes fog close to a stable amount (not increasing or decreasing, somewhere around 5 to 7), you can then pull out the cabin vents to see the fog decrease. This is not easy to set.

**Comment by legoboyvdlp** [comment]
>  I see no heat/cabin-air-temp-degc property in the tree, only a directory?

That probably means it's an actuator, sensor, or other component like that. JSBSIM works if you just refer to the directory but I prefer to use <output> for those.

**Comment by wlbragg** [comment]
Ah, thanks @legoboyvdlp I wondered about that. Yes, I think that is the case.

**Comment by wlbragg** [comment]
>It worked well when I tried it!

>However, I thought the rate of fog / frosting might have been too fast - it only took about 30 seconds to get maximum frosting at -2 degC? When I applied max heat and 10% airflow it went very rapidly to full fogging.

@legoboyvdlp I moved this discussion here as it is a more appropriate location.
Can you elaborate more on a couple comments, such as...
>fog / frosting might have been too fast - it only took about 30 seconds to get maximum frosting at -2 degC

I need the context behind this. What did you do to cause this high rate of fog increase? Is it when you turned on the heat or air?

>When I applied max heat and 10% airflow it went very rapidly to full fogging.

This is an effect that is not supposed to happen, It is supposed to reduce the fogging rapidly.

I think I am going to have to study the code a bit more. 

What did you do location and environment wise to get fog to happen using the heat and air vent?

**Comment by wlbragg** [comment]
@onox, I see you already have the heat and air vents accounted for in the logic, in a much more advanced way than I did. So I obviously didn't totally understand you explanation of what I need to do. I am studying it again with this new understanding and maybe it will make more sense to me.

**Comment by wlbragg** [comment]
After looking at this again, i think we need to talk about some of the logic. I don't think I can fix the issues I have with it without totally understanding the code that introduces the heat and air vent. As you say @onox it only calculates temperature being introduced into the cabin and in that case it increases the temp differential from outside and thus you get dew or moisture. That does make sense.
So why does the air blowing on the windscreen reduce the fogging? I think it is the air blowing across it evaporates the moister fairly fast, like blow drying your hair.
My issue is that the introduction of heat into the aircraft through the vent always introduces the air across the windscreen so that would always override the introduction of heat to the cabin. Thus instead of simply reversing the early calculations of heat being introduced to the cabin later on down in the code we just change the original code that is causing the heat and air to fog in the fist place, it should not cause fogging, it should only reduce it.
Otherwise your adding fogging with the heat and air vent early in the code only to remove it later on in the code with the heat and air vent. Makes no sense.

**Comment by legoboyvdlp** [comment]
I need to observe it more, but after about thirty to forty seconds of taking off with full power and mixture at M02 deg AT KBNA. I think it was below dew point if that's relevant.

After leaning to peak EGT and setting heat to full, then air to about 20% I then got rapid fogging increase.

**Comment by wlbragg** [comment]
Hum, this isn't getting any easier the more I understand how this code is working. I think we need to remove all four air vent code blocks from adding to the heat calculation and re-factor it to remove moisture instead.

**Comment by wlbragg** [comment]
The basic logic of RPM and temp are already there, we just need to use it to remove moisture VS add heat.

**Comment by wlbragg** [comment]
Effectively it would reverse the effect @legoboyvdlp indicated of the heat and air vent rapidly increasing fog, when it should in fact rapidly be decreasing fog.

**Comment by legoboyvdlp** [comment]
Apparently using a heater in cold, dry climates may result in fogging, while using air conditioning in warm, wet climates can cause fogging. 


> The reason for foggy windows has to do with temperature and the air’s moisture content. On a cold day, any moisture in the air inside your car —  from passengers exhaling, snow on your boots, etc. — turns to condensation when it hits air next to the windows that’s below a certain temperature, called the dew point. The condensation is what makes your car’s windows appear foggy. On a hot, humid day, the opposite happens, when the muggy air outside your car reaches the dew point against your windshield after it’s cooled by your AC system.

To solve fogging, when it's due to cold, dry air outside:

> First, turn the heat on its maximum setting, because hot air can hold more moisture.
Then, turn the AC on, which will pull the moisture from the air as it passes over the cooling coils.
Finally, turn off the recirculation button so colder, dryer air is brought into the car.
If possible, crack your windows for a couple minutes to help exchange the humid interior air for dryer outside air.

If you get fogging due to condensation on the exterior you want to warm up the inside to solve it.

**Comment by legoboyvdlp** [comment]
Another article:
> For the inside story, Cars.com spoke with Mike Hoppe, an engineer for Fiat Chrysler Automobiles in charge of climate control systems, who said windows fog up on the inside when warm, moist air in the car meets colder glass surfaces, causing condensation.

Related: Why Do Only Some of My Car's Windows Get Condensation on Them?

"In its simplest form, it's too much water in the air, and it condenses on the glass," Hoppe said. "It condenses on the inside because the outside is colder, and when it's colder outside, that lowers the relative humidity point.

"It's like when you see your breath when it's cold outside. Your breath generally has 100 percent humidity in it, but you're only seeing it when it's cold outside because that's when it's reaching the point where it's causing fog."

Humidity levels inside a car can increase from passengers breathing, clothes that are wet from rain, snow that people drag in on their boots, damp carpet or floormats, and — a classic example — an amorous couple. Even a hot pizza elevates moisture levels in a car.

"The steam that's coming off of that is 100 percent humidity, and it's all going into the cabin air," Hoppe said, referring to the pizza.

When the inside windows fog up, Hoppe advises to turn on the defrosters (front and rear) and turn up the heat. The air conditioning comes on automatically when the windshield defroster is turned on in most current vehicles, if not all, and Hoppe said that will dehumidify the air and clear windows faster.

Warm air contains more moisture, but Hoppe said it's the relative humidity that matters, so warm, dry air coming through the defroster will clear the glass faster than cool air. He added that it's best to use fresh air instead of the recirculation mode when running the defroster because the latter will work to recycle and replace the moist air that was the cause of the problem.

**Comment by wlbragg** [comment]
Thank you @legoboyvdlp it finally sunk in. That missing piece for me is that the defrost in a car activates the air conditioning. I always new that a heavier load was caused by turning on the defrost n a car and I never new exactly why. It's the air conditioning!
OK, I apologize to @onox because I think he has this right. We have no air conditioning in the c172p thus we have to rely on the other methods to reduce fogging.
I think the vent pattern on the windscreen still works effectively because if nothing else the air rushing over the windshield should evaporate more where it is the strongest. I'm good with this!

**Comment by wlbragg** [comment]
@onox @legoboyvdlp @gilbertohasnofb 
To be clear...
>To be clear there are 2 issues here:
    1) Implementing air vents to decrease fog/frost on the windscreen
    2) Warm air should eliminate fogging on windows

2 I think is not an issue.
1 I think is actually addressed in the code where we account for the heat and air vents.
You should be able to effectively decrease fog in a dry cold climate by using the air vent without the heat or opening the windows.

**Comment by wlbragg** [comment]
>And the reason the implementation is missing is because there was no ALS effect (mask) to show the air blowing against the windscreen and no knob to open/close the defrost outlets.

@onox I did mess with it but after reviewing it further and @legoboyvdlp great article about how the air conditioning plays a part in the defrost of a car window. I don't think it is necessary anymore. The c172p has no defrost mode (ie: air conditioner). So if the heat and air slider knobs are adding air and/or heat appropriately to the frost/fog code (which it does earlier in the code), then technically you don't need to do anything else. The adjustment of the heat or air slider is effectively doing what it is supposed to. If you get fog in the cabin then your only recourse is to open the air slider and turn off the heat slider and/or open windows. Obviously that is in the case of cold outside air and warn, moist inside air.
So I think you had it right, I was imparting an additional feature we don't have in the c172p of a true "defrost" switch. The air vents, ie: air that you can introduce heat into, is all their is and you modeled that correctly as far as I can tell. If you do what you suggest, it seemed to me we were just double dipping into the amount of air, hot or cold, we introduce to the aircraft cabin. Those vents in the dash may open and close manually, I don't know, but we don't model that. In our case they are just open and the heat and air sliders are what introduces the air through them.
So I am good with this as is unless I am missing something.
