### ISSUE TITLE
KMA20 instrument does not control the volume of radio's and ADF

### ISSUE THREAD

**Issue by onox** [c172p-team/c172p#306]
From #80:

> All sounds in the comm panel depend on the audio panel: vor, adf, comms. The audio panel is the amplifier of all audio channels, and also the device that selects if COMM1, COMM2, VOR1, VOR2 and ADF (or all of them together!) are connected to the ear speakers/mic or the cabin speakers/mic.
> 
> So, yes, the kma20 also controls the volume of all other devices.

Some code in `Nasal/kma20.nas` should be replaced with `<filter>`'s so we can control the volume. We can control `/instrumentation/marker-beacon/volume` for the marker-beacon.`/instrumentation/comm/volume` and `/instrumentation/comm[1]/volume` are probably a bit more difficult to fix because they can be (I assume) controlled via the radio instrument in the cockpit.

**Comment by tigert** [comment]
The way it works in the real plane, is that each radio (com1, nav2, adf etc..) has its own volume knob. And then the audio panel controls the intercom (or speaker) volume. This is usually slso separate for pilot and copilot (and the rest of cockpit, some fancier audio panels have also "isolate crew" and "isolate pilot" switches so you can split the pilot and copilot out and let the passengers (all the two of them in the 172 ;)) talk while you do radio comms.

I guess we should have a master volume variable from 0 to 1 as well as each radio has its own, and just multiply the com1 volume with both? 

instrument-n_volume = audiopanel_pilot_volume * instrument-n_volumeknob * instrument-n_volume

Wouldn't that work? 

Like an electric guitar and amp. So we should just  have the audio master

**Comment by gilbertohasnofb** [comment]
@onox I am a bit confused by this issue. The KMA20 does not have any volume knob, it only has toggles that can be set to SPEAKER, HEADPHONES or OFF. If I set COM1 to the ATIS frequency and the KMA20 is has the COM1 toggle set to either SPEAKER or HEADPHONES, then the volume knob in the COM1 radio controls the volume as expected. If the KMA20 is set to OFF then the ATIS message stops to be heard regardless of the COM1 radio volume knob. This is all as expected. What exactly is the problem?

**Comment by onox** [comment]
I think the issue is about whether the KMA20 instrument has power (circuit breaker).

https://github.com/c172p-team/c172p/issues/80#issuecomment-112130792:

> Should various sounds (marker beacon, afd, dme, comms) depend on whether the audio panel has power or not?

I think @mathieugouin did some work on the radio stack a while ago, so radio's might have already been fixed.

@gilbertohasnofb Did you test the marker beacon as well? (with power to the KMA20 instrument disabled via the circuit breaker)

**Comment by gilbertohasnofb** [comment]
> Did you test the marker beacon as well? (with power to the KMA20 instrument disabled via the circuit breaker)

@onox Yes. Without the power they don't illuminate and with power they can be tested as expected. By without power I tested having the master off as well as disabling the KMA20 breaker (radio breaker no. 1 with hoover label 'audio panel'). So it seems to be properly implemented already.

The POH schematic doesn't help much as the five radio circuit breakers are just marked as RADIO 1, RADIO 2, etc. But our implementation does make sense.

So do you know if there is anything left to be done? This looks like solved to me.
