### ISSUE TITLE
Instrument illumination is too strong during daytime

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#35]
XML14 - Instrument illumination is too strong during daytime. In the original c172p, one could hardly tell the difference between 0% and 100% instrument illumination during daytime. At night time, our project behave exactly as expected.

**Comment by legoboyvdlp** [comment]
Close after merge of #1103?

**Comment by gilbertohasnofb** [comment]
I think the instrument lights are still way too strong during the day. The dome lights are very faint which looks good. If we improve that then we could add this issue to the list of fixed stuff on that PR.

![fg](https://user-images.githubusercontent.com/5700795/41500987-bd7c5b26-7193-11e8-8282-e2d3f396dffc.jpg)

 @wlbragg would you consider that idea I floated of somehow lowering the intensity of the instrument lights during the day?

**Comment by wlbragg** [comment]
Yeah, absolutely, I think i even know what property to use.

**Comment by gilbertohasnofb** [comment]
Excellent, thank you!

**Comment by wlbragg** [comment]
I think your going to like this, pushing now. Let me know if you think it needs adjusting.
