### ISSUE TITLE
Shadows of other c172p models are not displayed correctly in MP

### ISSUE THREAD

**Issue by onox** [c172p-team/c172p#387]
We need to transmit `/position/altitude-agl-m` over MP and set the MP property to use in the `<effect>` element that uses Effects/shadow-vol in the .xml files in `Models/Effects/shadow/`:
1. Transmit `/position/altitude-agl-m` over MP
2. Override `<alt_agl>`, `<model-pitch>`, and `<model-roll>` in the .xml files

**Comment by onox** [comment]
I tried to use in `Models/Effects/shadow/3dbushdefshadow.xml`:

```xml
 60         <parameters>
 61             <alt_agl><use>sim/multiplay/generic/float[4]</use></alt_agl>
 62             <model-pitch><use>orientation/pitch-deg</use></model-pitch>
 63             <model-roll><use>orientation/roll-deg</use></model-roll>
 64         </parameters>
```

and in `c172p-set.xml`:

```xml
263                 <float n="4" alias="/position/altitude-agl-m"/>
```

but that causes th shadow to be at the height of the cockpit. In MP the shadow isn't visible at all. So I'll move this issue to 3.8 release.

**Comment by gilbertohasnofb** [comment]
Screenshot of problem:

![fgfs-screen-002 12](https://cloud.githubusercontent.com/assets/5700795/8639625/13180530-28e0-11e5-8283-6b30d5f07295.png)

**Comment by gilbertohasnofb** [comment]
@onox @wlbragg @Juanvvc @all-others 

sorry for using this space, but there is a discussion going on in the mailing list regarding our plane, about MP and console alerts. I am not familiar with MP at all, so maybe someone else can take a look at it?

**Comment by hbeni** [comment]
This is probably obsoleted by compositor and can be closed.
