### ISSUE TITLE
Shadows at fixed altitude after resetting sim

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#399]
When I load the sim, the 3D shadows work perfectly well. But if I click on the Reset option in the File menu, the shadow will then be fixed at the last position it had. Example:

First I took off and then at this is the moment I reset the sim:
![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/8635045/0d0adc62-2813-11e5-86a0-c787c463564a.png)

When the sim is reset, the shadow starts much below its regular position:
![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/8635049/250d55ce-2813-11e5-8567-f6fec347fdc1.png)

It will stay at this position relative to the aircraft for the whole flight:
![fgfs-screen-004](https://cloud.githubusercontent.com/assets/5700795/8635050/2ff99588-2813-11e5-8d49-25a269eb62a0.png)

**Comment by gilbertohasnofb** [comment]
@onox feel free to move this to the 3.8 release milestone if you think the fix is something complex that can't be done in time.

**Comment by wkitty42** [comment]
looks like the shadow position needs to be reset like we rest the engines and switches and such...

**Comment by wlbragg** [comment]
This has been a know issue since the shadow was first introduced. I don't think there is a fix for this without looking at the c++.
This isn't a c172p bug.

**Comment by onox** [comment]
This is something that Thorsten needs to take a look at.

**Comment by gilbertohasnofb** [comment]
Ok!

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry to bother you again with the forum, but I just came across this: https://forum.flightgear.org/viewtopic.php?f=37&t=30381

Maybe the user is experiencing something related to this issue here (that is, the "giant" shadow he sees from the cockpit is simply the shadow at a fixed distance from the aircraft). If this theory is correct, a screenshot from outside would make the matters clear. It also would be much easier if she or he would describe how to reproduce the bug, or if the bug is always present in his sim.

**Comment by wkitty42** [comment]
has Thorsten been asked about looking at it (yet)?

**Comment by wlbragg** [comment]
I asked for a little clarification and also informed the user about the shadow off switch.

>has Thorsten been asked about looking at it (yet)?

I know he is aware of it. I really don't remember the details, has to do with re-init. It might be worth looking at it with fresh eyes and see if we can catch it in our code, but it seems like it has to do with order of operation in re-init, it may be different that startup, in which case it would probably require a C++ fix. It's like all other shader effects. You can't re-init and see the changes, you must restart the sim.

**Comment by gilbertohasnofb** [comment]
@wlbragg About that forum thread, there is one more possible explanation why this user is the single one having issues: is he taking off by himself or is he using the "position aircraft in air" option? Because if he is doing the latter, there is nothing new to it.
