### ISSUE TITLE
use airfield elevation to calculate optimal mixture for autostart 

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#791]
Currently our autostart function does not take into consideration the elevation of the airport. This means that while trying to start a plane in a high altitude airfield, autostart will always use full mixture and will be cranking the engine forever. Maybe we could try to take the altitude in consideration, something like using full mixture up to a certain altitude, then using some formula to calculate (or guess) the optimal mixture for starting the engine

Inspired by this post here: https://forum.flightgear.org/viewtopic.php?f=25&t=29996

**Comment by wlbragg** [comment]
Yes, I think this is doable and a worthwhile idea.

**Comment by wkitty42** [comment]
On 07/09/2016 11:27 AM, wlbragg wrote:
> Yes, I think this is doable and a worthwhile idea.

agreed... we probably should have thought about maybe doing this the last time 
this came up ;)

**Comment by gilbertohasnofb** [comment]
I can give it a shot to code it myself. Would anyone know what is the standard procedure in the model P? Until how many feet should one use full rich mixture? And any guesses on what is the minimum mixture percentage one should try to use at extremely high altitudes?

**Comment by wkitty42** [comment]
On 07/09/2016 05:41 PM, Gilberto Agostinho wrote:
> I can give it a shot to code it myself. Would anyone know what is the
> standard procedure in the model P? Until how many feet should one use full
> rich mixture? And any guesses on what is the minimum mixture percentage one
> should try to use at extremely high altitudes?

well that last one was trying to start at that airport in India that was just 
over 13000 feet, IIRC... i think someone finally got the craft started there 
once or twice but no more... @wlbragg maybe??

i believe i also saw something related to this latest topic which said they were 
able to start at 7000 feet with about 45% mixture or something like that... i'm 
fairly sure i read it on the forums...

you may be able to do it with a table of mixture values based on ASL... i'm not 
sure if there is such an existing chart around but if there is, it would be 
great to convert it to a JSBSIM table if that can be used in the autostart... 
i'm thinking about how we have to reduce the mixture as we climb higher... i 
think the lowest i ever got was 60% but i was over 14000 feet and it was 
extremely touchy up there...

PS: sorry if i'm rambling... we had a storm last night that downed some trees 
and killed power to about 250 people... i couldn't sleep as it was much too 
quiet... then the power came back on about 0430 and i've been on my feet ever 
since... i've only been able to nap a few times today... this lack of sleep 
might still hurt next week...

**Comment by gilbertohasnofb** [comment]
@onox @wlbragg @Juanvvc @dany93 can you guys give me your opinions here? How would you approach this problem? The issues are:

- the POH does not state anything about a maximum airfield elevation, much less about a maximum pressure altitude or density altitude for take off
- also nothing about starting engines in those situations
- take off tables have data for up to 8000 ft, so that's a clue
- using only altitude might be a problem since I believe density altitude would be correct parameter, right?
- we have two engines, and they probably respond a bit different

With that in mind, what if the autostart function would work like this:

1. apply full mixture, start cranking
2. if engine still not running after 5 seconds,  continue go to 3. Else go to 5.
3. lower mixture by 5%
4. wait 1 second and go to 2.
5. end

**Comment by onox** [comment]
Is it possible at all to start the engine at high altitudes (> 8000 ft)? I don't think we should iteratively try to find the mixture needed to start the engine. That could take too much time and it would be difficult to cancel it.

I think it's easier to have a table to set the mixture to a certain level depending on the altitude. And show a message if the user tries to perform an autostart while the aircraft is above a certain altitude threshold (8000 or 9000 ft?).

Additionally we can set a timer (a couple of seconds) after performing an autostart and then display a message if the engine hasn't started. Something that says that the air is less dense at high altitude and the mixture needs to be leaned. Users might not be aware of this so they need to be educated a bit.

**Comment by gilbertohasnofb** [comment]
> Is it possible at all to start the engine at high altitudes (> 8000 ft)

I don't know. The POH gives take off distances for airports up to 8000 ft, so that altitude should be fine.

> I think it's easier to have a table to set the mixture to a certain level depending on the altitude. And show a message if the user tries to perform an autostart while the aircraft is above a certain altitude threshold (8000 or 9000 ft?).

That sounds good. But then again not only we have two engines (and therefore would need two tables), but I believe that altitude alone is not the only factor that affects the engine start up. I think pressure and temperature also affects it, right? So then we need to use density altitude. Would you know if this is correct? As for the warning message, that's clever.

> Additionally we can set a timer (a couple of seconds) after performing an autostart and then display a message if the engine hasn't started. Something that says that the air is less dense at high altitude and the mixture needs to be leaned. Users might not be aware of this so they need to be educated a bit.

But I thought we were trying to automate the mixture leaning for the autostart function, so I don't understand what you meant here.

**Comment by onox** [comment]
> But I thought we were trying to automate the mixture leaning for the autostart function, so I don't understand what you meant here.

What I mean is that in the case that our table happens to be insufficient (the engine still doesn't want to start on the user's FG instance for some reason, even with the best possible amount of mixture) that we tell the user that we're very sorry but the user is asking the impossible.

**Comment by onox** [comment]
> That sounds good. But then again not only we have two engines (and therefore would need two tables)

Lets first try to compute one table and see if it works for both engines. After all, they're very similar.

**Comment by wlbragg** [comment]
So the table will be used to adjust the mixture per altitude of the start up airport?

**Comment by gilbertohasnofb** [comment]
@onox yes, that sounds clear now! :+1: As for the two engines with one single table, let's try it

> So the table will be used to adjust the mixture per altitude of the start up airport?

Yes, but not exactly start up airport, but current location. And I still think we should use density altitude and not altitude.

@onox Do you know where can I read about implementing tables in Nasal? Or should I try to come up with some liner equation, or use a bunch of `if`s (if between A and B, then use linear formula1, if between B and C, then use linear formula 2, etc.)?

**Comment by onox** [comment]
> Yes, but not exactly start up airport, but current location. 

I don't think latitude/longitude matters. Just altitude or air pressure.

I think you should try to use a table in JSBSim/autopilot in which you map the altitude to a mixture setting. JSBSim/autopilot will then do the interpolation for you.

**Comment by onox** [comment]
Try to find airports at 0, 1000, 2000, ..., 8000 ft. Use standard air pressure (29.92).

**Comment by onox** [comment]
About the JSBSim table: name the output property something like `/path/to/recommended-mixture-value`. The Nasal code that performs the autostart then reads this property and sets the mixture.

**Comment by gilbertohasnofb** [comment]
>>  Yes, but not exactly start up airport, but current location.
> 
> I don't think latitude/longitude matters. Just altitude or air pressure.

Oh, what I meant is the current altitude!

> I think you should try to use a table in JSBSim/autopilot in which you map the altitude to a mixture setting. 

Sounds like a plan, I will read about it (as I am completely unfamiliar with it) and make a first attempt soon.

**Comment by onox** [comment]
Look at `<tableData>` in `Systems/indicated-airspeed.xml`.

**Comment by onox** [comment]
Something like this. Here I assume that at 3000 ft you can still start with 100 % mixture, and at 8000 ft you need 50 % (just guessing, this is an example).

```xml
<fcs_function name="fcs/recommended-autostart-mixture">
    <function>
        <table>
            <independentVar>/position/altitude-ft</independentVar>
            <tableData>
                3000    1.0
                4000    0.9
                5000    0.8
                6000    0.7
                7000    0.6
                8000    0.5
            </tableData>
        </table>
    </function>
</fcs_function>
```

In `Nasal/c172p.nas` you write:

```javascript
var recommended_mixture = getprop("/fdm/jsbsim/fcs/recommended-autostart-mixture");
setprop("/controls/engines/current-engine/mixture", recommended_mixture);
```

**Comment by onox** [comment]
```javascript
if (getprop("/position/altitude-ft") > 8000) {
    gui.popupTip("Cannot start engine above 8000 ft. Find an airport at a lower altitude", 5);
}
```

**Comment by onox** [comment]
And at the end of the autostart function you do:

```javascript
var engine_running_check_delay = 5.0;
settimer(func {
    if (!getprop("/engines/active-engine/running")) {
        gui.popupTip("Engine failed to start. Adjust (lean) mixture and start manually or find an airport at a lower altitude", 5);
    }
}, engine_running_check_delay);
```

**Comment by gilbertohasnofb** [comment]
@onox Ok, I got that part working so now I only need to fill the table. The problem I am having is that TerraSync is awfully slow for some reason so I am having troubles with that :cry: I will try again tomorrow though. Once the table is filled, then it's just using the new property in the Nasal code which should be trivial.

**Comment by gilbertohasnofb** [comment]
Oh, I just saw your last three posts (I hadn't updated this page). Yeah, that's pretty much what I head in mind for the Nasal code, and I had found how to create a table with a single variable in JSBSim using their documentation. Thanks a lot for the hand!

**Comment by gilbertohasnofb** [comment]
Guys, TerraSync is simply not working here... it says that it's downloading a tile at a rate of ~150 KBytes/s but the sim never loads. And TerraMaster, which is what I used to use, is simply not working any longer. The only terrain I have on my HD is Europe, and Europe's highest airport is St. Moritz at 5643 feet (and I can start the engine with 100% mixture at that altitude @pressure 1013 mbar). 

So can anyone give me a hand filling the table? For instance, all these airports below would be very handy (and all are in Colorado, US). Simply load the plane there, set pressure to 1013 mbar (29.92 inHg) and look for the highest mixture in which the engine starts comfortable (so even if the engine starts but took a while and coughed, turn it off, lower the mixture and try again). The airport list:

- KCEZ: Cortez Municipal Airport, at 5918 feet
- KFLY: Meadow Lake Airport, at 6874 feet
- KAEJ: Central Colorado Regional, at 7950 feet
- KC24: Mineral County Memorial, at 8680 feet
- KTEX: Telluride Regional, at 9070 feet
- KLXV: Lake County, at 9934 feet

In case you guys are also having troubles with TerraSync and don't have these downloaded, then I will have to try working on this later once the issue is fixed.

**Comment by wlbragg** [comment]
I can try it later tonight. I have most of the world down loded using terramaster. It's running right now, has been for a week or so. I'm not sure why you are having problems with it.

**Comment by gilbertohasnofb** [comment]
@wlbragg thanks a lot! As for TerraMaster, I am getting the following error:

> sync w110n30/w108n38... svn: '/svn/trunk/data/Scenery/Terrain/w110n30/w108n38' path not found: 404 Not Found (http://terrascenery.googlecode.com)
> svn: '/svn/trunk/data/Scenery/Objects/w110n30/w108n38' path not found: 404 Not Found (http://terrascenery.googlecode.com)

I just didn't have yet time to troubleshoot it.

**Comment by wkitty42** [comment]
On 07/23/2016 05:26 PM, Gilberto Agostinho wrote:
> @wlbragg <https://github.com/wlbragg> thanks a lot! As for TerraMaster, I am
> getting the following error:
>
>     sync w110n30/w108n38... svn:
>     '/svn/trunk/data/Scenery/Terrain/w110n30/w108n38' path not found: 404 Not
>     Found (http://terrascenery.googlecode.com)
>     svn: '/svn/trunk/data/Scenery/Objects/w110n30/w108n38' path not found: 404
>     Not Found (http://terrascenery.googlecode.com)
>
> I just didn't have yet time to troubleshoot it.

that's easy... googlecode is long gone... it closed shop at the same time that 
gitorious did which was two of the main driving factors for the FGFS project to 
move to SF back in the beginning of 2015... the terrain is now hosted on SF with 
a couple of mirror sites...

the old SVN stuff, while still operational, cannot easily switch to a new server 
like GIT can by editing the config file... if one wants to retain using SVN but 
switch to the new server(s), they have to delete the old .svn database 
directory... that means downloading everything all over again even if you 
already have the actual data files... believe me, i've done it numerous times 
now and it hasn't been fun at all... especially on a 3Meg DSL line...

this is one of the major reasons why the whole terrasync thing has switched to 
http... there's no more svn database to eat up drive space (i freed ~100Gig when 
i deleted my .svn yesterday) and switching between servers or even pulling data 
from multiple mirrors is no problem... quite unlike cvs, svn, git and others...

**Comment by gilbertohasnofb** [comment]
@wkitty42 thanks for all the info. As I wrote, I still didn't have the time to troubleshoot this, but I will try to check it out as soon as I can.

**Comment by onox** [comment]
I can start at KGCN (6600 ft) with 100 % mixture.

**Comment by onox** [comment]
KAEJ as well.

**Comment by onox** [comment]
KTEX (9000 ft) ok too.

**Comment by onox** [comment]
KLXV (9900 ft) not ok.

**Comment by onox** [comment]
Seems even with 65 % mixture, I cannot start at KLXV. Will try to increase throttle.

**Comment by onox** [comment]
It seems you have to look at `/environment/pressure-inhg`. At 20.65 I cannot start the engine even at KTEX. Even with increased throttle and reduced mixture.

**Comment by onox** [comment]
At 21.33 I could start the engine with 45 % throttle and 70 % mixture.

**Comment by onox** [comment]
At 21.41 needed 40 % throttle and 50 % to 100 % mixture.

**Comment by onox** [comment]
At 21.49 needed 35 % throttle and 100 % mixture to 50 % mixture (recommended mixture (good RPM) between 90 % and 60 %).

**Comment by onox** [comment]
At 21.56 starts at 25 % throttle and 90 % mixture.

**Comment by onox** [comment]
At 21.64 starts with 20 % throttle and 90 % mixture.

**Comment by onox** [comment]
At 21.75 starts with default settings (20 % throttle and 100 % mixture)

**Comment by onox** [comment]
At 20.65 I can start the engine with 20 % throttle and 95 % mixture.

**Comment by onox** [comment]
Hmm... I am messing with the air pressure, and now I can suddenly no longer start at 20.65 with 20 % throttle and 95 % mixture :confused:

**Comment by onox** [comment]
I'm looking at `c172p.xml` and I see that `fcs/mixture-pos-norm[1]` uses the primer (value is 1.0) if primer is used at oil temperature is less than 75 F.

If the engine is not running and I'm not starting the engine, then `fcs/mixture-pos-norm[1]` has the value of the actual mixture control, but engine doesn't run (duh). So what is telling JSBSim to start the engine?

**Comment by onox** [comment]
I don't have any clue how JSBSim knows when to 'start' the engine, but maybe we should at least multiply `fcs/mixture-primer` with `fcs/mixture-cmd-norm[0]` or `fcs/mixture-cmd-norm[1]`?

**Comment by onox** [comment]
@dany93 What's the purpose of the primer again? Does it really imitate mixture at 100 % or is it just meant to make sure mixture is 0 % if throttle is out of range (10 % to 50 %)?

**Comment by wlbragg** [comment]
Just a thought that isn't really related to this subject, but, isn't it true that a typical primer is used to supply an "immediate" volume of fuel to the carb or combustion chamber (a choke would give a richer mix)? Almost as a fuel injector does. If this is true then we should still be able to start vehicles without using the primer, it just takes more cranking.

**Comment by onox** [comment]
I've set the mixture to 95 % instead of 100 %. See branch [`bug-791`](https://github.com/Juanvvc/c172p-detailed/tree/bug-791).

Now I can start at KLXV (9900 feet) and VNLK (9300 ft) for example.

**Comment by onox** [comment]
Can somebody try my branch at ZUAL (14000 ft)?

**Comment by wkitty42** [comment]
On 07/24/2016 11:45 AM, wlbragg wrote:
> Just a thought that isn't really related to this subject, but, isn't it true
> that a typical primer is used to supply an "immediate" volume of fuel to the
> carb or combustion chamber (a choke would give a richer mix)? Almost as a fuel
> injector does. If this is true then we should still be able to start vehicles
> without using the primer, it just takes more cranking.

correct... many of out motorized tools have a primer on them... it is especially 
useful when they've sat for a while and the fuel chamber is dry where the fuel 
evaporated... the primer shoves a bunch of fuel into the chamber so that it can 
be drawn into the cylinders faster and make for a much easier start...

**Comment by gilbertohasnofb** [comment]
@onox thanks for all these tests and valuable information! :smile: 

> Can somebody try my branch at ZUAL (14000 ft)?

I will try it and report in a second.

But I think we are maybe over complicating things. First of all, this is being a bit of guesswork given that the POH doesn't say much (or anything at all) about starting an engine and taking off from airfields at high elevation. Then there is the thing that not only the altitude affects the problem, but also the pressure (what about temperature, does it also affect anything?). Then we have two variables to control in our simulated engine (again, just guesswork since no info from the POH): mixture AND throttle. With all this in mind, please remember that we are not improving the engine itself but we are simply talking about a function used by newbs.

So with all that said, what about a much simpler solution: autostart attempts to use 100% mixture and if the engine is not on in let's say 10 seconds, it stops trying and display a warning: "Due to the current altitude and atmospheric conditions the autostart function wasn't able to start the engine. You must attempt to do so manually or change one of those parameters." or something like that. And given that 100% mixture was fine up to 8000 or 9000 ft in onox's tests, I think that's fair enough (the POH only talks about take off distances for airfields up to 8000 ft anyway). That would simplify a lot this whole issue.

So what do you say?

**Comment by gilbertohasnofb** [comment]
@onox BTW, I tested your autostart function at KLXV with Standard Atmosphere (696.817 mbar) and the engine starts without a problem! Now taking off is a complete different story, what a sluggish take off run and even worse climb! I am finishing downloading ZUAL now and I will test it, but that's quite beyond our ceiling anyway (and unpressurised aircraft without oxygen masks should not fly higher than 12500 feet due to the risk of hypoxia)

**Comment by gilbertohasnofb** [comment]
@onox ok, so I can't start using your function at ZUAL. I tried using Q595 (which is a standard atmosphere), and I also tried two of the weather scenarios (high pressure and low pressure). Anyway, I would suggest we do the following:

- use the regular autostart function for density altitude of up to 6000 ft
- for higher altitudes than that, use your slightly modified function (i.e. mix 95% throttle 20%)
- set a timer for 10 seconds. If it doesn't start, abort autostart and display the error message I suggested above

What do you say?

**Comment by onox** [comment]
What I did in the autostart function is to set mixture at 95 % instead of 100 %. That would mean the difference between successfully starting the engine or not getting the engine started at all.

95 % should work for 9900 ft, but it might not be lean enough for a good takeoff. So perhaps at 9900 ft the mixture should be lower.

Are you saying that 95 % was not sufficient for ZUAL? At what mixture level did you successfully start the engine?

**Comment by gilbertohasnofb** [comment]
> Are you saying that 95 % was not sufficient for ZUAL? At what mixture level did you successfully start the engine?

After autostart failed, I wasn't able to manually start the engine at all!

> 95 % should work for 9900 ft, but it might not be lean enough for a good takeoff. So perhaps at 9900 ft the mixture should be lower.

The question that comes to mind is the following: if the engine is off, then one cannot know the ideal mixture before starting the engine (since you can't use the tachometer nor EGT for that). And since the POH doesn't give you info, then I think that probably pilots lean _after_ starting the engine.

**Comment by onox** [comment]
Did you set magneto's to 3, throttle to 20 %, mixture to level 60 .. 90 % and prime 3 times before holding "s" key?

**Comment by gilbertohasnofb** [comment]
I am sure I did, but I will test again now.

**Comment by onox** [comment]
You should put `/controls/engines/engine/primer`, `/engines/active-engine/rpm`, and `/engines/active-engine/running` in the top left corner. That might help.

**Comment by gilbertohasnofb** [comment]
@onox yes, I can start the engine when I lower the mixture a bit (~ 75%, depending on the atmospheric conditions), sorry for the bogus report

**Comment by onox** [comment]
What's your `/environment/pressure-inhg` at ZUAL?

**Comment by gilbertohasnofb** [comment]
Around 17.5 and 18.

**Comment by onox** [comment]
I get it started at 80 % mixture when pressure is 17.6

**Comment by gilbertohasnofb** [comment]
For me it's similar to that, yes. At around 18 inHg I think my mixture was 77%

**Comment by gilbertohasnofb** [comment]
Anyway, now that we have all this data what shall we do? Let's stick to the original plan of using a table, and leave the leaning for take off up to the player? And should we implement that timer just in case or not even bother, now that we know the engine can start in basically any situation?

**Comment by onox** [comment]
We could add the timer. About the table, I think we should use `/environment/pressure-ing` instead of altitude.

> Anyway, now that we have all this data what shall we do?

Sleep :wink: :sleeping:

**Comment by gilbertohasnofb** [comment]
> I think we should use /environment/pressure-ing instead of altitude.

That sounds good (I think effectively that's the same as pressure altitude, but that's all right)

>> Anyway, now that we have all this data what shall we do?
>
> Sleep :wink: :sleeping: 

Oh yeah, here is also 3am. See you soon and good night! :wink:

**Comment by gilbertohasnofb** [comment]
@onox 

> It seems you have to look at `/environment/pressure-inhg`. 
> [...]
> At 21.33 I could start the engine with 45 % throttle and 70 % mixture to 100 % mixture.
20 % throttle with 95 % mixture to 55 % mixture.

I tried working on this right now but I ran into some more problems. I changed the pressure to 21.33 and the engine won't start at any cost! :sob:

**Comment by onox** [comment]
Are you using branch `bug-791`? I could autostart the engine with a pressure of 21.10.

**Comment by gilbertohasnofb** [comment]
No, I was in the `master`... :tired_face: 

Now using bug-791 I could autostart even at `20.65`!

**Comment by onox** [comment]
Which airport?

**Comment by gilbertohasnofb** [comment]
I used SAWB, which is almost at sea level. But if the pressure is all that matters, then it shouldn't make a difference which airport I pick, right?

(I use SAWB because it's a very fast loading airport)

**Comment by onox** [comment]
How do you change the air pressure? Via the weather dialog's METAR field?

**Comment by gilbertohasnofb** [comment]
Yep. I first select some of the Weather scenarios (such as High Pressure), then  I change it to manual METAR and change the Q1013 bit, where 1013 is the pressure in hPa. Note that you always need to have four digits after `Q`, so for lower pressure you need a zero such as in Q0723

**Comment by onox** [comment]
SAWB is an ocean for me, I tested at KLSV.

**Comment by gilbertohasnofb** [comment]
> SAWB is an ocean for me

You must not have the scenery on your hard drive then. SAWB is a small airfield in Antarctica (!) and which has a very lightweight scenery and loads ultra fast.

> I tested at KLSV

I will try it there then

**Comment by onox** [comment]
I don't think the airport should matter though.

**Comment by gilbertohasnofb** [comment]
Me neither. And when I say the engine started at pressure 20.65 with autostart, I mean it barely started. I think the leaning should start much earlier. I will try to come up with a table.

**Comment by gilbertohasnofb** [comment]
@onox at KLSV using Q0752 you will get 20.66 inHg and the autostart does work! :clap:

**Comment by gilbertohasnofb** [comment]
@onox please take a look at the following table:

```
Pressure altitude:

 feet | inMg  | hPA
---------------------
0     | 29.92 | 1013
5000  | 24.89 | 0843
6000  | 23.98 | 0813
7000  | 23.08 | 0782
8000  | 22.22 | 0752
9000  | 21.38 | 0724
10000 | 20.57 | 0697
```

The value of my last test, 20.66 inHg, is equivalent to a standard atmosphere at the altitude of around 10.000 ft. Given the ceiling of our airplane, it means that our autostart basically works under standard atmosphere up to a ridiculously high elevation! Given that, I am quite tempted to simply implement the timer and close this issue... that is, not bother with the table, just let the autostart try to star the engine for some 10 seconds and if it fails to tell the user "The autostart could not start the engine at the current altitude and pressure. You must lean the mixture and start the engine manually." or something to that effect.

**Comment by gilbertohasnofb** [comment]
@onox I pushed some modifications to this branch, could you please give it a try? Now the autostart should quit after 5 seconds if the engine didn't start properly.

**Comment by gilbertohasnofb** [comment]
So let me know if you agree that that's enough, and then I can create a PR. Else if you think we should bother with the table, then I will try to gather some more values.

**Comment by onox** [comment]
You have put the `engineRunning` listener inside the timer callback. Is that really what you meant?

**Comment by gilbertohasnofb** [comment]
Yes, that was intentional, but now I see it was totally unnecessary, I could have set the listener of the engine before the timer, and simply cancel the listener once the timer reaches 5 seconds. I pushed an improved version, can you check if it's all right? It is working fine at least :stuck_out_tongue_winking_eye:

**Comment by onox** [comment]
It seems the listener is no longer necessary.

**Comment by gilbertohasnofb** [comment]
I think it is, since the engine might start within those 5 seconds, and we want to stop cranking at that point, right?

**Comment by onox** [comment]
Although it will take 5 seconds before we turn off the starter then. I don't like we're creating a new listener every time a user does autostart. The listener does get cleaned up though because of the `removelistener()` call in the timer.

**Comment by gilbertohasnofb** [comment]
Yes, it does remove itself in both cases (engine starting before 5 seconds, engine not starting). Would there be a better solution?

**Comment by onox** [comment]
I added debug statements and it seemed to always remove the listener via the timer. I'm trying 1 permanent listener at the end of the file.

**Comment by gilbertohasnofb** [comment]
> it seemed to always remove the listener via the timer.

That's really strange, is that the case even when the engine did start successfully? Because if so, how come the timer is removing the listener if the condition `!getprop("/engines/active-engine/running")` is not being satisfied?

**Comment by onox** [comment]
Hmm.. it seems we have never overridden the 's' key?

**Comment by onox** [comment]
Oh wait, we did.

**Comment by onox** [comment]
Do we want to allow using the starter when the engine is running? If you click on the starter in the panel it works, but not if you press 's' key.

**Comment by onox** [comment]
@gilbertohasnofb I have some changes in a minute.

**Comment by onox** [comment]
@gilbertohasnofb If you enable starter and release it, should the key go back to "magnetos both"?

**Comment by onox** [comment]
(with engine already running)

**Comment by onox** [comment]
Currently it goes back to whatever magneto setting you were using.

**Comment by onox** [comment]
I guess we can keep the logic for the 's' key as it is.

@gilbertohasnofb I have pushed a new commit. Instead of creating a new listener every time `autostart()` is called, we create just one listener after the FDM has initialized.

**Comment by gilbertohasnofb** [comment]
@onox Okay, I am back! So I pulled your modifications, they look quite good I think, certainly a more elegant solution :smile: :+1: 

So what do you think about the table then, should we bother trying to make the autostart work with different pressures or should we just merge what we have here? I personally vote for the latter.

**Comment by gilbertohasnofb** [comment]
@onox I went ahead and created a PR. So if you agree with me, you can merge it, else we keep working on it.

**Comment by dany93** [comment]
Why is mixture set at 0.95 instead of 1 at sea level with 'Autostart'?
`Systems/c172p-engine.xml` table, line 215.
The POH says 'RICH' (which obviously mainly depends on the altitude) but at sea level I would expect 100% mixture.
With 0.95 we loose some power.

**Comment by wlbragg** [comment]
I noticed that as well and wondered the same thing? I passed that on (.95) when creating the auto mixture, maybe now would be a good time to change it to 0 at sea level.

**Comment by dany93** [comment]
Yes. (change it to **1** at sea level, not 0).
I think that you merely kept it at 0.95 because it already was at 0.95, constant, in c172p.nas # Autostart in the previous version.

**Comment by onox** [comment]
@dany93 See https://github.com/c172p-team/c172p/issues/791#issuecomment-234784355 I think I set it to 0.95 because for some strange reason if setting it to 1.0 the engine would not start at the airports I used during testing.

**Comment by dany93** [comment]
@onox This also was my supposition See https://github.com/c172p-team/c172p/pull/1229#discussion_r231544859
