### ISSUE TITLE
Check dimensions of the levers

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#802]
Heiko has found a schematic of the throttle and mixture levers of a 172. Values are in inches:

![](http://i416.photobucket.com/albums/pp244/Ronson2k3/VernerControlsmall.jpg~original)

Could anyone who knows Blender well check if our values are correct?

**Comment by wlbragg** [comment]
I'm not a mechanical engineer so I can't tell from this what the length of travel should be when pulling a knob open, any suggestions on that? I can check the knob length when closed and make sure that matches.

**Comment by gilbertohasnofb** [comment]
@wlbragg I think the measurement we are interested is 2.75 inches + 5.95 inches, that would give us the full length of the lever (at 0% throttle or mixture) from the front face of the lever until the place where it enters the panel.

**Comment by wlbragg** [comment]
From what I could tell the fully extended object (the default position) is appx. 3.41in or 8.66cm.

**Comment by gilbertohasnofb** [comment]
So that's quite shorter than the schematic above suggests. But are we reading this schematic correctly? It sounds crazy that our levers are currently less than 50% of the size they should be :scream:

**Comment by gilbertohasnofb** [comment]
Or here is a thought: maybe the schematic is in cm, not in. And 8.7 is aprox. 8.66. Maybe Heiko was wrong about the size, I will mention this to him.

**Comment by wlbragg** [comment]
That is what I was thinking, because they don't look that short.

**Comment by HHS81** [comment]
@gilbertohasnofb 
@wlbragg 
The user who posted the image in a forum cleary stated that it is in inch:
[http://www.mycockpit.org/forums/showthread.php?t=24503&p=130775&viewfull=1#post130775](http://www.mycockpit.org/forums/showthread.php?t=24503&p=130775&viewfull=1#post130775)

**Comment by gilbertohasnofb** [comment]
@HHS81 But couldn't he have made a mistake? It's really hard to believe our levers are only 39% of the size that they should be!

**Comment by gilbertohasnofb** [comment]
8.7 in would be the same as 22 cm, which is reaaaally long. I am absolutely convinced the user was mistaken about the units.

**Comment by HHS81** [comment]
hä?
the 2,74inch part is the visibile part when throttle is **full in** and **includes** the metal thing behind (not the knob alone).
2.74.inch = about 7cm
the 5.95inch part is the rod. 5.95inch = about 15cm
I can't tell you if he made a mistake. 

But on the C182S the size of the throttle knob fits it perfect, without any change! Just the rod is too short! :smile:

**Comment by HHS81** [comment]
Btw.: the drawings shows not the throttle but mixture and prop lever

**Comment by HHS81** [comment]
Second: travel way must not be full

**Comment by gilbertohasnofb** [comment]
@HHS81 Sorry but there is something wrong. That 2.75 <unknown units> correspond only to the red part which you hold, correct? If that would be inches, it would be about 7 cm as you say. Now please look at this and tell me if you think the red part is really 7 cm long in the image below, or rather 2.75:

![](https://www.aopa.org/-/media/images/legacy/aopa/home/news/all/2015/february/0209_training_tip.jpg)

**Comment by HHS81** [comment]
[http://www.aircraftspruce.com/catalog/appages/a750.php](http://www.aircraftspruce.com/catalog/appages/a750.php)
Travel: 3-3/8"

**Comment by HHS81** [comment]
@gilbertohasnofb not, not the red part alone. The black part on the panel as well.

**Comment by HHS81** [comment]
@gilbertohasnofb 
@wlbragg 
You can use this as reference: http://www.aircraftspruce.com/catalog/graphics/acscontorls-s.jpg

**Comment by gilbertohasnofb** [comment]
> not the red part alone. The black part on the panel as well. 

Oh, I see!

> Travel: 3-3/8"

So that's 8.75 cm, which is reasonable with what we have here I think

**Comment by gilbertohasnofb** [comment]
Thanks Heiko! :smile:

**Comment by HHS81** [comment]
http://www.mcfarlaneaviation.com/pdfDocuments/MC600InstallationInstructions.pdf

**Comment by gilbertohasnofb** [comment]
@HHS81 Really appreciate it 
@wlbragg so do you think we could check again, particularly if the travel lenght of the tube (which enters the panel) is 8.75 cm

**Comment by wlbragg** [comment]
Starting value of the 
Throttle rod
0.09245 cm or 0.03639 in
Mixture rod
0.08757 cm 0.03447 in

**Comment by gilbertohasnofb** [comment]
0.09 cm? That's the diameter of a grain of rice. Are you sure these dimensions are right?

**Comment by wlbragg** [comment]
Wow, I'm just a dumb American Imperialist, ha!

Throttle rod
0.36407 - 0.27162
= 0.09245 m
Mixture rod
0.36382 - 0.27625
= 0.08757 m

If you want to verify my excellent math skills!
I was half asleep when I posted that this morning. My blender is set to meters so any measurements I get are meters, not cm.
Sorry about that.
I edited the original post/

**Comment by wlbragg** [comment]
Those measurements are the "visible" rod. I didn't look at the xml to see what we do with it at startup. Whether we offset it or what.

**Comment by gilbertohasnofb** [comment]
@wlbragg So it looks to me our measurements are spot on with what they are supposed to be, correct? If so we can close this issue.

**Comment by wlbragg** [comment]
Yes, looks right.
