### ISSUE TITLE
Add cowl plugs and/or engine covers

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#881]
~~What about adding cabin and engine covers to the aircraft? See:~~

We could add cowl plugs to our aircraft as part of securing it:

![](https://www.shop.kennoncovers.com/images/Cessna177B_CowlPlugs.jpg)

Alternatively we could also have the option of a full engine cover, but that might be completely unecessary:

![](http://cdn3.volusion.com/ugavy.szapz/v/vspfiles/photos/CoversCessna172-9.jpg?1443182629)

Previously I had suggested cabin covers but I don't think those are typically used in the 172, the photos below are from Cessnas 150/152. Let's just scratch this idea.

![](http://i.ebayimg.com/images/g/Cs4AAOSwmrlUtEbP/s-l300.jpg)

![](http://i.ebayimg.com/images/i/221949115011-0-1/s-l1000.jpg)

**Comment by gilbertohasnofb** [comment]
Perhaps adding the cabin cover would be too much and would lead to problems (doors opening for instance), but we could add the two elements from the very first picture: engine cover and the aluminium window sun protector. Those should be fairly easy I suppose.

**Comment by legoboyvdlp** [comment]
Please ping me if you are working on this, as it would be good to actually model the effects of the cover on the engine temperatures, in the oil and engine system.

**Comment by gilbertohasnofb** [comment]
I updates the description. IMO we could simply add cowl plugs as part of the securing aircraft system. That should be very easy to model and texturize.

**Comment by wlbragg** [comment]
@gilbertohasnofb I think I can do this tonight or tomorrow  (as you suggest, only the cowl plugs) if you want to wait for it before doing the exterior splash and previews.

**Comment by wlbragg** [comment]
Almost done, still have to do the straps, then it'll be ready for you to come up with some textures.

![cowl1](https://user-images.githubusercontent.com/11069680/43879192-5d60c6e2-9b68-11e8-933e-a5920384b12e.jpg)
![cowl2](https://user-images.githubusercontent.com/11069680/43879193-5d7e6ae4-9b68-11e8-94e1-d3b844770f33.jpg)

**Comment by wlbragg** [comment]
@gilbertohasnofb here is the UV mapping.

![cowlplugs-uv](https://user-images.githubusercontent.com/11069680/43882104-18466970-9b74-11e8-9ee1-0328422c02e5.png)

I pushed the temporary texture in case you need it for reference.

**Comment by wlbragg** [comment]
There is no logic to install or remove them, I only added the model tag to show them for testing.

**Comment by gilbertohasnofb** [comment]
omg the place holder texture you used is so amazing, I really feel under pressure to deliver a GPL friendly one now :scream: This looks seriously good.

Just a couple of questions:

* in your screenshots, the strap is black but in your texture I don't see any black texture. Where did you map it to? See image below.
* your texture is also missing one of the UV-map bits, was that removed? See the green square below.
![image](https://user-images.githubusercontent.com/5700795/43890872-d28f71dc-9bbf-11e8-9543-ffb66f242b31.png)
* also, I can implement the logic behind it, add it to the aircraft dialog and later (once we merge @legoboyvdlp's new changes to the tutorials and checklists) I will also add it to those. But could you please create for me one single object made out of two invisible cuboids places one on each cowl which I will use as a _single_ hotspot. Something like this:

![image](https://user-images.githubusercontent.com/5700795/43891017-35ce7464-9bc0-11e8-8fc4-c8ddeca05123.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg I will try to work on this texture still today, though I really feel sorry for replacing yours... I will try to find some CC0 photo of this type of material somewhere but so far I found nothing :sob:

**Comment by legoboyvdlp** [comment]
http://www.photos-public-domain.com/2012/02/12/red-plastic-texture/

Is something like that useful?

**Comment by gilbertohasnofb** [comment]
> Is something like that useful?

YES!!!

**Comment by wlbragg** [comment]
>in your screenshots, the strap is black but in your texture I don't see any black texture. Where did you map it to? See image below.

I mapped the strap to one of the dark red portions and then actually moved the strap mapping to an empty place (where your green square is) before I posted the "NEW" UV map for you to use as your guide.
So the final mapping is that UV map.

>could you please create for me one single object made out of two invisible cuboids places one on each cowl which I will use as a single hotspot.

Why don't we use the actual objects as the hotspots?

**Comment by wlbragg** [comment]
>sorry for replacing yours

I know, I know better than to use an image and then have to be disappointed because we can't find as good as a substitute. I was wanting to make sure it was going to look OK if done with the right resources.

**Comment by gilbertohasnofb** [comment]
> Why don't we use the actual objects as the hotspots?

I need the hotspots when the plugs are removed, so that we can add them there. For removing them I will of course use the actual objects. Or am I misunderstanding something? Once you are done doing that I will work on the texture and the implementation.

**Comment by wlbragg** [comment]
>I need the hotspots when the plugs are removed,

Ah, OK.

**Comment by wlbragg** [comment]
@gilbertohasnofb 
This is done, hotspot is, CowlPlugHotSpot

**Comment by gilbertohasnofb** [comment]
Excellent. And have you seen my report about the lack of texture on the cowl plugs?

**Comment by wlbragg** [comment]
>Excellent. And have you seen my report about the lack of texture on the cowl plugs?

No?

**Comment by gilbertohasnofb** [comment]
Weird. I am posting so much but now I can't find it. Sorry, multitasking like crazy right now. But basically my cowl plugs are fully white, no texture at all. I tried replacing that png with another one made by me but it is still fully white.

**Comment by wlbragg** [comment]
Wow, I have the same thing happen and when I refreshed it shows up. I have no answer for this weird behavior. I am out of time until late tonight so for now can you just refresh the model (debug) and I'll try to figure out what the weird glitch is later.

**Comment by wlbragg** [comment]
@gilbertohasnofb also, I just pushed the final mapping (with the strap in the blank portion of the texture sheet that we talked about) I forgot to push it last night. I don't think this affects you any other than you need to pull it before you push.

**Comment by gilbertohasnofb** [comment]
@wlbragg I am also away from now so I will just quickly test what you push and then wait for you to solve this glitch before working on the textures.

**Comment by wlbragg** [comment]
@gilbertohasnofb I think I got it figured out. We needed livery support for these as well. I think your ready to take over on this.

**Comment by gilbertohasnofb** [comment]
Hmm, I don't like that the texture is now on the `/Models` folder as well as in `/Models/Interior/cowlplugs`. I tried removing one of them but then the texture looks buggy, parts of the texture weren't showing up in the sim.

Let's keep things consistent and use only the object folder for its filed. For instance, the `control-lock` folder contains model, texture and xml.

**Comment by wlbragg** [comment]
>Let's keep things consistent and use only the object folder for its filed. For instance, the control-lock folder contains model, texture and xml.

This is different. For one, the texture should no longer be in the cowlplugs folder, if it is then that is my mistake. The difference from control-lock for example and any other object that has the texture residing in it's own folder is that this is livery dependent.
All the livery dependent textures are in Models/ 

>I tried removing one of them but then the texture looks buggy, parts of the texture weren't showing up in the sim.

Again, the texture should no longer be in the cowlplugs folder. What part exactly wasn't showing up or was buggy?

**Comment by gilbertohasnofb** [comment]
> For one, the texture should no longer be in the cowlplugs folder, if it is then that is my mistake. The difference from control-lock for example and any other object that has the texture residing in it's own folder is that this is livery dependent.

The question is why do we need livery support for them. Was that the only way you found of solving whatever issue you previously had? Because IMO it doesn't make sense to make them livery dependent. And the file was in both folders indeed.

> Again, the texture should no longer be in the cowlplugs folder. What part exactly wasn't showing up or was buggy?

The cord connecting the two sides. I will investigate this later today or tomorrow.

**Comment by wlbragg** [comment]
@gilbertohasnofb I redid the strap, it should be much better. I also saved a new UV-layout as it changes a little bit.
Should be ready for you to work on unless you still don't want it to be livery dependent.

![cowlplugs-uv](https://user-images.githubusercontent.com/11069680/43982012-dcca99f6-9cb9-11e8-95f7-7db19b925ebb.png)

**Comment by gilbertohasnofb** [comment]
Cool, I will work on this tomorrow.

> But I think they are as you don't want "Red" plugs on a blue aircraft, that looked really bad.
> If they are not livery dependent, what color are you going to make them?

These things tend to always be red, they don't match the livery. The whole point is that you should see it and remember to remove it:

![](http://www.kennoncovers.com/images/aircraft/cowlnew.gif)
![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0rFveWWJYLrL0aLUBbEJ1XnWx8P6vRj0JQIxJPouCUQuKYEoX)
![](https://cdn3.volusion.com/ugavy.szapz/v/vspfiles/photos/CoversPA15-4.jpg?1442567173)
![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd5uWCH6TCz1yyF9JnB5IcybJ17pso75x79koNIi4oDaGTQwCkKQ)

So please do not make them livery dependent.

**Comment by gilbertohasnofb** [comment]
@wlbragg give me a ping when you fix the stuff above, I should be able to get the textures done by today

**Comment by wlbragg** [comment]
@gilbertohasnofb this is ready. A couple notes. There is a big difference in the look of these depending on whether or not you assign "bumpspec" effect to them. If you do you could eventually make a normals map to make them pop a bit better. But I thought using that effect as is had positive and negative effects. I left it commented (/Models/Exterior/cowlplugs/cowlplugs.xml) out so you can experiment for yourself and decide how you want to proceed. Just uncomment it to see the difference.
Also below is a with and without bumpspec effect. Depending on which way you go you might have to adjust the brightness/contrast of the texture art.
Also is the new mapping including the "remove before flight" flag.
This has been removed from liveries.

New uv-map
![cowlplugs-uv](https://user-images.githubusercontent.com/11069680/43994535-42c175b8-9d64-11e8-8c19-e1b07cd24b79.png)

With bumpspec
![cowlplugs](https://user-images.githubusercontent.com/11069680/43994537-4cebf270-9d64-11e8-8fed-e19b0bdaaeac.jpg)

Without bumpspec
![cowlplugs2](https://user-images.githubusercontent.com/11069680/43994540-58a42506-9d64-11e8-9fcf-b38fb79be960.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg I think this object needs to be completely without any bumpspec, the bottom image in your post look much more realistic to me. These things are made out of some plastic material and shouldn't be shinny or anything, your first photo looks very metallic to me. My 2 cents is to go completely without any bumpspec.

**Comment by wlbragg** [comment]
@gilbertohasnofb then go ahead and delete the lines that are already commented out in /Models/Exterior/cowlplugs/cowlplugs.xml

~~~
<!--effect>
        <inherits-from>../../Effects/exterior/bumpspec</inherits-from>
        <object-name>cowlplugs</object-name>
    </effect-->
~~~

**Comment by dany93** [comment]
I think that, IRL, the pilot manually rotates the propeller (with magnetos OFF !!) in a correct position.

**Comment by gilbertohasnofb** [comment]
I think we could come up with a Nasal function that would interpolate the propeller to the correct position (similar to the one we have for testing the control surfaces), but the ejection would still be _very_ tricky to pull off.

**Comment by dany93** [comment]
Yes, the ejection is too tricky, that doesn't worth the time to do it. Deleting it or, at best (more work for a small detail), letting it on the ground would be enough. The most important is piloting.

**Comment by gilbertohasnofb** [comment]
@dany93 the problem with letting it on the ground is that this object is actually part of the aircraft. I don't know if that's possible unless we use those techniques for the ground equipments. But then this will become really complex. @wlbragg any thoughts on any of these things?

**Comment by wlbragg** [comment]
It's not a matter of technique to move it, it's the fact that it's not in the right position to be laying on the ground, the orientation of the model. You would have to create a second model. Simplest would be to just make it disappear.
@gilbertohasnofb had it correct that the propeller could be in the way of the strap. if we can fix the propeller to always be at least let's say a 10 degree angle every time we shut it off, I can move the strap to the outside.

**Comment by gilbertohasnofb** [comment]
>  if we can fix the propeller to always be at least let's say a 10 degree angle every time we shut it off

That's tricky because if you fail to start the engine the propeller will be anywhere (try just hitting `s` for a millisecond). The best approach would be to find what property controls the propeller and then setting it to a value `x` when the cowl plugs are on. I will see if I can find it out...

**Comment by wlbragg** [comment]
I cut my last post short as I was mobile. I think we should interpolate the prop from any position to the desired position when the cowl plugs are placed and I think I know how to to it. Also I am going to push c172p.ac with a change to the default prop start position of about -70 from where it is now which will leave it sitting at about a 10-20 degree tilt from vertical.

 I'm going to push this fix to a miscellaneous-issues-cleanup PR I will make when done.

**Comment by gilbertohasnofb** [comment]
I just took a look and it seems to me that, unfortunately, the propeller is not controlled by any single property but rather by a `spin` type of animation using the `rpm` as source. As such I don't know how could we rotate it when clicking on the hotspots for adding the cowl plugs...

If we find a way though then I would say that we can take the easy route with the ejection and just remove it. And then we should also delete my code that makes the engine cough if the plugs are left on.

**Comment by wlbragg** [comment]
>If we find a way though then I would say that we can take the easy route with the ejection and just remove it. And then we should also delete my code that makes the engine cough if the plugs are left on.

We can easily rotate it, I just don't know if we can tell where it is and where exactly to rotate it to?

**Comment by wlbragg** [comment]
@gilbertohasnofb looks like we can easily place the prop at the default starting location when you select the cowl plugs even after the engine rpm has left it elsewhere. But I don't think we have access to the current rotation value of the propeller object needed in order to interpolate it.

**Comment by wlbragg** [comment]
So you have to use your imagination to assume the pilot turned the prop by hand when installing the cowl plugs.

**Comment by gilbertohasnofb** [comment]
That's not a problem, that's just cosmetic. Would you mind to take care of this then? I just don't know how to reset the propeller. Once you have the PR opened I will remove my code for the coughing.

**Comment by wlbragg** [comment]
So as far as I can tell by setting the prop to where we want it as default in the blend/ac and then using this code.
~~~
    <!-- Rotate propeller when applying cowl plugs -->
    <animation>
        <type>rotate</type>
        <object-name>leftaileron</object-name>
        <property>/sim/model/c172p/proppos</property>
        <condition>
            <property>/sim/model/c172p/securing/cowl-plugs-visible</property>s
        </condition>
        <center>
            <x-m>-1.96139</x-m>
            <y-m>0.00127</y-m>
            <z-m>-0.0519</z-m>
        </center>
        <axis>
            <x>1.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </axis>
    </animation>
~~~
to place it back to center (where /sim/model/c172p/proppos is set at 0 in c172p-set.xml).
It just works. Is that OK, do you want me to push it?

**Comment by wlbragg** [comment]
>That's not a problem, that's just cosmetic. Would you mind to take care of this then? I just don't know how to reset the propeller. Once you have the PR opened I will remove my code for the coughing.

Yeah, let me push this and also we will need to add the disappearance code when starting the engine.

**Comment by wlbragg** [comment]
@gilbertohasnofb it's not working. I did a simple test and thought it did, but apparently not. We can rotate it but I am not sure if we can know it's rotation position. I'm going to ask on the forums.

**Comment by gilbertohasnofb** [comment]
> We can rotate it but I am not sure if we can know it's rotation position. I'm going to ask on the forums.

I have an idea, but it's a mega hack: what if the cowl plug model would also have a propeller added to it? That is, we make a group with both objects. So then when the plugs are added we hide the 'real' propeller and show the plugs + the 'plug propeller'. Once they are removed, we switch back. This means that the propeller will teleport both when adding the plug and when removing it though...

But frankly I am starting to think this is just a too small detail to care. I will certainly remove the cough code + auto remove the plugs if the engine starts, but the modelling bit sounds a bit too complicated...

**Comment by wlbragg** [comment]
@gilbertohasnofb it's not really complicated at all. I actually (temporarily) added the prop to the cowlplug blend in order to edit the strap to sit on the outside of it. It is a very simple select statement to have the one in the cowlplug blend selected and the real one not selected when cowlplug-visible = true and vis-verse when the opposite is true. Not really a bad solution.
Lets give my question a day and we can use this idea as a fall back.

**Comment by gilbertohasnofb** [comment]
Great! Once you decide how to tackle the modelling side I will take care of the cough and the rest of the code. Just give me a shout when you have a PR.

**Comment by wlbragg** [comment]
I went ahead and just did what we discussed, I think it turned out to be a reasonable fix. See Miscellaneous issues #1181 PR
