### ISSUE TITLE
Create variants for startup options

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#892]
Please see the latest version of J3Cub and the way I did the QT launcher variants. You can now start the aircraft in a predefined configuration and still have the flexibility to change the configuration on the fly.
If we choose to do this I would suggest we come up with a list of the best, smallest list to showcase the available configurations and limit the amount of variants.

**Comment by wkitty42** [comment]
is this a duplicate or at least related to #789 and maybe #932 ??

**Comment by wlbragg** [comment]
>is this a duplicate or at least related to #789 and maybe #932 ??

No, this is "variants" not states. It would give the option of starting the aircraft configured a certain way, like with skis or pontoons or bush wheels VS starting up and then selecting what configuration you want. There are some added bonuses to doing this, like having different previews in the launcher showing the aircraft in that configuration. See the J3Cub in the launcher for an example.

**Comment by wkitty42** [comment]
so basically this is -set files all combined into one with some sort of property setters to choose the engines and gear?? hummm...
