### ISSUE TITLE
Keys in the magneto switch are the wrong model

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#929]
Keys in the magneto switch are the wrong model, they should look like this:

![](https://i.ebayimg.com/00/s/MTU1MFgxNjAw/z/JJ4AAOSw9uFW9JoH/$_57.JPG)

(thanks @HHS81 for spotting it)

**Comment by wlbragg** [comment]
@gilbertohasnofb more artwork needed!

![key](https://user-images.githubusercontent.com/11069680/41816435-e6080718-774a-11e8-81c7-a960098fab98.jpg)

![key2](https://user-images.githubusercontent.com/11069680/41816437-ea5aca08-774a-11e8-8da5-7d61039859e9.jpg)

**Comment by gilbertohasnofb** [comment]
I will work on this today

**Comment by gilbertohasnofb** [comment]
Done.

**Comment by wlbragg** [comment]
Did this issue not close out for some reason?

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/c172p-team/c172p/pull/1103
