### ISSUE TITLE
Model defroster outlets

### ISSUE THREAD

**Issue by onox** [c172p-team/c172p#961]
Model the adjustable defroster outlets because they don't exist in the 3D model.

Do we need to paint one of the R/G/B layers in the ALS glass mask? (so that you see the fog disappearing where the defroster outlets are)

See https://github.com/c172p-team/c172p-detailed/issues/910#issuecomment-280856815

Also See https://github.com/c172p-team/c172p-detailed/issues/202#issuecomment

**Comment by wlbragg** [comment]
Yes, I actually did this on the J3Cub so we have an example to use. I'll see if I can do the mask.

**Comment by wlbragg** [comment]
@onox, do you mean actually model in Blender defroster outlets? Is this then a different issue that #202

**Comment by onox** [comment]
I think I just meant the modeling, but it can be done in #202 as well. This issue looks a bit like a duplicate.

**Comment by wlbragg** [comment]
I may be able to model the outlets when I do the panel work (raising the panel).

**Comment by wlbragg** [comment]
An interesting tidbit I found today. I was searching for a G1000 c172p implementation and found the C172S-G1000-POH.pdf (simple search will find it).
I skimmed through it and was amazed at how detailed the more obscure systems that were included in it.
This details the heat and air system

![c172sp-heat-air-sys](https://user-images.githubusercontent.com/11069680/43155522-40b9d678-8f3d-11e8-955a-c9feb9085824.jpg)

**Comment by legoboyvdlp** [comment]
Doesn't the 1982 C172P have those diagrams as well? For consistency I feel it is better to stick with the 172P poh apart from the G1000. Otherwise, thanks for posting this!

**Comment by wlbragg** [comment]
>Doesn't the 1982 C172P have those diagrams as well?

I don't recall seeing anything with this detail. Anyone know what the differences are between the c172p and the c172sp? Isn't it mainly the G1000 and the panel layout? From the description I read that was the inference.

You notice anything wrong with the diagram?
Doesn't it look like they got the upper air and lower air outlets labeled wrong?

**Comment by legoboyvdlp** [comment]
As far as I know the C172S has the improvements of the C172R:

> The 172R's maximum takeoff weight is 2,450 lb (1,111 kg). This model year introduced many improvements, including a new interior with soundproofing, an all new multi-level ventilation system, a standard four point intercom, contoured, energy absorbing, 26g front seats with vertical and reclining adjustments and inertia reel harnesses.

with the G1000 and a better engine.

**Comment by legoboyvdlp** [comment]
Page 163:
![image](https://user-images.githubusercontent.com/10434911/43184994-72f9d926-8fe2-11e8-94b5-2cf41015b192.png)

[Cessna_172_C172P-1982-POH.pdf](https://github.com/c172p-team/c172p/files/2226880/Cessna_172_C172P-1982-POH.pdf)

**Comment by gilbertohasnofb** [comment]
> Anyone know what the differences are between the c172p and the c172sp? Isn't it mainly the G1000 and the panel layout? From the description I read that was the inference.

C172P: introduced in 1981.
C172Q: introduced in 1983, basically a model P with a 180hp engine.
C172R: introduced in 1996, first 172 with a fuel-injected engine. This model year introduced many improvements, including a new interior with soundproofing, an all new multi-level ventilation system, a standard four point intercom, contoured, energy absorbing, 26g front seats with vertical and reclining adjustments and inertia reel harnesses. 
C172S: introduced in 1998, basically a model R with a 180hp engine.
C172SP: a variant of model C172S with some added features like leather seats and a Garmin G1000.

Do notice that while the models P and Q are fairly similar the model R is over 15 years more recent than our model! The engine is completely different, some of the systems are completely different, the procedures are also completely different (e.g. starting the engine is totally different, there is no primer, there is a fuel pump switch, etc). I would refrain from using _anything_ from any model beyond model Q. A model R, S or SP are really a different beast than the older models from the late 1970s and early 1980s.

**Comment by legoboyvdlp** [comment]
Is our 180hp a C172Q then?

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Not really, about ours what we had in mind is a model P with a different engine. This happens a lot in RL, someone owns a regular model P and then upgrades the engine to a 180hp, particularly if they also transform it in to a float variant but not necessarily. That doesn't make it a model Q since that is not what Cessna called it at manufacturing. Of course in the sim there was no manufacturing, but for the sake of simplicity they are all model P's as far as I can tell. Also, we don't know what other minuscule differences there might be between a model Q and P other than the engine so I would just keep calling them the same right now :smile:

**Comment by wlbragg** [comment]
>new multi-level ventilation system

Interesting difference, pilots must have complained about having hot feet! :smile:

**Comment by wlbragg** [comment]
I don't think this there is really anything to do here. Did we or did we not determine the c172p has these vents in the dash, regardless, I think the fog frost system as written simulates the air introduction to the cabin by using the sliders. The fog/frost texture simulates there being vents where air comes into the cabin at those two locations.
So as the fog/frost clears, it clears first at those two locations.
If there are those two vents in the dash and If there are vent handles that can shut those down, then we would need to model that in the mesh. We would also then need to have a way to not use the new glass fog/frost texture if those vents were closed. Sounds like it's getting a bit too complicated for my liking.
So, if those vents are there in the c172p, I say we assume they are always open and don't allow you to close them (simply not model them). If those two vents are not there, then the new fog/frost overlay textures are not correct and they should actually show the increase in defrost where the two vents coming out of the wing butts are.
