### ISSUE TITLE
Recreate splash screens

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#967]
Given that we have made considerable improvements to the external 3D model since the splash screens have been created, I propose we re-create them in order to showcase how our aircraft is currently looking. 

@wlbragg wrote:

> I should do some variant startup states, that would go hand in hand with the previews and splash screen work.
> 
> The variants I would include are
> 
>     Default (160 engine, default tires)
>     Bush (180 engine, 26" tires)
>     Float (160 engine, floats)
>     Amphibian (180 engine, amphibious floats)
>     Snow Skis (160 or 180 engine, skis)
> 
> I would have a different splash screen for each.
> I would have at least one preview for each of the above and also include a preview for the 36" tire.

**Comment by gilbertohasnofb** [comment]
This is particularly true after we merge https://github.com/c172p-team/c172p-detailed/pull/964. Also, I have since got a new and more powerful computer so I believe I can recreate those screenshots with much better quality than before. I will take care of this in the near future.

**Comment by legoboyvdlp** [comment]
Excellent. What is the min res you require... is 1362 * 701 any good? I imagine it's too low, but it's the screen size I have...

**Comment by legoboyvdlp** [comment]
I'm sure you'd prefer to do it on your own, on a higher res, but if you want any screenshots let me know!

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp many thanks for offering help, Lego, but I think we need at least 1920 x 1080 so that it looks good on most monitors. I will wait a bit to work on this since we are still doing visual improvements and I wouldn't like to miss the opportunity to include those as well :smile:

**Comment by onox** [comment]
Do we really need to recreate all of them? Aren't some still usable because the changes are not visible due to the camera angle being used?

**Comment by wlbragg** [comment]
>Do we really need to recreate all of them?

"need to", no not really, but @gilbertohasnofb and myself can really notice the differences in the old screen shots VS the new work that has been done. It is extensive and probably visible at almost every angle. Although we're probably the only ones that will notice the differences in the splash screens. :smile:

**Comment by gilbertohasnofb** [comment]
@onox I think I need to recreate _all_ of them, really. They are all quite old and missing nice new features, none of them show the reflection effects we now have, most have outdated shapes for the rudder, ugly mesh or ugly UV-mapping here and there, etc. It's not so much work to be honest, and I will try to recreate them in the exact locations and conditions so there is nothing to worry about except my time investment on this issue, which I guarantee is fine by me :laughing:

**Comment by gilbertohasnofb** [comment]
@wlbragg but I will probably wait for the major cockpit improvements before doing so, as that might be a bit visible from the outside, and splash 1 is a cockpit shot.
